chore: tight range checks in NodeIndex
starkware-libs/committer pull request #100
Opened 2024-05-07 09:00 UTC by TzahiTaub

2024-05-07 14:01 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxI83v4BCD8hVwhSq07:-NxI83v5EnouK7rYgn5u:b582pk2) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L13)):*
> ```XML
> 
> pub const MAX_HEIGHT: u8 = 251;
> static MAX_INDEX: Lazy<U256> = Lazy::new(|| (U256::ONE << (MAX_HEIGHT + 1)) - U256::ONE);
> ```

Does this work? if so, better to keep it simple



_Suggestion:_
```XML
use ethnum::U256;

#[cfg(test)]
#[path = "types_test.rs"]
pub mod types_test;

const MAX_HEIGHT: u8 = 251;
const MAX_INDEX: U256 = (U256::ONE << MAX_HEIGHT + 1) - U256::ONE;
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIG1PoCrjgpQN1Iedb:-NxIG1PoCrjgpQN1Iedc:b-18dzlv) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L29)):*
> ```XML
>     Ord,
> )]
> pub(crate) struct NodeIndex(pub U256);
> ```

This will make the constructor private and enforce using the `new` function



_Suggestion:_
```XML
pub(crate) struct NodeIndex(U256);
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxILZwK8iTOwOZS5s67:-NxILZwK8iTOwOZS5s68:bxppw65) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L34)):*
> ```XML
> // Wraps a U256. Maximal possible value is the largest index in a tree of height 251 (2 ^ 252 - 1).
> impl NodeIndex {
>     pub const BITS: u8 = MAX_HEIGHT + 1;
> ```

`BIT_LENGTH`/`BIT_LEN`/`N_BITS`



_Code quote:_
```XML
BITS
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIJOeY83r8f1jo5tSP:-NxIJOeY83r8f1jo5tSQ:bwbcqdh) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L41)):*
> ```XML
>         }
>         Self(index)
>     }
> ```

Maybe implement the trait `From` from U256



_Code quote:_
```XML
    pub(crate) fn new(index: U256) -> Self {
        if index > *MAX_INDEX {
            panic!("Index is too large.");
        }
        Self(index)
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIKJVm1nvEYvIzH847:-NxIKJVm1nvEYvIzH848:brcvw5d) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L49)):*
> ```XML
>     pub(crate) fn highest_index() -> NodeIndex {
>         NodeIndex::new(*MAX_INDEX)
>     }
> ```

If it works, better to do it in compile time



_Suggestion:_
```XML
    pub(crate) const ROOT: Self = { Self::from(U256::ONE) };

    pub(crate) const MAX: Self = { Self::from(*MAX_INDEX) };
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIDopU3DK6uHFW2EhO:-NxIDopV1JyckQnANOst:b-ohrmor) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L84)):*
> ```XML
>         Self(U256::from(1_u8) << tree_height.0) + Self::from(address.0)
>     }
> }
> ```

Why not here?



_Code quote:_
```XML
    pub(crate) fn from_starknet_storage_key(
        key: &StarknetStorageKey,
        tree_height: &TreeHeight,
    ) -> Self {
        Self(U256::from(1_u8) << tree_height.0) + Self::from(key.0)
    }

    pub(crate) fn from_contract_address(
        address: &ContractAddress,
        tree_height: &TreeHeight,
    ) -> Self {
        Self(U256::from(1_u8) << tree_height.0) + Self::from(address.0)
    }
}
```


<!-- Sent from Reviewable.io -->

2024-05-07 14:04 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxILZwK8iTOwOZS5s67:-NxIMgdT8Kncrju90GlV:b-qvauud) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L34)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

`BIT_LENGTH`/`BIT_LEN`/`N_BITS`
</blockquote></details>

NVM, I see it's consistent with U256
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIMQuH-BEOKGxl3gzy:-NxIMQuH-BEOKGxl3gzz:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L61)):*
> ```XML
> 
>     /// Returns the number of leading zeroes when represented with Self::BITS bits (252).
>     pub(crate) fn leading_zeros(&self) -> u8 {
> ```





_Suggestion:_
```XML
    /// Returns the number of leading zeroes when represented with Self::BITS bits.
    pub(crate) fn leading_zeros(&self) -> u8 {
```


<!-- Sent from Reviewable.io -->

2024-05-07 14:10 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIN8TU9dAEaOzdhtsm:-NxIN8TV0MWG3NQFN7eM:btdqpmo) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L62)):*
> ```XML
>     /// Returns the number of leading zeroes when represented with Self::BITS bits (252).
>     pub(crate) fn leading_zeros(&self) -> u8 {
>         (self.0.leading_zeros() - (U256::BITS - u32::from(Self::BITS)))
> ```

Why not keep `Self::BITS` as `u32`?



_Code quote:_
```XML
u32::from(Self::BITS)))
```


<!-- Sent from Reviewable.io -->

2024-05-07 16:33 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxI83v4BCD8hVwhSq07:-NxIO94E8oRGF2CB9Xzs:b52nyl6) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L13)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Does this work? if so, better to keep it simple
</blockquote></details>

No, shift (<<) is not a const function, this is why I use Lazy.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIG1PoCrjgpQN1Iedb:-NxIOdi2CuhyKD3u9N6_:b-edthr9) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L29)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This will make the constructor private and enforce using the `new` function
</blockquote></details>

:+1: good pointer
The problem is I do access the field to use its functions. e.g., `(first\_leaf.0 & child\_direction\_mask)` where the mask is U256. I can use derive_more and turn the mask to NodeIndex, but I'm not sure it's a good idea (as it makes NodeIndex represent numbers and not really just indices in a tree). WDYT?
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxILZwK8iTOwOZS5s67:-NxIOmTd3wLU3_bZ7ALo:bgmll6e) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L34)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

NVM, I see it's consistent with U256
</blockquote></details>

Yes, I don't like the names either.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIJOeY83r8f1jo5tSP:-NxIrnWwE2RGTgw6i9eC:bqvfptx) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L41)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Maybe implement the trait `From` from U256
</blockquote></details>

Instead of `new`? I can make TryFrom (as not every U256 can be converted) but I prefer to use the ctor with panic than to get an error and handle it everywhere if it makes sense.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIKJVm1nvEYvIzH847:-NxIqNLRCHIiY5dPg6Mf:b-o7tsxo) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L49)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

If it works, better to do it in compile time
</blockquote></details>

root is fine, max isn't possible inside the NodeIndex impl.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIN8TU9dAEaOzdhtsm:-NxIqt2_39qWumyCnRJM:bausmhq) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L62)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not keep `Self::BITS` as `u32`?
</blockquote></details>

We can , it's just fits in a u8 and is like the TreeHeight (I don't know why U256 uses u32).
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIDopU3DK6uHFW2EhO:-NxIrbay-BpJJl713HnB:b-7urlf9) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L84)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not here?
</blockquote></details>

Why WHAT is not here?


<!-- Sent from Reviewable.io -->

2024-05-07 17:45 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxI83v4BCD8hVwhSq07:-NxJ8GqYDc9xZz-ooStl:b-vy7etv) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L13)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

No, shift (<<) is not a const function, this is why I use Lazy.
</blockquote></details>

Suggestion: something like
```rust
const MAX_INDEX: U256 = U256::from_words(!0 >> (255 - MAX_HEIGHT), !0);
```
Use can move them to NodeIndex and replace `(255 - MAX_HEIGHT)` with `(U256::BITS - Self::BITS)`
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIG1PoCrjgpQN1Iedb:-NxIxo5j1T4nr44rBL-5:b-qxgmqn) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L29)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

:+1: good pointer
The problem is I do access the field to use its functions. e.g., `(first\_leaf.0 & child\_direction\_mask)` where the mask is U256. I can use derive_more and turn the mask to NodeIndex, but I'm not sure it's a good idea (as it makes NodeIndex represent numbers and not really just indices in a tree). WDYT?
</blockquote></details>

You can add a getter:
`first_leaf.0` -> `first_leaf.index()`/`first_leaf.num()` or something like that
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIN8TU9dAEaOzdhtsm:-NxIz_JE2fDPjDyaQCGY:b-70q5a) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L62)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

We can , it's just fits in a u8 and is like the TreeHeight (I don't know why U256 uses u32).
</blockquote></details>

Because 256 does not fit in 8 bits. Okay, your choice
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxJ-urt88iIMLHkIgI6:-NxJ-urt88iIMLHkIgI7:b3jc1p2) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L80)):*
> ```XML
>     pub(crate) fn from_contract_address(
>         address: &ContractAddress,
>         tree_height: &TreeHeight,
> ```

The addition is not safe (not going through your `new` method)
Can we disable the `Add` impl? are we using it elsewhere?



_Suggestion:_
```XML
Self(U256::ONE << tree_height.0) + Self::from(address.0)
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIDopU3DK6uHFW2EhO:-NxJ-37f4g2uQF3aYMyt:b-tcpcgl) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L84)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Why WHAT is not here?
</blockquote></details>

Using `Self::new`


<!-- Sent from Reviewable.io -->

2024-05-08 08:07 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: all files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIKJVm1nvEYvIzH847:-NxMDN2EClHbfMXPXkGa:b-c5f10m) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L49)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

root is fine, max isn't possible inside the NodeIndex impl.
</blockquote></details>

max is impossible also because it's not const (the shift-left operator is not const)
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxJ-urt88iIMLHkIgI6:-NxMDybD7359B1cwQfoB:b-g69r09) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L80)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

The addition is not safe (not going through your `new` method)
Can we disable the `Add` impl? are we using it elsewhere?
</blockquote></details>

@Yoni-Starkware contract addresses, class hashes and storage keys are all less than 2^251 (which is *much less than* PRIME-1), right?
(otherwise a height of 251 is not enough)
if so, why is the addition unsafe?
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMCtc4E0JTLxZ_r0ZN:-NxMCtc4E0JTLxZ_r0ZO:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/e7358dc96d190bab1821ff2e3789ccc67d63efb4/crates/committer/src/patricia_merkle_tree/types.rs#L13)):*
> ```XML
> 
> pub const MAX_HEIGHT: u8 = 251;
> static MAX_INDEX: Lazy<U256> = Lazy::new(|| (U256::ONE << (MAX_HEIGHT + 1)) - U256::ONE);
> ```





_Suggestion:_
```XML
pub const MAX_HEIGHT: u8 = 251;
const NODE_INDEX_BITS: u8 = MAX_HEIGHT + 1;
static MAX_INDEX: Lazy<U256> = Lazy::new(|| (U256::ONE << NODE_INDEX_BITS) - U256::ONE);
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMD-786b__D6YV2DI3:-NxMD-786b__D6YV2DI4:bxaf36m) ([raw file](https://github.com/starkware-libs/committer/blob/e7358dc96d190bab1821ff2e3789ccc67d63efb4/crates/committer/src/patricia_merkle_tree/types.rs#L35)):*
> ```XML
> // Wraps a U256. Maximal possible value is the largest index in a tree of height 251 (2 ^ 252 - 1).
> impl NodeIndex {
>     pub const BITS: u8 = MAX_HEIGHT + 1;
> ```

delete (see above, use NODE_INDEX_BITS)
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMD8t3CKoDRr3RJXRS:-NxMD8t3CKoDRr3RJXRT:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/e7358dc96d190bab1821ff2e3789ccc67d63efb4/crates/committer/src/patricia_merkle_tree/types.rs#L40)):*
> ```XML
>     pub(crate) fn new(index: U256) -> Self {
>         if index > *MAX_INDEX {
>             panic!("Index is too large.");
> ```





_Suggestion:_
```XML
"Index {index} is too large."
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMDGy27ulWbYVmlUg7:-NxMDGy27ulWbYVmlUg8:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/e7358dc96d190bab1821ff2e3789ccc67d63efb4/crates/committer/src/patricia_merkle_tree/types.rs#L47)):*
> ```XML
>     pub(crate) fn highest_index() -> NodeIndex {
>         NodeIndex(*MAX_INDEX)
>     }
> ```





_Suggestion:_
```XML
    pub(crate) fn highest_index() -> Self {
        Self(*MAX_INDEX)
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMEL3YBHh1RYb2Sp4U:-NxMEL3YBHh1RYb2Sp4V:bizhblt) ([raw file](https://github.com/starkware-libs/committer/blob/e7358dc96d190bab1821ff2e3789ccc67d63efb4/crates/committer/src/patricia_merkle_tree/types.rs#L100)):*
> ```XML
>         NodeIndex::new(self.0 >> rhs)
>     }
> }
> ```

while you're here



_Suggestion:_
```XML
impl std::ops::Shl<u8> for NodeIndex {
    type Output = Self;

    /// Returns the index of the left descendant (child for rhs=1) of the node.
    fn shl(self, rhs: u8) -> Self::Output {
        Self::new(self.0 << rhs)
    }
}

impl std::ops::Shr<u8> for NodeIndex {
    type Output = Self;

    /// Returns the index of the ancestor (parent for rhs=1) of the node.
    fn shr(self, rhs: u8) -> Self::Output {
        Self::new(self.0 >> rhs)
    }
}
```


<!-- Sent from Reviewable.io -->

2024-05-08 08:17 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: all files reviewed, 9 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxI83v4BCD8hVwhSq07:-NxMG29E4mAyn_8sEAVL:b-valo84) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L13)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Suggestion: something like
```rust
const MAX_INDEX: U256 = U256::from_words(!0 >> (255 - MAX_HEIGHT), !0);
```
Use can move them to NodeIndex and replace `(255 - MAX_HEIGHT)` with `(U256::BITS - Self::BITS)`
</blockquote></details>

I don't understand what is written in your proposal. Is it supposed to be more readable? :confused: 
And I CAN'T USE << (a non const function) in NodeIndex as we can't define a static there (and we can't use if for const in general)
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIG1PoCrjgpQN1Iedb:-NxM4OXy98pUfDg5faId:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L29)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You can add a getter:
`first_leaf.0` -> `first_leaf.index()`/`first_leaf.num()` or something like that
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIKJVm1nvEYvIzH847:-NxMEyxK805zfDA3MuoO:bt9ja4b) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

max is impossible also because it's not const (the shift-left operator is not const)
</blockquote></details>

Yep. I meant it also isn't possible to put a static inside the impl.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxJ-urt88iIMLHkIgI6:-NxMFY2t90f8SkO1BwBd:b-qt1o1n) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L80)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@Yoni-Starkware contract addresses, class hashes and storage keys are all less than 2^251 (which is *much less than* PRIME-1), right?
(otherwise a height of 251 is not enough)
if so, why is the addition unsafe?
</blockquote></details>

It's not safe in general (as two NodeIndices can overflow the 252 bit limitations).
As a side note I think we should enforce the hight limitation in TreeHeight as done in NodeIndex (and in other strcuts if there are any).
Not sure what to do here ATM.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxIDopU3DK6uHFW2EhO:-NxMAxH3-e8n0GDjmyjl:b-tyx0n5) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L84)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Using `Self::new`
</blockquote></details>

Didn't find it in my search&replace because of the `Self` usage...
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMCtc4E0JTLxZ_r0ZN:-NxMGSyJ0glKg1CQ9QUc:b-k4xugm) ([raw file](https://github.com/starkware-libs/committer/blob/e7358dc96d190bab1821ff2e3789ccc67d63efb4/crates/committer/src/patricia_merkle_tree/types.rs#L13)):*
> ```XML
> 
> pub const MAX_HEIGHT: u8 = 251;
> static MAX_INDEX: Lazy<U256> = Lazy::new(|| (U256::ONE << (MAX_HEIGHT + 1)) - U256::ONE);
> ```

Why? I think it's better for the consts/statics related to a struct to be in it if possible. How about this?
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMD8t3CKoDRr3RJXRS:-NxMEsCY0NPRzA8MCz6U:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e7358dc96d190bab1821ff2e3789ccc67d63efb4/crates/committer/src/patricia_merkle_tree/types.rs#L40)):*
> ```XML
>     pub(crate) fn new(index: U256) -> Self {
>         if index > *MAX_INDEX {
>             panic!("Index is too large.");
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMDGy27ulWbYVmlUg7:-NxMF9G22ulf1RTa_3Bu:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e7358dc96d190bab1821ff2e3789ccc67d63efb4/crates/committer/src/patricia_merkle_tree/types.rs#L47)):*
> ```XML
>     pub(crate) fn highest_index() -> NodeIndex {
>         NodeIndex(*MAX_INDEX)
>     }
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMEL3YBHh1RYb2Sp4U:-NxMFtdFBZmLZltp3igp:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e7358dc96d190bab1821ff2e3789ccc67d63efb4/crates/committer/src/patricia_merkle_tree/types.rs#L100)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

while you're here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-08 08:37 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: 8 of 10 files reviewed, 9 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxI83v4BCD8hVwhSq07:-NxMKjIQ4UxWAwjdkIwz:b-etvc6w) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L13)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I don't understand what is written in your proposal. Is it supposed to be more readable? :confused: 
And I CAN'T USE << (a non const function) in NodeIndex as we can't define a static there (and we can't use if for const in general)
</blockquote></details>

This line works, I checked. The >> operates on `u128`
It is similar to the way U256 defined MAX (`pub const MAX: Self = Self([!0; 2]);`).
The goal is do avoid `Lazy` and to define our MAXas const as well.


<!-- Sent from Reviewable.io -->

2024-05-08 08:37 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: 8 of 10 files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-05-08 08:39 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: 8 of 10 files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxJ-urt88iIMLHkIgI6:-NxMLlPKE_YbrL7skxmB:b8uuw1w) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L80)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

It's not safe in general (as two NodeIndices can overflow the 252 bit limitations).
As a side note I think we should enforce the hight limitation in TreeHeight as done in NodeIndex (and in other strcuts if there are any).
Not sure what to do here ATM.
</blockquote></details>

@TzahiTaub do we use this addition anywhere outside this file?


<!-- Sent from Reviewable.io -->

2024-05-08 08:53 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMOgJi7weA81tyOgf9:-NxMOgJi7weA81tyOgfA:brohh78) ([raw file](https://github.com/starkware-libs/committer/blob/099e62491375d102ceb3b5c90175734fbc170c86/crates/committer/src/patricia_merkle_tree/types.rs#L52)):*
> ```XML
>     pub(crate) fn index(&self) -> U256 {
>         self.0
>     }
> ```

why not `impl From<NodeIndex> for U256`? it's safe (the other way around is unsafe)



_Code quote:_
```XML
    /// Returns the index as U256.
    pub(crate) fn index(&self) -> U256 {
        self.0
    }
```


<!-- Sent from Reviewable.io -->

2024-05-08 09:37 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxI83v4BCD8hVwhSq07:-NxMTnAe6ExhoBbqq513:bnapi9o) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L13)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This line works, I checked. The >> operates on `u128`
It is similar to the way U256 defined MAX (`pub const MAX: Self = Self([!0; 2]);`).
The goal is do avoid `Lazy` and to define our MAXas const as well.
</blockquote></details>

Uhhh, OK then. Changed to u128::MAX, seems less confusing to me (ATM).
You've just searched for `const fn from` in U256?
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxJ-urt88iIMLHkIgI6:-NxMYb2v3EMZ4ORrnV_A:b-kohol1) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L80)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@TzahiTaub do we use this addition anywhere outside this file?
</blockquote></details>

Yes. Not sure how to find all usages, but there are some, e.g., in `updated_skeleton_tree/tree.rs`
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMOgJi7weA81tyOgf9:-NxMXpW73xsuASqru5Ic:b-e816j6) ([raw file](https://github.com/starkware-libs/committer/blob/099e62491375d102ceb3b5c90175734fbc170c86/crates/committer/src/patricia_merkle_tree/types.rs#L52)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not `impl From<NodeIndex> for U256`? it's safe (the other way around is unsafe)
</blockquote></details>

I don't know, it's not really a conversion but a getter. Does this options seem more "rust appropriate"?


<!-- Sent from Reviewable.io -->

2024-05-08 09:47 UTC, TzahiTaub commented
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMaFDCA-vvrRjRKqpl:-NxMaFDCA-vvrRjRKqpm:bw10dgl) ([raw file](https://github.com/starkware-libs/committer/blob/bc2f4bf91b4dae8fea40ee927ff150e739db65a4/crates/committer/src/patricia_merkle_tree/types.rs#L90)):*
> ```XML
> 
>     fn from_leaf_felt(felt: &Felt, tree_height: &TreeHeight) -> Self {
>         Self(U256::ONE << tree_height.0) + (*felt).into()
> ```

Had some conflicts with a recent merge to main - fixed accordingly.



_Code quote:_
```XML
 (*felt).into()
```


<!-- Sent from Reviewable.io -->

2024-05-08 09:49 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: 8 of 10 files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxI83v4BCD8hVwhSq07:-NxMZeBa1av4wquISe7V:butbjvy) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L13)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Uhhh, OK then. Changed to u128::MAX, seems less confusing to me (ATM).
You've just searched for `const fn from` in U256?
</blockquote></details>

I wrote `U256::MAX` and went to the impl
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMZtep3xJAHb2C61W2:-NxMZtep3xJAHb2C61W3:b-xk97kv) ([raw file](https://github.com/starkware-libs/committer/blob/77a6c14463e4efcdce2ee8d62f3e8a07465a252e/crates/committer/src/patricia_merkle_tree/types.rs#L34)):*
> ```XML
>     #[allow(clippy::as_conversions)]
>     pub const MAX_INDEX: Self = Self(U256::from_words(
>         u128::MAX >> (U256::BITS - Self::BITS as u32),
> ```

We don't use `as` at all (bad practice).
I think it's time to store `BITS` in u32



_Code quote:_
```XML
Self::BITS as u32
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/committer/100#-NxM_zZd-6CtPscbAPOF:-NxM_zZd-6CtPscbAPOG:b-xfo3bd) ([raw file](https://github.com/starkware-libs/committer/blob/77a6c14463e4efcdce2ee8d62f3e8a07465a252e/crates/committer/src/patricia_merkle_tree/types.rs#L36)):*
> ```XML
>         u128::MAX >> (U256::BITS - Self::BITS as u32),
>         u128::MAX,
>     ));
> ```

A nice convention from SN API repo.



_Suggestion:_
```XML
impl NodeIndex {
    pub const BITS: u8 = MAX_HEIGHT + 1;
    
    /// [NodeIndex] constant that represents the root index.
    pub const ROOT: Self = Self(U256::ONE);
    
    /// [NodeIndex] constant that represents the largest index in a tree.
    #[allow(clippy::as_conversions)]
    pub const MAX_INDEX: Self = Self(U256::from_words(
        u128::MAX >> (U256::BITS - Self::BITS as u32),
        u128::MAX,
    ));
```


<!-- Sent from Reviewable.io -->

2024-05-08 09:52 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: 8 of 10 files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxJ-urt88iIMLHkIgI6:-NxMbKRe5EfCDXokGAl-:b9tb8wr) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L80)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Yes. Not sure how to find all usages, but there are some, e.g., in `updated_skeleton_tree/tree.rs`
</blockquote></details>

So I think you should impl these by yourself
```
    derive_more::Add,
    derive_more::BitAnd,
    derive_more::Mul,
    derive_more::Sub,
```
(not a big deal)


<!-- Sent from Reviewable.io -->

2024-05-08 10:45 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMOgJi7weA81tyOgf9:-NxMnUu3Ct6w100-vQHW:b-cwfbbx) ([raw file](https://github.com/starkware-libs/committer/blob/099e62491375d102ceb3b5c90175734fbc170c86/crates/committer/src/patricia_merkle_tree/types.rs#L52)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I don't know, it's not really a conversion but a getter. Does this options seem more "rust appropriate"?
</blockquote></details>

I think so.
NodeIndex -> U256 is a "natural conversion"
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMZtep3xJAHb2C61W2:-NxMn7CaC5qzrxNhsB--:b-r0z4az) ([raw file](https://github.com/starkware-libs/committer/blob/77a6c14463e4efcdce2ee8d62f3e8a07465a252e/crates/committer/src/patricia_merkle_tree/types.rs#L34)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

We don't use `as` at all (bad practice).
I think it's time to store `BITS` in u32
</blockquote></details>

@Yoni-Starkware `u32::from` is not const unfortunately; uint conversions in const expressions use `as` (see blockifier for examples)


<!-- Sent from Reviewable.io -->

2024-05-08 10:50 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/committer/100#-NxJ-urt88iIMLHkIgI6:-NxMiN8pA1UrzvXTvrJ4:b-no0gti) ([raw file](https://github.com/starkware-libs/committer/blob/489e2b0c9f3f2776414e9cc7612648942d217dcb/crates/committer/src/patricia_merkle_tree/types.rs#L80)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

So I think you should impl these by yourself
```
    derive_more::Add,
    derive_more::BitAnd,
    derive_more::Mul,
    derive_more::Sub,
```
(not a big deal)
</blockquote></details>

I think Add and Mul are sufficient (the rest can only decrease numbers)
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMOgJi7weA81tyOgf9:-NxModhy2iP32ca5mKfH:b3upa66) ([raw file](https://github.com/starkware-libs/committer/blob/099e62491375d102ceb3b5c90175734fbc170c86/crates/committer/src/patricia_merkle_tree/types.rs#L52)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think so.
NodeIndex -> U256 is a "natural conversion"
</blockquote></details>

Alrighty then.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMZtep3xJAHb2C61W2:-NxMezg33KGLefl3Xjtg:b-j7w57b) ([raw file](https://github.com/starkware-libs/committer/blob/77a6c14463e4efcdce2ee8d62f3e8a07465a252e/crates/committer/src/patricia_merkle_tree/types.rs#L34)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

We don't use `as` at all (bad practice).
I think it's time to store `BITS` in u32
</blockquote></details>

This causes a chain reaction to that everything needs to be u32 or converted from u8 (TREE_HEIGHT, bit_length, leading_zeros, maybe more). Why not allow `as` usage in special casses when you don't lose accuracy (I do need to suppress clippy explicitly so it seems like a reasonable "do if you're sure its OK" thing).


<!-- Sent from Reviewable.io -->

2024-05-08 10:55 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 96 at r6](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMp_wdC8CElV7EyJGe:-NxMp_wdC8CElV7EyJGf:bqjmler) ([raw file](https://github.com/starkware-libs/committer/blob/a18065584bcba6b9df82d6ef40fafc5dd526d06f/crates/committer/src/patricia_merkle_tree/types.rs#L96)):*
> ```XML
>         Self::new(self.0 * rhs.0)
>     }
> }
> ```

does `U256` panic on overflow?
I think we'll want to panic.
1. If U256 already panics then @Yoni-Starkware I think using the `derive` was just as good
2. If not, please panic explicitly



_Code quote:_
```XML
impl std::ops::Add for NodeIndex {
    type Output = Self;

    fn add(self, rhs: Self) -> Self {
        Self::new(self.0 + rhs.0)
    }
}

impl std::ops::Mul for NodeIndex {
    type Output = Self;

    fn mul(self, rhs: Self) -> Self {
        Self::new(self.0 * rhs.0)
    }
}
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMpiML6nsZwnmfRO33:-NxMpiML6nsZwnmfRO34:b-udy2jf) ([raw file](https://github.com/starkware-libs/committer/blob/a18065584bcba6b9df82d6ef40fafc5dd526d06f/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L57)):*
> ```XML
>         let child_direction_mask = U256::ONE << (root_height.0 - 1);
>         (U256::from(first_leaf) & child_direction_mask)
>             != (U256::from(*last_leaf) & child_direction_mask)
> ```

or not, your call, non-blocking



_Suggestion:_
```XML
        let child_direction_mask = U256::ONE << (root_height.0 - 1);
        (child_direction_mask & first_leaf.into())
            != (child_direction_mask & last_leaf.into())
```


<!-- Sent from Reviewable.io -->

2024-05-08 10:57 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 96 at r6](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMp_wdC8CElV7EyJGe:-NxMqJ1647Cc32uVnqGB:bwhurtm) ([raw file](https://github.com/starkware-libs/committer/blob/a18065584bcba6b9df82d6ef40fafc5dd526d06f/crates/committer/src/patricia_merkle_tree/types.rs#L96)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does `U256` panic on overflow?
I think we'll want to panic.
1. If U256 already panics then @Yoni-Starkware I think using the `derive` was just as good
2. If not, please panic explicitly
</blockquote></details>

It does, thats why `Sub` is fine, but we want to avoid an overflow of NodeIndex (252 bits) and not U256.


<!-- Sent from Reviewable.io -->

2024-05-08 10:57 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMpiML6nsZwnmfRO33:-NxMqWBw7VvbSmyZJFvo:bljqtu3) ([raw file](https://github.com/starkware-libs/committer/blob/a18065584bcba6b9df82d6ef40fafc5dd526d06f/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L57)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

or not, your call, non-blocking
</blockquote></details>

Tried that before, didn't work (it needs an explicit type in any case)


<!-- Sent from Reviewable.io -->

2024-05-08 11:16 UTC, Yoni-Starkware reviewed
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMZtep3xJAHb2C61W2:-NxMpkpY1iSZBnvYtuWw:b-px4nwg) ([raw file](https://github.com/starkware-libs/committer/blob/77a6c14463e4efcdce2ee8d62f3e8a07465a252e/crates/committer/src/patricia_merkle_tree/types.rs#L34)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

This causes a chain reaction to that everything needs to be u32 or converted from u8 (TREE_HEIGHT, bit_length, leading_zeros, maybe more). Why not allow `as` usage in special casses when you don't lose accuracy (I do need to suppress clippy explicitly so it seems like a reasonable "do if you're sure its OK" thing).
</blockquote></details>

Okay, that sounds reasonable.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 96 at r6](https://reviewable.io/reviews/starkware-libs/committer/100#-NxMp_wdC8CElV7EyJGe:-NxMrY1MBEVTj_2TEA-B:b27fazn) ([raw file](https://github.com/starkware-libs/committer/blob/a18065584bcba6b9df82d6ef40fafc5dd526d06f/crates/committer/src/patricia_merkle_tree/types.rs#L96)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

It does, thats why `Sub` is fine, but we want to avoid an overflow of NodeIndex (252 bits) and not U256.
</blockquote></details>

Yeah, what @TzahiTaub said


<!-- Sent from Reviewable.io -->

2024-05-08 11:33 UTC, Yoni-Starkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: 6 of 10 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-05-08 11:34 UTC, Yoni-Starkware reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 6 files at r2, 1 of 2 files at r4, 3 of 4 files at r6, 3 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100#-:-NxMz-bF6imuDj33bKBK:bnfp4nl)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-05-08 11:42 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 8 at r7](https://reviewable.io/reviews/starkware-libs/committer/100#-NxN-HVmAYUTUbAzwHke:-NxN-HVmAYUTUbAzwHkf:bhtjlo) ([raw file](https://github.com/starkware-libs/committer/blob/1fd20f3e6cbf53bd7b1859598b284499aac5b64c/crates/committer/src/patricia_merkle_tree/types.rs#L8)):*
> ```XML
> use ethnum::U256;
> 
> use super::node_data::inner_node::EdgePath;
> ```

don't use `super` outside of tests



_Code quote:_
```XML
use super::node_data::inner_node::EdgePath;
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 52 at r7](https://reviewable.io/reviews/starkware-libs/committer/100#-NxN-Zt19MTDCXVt72C5:-NxN-Zt19MTDCXVt72C6:bm6ynbd) ([raw file](https://github.com/starkware-libs/committer/blob/1fd20f3e6cbf53bd7b1859598b284499aac5b64c/crates/committer/src/patricia_merkle_tree/types.rs#L52)):*
> ```XML
>     ) -> NodeIndex {
>         let PathToBottom { path, length } = path_to_bottom;
>         (index << length.0) + (*path).into()
> ```

make this explicit



_Code quote:_
```XML
(*path).into()
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 143 at r7](https://reviewable.io/reviews/starkware-libs/committer/100#-NxN-bBW8eoQ31OVaNUq:-NxN-bBXEYAFTs7o4xTH:bkutiwa) ([raw file](https://github.com/starkware-libs/committer/blob/1fd20f3e6cbf53bd7b1859598b284499aac5b64c/crates/committer/src/patricia_merkle_tree/types.rs#L143)):*
> ```XML
>         Self::new(U256::from_be_bytes(value.0.to_bytes_be()))
>     }
> }
> ```

remove (see above)



_Code quote:_
```XML
impl From<EdgePath> for NodeIndex {
    fn from(value: EdgePath) -> Self {
        Self::new(U256::from_be_bytes(value.0.to_bytes_be()))
    }
}
```


<!-- Sent from Reviewable.io -->

2024-05-08 12:12 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 8 at r7](https://reviewable.io/reviews/starkware-libs/committer/100#-NxN-HVmAYUTUbAzwHke:-NxN4xqt1XV-dJvpm7Ue:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/1fd20f3e6cbf53bd7b1859598b284499aac5b64c/crates/committer/src/patricia_merkle_tree/types.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't use `super` outside of tests
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 52 at r7](https://reviewable.io/reviews/starkware-libs/committer/100#-NxN-Zt19MTDCXVt72C5:-NxN5M0O0dB4kZ9TicE_:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/1fd20f3e6cbf53bd7b1859598b284499aac5b64c/crates/committer/src/patricia_merkle_tree/types.rs#L52)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

make this explicit
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 143 at r7](https://reviewable.io/reviews/starkware-libs/committer/100#-NxN-bBW8eoQ31OVaNUq:-NxN5O9S31G1noxec8N2:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/1fd20f3e6cbf53bd7b1859598b284499aac5b64c/crates/committer/src/patricia_merkle_tree/types.rs#L143)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

remove (see above)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-08 12:30 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 50 at r8](https://reviewable.io/reviews/starkware-libs/committer/100#-NxNAc235alrmklX6I1G:-NxNAc235alrmklX6I1H:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/5f7259de6cb2b74fb07b5f8c0552d57cd8f87e3d/crates/committer/src/patricia_merkle_tree/types.rs#L50)):*
> ```XML
>     ) -> NodeIndex {
>         let PathToBottom { path, length } = path_to_bottom;
>         (index << length.0) + Self::new(U256::from_be_bytes(path.0.to_bytes_be()))
> ```





_Suggestion:_
```XML
Self::from_felt_value(path.0)
```


<!-- Sent from Reviewable.io -->

2024-05-08 12:35 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 50 at r8](https://reviewable.io/reviews/starkware-libs/committer/100#-NxNAc235alrmklX6I1G:-NxNBnxKBqcie-Zq2q34:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/5f7259de6cb2b74fb07b5f8c0552d57cd8f87e3d/crates/committer/src/patricia_merkle_tree/types.rs#L50)):*
> ```XML
>     ) -> NodeIndex {
>         let PathToBottom { path, length } = path_to_bottom;
>         (index << length.0) + Self::new(U256::from_be_bytes(path.0.to_bytes_be()))
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-08 12:56 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/100#-:-NxNGhxf7nEdXiugbVu8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-05-08 13:08 UTC, merged