feat!: add and use Modifications type
starkware-libs/committer pull request #122
Opened 2024-05-17 09:52 UTC by dorimedini-starkware

2024-05-17 09:57 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/122)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/committer/122#-Ny4yEzuDL1ZYR_kXhEg:-Ny4yEzuDL1ZYR_kXhEh:bjr455) ([raw file](https://github.com/starkware-libs/committer/blob/6c5ab9b2d9197b58373330c43438d8e1bd8cb3e3/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L169)):*
> ```XML
>             }
>             UpdatedSkeletonNode::Sibling(hash_result) => Ok(*hash_result),
>             UpdatedSkeletonNode::Leaf(_) => {
> ```

after this change, the creation of a filled tree from an updated skeleton tree no longer requires the leaf values from the skeleton.



_Code quote:_
```XML
Leaf(_)
```


<!-- Sent from Reviewable.io -->

2024-05-19 08:21 UTC, amosStarkware reviewed
IMO the `FilledTree` should compute the filled leaves.
WYT of adding a method: `FilledTree::compute_filled_leaves(...) -> &Modifications`?
possible signature for``FilledTree::from_updated_skeleton_tree()`:
`from_updated_skeleton_tree<H: HashFunction, TH: TreeHashFunction<L, H>, D>(&self, additional_data: Option<&D>)`.

can be done after merging stack.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/122#-:-NyEukKN5hTkwru3O09O:br1xg4o)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-05-19 08:30 UTC, dorimedini-starkware reviewed
Modifications are computed directly from the state diff / computed storage roots, why should the tree trait be responsible for this computation?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/122#-:-NyEy53r58qWreGV6O12:b-rt8zby)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-05-19 12:14 UTC, TzahiTaub requested changes
> Reviewed 2 of 6 files at r1, 5 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/122)* status: 7 of 9 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFhvQqDoYLigKd__5_:-NyFhvQrAhCZ8H_-i1YA:bwx4hk6) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L8)):*
> ```XML
> use crate::patricia_merkle_tree::types::NodeIndex;
> 
> pub trait LeafData: Clone {
> ```

Why is this important?



_Code quote:_
```XML
 Clone
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFhD8k1SNb9d6Sv-of:-NyFhD8k1SNb9d6Sv-og:b3kre) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L78)):*
> ```XML
> }
> 
> pub(crate) type Modifications<L> = HashMap<NodeIndex, L>;
> ```

?



_Suggestion:_
```XML
pub(crate) type Modifications<L: LeafData> = HashMap<NodeIndex, L>;
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFhitCAI2k9wgo8c93:-NyFhitCAI2k9wgo8c94:b-r8jnpm) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L18)):*
> ```XML
>     pub(crate) fn compute_updated_skeleton_tree_impl(
>         &self,
>         _index_to_updated_leaf: &Modifications<L>,
> ```

Thats how we define the  modifications type.



_Suggestion:_
```XML
 _modifications: &Modifications<L>,
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 177 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFi4Al2415M4dDeY-n:-NyFi4Al2415M4dDeY-o:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L177)):*
> ```XML
> fn test_fetch_nodes(
>     #[case] storage: MapStorage,
>     #[case] leaf_modifications: Modifications<LeafDataImpl>,
> ```





_Suggestion:_
```XML
modifications: Modifications<LeafDataImpl>,
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFiMUO9cfH9_BiAMNf:-NyFiMUP0U8eQg9mTtS2:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L36)):*
> ```XML
>     fn compute_updated_skeleton_tree(
>         &self,
>         index_to_updated_leaf: &Modifications<L>,
> ```





_Suggestion:_
```XML
modifications: &Modifications<L>,
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFiObl3XLorby4n3XQ:-NyFiObl3XLorby4n3XR:bb7od0r) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L61)):*
> ```XML
>     fn compute_updated_skeleton_tree(
>         &self,
>         index_to_updated_leaf: &Modifications<L>,
> ```

same



_Code quote:_
```XML
 index_to_updated_leaf: &Modifications<L>,
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/committer/122#-Ny4yEzuDL1ZYR_kXhEg:-NyFisrqEzRjetTgTevM:b-31schk) ([raw file](https://github.com/starkware-libs/committer/blob/6c5ab9b2d9197b58373330c43438d8e1bd8cb3e3/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L169)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

after this change, the creation of a filled tree from an updated skeleton tree no longer requires the leaf values from the skeleton.
</blockquote></details>

It might be a good idea to assert that the original data (empty/non-empty) equals the extracted `data.is_empty()` to catch possible bugs.


<!-- Sent from Reviewable.io -->

2024-05-19 12:15 UTC, TzahiTaub reviewed
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/122)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-05-19 12:32 UTC, amosStarkware requested changes
> Reviewed 1 of 6 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/122)* status: all files reviewed, 15 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFjyx8BhJYkCA7h-2I:-NyFjyx8BhJYkCA7h-2J:b-wro6r7) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L78)):*
> ```XML
> }
> 
> pub(crate) type Modifications<L> = HashMap<NodeIndex, L>;
> ```

IMO this is more readable, when encountering this type across the code



_Code quote (i):_
```XML
pub(crate) type Modifications<L> = HashMap<NodeIndex, L>;
```



_Suggestion (ii):_
```XML
pub(crate) type LeafModifications<L> = HashMap<NodeIndex, L>;
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFgHnh0AI5MtTqvC5E:-NyFgHnh0AI5MtTqvC5F:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L18)):*
> ```XML
>     pub(crate) fn compute_updated_skeleton_tree_impl(
>         &self,
>         _index_to_updated_leaf: &Modifications<L>,
> ```





_Code quote (i):_
```XML
_index_to_updated_leaf: &Modifications<L>,
```



_Suggestion (ii):_
```XML
_leaf_modifications: &Modifications<L>,
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFgtjz7xncwS2-M07E:-NyFgtk-A5RIczQQ2J2f:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L41)):*
> ```XML
>     fn compute_updated_skeleton_forest<U: UpdatedSkeletonTree<L>>(
>         &self,
>         class_hash_to_compiled_class_hash: &Modifications<L>,
> ```





_Code quote (i):_
```XML
class_hash_to_compiled_class_hash: &Modifications<L>,
```



_Suggestion (ii):_
```XML
class_hash_leaf_modifications: &Modifications<L>,
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFhY3DAVxKpoZTlHfm:-NyFhY3DAVxKpoZTlHfn:b-7ropln) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L105)):*
> ```XML
>     fn compute_updated_skeleton_forest<U: UpdatedSkeletonTree<L>>(
>         &self,
>         _class_hash_to_compiled_class_hash: &Modifications<L>,
> ```

ditto



_Code quote:_
```XML
_class_hash_to_compiled_class_hash: &Modifications<L>,
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFiSjI2FcmC8X4VeZ1:-NyFiSjI2FcmC8X4VeZ2:b-7ropln) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L36)):*
> ```XML
>     fn compute_updated_skeleton_tree(
>         &self,
>         index_to_updated_leaf: &Modifications<L>,
> ```

ditto
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFiVbe292rFyxr9k9i:-NyFiVbe292rFyxr9k9j:b-7ropln) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L61)):*
> ```XML
>     fn compute_updated_skeleton_tree(
>         &self,
>         index_to_updated_leaf: &Modifications<L>,
> ```

ditto



_Code quote:_
```XML
index_to_updated_leaf: &Modifications<L>,
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFilkD2jSfDn2h53_E:-NyFilkD2jSfDn2h53_F:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L31)):*
> ```XML
>     async fn compute_filled_tree<H: HashFunction, TH: TreeHashFunction<L, H>>(
>         &self,
>         modifications: &Modifications<L>,
> ```





_Code quote (i):_
```XML
modifications: &Modifications<L>,
```



_Suggestion (ii):_
```XML
leaf_modifications: &Modifications<L>,
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFixi6-hnD7XZFJBmP:-NyFixi6-hnD7XZFJBmQ:b-7ropln) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L116)):*
> ```XML
>         &self,
>         index: NodeIndex,
>         modifications: &Modifications<L>,
> ```

ditto



_Code quote:_
```XML
modifications: &Modifications<L>,
```


<!-- Sent from Reviewable.io -->

2024-05-19 12:40 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/122)* status: all files reviewed, 12 unresolved discussions (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFhvQqDoYLigKd__5_:-NyFqsiX3RNvk-KXASbH:b-szv3g8) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L8)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Why is this important?
</blockquote></details>

not needed :) removed
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFhD8k1SNb9d6Sv-of:-NyFmPf60Uz5wfalecis:b-y3nc21) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L78)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

?
</blockquote></details>

tried, but no trait enforcement on type declarations
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFjyx8BhJYkCA7h-2I:-NyFqvbUC4LwZGVb8GwT:b-fapiig) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L78)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

IMO this is more readable, when encountering this type across the code
</blockquote></details>

@TzahiTaub WDYT? I'm neutral
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFhitCAI2k9wgo8c93:-NyFmt220VaDSFYgCAWq:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L18)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Thats how we define the  modifications type.
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFgHnh0AI5MtTqvC5E:-NyFrauPDviDMZCvF7oG:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L18)):*
> ```XML
>     pub(crate) fn compute_updated_skeleton_tree_impl(
>         &self,
>         _index_to_updated_leaf: &Modifications<L>,
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 177 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFi4Al2415M4dDeY-n:-NyFmzmV-FtqC3ElqNTp:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L177)):*
> ```XML
> fn test_fetch_nodes(
>     #[case] storage: MapStorage,
>     #[case] leaf_modifications: Modifications<LeafDataImpl>,
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFgtjz7xncwS2-M07E:-NyFrTB5-OIN-qfByGQ2:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L41)):*
> ```XML
>     fn compute_updated_skeleton_forest<U: UpdatedSkeletonTree<L>>(
>         &self,
>         class_hash_to_compiled_class_hash: &Modifications<L>,
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFhY3DAVxKpoZTlHfm:-NyFrT_j16yAvtul8iBw:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L105)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFiMUO9cfH9_BiAMNf:-NyFn4v_5FWD_Pfy0u4M:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L36)):*
> ```XML
>     fn compute_updated_skeleton_tree(
>         &self,
>         index_to_updated_leaf: &Modifications<L>,
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFiSjI2FcmC8X4VeZ1:-NyFrV2f5FyX8k2HlpMi:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L36)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFiObl3XLorby4n3XQ:-NyFn5LE3-tHx1mpXh0i:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L61)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFiVbe292rFyxr9k9i:-NyFrW9b4yQKmQymiqss:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L61)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFilkD2jSfDn2h53_E:-NyFqiCtCuo6n7jMPdlO:b-i7mdyl) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L31)):*
> ```XML
>     async fn compute_filled_tree<H: HashFunction, TH: TreeHashFunction<L, H>>(
>         &self,
>         modifications: &Modifications<L>,
> ```

@TzahiTaub @amosStarkware please sync :)
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFixi6-hnD7XZFJBmP:-NyFql8b4TER1yfVbfeI:byr4ffv) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L116)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

see above


<!-- Sent from Reviewable.io -->

2024-05-19 12:50 UTC, TzahiTaub requested changes
> Reviewed 7 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/122)* status: 9 of 10 files reviewed, 9 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFjyx8BhJYkCA7h-2I:-NyFt8PY9iMSe71M1O27:b-31wmwy) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L78)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@TzahiTaub WDYT? I'm neutral
</blockquote></details>

Guess its clearer if you have no context.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 225 at r3](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFtSvCB4ofYBXlu8sl:-NyFtSvD08m7IwJr8fka:bak1q1c) ([raw file](https://github.com/starkware-libs/committer/blob/65d6e09ec5786e5d34548baf0757676189f9d505/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L225)):*
> ```XML
> }
> 
> fn create_modifications(modifications: Vec<(u128, u128)>) -> LeafModifications<LeafDataImpl> {
> ```

I suggest search & replace in the entire code to avoid confusion.



_Suggestion:_
```XML
leaf_modifications
```


<!-- Sent from Reviewable.io -->

2024-05-19 12:51 UTC, TzahiTaub reviewed
> Reviewed 1 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/122)* status: all files reviewed, 9 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-05-19 12:54 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/122)* status: 9 of 10 files reviewed, 9 unresolved discussions (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFjyx8BhJYkCA7h-2I:-NyFuHZxCmCnzlvXOC6w:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L78)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Guess its clearer if you have no context.
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 225 at r3](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFtSvCB4ofYBXlu8sl:-NyFugH16v3uboJDRr3p:bngputx) ([raw file](https://github.com/starkware-libs/committer/blob/65d6e09ec5786e5d34548baf0757676189f9d505/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L225)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I suggest search & replace in the entire code to avoid confusion.
</blockquote></details>

done.
have some variables in tests called `modifications` but that's ok IMO


<!-- Sent from Reviewable.io -->

2024-05-19 13:25 UTC, amosStarkware requested changes
> Reviewed 1 of 6 files at r1, 7 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/122)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFhvQqDoYLigKd__5_:-NyFxlgH16en9euPUfqc:bbw5vhc) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not needed :) removed
</blockquote></details>

why isn't it needed? it looks to me like `compute_filled_tree` assumes leaves can be cloned
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/committer/122#-NyG0TwO3lnXDs7CWYQe:-NyG0TwO3lnXDs7CWYQf:beaghd5) ([raw file](https://github.com/starkware-libs/committer/blob/d7a7fdfab8f910247068c533b250a89f99d8f6b5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs#L17)):*
> ```XML
>     // TODO(Dori, 1/6/2024): Add existing node value + modification values to the inconsistency
>     //   error.
>     InconsistentModification(NodeIndex),
> ```

add a message for these two errors / a TODO to add one?
also - why is this better than panicking? how can the code recover?



_Code quote:_
```XML
InconsistentModification(NodeIndex),
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFilkD2jSfDn2h53_E:-NyFx9zQEMYNjFrDaWjb:b-j6iomj) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L31)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@TzahiTaub @amosStarkware please sync :)
</blockquote></details>

@TzahiTaub you wanted something else?


<!-- Sent from Reviewable.io -->

2024-05-19 17:30 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/122)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFhvQqDoYLigKd__5_:-NyGt3jfBBjcdvzhaRfn:b-y9b83i) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L8)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why isn't it needed? it looks to me like `compute_filled_tree` assumes leaves can be cloned
</blockquote></details>

the definition of the `UpdatedSkeletonTree` trait enforces the `Clone`.
```
pub(crate) trait UpdatedSkeletonTree<L: LeafData + std::clone::Clone> { ... }
```
there are many such explicit `LeafData + std::clone::Clone` trait bindings, which are removed by [the end of the stack](https://reviewable.io/reviews/starkware-libs/committer/126) for unrelated reasons.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/committer/122#-NyG0TwO3lnXDs7CWYQe:-NyGsMXG6EQrMBPczy2f:brqoplc) ([raw file](https://github.com/starkware-libs/committer/blob/d7a7fdfab8f910247068c533b250a89f99d8f6b5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs#L17)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

add a message for these two errors / a TODO to add one?
also - why is this better than panicking? how can the code recover?
</blockquote></details>

1. [this PR](https://reviewable.io/reviews/starkware-libs/committer/125) adds `thiserror::Error` and `#[error]` attributes (later in the stack)
2. in theory, the caller can choose to add more modifications data on error... not that I can think of a use case.
I'm fine with reverting to panic, but it feels more natural to me to panic at the caller side, because the API doesn't actually enforce (by type system, compiler errors etc) that all expected modification indices exist in the hashmap.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFilkD2jSfDn2h53_E:-NyGszgY4kM_3vZU8KTl:b-wjbhan) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L31)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

@TzahiTaub you wanted something else?
</blockquote></details>

nope, done


<!-- Sent from Reviewable.io -->

2024-05-19 20:00 UTC, TzahiTaub approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/122#-:-NyHRJZY4KNCMXrwlgX3:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-05-20 07:31 UTC, amosStarkware approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/122)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/committer/122#-NyFhvQqDoYLigKd__5_:-NyJsl-_1n0bcmE9tPlu:b-8o9pkj) ([raw file](https://github.com/starkware-libs/committer/blob/efe052b132efb55ec5ee7c2fea3d5d4fdef7f04d/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the definition of the `UpdatedSkeletonTree` trait enforces the `Clone`.
```
pub(crate) trait UpdatedSkeletonTree<L: LeafData + std::clone::Clone> { ... }
```
there are many such explicit `LeafData + std::clone::Clone` trait bindings, which are removed by [the end of the stack](https://reviewable.io/reviews/starkware-libs/committer/126) for unrelated reasons.
</blockquote></details>

since it's not possible to implement `FilledTree::from_updated_skeleton_tree()` if the leaf doesn't implement clone, the `FilledTree` / `LeafData` trait should require it. no?
you can add this requirement to Filled tree to top of the stack if you want
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/committer/122#-NyG0TwO3lnXDs7CWYQe:-NyJqk5w8IqXyRy9Fv2P:b-ldtvz5) ([raw file](https://github.com/starkware-libs/committer/blob/d7a7fdfab8f910247068c533b250a89f99d8f6b5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. [this PR](https://reviewable.io/reviews/starkware-libs/committer/125) adds `thiserror::Error` and `#[error]` attributes (later in the stack)
2. in theory, the caller can choose to add more modifications data on error... not that I can think of a use case.
I'm fine with reverting to panic, but it feels more natural to me to panic at the caller side, because the API doesn't actually enforce (by type system, compiler errors etc) that all expected modification indices exist in the hashmap.
</blockquote></details>

1. I don't see that you add anything to `InconsistentModification`, but not important enough to block


<!-- Sent from Reviewable.io -->

2024-05-20 08:09 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/122)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/committer/122#-NyG0TwO3lnXDs7CWYQe:-NyK28GL751bhDV-LTUS:b-pbekww) ([raw file](https://github.com/starkware-libs/committer/blob/d7a7fdfab8f910247068c533b250a89f99d8f6b5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs#L17)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

1. I don't see that you add anything to `InconsistentModification`, but not important enough to block
</blockquote></details>

because the error is new. when I'll rebase PR 125 I'll add it


<!-- Sent from Reviewable.io -->

2024-05-20 08:11 UTC, merged