test: forest to python
starkware-libs/committer pull request #143
Opened 2024-05-26 07:17 UTC by AvivYossef-starkware

This PR introduces the following changes:

-RandomValue and DumpyRandomValue traits: Defines methods for generating random values for types like Felt, HashOutput, LeafDataImpl, BinaryData, PathToBottom, EdgePath, EdgePathLength, EdgeData, NodeData, NodeIndex, FilledNode, FilledTreeImpl and FilledForestImpl.

- Test that outputs a random FilledForestImpl to Python.

2024-05-26 07:32 UTC, AvivYossef-starkware reviewed
Python PR https://github.com/starkware-libs/committer/pull/143/commits/d953fe4062503c12f11a7f8790a00fdd94bc34f5

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/143#-:-Nyno2RX0arvNP8o1XKK:bd5svy7)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @amosStarkware and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-05-26 08:04 UTC, dorimedini-starkware requested changes
this is the python commit, not a link to the PR :)

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/143#-:-NynvYfK3Aw5B2gwj0Zs:b9lw30s)* status: all files reviewed, 20 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer/Cargo.toml` line 28 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NynnJCWCXJq0aGAABVJ:-NynnJCWCXJq0aGAABVK:bb7onj7) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/Cargo.toml#L28)):*
> ```TOML
> thiserror.workspace = true
> tokio.workspace = true
> rand.workspace = true
> ```

sort



_Suggestion:_
```TOML
hex.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet-types-core.workspace = true
thiserror.workspace = true
tokio.workspace = true
```
___
*[`crates/committer/src/felt.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NynnY83CmHlK6fGfOs1:-NynnY83CmHlK6fGfOs2:b-6znjrz) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/felt.rs#L1)):*
> ```XML
> use derive_more::Display;
> ```

why not `std::fmt::Display`?



_Code quote:_
```XML
use derive_more::Display;
```
___
*[`crates/committer/src/patricia_merkle_tree.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-Nynv85ED6zBFTvzIBHK:-Nynv85FEKO__yPw-GeA:boikf7k) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree.rs#L7)):*
> ```XML
> pub mod types;
> pub mod updated_skeleton_tree;
> pub mod utils;
> ```

there are two options:
1. this is a module with test utils
2. this is a module for utils used in the CLI crate.
if (1), then rename this module to `test_utils` and mark it with `#[cfg(test)]`;
if (2), then move the module to the CLI crate;
if both, then split the module into part (1) (rename+mark) and part (2) (move to CLI crate)



_Code quote:_
```XML
pub mod utils;
```
___
*[`crates/committer/src/hash/hash_trait.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-Nynnb2iBQT5XdzvEMSs:-Nynnb2iBQT5XdzvEMSt:b-6znjrz) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/hash/hash_trait.rs#L2)):*
> ```XML
> use crate::felt::Felt;
> use derive_more::Display;
> ```

why not `std::fmt::Display`?



_Code quote:_
```XML
use derive_more::Display;
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-Nynud_nA7_2vQoObFTT:-Nynud_nA7_2vQoObFTU:bc2l9sx) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree/filled_tree/node.rs#L21)):*
> ```XML
> #[allow(dead_code)]
> #[derive(Clone, Debug, PartialEq, Eq, Display)]
> #[display(fmt = "FilledNode {{ hash: {}, data: {:?} }}", hash, data)]
> ```

why override the default display?
if this is for serialization, make it an explicit function, not a custom `Display`



_Code quote:_
```XML
#[display(fmt = "FilledNode {{ hash: {}, data: {:?} }}", hash, data)]
```
___
*[`crates/committer/src/patricia_merkle_tree/utils/random_structs.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NynrkWEEUr-bYxoENTg:-NynrkWEEUr-bYxoENTh:bffbnlx) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree/utils/random_structs.rs#L0)):*
many of the functions in this module don't really sound useful because you can't provide an explicit upper bound.
in tests the tree height is usually at most 4, so randomizing a node index / edge path / edge path length over the entire range is rarely useful.
consider adding an optional upper bound, like this (bound should :
```
pub trait RandomValue {
    fn random(max: Option<U256>) -> Self;
}
```
___
*[`crates/committer/src/patricia_merkle_tree/utils/random_structs.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NynpyIyDiPkjEZDvaRl:-NynpyIyDiPkjEZDvaRm:b-wf2t3s) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree/utils/random_structs.rs#L56)):*
> ```XML
> 
> pub trait RandomValue {
>     fn random() -> Self;
> ```

random functions should get injected randomness so users can control the randomness



_Suggestion:_
```XML
fn random<R: Rng>(rng: &mut R) -> Self;
```
___
*[`crates/committer/src/patricia_merkle_tree/utils/random_structs.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NynningCqFxjJ9dw9WU:-NynningCqFxjJ9dw9WV:baxxn1l) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree/utils/random_structs.rs#L59)):*
> ```XML
> }
> 
> pub trait DumpyRandomValue {
> ```

what does "dumpy" mean? if it's "dummy-for-python" then it should be in the CLI crate only



_Code quote:_
```XML
Dumpy
```
___
*[`crates/committer/src/patricia_merkle_tree/utils/random_structs.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-Nynq60f8FlW1h_-T_Ex:-Nynq60f8FlW1h_-T_Ey:byr4ffv) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree/utils/random_structs.rs#L60)):*
> ```XML
> 
> pub trait DumpyRandomValue {
>     fn dumpy_random() -> Self;
> ```

see above



_Suggestion:_
```XML
dumpy_random<R: Rng>(rng: &mut R) -> Self;
```
___
*[`crates/committer/src/patricia_merkle_tree/utils/random_structs.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyno1_73SOaU9Go6cbk:-Nyno1_73SOaU9Go6cbl:b-x5ho42) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree/utils/random_structs.rs#L65)):*
> ```XML
> impl RandomValue for Felt {
>     fn random() -> Self {
>         Felt::from(rand::random::<u128>())
> ```

this is not a uniform field element.
please use the random u256 function with an upper bound of:
```
U256::from(Felt::MAX) + 1
```



_Code quote:_
```XML
Felt::from(rand::random::<u128>())
```
___
*[`crates/committer/src/patricia_merkle_tree/utils/random_structs.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NynqC5j-wCV6FcfDflo:-NynqC5j-wCV6FcfDflp:b-ivoly9) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree/utils/random_structs.rs#L65)):*
> ```XML
> impl RandomValue for Felt {
>     fn random() -> Self {
>         Felt::from(rand::random::<u128>())
> ```

use the input RNG (see above) and not the global



_Code quote:_
```XML
rand::random::<u128>()
```
___
*[`crates/committer/src/patricia_merkle_tree/utils/random_structs.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NynosRMBBPVgmY6SLQT:-NynosRMBBPVgmY6SLQU:b-m5l537) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree/utils/random_structs.rs#L86)):*
> ```XML
>             }),
>             _ => unreachable!(),
>         }
> ```

the problem with this is it's not future-proof. if someone adds/removes an enum variant, the compiler won't catch an issue.
I suggest:
1. make the LeafDataImpl enum *iterable* using the [strum_macros crate](https://docs.rs/strum_macros/latest/strum_macros/derive.EnumIter.html) (derive `EnumIter` on the enum).
2. use the `rand` crate's [iterator choice](https://rust-random.github.io/rand/rand/seq/trait.IteratorRandom.html)  [...]

2024-05-26 13:21 UTC, AvivYossef-starkware reviewed
https://github.com/starkware-industries/starkware/pull/35062

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/143#-:-NynxnsO-TkKX28hwF8T:b-j59m28)* status: 1 of 23 files reviewed, 20 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/felt.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NynnY83CmHlK6fGfOs1:-NynzGbv0eatWKEOUTA1:b5e7ws) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/felt.rs#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not `std::fmt::Display`?
</blockquote></details>

Im not sure I understend, 
this is a trait -  `std::fmt::Display`
this is a macro that implements the trait  - 'derive_more::Display'

The reason I used it was a compiler error caused by the snippet.
I solved it without using the macro with {existing_value:?} instead of implementing Display.



_Code snippet:_
```XML
    #[error("Double update at node {index:?}. Existing value: {existing_value}.")]
    DoubleUpdate {
        index: NodeIndex,
        existing_value: Box<FilledNode<L>>,
    },
```
___
*[`crates/committer/src/patricia_merkle_tree.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-Nynv85ED6zBFTvzIBHK:-NyoKpq84864sDHQh-9a:bns8uff) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree.rs#L7)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there are two options:
1. this is a module with test utils
2. this is a module for utils used in the CLI crate.
if (1), then rename this module to `test_utils` and mark it with `#[cfg(test)]`;
if (2), then move the module to the CLI crate;
if both, then split the module into part (1) (rename+mark) and part (2) (move to CLI crate)
</blockquote></details>

I did 2 , with a feature as discussed 
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-Nynud_nA7_2vQoObFTT:-Nyo2QIt3P9Ar3NuB4Fy:b-q64pkt) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree/filled_tree/node.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why override the default display?
if this is for serialization, make it an explicit function, not a custom `Display`
</blockquote></details>

See above.
___
*[`crates/committer_cli/src/filled_tree_output/filled_forest.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NyntWUL-BkyF4OBwXJn:-NyozjpH28n2sO2iA328:b-5hancu) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer_cli/src/filled_tree_output/filled_forest.rs#L11)):*
> ```XML
> impl SerializedForest {
>     #[allow(dead_code)]
>     pub fn forest_to_python(&self) -> Result<(), FilledForestError<LeafDataImpl>> {
> ```

But I use it in the committer_cli
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NyntcceDfWja2SnfwK0:-NyozrQ2-u07bKSc4hsd:b-896fjx) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer_cli/src/tests/python_tests.rs#L67)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you do not know at this point what exactly the filled tree error is; maybe it's not related to output printing?
when wrapping internal errors IMO the only valid option is naming the enum variant after the inner error enum name
</blockquote></details>

Done
___
*[`crates/committer/src/hash/hash_trait.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-Nynnb2iBQT5XdzvEMSs:-Nyo-chD2n3l6jLodDmY:b-q64pkt) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/hash/hash_trait.rs#L2)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not `std::fmt::Display`?
</blockquote></details>

See above.
___
*[`crates/committer/src/patricia_merkle_tree/utils/random_structs.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NynpyIyDiPkjEZDvaRl:-Nyp0SMJ6_570VICwFEh:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree/utils/random_structs.rs#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

random functions should get injected randomness so users can control the randomness
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/utils/random_structs.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NynningCqFxjJ9dw9WU:-NynwXGR4rlgDwOPRbmJ:bevzmbm) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree/utils/random_structs.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what does "dumpy" mean? if it's "dummy-for-python" then it should be in the CLI crate only
</blockquote></details>

I call it dumpy because it does not necessarily represent a valid tree. 
___
*[`crates/committer/src/patricia_merkle_tree/utils/random_structs.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-Nynq60f8FlW1h_-T_Ex:-Nyp0NZQDxDKiWYjBwLK:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree/utils/random_structs.rs#L60)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/utils/random_structs.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NynqC5j-wCV6FcfDflo:-Nyp0F5N7VMvjY7CmET9:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree/utils/random_structs.rs#L65)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use the input RNG (see above) and not the global
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/utils/random_structs.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyno1_73SOaU9Go6cbk:-Nyp0FY21vMrz-X3TR1R:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree/utils/random_structs.rs#L65)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is not a uniform field element.
please use the random u256 function with an upper bound of:
```
U256::from(Felt::MAX) + 1
```
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/utils/random_structs.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NynosRMBBPVgmY6SLQT:-NyoUwXh5f8-_CbfkBmi:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer/src/patricia_merkle_tree/utils/random_structs.rs#L86)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the problem with this is it's not future-proof. if someone adds/removes an enum variant, the compiler won't catch an issue.
I suggest:
1. make the LeafDataImpl enum *iterable* using the [strum_macros crate](https://docs.rs/strum_macros/latest/strum_macros/derive.EnumI [...]

2024-05-26 13:45 UTC, dorimedini-starkware requested changes
> Reviewed 22 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/143)* status: all files reviewed, 15 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer/Cargo.toml` line 34 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp5989C0prCZqpjb96:-Nyp5989C0prCZqpjb97:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer/Cargo.toml#L34)):*
> ```TOML
> tokio.workspace = true
> rand.workspace = true
> rstest.workspace = true
> ```





_Suggestion:_
```TOML
hex.workspace = true
rand.workspace = true
rstest.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet-types-core.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
tokio.workspace = true
```
___
*[`crates/committer/src/felt.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp5EI53du-VCyxyNFs:-Nyp5EI53du-VCyxyNFt:b-flo546) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer/src/felt.rs#L54)):*
> ```XML
>         Self::from_bytes_be(&value.to_be_bytes())
>     }
> }
> ```

this can panic. `U256::MAX` is larger than a field element.
Try implemeting `TryFrom` instead



_Code quote:_
```XML
impl From<&U256> for Felt {
    fn from(value: &U256) -> Self {
        Self::from_bytes_be(&value.to_be_bytes())
    }
}
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp5R5z9e_OsUg4Gv5D:-Nyp5R5z9e_OsUg4Gv5E:b-30o8aj) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer/src/patricia_merkle_tree/test_utils.rs#L16)):*
> ```XML
>         }
>     }
> }
> ```

reuse conversion code. may be inefficient but this is testing code and it saves boilerplate



_Suggestion:_
```XML
impl From<u8> for SkeletonLeaf {
    fn from(value: u8) -> Self {
        Self::from(Felt::from(value))
    }
}
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp6EGk85MEhTg-w-wy:-Nyp6EGk85MEhTg-w-wz:b-xecox7) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L9)):*
> ```XML
> 
> #[derive(Clone, Debug, PartialEq, Eq, EnumDiscriminants)]
> #[strum_discriminants(derive(EnumIter))]
> ```

only needing for testing/ python side, right?
try this (conditionally add attribute with `cfg_attr`)



_Suggestion:_
```XML
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(
    any(test, feature = "testing"),
    derive(EnumDiscriminants)
)]
#[cfg_attr(
    any(test, feature = "testing"),
    strum_discriminants(derive(EnumIter))
)]
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp60C0EwxieQ5oPpOp:-Nyp60C0EwxieQ5oPpOq:b-lkiic) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L70)):*
> ```XML
>     #[allow(clippy::as_conversions)]
>     pub const MAX: Self = Self(TreeHeight::MAX.0);
> }
> ```

why not put this in `crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs`, where `EdgePathLength` is defined?



_Code quote:_
```XML
impl EdgePathLength {
    /// [EdgePathLength] constant that represents the longest path (from some node) in a tree.
    #[allow(clippy::as_conversions)]
    pub const MAX: Self = Self(TreeHeight::MAX.0);
}
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp6bnJ8eNE5PQ4dK6d:-Nyp6bnJ8eNE5PQ4dK6e:b-oqo1ii) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L24)):*
> ```XML
> #[allow(dead_code)]
> #[derive(Clone, Debug, Eq, PartialEq, EnumDiscriminants)]
> #[strum_discriminants(derive(EnumIter))]
> ```

see above remark about  `cfg_attr`



_Code quote:_
```XML
#[derive(Clone, Debug, Eq, PartialEq, EnumDiscriminants)]
#[strum_discriminants(derive(EnumIter))]
```
___
*[`crates/committer_cli/Cargo.toml` line 25 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp6fWB7qOg7-pB_HTO:-Nyp6fWB7qOg7-pB_HTP:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer_cli/Cargo.toml#L25)):*
> ```TOML
> rand.workspace = true
> strum.workspace = true
> strum_macros.workspace = true
> ```





_Suggestion:_
```TOML
ethnum.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
```
___
*[`crates/committer_cli/src/filled_tree_output/filled_forest.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NyntWUL-BkyF4OBwXJn:-Nyp6lYI6fuHfXoIkfRK:b-bznt6j) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer_cli/src/filled_tree_output/filled_forest.rs#L11)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

But I use it in the committer_cli
</blockquote></details>

you *are* in the committer cli, it should be fine
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp6x02ESDUmwfGGbOr:-Nyp6x02ESDUmwfGGbOs:b-d51p7k) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer_cli/src/tests/utils/random_structs.rs#L36)):*
> ```XML
> impl RandomValue for Felt {
>     fn random<R: Rng>(_rng: &mut R, _max: Option<U256>) -> Self {
>         Felt::from(&get_random_u256(U256::ONE, U256::from(&Felt::MAX) + 1))
> ```

ok, please inject the randomness into `get_random_u256`... this function should also get randomness as a parameter.
I know it's out of scope but you've already started, sorry about that



_Code quote:_
```XML
get_random_u256
```
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp7Ml29Lg1rFtUP2CL:-Nyp7Ml30zNM-OSr112X:b-594pnl) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer_cli/src/tests/utils/random_structs.rs#L78)):*
> ```XML
>         Self {
>             path: EdgePath::random(rng, max),
>             length: EdgePathLength::random(rng, max),
> ```

do not randomize the length like this; you may get an invalid edge (path="111111" and length="1" for example).
randomize the path, then you can try randomizing how many "leading zeros" the path has.



_Code quote:_
```XML
EdgePathLength::random(rng, max)
```
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp7jGwAI30yf31uSY-:-Nyp7jGwAI30yf31uSY0:by9k0el) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer_cli/src/tests/utils/random_structs.rs#L88)):*
> ```XML
>         let max_value = match max {
>             Some(m) if m < EdgePath::MAX.0 => m,
>             _ => EdgePath::MAX.0,
> ```

with only one case left: be explicit



_Suggestion:_
```XML
None =>
```
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp7qo166BFk6opLKgX:-Nyp7qo166BFk6opLKgY:b-4146m7) ([raw file](h [...]

2024-05-26 19:59 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/143)* status: 10 of 23 files reviewed, 15 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/Cargo.toml` line 34 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp5989C0prCZqpjb96:-Nyp9BP539VUShnqC3ax:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer/Cargo.toml#L34)):*
> ```TOML
> tokio.workspace = true
> rand.workspace = true
> rstest.workspace = true
> ```

Done.
___
*[`crates/committer/src/felt.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp5EI53du-VCyxyNFs:-NyqP4dc6jE5Tm5Ec5Tz:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer/src/felt.rs#L54)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this can panic. `U256::MAX` is larger than a field element.
Try implemeting `TryFrom` instead
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp5R5z9e_OsUg4Gv5D:-NyqQJYlAdVIfnBM0NA4:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer/src/patricia_merkle_tree/test_utils.rs#L16)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

reuse conversion code. may be inefficient but this is testing code and it saves boilerplate
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp6EGk85MEhTg-w-wy:-Nypl6EpAhHJ6gLsULtF:b-zcjvte) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

only needing for testing/ python side, right?
try this (conditionally add attribute with `cfg_attr`)
</blockquote></details>

Thanks
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp60C0EwxieQ5oPpOp:-NypmuLF3yIAWvQRWMho:b-7aip0y) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L70)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not put this in `crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs`, where `EdgePathLength` is defined?
</blockquote></details>

I dont understand, its here `crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs`
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp6bnJ8eNE5PQ4dK6d:-NypnEgl2k40UHllkGKa:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L24)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above remark about  `cfg_attr`
</blockquote></details>

Done.
___
*[`crates/committer_cli/Cargo.toml` line 25 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp6fWB7qOg7-pB_HTO:-Nyp9o4o34gmSnksaPg7:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer_cli/Cargo.toml#L25)):*
> ```TOML
> rand.workspace = true
> strum.workspace = true
> strum_macros.workspace = true
> ```

Done.
___
*[`crates/committer_cli/src/filled_tree_output/filled_forest.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/143#-NyntWUL-BkyF4OBwXJn:-Nyp9xm6AD7FEan3por2:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d953fe4062503c12f11a7f8790a00fdd94bc34f5/crates/committer_cli/src/filled_tree_output/filled_forest.rs#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you *are* in the committer cli, it should be fine
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp6x02ESDUmwfGGbOr:-NypLiMd9lMyeLl-pLBH:b3tibcz) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer_cli/src/tests/utils/random_structs.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok, please inject the randomness into `get_random_u256`... this function should also get randomness as a parameter.
I know it's out of scope but you've already started, sorry about that
</blockquote></details>

Done in separate PR 
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp7Ml29Lg1rFtUP2CL:-NyqU4bGBGju2paSI1Rc:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer_cli/src/tests/utils/random_structs.rs#L78)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do not randomize the length like this; you may get an invalid edge (path="111111" and length="1" for example).
randomize the path, then you can try randomizing how many "leading zeros" the path has.
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp7jGwAI30yf31uSY-:-NypMQBz2n4Z7DSOhI_N:bsp3yka) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer_cli/src/tests/utils/random_structs.rs#L88)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

with only one case left: be explicit
</blockquote></details>

There is also the case that Some(m) and m > EdgePath::MAX.0
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp7qo166BFk6opLKgX:-NypMcfp-tI5yVVqzY33:bt0jvl9) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer_cli/src/tests/utils/random_structs.rs#L104)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete this (see above - you cannot really randomize a path length like this)
</blockquote></details>

I don't care about Edge Data's value, so I'll impl DummyRandom instead of Random. is it ok? 
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp7zfh1dHsIBm4bhug:-NypMs-VCHcdU5BeD0JB:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer_cli/src/tests/utils/random_structs.rs#L132)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

whoops
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 188 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp8Bzw2CChGKzTvJF3:-NypMzSd14FV1s5WNAai:by9tgbf) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer_cli/src/tests/utils/random_structs.rs#L188)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why 98 here and 101 above?
</blockquote></details>

It has 98 storage trees, and the for [...]

2024-05-26 20:45 UTC, dorimedini-starkware requested changes
> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/143)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer/src/felt.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/committer/143#-NyqbEPH96Bd8JWFrDdx:-NyqbEPH96Bd8JWFrDdy:by7dsbk) ([raw file](https://github.com/starkware-libs/committer/blob/084ad4e63bd0d6cb593aa42cb0c2a056e3a1d5c9/crates/committer/src/felt.rs#L56)):*
> ```XML
>     fn try_from(value: &U256) -> Result<Self, Self::Error> {
>         panic::catch_unwind(|| Self::from_bytes_be(&value.to_be_bytes())).map_err(|_| FromStrError)
>     }
> ```

1. I would refrain from using `catch_unwind`; just perform a manual check
2. why `FromStrError`? there is no string conversion involved



_Suggestion:_
```XML
    fn try_from(value: &U256) -> Result<Self, Self::Error> {
        if value > U256::from(Felt::MAX) {
            return Err(Self::Error::???);
        }
        Ok(Self::from_bytes_be(&value.to_be_bytes()))
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp60C0EwxieQ5oPpOp:-Nyqc2040TyrdGmax6DL:be1skmj) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L70)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

I dont understand, its here `crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs`
</blockquote></details>

ah whoops... my bad
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 620 at r3](https://reviewable.io/reviews/starkware-libs/committer/143#-NyqcGr9C0_9Ns5ne4WG:-NyqcGr9C0_9Ns5ne4WH:b-xomn7e) ([raw file](https://github.com/starkware-libs/committer/blob/084ad4e63bd0d6cb593aa42cb0c2a056e3a1d5c9/crates/committer_cli/src/tests/python_tests.rs#L620)):*
> ```XML
> /// Generates a dumpy random filled forest and serializes it to a JSON string.
> pub(crate) fn filled_forest_output_test() -> Result<String, PythonTestError> {
>     let dumpy_forest = SerializedForest(FilledForestImpl::dummy_random(
> ```

please search for all `dumpy` in the repo and fix



_Suggestion:_
```XML
dummy_forest
```
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/committer/143#-Nyp7jGwAI30yf31uSY-:-NyqdI4iDc93kff97cA7:b-gd6jpt) ([raw file](https://github.com/starkware-libs/committer/blob/2b53d3529ac08c3c9f168fbc17ae6ff41a407d58/crates/committer_cli/src/tests/utils/random_structs.rs#L88)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

There is also the case that Some(m) and m > EdgePath::MAX.0
</blockquote></details>

noted; see new comment for a solution
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/committer/143#-NyqcbXDEAjtEZyAXbPt:-NyqcbXDEAjtEZyAXbPu:bseru1j) ([raw file](https://github.com/starkware-libs/committer/blob/084ad4e63bd0d6cb593aa42cb0c2a056e3a1d5c9/crates/committer_cli/src/tests/utils/random_structs.rs#L86)):*
> ```XML
>         Self {
>             path,
>             length: EdgePathLength(length),
> ```

if I understand correctly: the path length will always be the bit length of `path`, right?
1. is there no built-in `bit_length` function on U256? if not, please add a TODO to use a built in function once we migrate to a better big-integer library
2. this is not "random" in the sense that every "random path" will start with `1`. consider sampling a bit, and if it's zero (and the path isn't already length `EdgePathLength::MAX`), do +1 to the length.



_Code quote:_
```XML
        let length: u8 = (256_u32 - path.0.leading_zeros())
            .try_into()
            .expect("Leading zeros conversion to u8 failed");

        Self {
            path,
            length: EdgePathLength(length),
```
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/committer/143#-NyqdCwI5j84sdchFZ9a:-NyqdCwI5j84sdchFZ9b:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/084ad4e63bd0d6cb593aa42cb0c2a056e3a1d5c9/crates/committer_cli/src/tests/utils/random_structs.rs#L97)):*
> ```XML
>             Some(m) if m < EdgePath::MAX.0 => m,
>             _ => EdgePath::MAX.0,
>         };
> ```





_Suggestion:_
```XML
        let max_value = match max {
            Some(m) => min(m, EdgePath::MAX.0),
            None => EdgePath::MAX.0,
        };
```
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 131 at r3](https://reviewable.io/reviews/starkware-libs/committer/143#-NyqdPI31nM6UXMlJSVE:-NyqdPI31nM6UXMlJSVF:b-632y7i) ([raw file](https://github.com/starkware-libs/committer/blob/084ad4e63bd0d6cb593aa42cb0c2a056e3a1d5c9/crates/committer_cli/src/tests/utils/random_structs.rs#L131)):*
> ```XML
>             Some(m) if m < NodeIndex::MAX.0 => m,
>             _ => NodeIndex::MAX.0,
>         };
> ```

similar to above



_Suggestion:_
```XML
        let max_value = match max {
            Some(m)=> min(m, NodeIndex::MAX.0),
            None => NodeIndex::MAX.0,
        };
```


<!-- Sent from Reviewable.io -->

2024-05-29 06:02 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/143)* status: 20 of 23 files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/felt.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/committer/143#-NyqbEPH96Bd8JWFrDdx:-Nyqi5X3DTMuJIqSIxRu:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/084ad4e63bd0d6cb593aa42cb0c2a056e3a1d5c9/crates/committer/src/felt.rs#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. I would refrain from using `catch_unwind`; just perform a manual check
2. why `FromStrError`? there is no string conversion involved
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 620 at r3](https://reviewable.io/reviews/starkware-libs/committer/143#-NyqcGr9C0_9Ns5ne4WG:-NyqiP8e8r4s7u4N0lED:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/084ad4e63bd0d6cb593aa42cb0c2a056e3a1d5c9/crates/committer_cli/src/tests/python_tests.rs#L620)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please search for all `dumpy` in the repo and fix
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/committer/143#-NyqcbXDEAjtEZyAXbPt:-NyqkPMvCtCtcK89PQ8w:berw5wz) ([raw file](https://github.com/starkware-libs/committer/blob/084ad4e63bd0d6cb593aa42cb0c2a056e3a1d5c9/crates/committer_cli/src/tests/utils/random_structs.rs#L86)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if I understand correctly: the path length will always be the bit length of `path`, right?
1. is there no built-in `bit_length` function on U256? if not, please add a TODO to use a built in function once we migrate to a better big-integer library
2. this is not "random" in the sense that every "random path" will start with `1`. consider sampling a bit, and if it's zero (and the path isn't already length `EdgePathLength::MAX`), do +1 to the length.
</blockquote></details>

1. There is no such a function ( I don't find one ) 
2. I don't understand why it's not random. I think I missed something. The path is random in the legal range between max and Path::max, and the length is determined. no? 
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/committer/143#-NyqdCwI5j84sdchFZ9a:-NyqjSUQ2gmster5nu34:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/084ad4e63bd0d6cb593aa42cb0c2a056e3a1d5c9/crates/committer_cli/src/tests/utils/random_structs.rs#L97)):*
> ```XML
>             Some(m) if m < EdgePath::MAX.0 => m,
>             _ => EdgePath::MAX.0,
>         };
> ```

Done.
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 131 at r3](https://reviewable.io/reviews/starkware-libs/committer/143#-NyqdPI31nM6UXMlJSVE:-NyqjV0qAjc5Vsnbc9Qy:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/084ad4e63bd0d6cb593aa42cb0c2a056e3a1d5c9/crates/committer_cli/src/tests/utils/random_structs.rs#L131)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

similar to above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-29 07:19 UTC, dorimedini-starkware reviewed
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/143)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer/src/felt.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/committer/143#-Nz2BbgQ32MvF-zcmfYw:-Nz2BbgQ32MvF-zcmfYx:bdzde24) ([raw file](https://github.com/starkware-libs/committer/blob/47f1a6bd8f9196c0ea9e9623d30913e749ed9e37/crates/committer/src/felt.rs#L60)):*
> ```XML
>                 to: ("Felt"),
>                 reason: ("value is bigger than felt::max"),
>             });
> ```

why the parens...? non-blocking, asking



_Suggestion:_
```XML
            return Err(TypesError::ConversionError {
                from: *value,
                to: "Felt",
                reason: "value is bigger than felt::max",
            });
```


<!-- Sent from Reviewable.io -->

2024-05-29 07:20 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/143)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/committer/143#-NyqcbXDEAjtEZyAXbPt:-Nz2D39W9a4_1-tzW5xC:bcyry03) ([raw file](https://github.com/starkware-libs/committer/blob/084ad4e63bd0d6cb593aa42cb0c2a056e3a1d5c9/crates/committer_cli/src/tests/utils/random_structs.rs#L86)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

1. There is no such a function ( I don't find one ) 
2. I don't understand why it's not random. I think I missed something. The path is random in the legal range between max and Path::max, and the length is determined. no?
</blockquote></details>

still an issue


<!-- Sent from Reviewable.io -->

2024-05-29 08:04 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/143)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/felt.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/committer/143#-Nz2BbgQ32MvF-zcmfYw:-Nz2Mdd_EuWJNavKc-MI:b-b84umf) ([raw file](https://github.com/starkware-libs/committer/blob/47f1a6bd8f9196c0ea9e9623d30913e749ed9e37/crates/committer/src/felt.rs#L60)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why the parens...? non-blocking, asking
</blockquote></details>

I still get confused about when I need parents :) 
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/committer/143#-NyqcbXDEAjtEZyAXbPt:-Nz2LU9W6ydDC7s0rdXh:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/084ad4e63bd0d6cb593aa42cb0c2a056e3a1d5c9/crates/committer_cli/src/tests/utils/random_structs.rs#L86)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

still an issue
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-29 08:25 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/143#-:-Nz2S-jMCILsfHL94jbD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 89 at r5](https://reviewable.io/reviews/starkware-libs/committer/143#-Nz2RnM18BzN2ssgmxNk:-Nz2RnM22q7diVKEDDTb:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/7270b777248c37e3fc827c619bf4657a468c882f/crates/committer_cli/src/tests/utils/random_structs.rs#L89)):*
> ```XML
>         let real_leading_zeros = std::cmp::min(
>             Geometric::new(0.5)
>                 .expect("Failed to crate random variable.")
> ```

typo



_Suggestion:_
```XML
create
```


<!-- Sent from Reviewable.io -->

2024-05-29 08:40 UTC, merged