feat: move leaf fetching logic to leaf data trait
starkware-libs/committer pull request #166
Opened 2024-05-30 07:06 UTC by dorimedini-starkware

2024-05-30 13:00 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/166)* status: 0 of 19 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/committer/166#-Nz8X2OKAZRpJNexPk48:-Nz8X2OKAZRpJNexPk49:b-7wlsky) ([raw file](https://github.com/starkware-libs/committer/blob/75f52d10f12e1784bccf21330ec7bec63aeccea5/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L18)):*
> ```XML
> 
> use super::node::CompiledClassHash;
> use super::tree::{CompiledClassTrie, ContractTrie, StorageTrie};
> ```

note to self: don't use `super`



_Code quote:_
```XML
use super::node::CompiledClassHash;
use super::tree::{CompiledClassTrie, ContractTrie, StorageTrie};
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/committer/166#-Nz8Z3NM3sP04iwhEuPW:-Nz8Z3NM3sP04iwhEuPX:bmstjkx) ([raw file](https://github.com/starkware-libs/committer/blob/75f52d10f12e1784bccf21330ec7bec63aeccea5/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L25)):*
> ```XML
> use crate::storage::storage_trait::StorageValue;
> 
> use super::node::CompiledClassHash;
> ```

no super



_Code quote:_
```XML
use super::node::CompiledClassHash;
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 183 at r2](https://reviewable.io/reviews/starkware-libs/committer/166#-Nz8Ze0jAC-hmxxSrgAn:-Nz8Ze0jAC-hmxxSrgAo:b-fjf845) ([raw file](https://github.com/starkware-libs/committer/blob/75f52d10f12e1784bccf21330ec7bec63aeccea5/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L183)):*
> ```XML
>                     hash: subtree.root_hash,
>                     // Dummy value that will be ignored.
>                     data: NodeData::Leaf(StarknetStorageValue::default()),
> ```

should this be generic?



_Suggestion:_
```XML
    /// The leaf type of the returned node is irrelevant, as it will be ignored.
    fn calculate_subtrees_roots<L: LeafData>(
        subtrees: &[SubTree<'_>],
        storage: &impl Storage,
        total_tree_height: &TreeHeight,
    ) -> OriginalSkeletonTreeResult<Vec<FilledNode<StarknetStorageValue>>> {
        let mut subtrees_roots = vec![];
        for subtree in subtrees.iter() {
            if subtree.is_leaf(total_tree_height) {
                subtrees_roots.push(FilledNode {
                    hash: subtree.root_hash,
                    // Dummy value that will be ignored.
                    data: NodeData::Leaf(L::default()),
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/committer/166#-Nz8_1aO4qXDxLU66tYS:-Nz8_1aO4qXDxLU66tYT:b-7ov4f3) ([raw file](https://github.com/starkware-libs/committer/blob/ee674c442e1328af352e92aea87ee62f9ee63c4e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs#L76)):*
> ```XML
>     Felt::from_hex("0x49ed9a06987e7e55770d6c4d7d16b819ad984bf4aed552042847380cc31210d").unwrap()
> )]
> #[case(NodeData::Leaf(LeafDataImpl::StorageValue(Felt::from_hex("0xDEAFBEEF").unwrap())), Felt::from_hex("0xDEAFBEEF").unwrap())]
> ```

these two cases where moved to specific tests below (can't figure out how to write type-generic tests)



_Code quote:_
```XML
#[case(
    NodeData::Leaf(
        LeafDataImpl::CompiledClassHash(CompiledClassHash(Felt::from_hex("0xACDC").unwrap()))
    ),
    Felt::from_hex("0x49ed9a06987e7e55770d6c4d7d16b819ad984bf4aed552042847380cc31210d").unwrap()
)]
#[case(NodeData::Leaf(LeafDataImpl::StorageValue(Felt::from_hex("0xDEAFBEEF").unwrap())), Felt::from_hex("0xDEAFBEEF").unwrap())]
```


<!-- Sent from Reviewable.io -->

2024-05-30 13:17 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/166)* status: 0 of 19 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 183 at r2](https://reviewable.io/reviews/starkware-libs/committer/166#-Nz8Ze0jAC-hmxxSrgAn:-Nz8coUgEtezxwG_nCqe:b-g3djww) ([raw file](https://github.com/starkware-libs/committer/blob/75f52d10f12e1784bccf21330ec7bec63aeccea5/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L183)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

should this be generic?
</blockquote></details>

no... need to remove the need for the original skeleton being aware of filled leaves


<!-- Sent from Reviewable.io -->

2024-06-09 15:28 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/166)* status: 0 of 24 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-NzxahCrBuXHiQwdPxuz:-NzxahCrBuXHiQwdPxv-:b-tkefth) ([raw file](https://github.com/starkware-libs/committer/blob/241dd77460c5253599aa9c22422a6afcf1d1eed0/crates/committer_cli/src/tests/utils/random_structs.rs#L55)):*
> ```XML
>         match LeafDataVariants::iter()
>             .choose(rng)
>             .expect("Failed to choose a random variant for LeafDataImpl")
> ```

since there is no longer a single struct representing all leaf variants, sampling a variant is no longer relevant.
Also, it's *usage* was erroneous (see comment below in this module)



_Code quote:_
```XML
        match LeafDataVariants::iter()
            .choose(rng)
            .expect("Failed to choose a random variant for LeafDataImpl")
```
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 219 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-Nzxb59v0gmlMtdO9v03:-Nzxb59w1sPGpuaeSxCo:bqcg1q3) ([raw file](https://github.com/starkware-libs/committer/blob/241dd77460c5253599aa9c22422a6afcf1d1eed0/crates/committer_cli/src/tests/utils/random_structs.rs#L219)):*
> ```XML
> 
>         let contracts_trie = FilledTreeImpl::dummy_random(rng, max_size);
>         let classes_trie = FilledTreeImpl::dummy_random(rng, max_size);
> ```

this was a mistake before; you could end up with a forest of all kinds of trees, instead of one classes, one contracts and N storage tries.



_Code quote:_
```XML
        let storage_tries: HashMap<ContractAddress, FilledTreeImpl> = (0..max_trees_number)
            .map(|_| {
                (
                    ContractAddress::random(rng, max_size),
                    FilledTreeImpl::dummy_random(rng, max_size),
                )
            })
            .collect::<HashMap<_, _>>();

        let contracts_trie = FilledTreeImpl::dummy_random(rng, max_size);
        let classes_trie = FilledTreeImpl::dummy_random(rng, max_size);
```


<!-- Sent from Reviewable.io -->

2024-06-10 15:05 UTC, nimrod-starkware requested changes
> Reviewed 23 of 24 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/166)* status: 23 of 24 files reviewed, 19 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1SdHl3XsRa7SjGsfM:-O-1SdHl3XsRa7SjGsfN:byn2p8v) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs#L37)):*
> ```XML
> 
> pub type StorageTrieError = FilledTreeError<StarknetStorageValue>;
> pub type CompiledClassTrieError = FilledTreeError<CompiledClassHash>;
> ```

please rename



_Suggestion:_
```XML
ClassesTrieError
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs` line 38 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1SoTo4ixVUB1z_Wod:-O-1SoTo4ixVUB1z_Woe:byn2p8v) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs#L38)):*
> ```XML
> pub type StorageTrieError = FilledTreeError<StarknetStorageValue>;
> pub type CompiledClassTrieError = FilledTreeError<CompiledClassHash>;
> pub type ContractTrieError = FilledTreeError<ContractState>;
> ```

please rename



_Suggestion:_
```XML
ContractsTrieError
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1Uu6U-aJZ19uO540F:-O-1Uu6U-aJZ19uO540G:b-5lj8jy) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L30)):*
> ```XML
> 
> pub struct FilledForestImpl {
>     pub storage_tries: HashMap<ContractAddress, StorageTrie>,
> ```

consider defining an alias for this



_Code quote:_
```XML
HashMap<ContractAddress, StorageTrie>
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 56 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1Uf6w3AgMk5MA4tVK:-O-1Uf6w3AgMk5MA4tVL:b-eu9i3) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L56)):*
> ```XML
> 
> pub type StorageTrie = FilledTreeImpl<StarknetStorageValue>;
> pub type CompiledClassTrie = FilledTreeImpl<CompiledClassHash>;
> ```

plz rename



_Suggestion:_
```XML
ClassesTrie
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1UiUz3ypKEq2h3emF:-O-1UiUz3ypKEq2h3emG:b-l6mkjh) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L57)):*
> ```XML
> pub type StorageTrie = FilledTreeImpl<StarknetStorageValue>;
> pub type CompiledClassTrie = FilledTreeImpl<CompiledClassHash>;
> pub type ContractTrie = FilledTreeImpl<ContractState>;
> ```

rename



_Suggestion:_
```XML
ContractsTrie
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 13 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1WqtQ7JK58JzTsXAq:-O-1WqtQ7JK58JzTsXAr:b-b2372u) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L13)):*
> ```XML
> use crate::storage::db_object::DBObject;
> 
> pub trait LeafData: Clone + Default + Sync + Send + DBObject {
> ```

why is that needed?



_Code quote:_
```XML
+ Default
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 505 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1_2GJ0SpCHtzg5VHl:-O-1_2GKEU6zOlMs4RKI:bwphyqj) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L505)):*
> ```XML
> #[case::non_empty_tree(HashOutput(Felt::from(77_u128)))]
> #[tokio::test]
> async fn test_update_non_modified_tree(#[case] root_hash: HashOutput) {
> ```

rename test please



_Suggestion:_
```XML
test_update_non_modified_storage_trie
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1_RaP4gaNGY4OsTl5:-O-1_RaP4gaNGY4OsTl6:bozvjzm) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L15)):*
> ```XML
> #[path = "hash_function_test.rs"]
> pub mod hash_function_test;
> ```

After realizing today that the hash of inner nodes depends on the leaf type, I suggest removing 'compute_leaf_hash` from the trait and implementing `compute_node_hash` separately for each leaf type.

Another possible solution is to keep `fn compute_leaf_hash` and change the signature to 
`fn compute_node_hash(node_data: &NodeData<L>,  hash_func: &impl HashFunction)` and define 
```pub trait HashFunction{
fn hash(a: Felt, b: Felt) -> HashOutput;
}```
Both ways are good IMO
```

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1cEKA6MYcLY13Uveu:-O-1cEKA6MYcLY13Uvev:b-7xlsrd) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L52)):*
> ```XML
> }
> 
> /// Implementation of TreeHashFunction for contract state trees.
> ```

rename please



_Suggestion:_
```XML
 for contracts trie.
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1cOue8nmATkwPq698:-O-1cOue8nmATkwPq699:b-7xlsrd) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L73)):*
> ```XML
> }
> 
> /// Implementation of TreeHashFunction for compiled class hash trees.
> ```

rename please



_Suggestion:_
```XML
for classes trie.
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 92 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1ci1Z7WnDDV62XaoJ:-O-1ci1Z7WnDDV62XaoK:b-l6mkjh) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L92)):*
> ```XML
> }
> 
> /// Implementation of TreeHashFunction for storage trees.
> ```

rename



_Suggestion:_
```XML
for storage trie.
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 113 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1fRuNBxQ0u200tnFf:-O-1fRuNBxQ0u200tnFg:bqgqn3z) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L113)):*
> ```XML
>         + TreeHashFunction<StarknetStorageValue>
> {
> }
> ```

is that needed? can it be achieved with an alias?



_Code quote:_
```XML
impl<T> ForestHashFunction for T where
    T: TreeHashFunction<ContractState>
        + TreeHashFunction<CompiledClassHash>
        + TreeHashFunction<StarknetStorageValue>
{
}
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs` line 26 at r4](https://reviewable.io/reviews/st [...]

2024-06-10 17:07 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/166)* status: 14 of 24 files reviewed, 19 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1SdHl3XsRa7SjGsfM:-O-230fO5QKTbgD2RUt1:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs#L37)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

please rename
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs` line 38 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1SoTo4ixVUB1z_Wod:-O-23BXc56Ej2W-BYmv8:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs#L38)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

please rename
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1Uu6U-aJZ19uO540F:-O-23Rjm8f_b7LYHlgfX:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L30)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

consider defining an alias for this
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 56 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1Uf6w3AgMk5MA4tVK:-O-23TNM1xOWvgU41yCz:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L56)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

plz rename
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1UiUz3ypKEq2h3emF:-O-23Tdh6njqVHrFpOfv:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L57)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 13 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1WqtQ7JK58JzTsXAq:-O-23jTZ-c9CME0zix-t:b25e1v8) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L13)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

why is that needed?
</blockquote></details>

no longer needed; good catch!
was needed temporarily to allow `L::default()` for empty leaf construction in a function that is generic in leaf type
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 505 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1_2GJ0SpCHtzg5VHl:-O-23uMO6zjGhO_V8evI:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L505)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

rename test please
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1_RaP4gaNGY4OsTl5:-O-23ymj1wXzA-N6s9rY:b-6vh79o) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L15)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

After realizing today that the hash of inner nodes depends on the leaf type, I suggest removing 'compute_leaf_hash` from the trait and implementing `compute_node_hash` separately for each leaf type.

Another possible solution is to keep `fn compute_leaf_hash` and change the signature to 
`fn compute_node_hash(node_data: &NodeData<L>,  hash_func: &impl HashFunction)` and define 
```pub trait HashFunction{
fn hash(a: Felt, b: Felt) -> HashOutput;
}```
Both ways are good IMO
```

</blockquote></details>

I prefer to keep the scope of the PR without any logic change. the hash of the classes tree will still be wrong after this is merged.
In later PRs I was thinking splitting into two traits: `LeafHash` and `TreeHash: LeafHash` (i.e. cannot `impl TreeHash for X` if `X` is not `LeafHash`).
`LeafHash` will have the `compute_leaf_hash` api (no default implementation), and `TreeHash` will have the `compute_node_hash` with a *default* (pedersen) implementation.
This way, we will only need this:
```
struct ForestHasher;

// Leaf impls.
impl LeafHash<StarknetStorageValue> for ForestHasher { ... }
impl LeafHash<CompiledClassHash> for ForestHasher { ... }
impl LeafHash<ContractState> for ForestHasher { ... }

// Inner node impls: only the compiled class impl will require an actual non-default implementation.
impl TreeHash<StarknetStorageValue> for ForestHasher {}
impl TreeHash<CompiledClassHash> for ForestHasher { /* real impl */ }
impl TreeHash<ContractState> for ForestHasher {}
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1cEKA6MYcLY13Uveu:-O-25N0m0fFqVGenrgyu:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L52)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

rename please
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1cOue8nmATkwPq698:-O-25WWMEbOez3dM9mNr:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L73)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

rename please
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 92 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1ci1Z7WnDDV62XaoJ:-O-25eoRC07M0Q4XYwIc:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L92)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 113 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1fRuNBxQ0u200tnFf:-O-25fXwCmMYTA1A4vZh:b-5tkalj) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L113)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>
 [...]

2024-06-16 05:27 UTC, nimrod-starkware requested changes
> Reviewed 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/166)* status: all files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/block_committer/input.rs` line 19 at r5](https://reviewable.io/reviews/starkware-libs/committer/166#-O-UVhNz0YgyrsttHWdW:-O-UVhNz0YgyrsttHWdX:b-akq0c4) ([raw file](https://github.com/starkware-libs/committer/blob/a3d5093d26d7f89ed14496eedd058493d513a134/crates/committer/src/block_committer/input.rs#L19)):*
> ```XML
> pub struct StarknetStorageKey(pub Felt);
> 
> #[derive(Clone, Debug, Default, Eq, PartialEq)]
> ```

is that needed now?



_Code quote:_
```XML
Default,
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/committer/166#-O-UVmgt5z_WSRB_rntR:-O-UVmgt5z_WSRB_rntS:b-pybxz2) ([raw file](https://github.com/starkware-libs/committer/blob/a3d5093d26d7f89ed14496eedd058493d513a134/crates/committer/src/patricia_merkle_tree/filled_tree/node.rs#L8)):*
> ```XML
> // TODO(Nimrod, 1/6/2024): Swap to starknet-types-core types once implemented.
> 
> #[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
> ```

is that needed?



_Code quote:_
```XML
Default,
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node.rs` line 11 at r5](https://reviewable.io/reviews/starkware-libs/committer/166#-O-UVpY-2XmkXoKFmd5P:-O-UVpY-2XmkXoKFmd5Q:b-pybxz2) ([raw file](https://github.com/starkware-libs/committer/blob/a3d5093d26d7f89ed14496eedd058493d513a134/crates/committer/src/patricia_merkle_tree/filled_tree/node.rs#L11)):*
> ```XML
> pub struct ClassHash(pub Felt);
> 
> #[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
> ```

is that needed?



_Code quote:_
```XML
Default,
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node.rs` line 14 at r5](https://reviewable.io/reviews/starkware-libs/committer/166#-O-UVrSn0T4kNbdNHnKd:-O-UVrSn0T4kNbdNHnKe:b-pybxz2) ([raw file](https://github.com/starkware-libs/committer/blob/a3d5093d26d7f89ed14496eedd058493d513a134/crates/committer/src/patricia_merkle_tree/filled_tree/node.rs#L14)):*
> ```XML
> pub struct Nonce(pub Felt);
> 
> #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
> ```

is that needed?



_Code quote:_
```XML
 Default
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 38 at r5](https://reviewable.io/reviews/starkware-libs/committer/166#-O-UVvGvEsmNqrqEPx1L:-O-UVvGvEsmNqrqEPx1M:b-pybxz2) ([raw file](https://github.com/starkware-libs/committer/blob/a3d5093d26d7f89ed14496eedd058493d513a134/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L38)):*
> ```XML
> }
> 
> #[derive(Clone, Debug, Default, Eq, PartialEq)]
> ```

is that needed?



_Code quote:_
```XML
 Default,
```


<!-- Sent from Reviewable.io -->

2024-06-16 08:44 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/166)* status: all files reviewed, 5 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/block_committer/input.rs` line 19 at r5](https://reviewable.io/reviews/starkware-libs/committer/166#-O-UVhNz0YgyrsttHWdW:-O-VCzTf7I5DecpcIgEA:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/a3d5093d26d7f89ed14496eedd058493d513a134/crates/committer/src/block_committer/input.rs#L19)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

is that needed now?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/committer/166#-O-UVmgt5z_WSRB_rntR:-O-VCkhh2j0HVfgku3yi:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/a3d5093d26d7f89ed14496eedd058493d513a134/crates/committer/src/patricia_merkle_tree/filled_tree/node.rs#L8)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

is that needed?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node.rs` line 11 at r5](https://reviewable.io/reviews/starkware-libs/committer/166#-O-UVpY-2XmkXoKFmd5P:-O-VCoQH7e9tewEph6b8:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/a3d5093d26d7f89ed14496eedd058493d513a134/crates/committer/src/patricia_merkle_tree/filled_tree/node.rs#L11)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

is that needed?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node.rs` line 14 at r5](https://reviewable.io/reviews/starkware-libs/committer/166#-O-UVrSn0T4kNbdNHnKd:-O-VCouVDjn_43s18uZx:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/a3d5093d26d7f89ed14496eedd058493d513a134/crates/committer/src/patricia_merkle_tree/filled_tree/node.rs#L14)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

is that needed?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 38 at r5](https://reviewable.io/reviews/starkware-libs/committer/166#-O-UVvGvEsmNqrqEPx1L:-O-VCrdJ9tW30s3qmlNj:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/a3d5093d26d7f89ed14496eedd058493d513a134/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L38)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

is that needed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-16 09:12 UTC, nimrod-starkware approved these changes
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/166)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-06-16 09:18 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/166)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/166#-O-VKrft8RrqyD4DLQuy:-O-VKrfu0pr-TS4xnbZ3:b26r2k) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/35224)

___


<!-- Sent from Reviewable.io -->

2024-06-17 12:00 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/166)* status: 25 of 26 files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/forest_errors.rs` line 20 at r7](https://reviewable.io/reviews/starkware-libs/committer/166#-O-WPqLq4hCR9Wt0_45J:-O-a3D5H9jYnQOvQRySA:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/9683e7359862c9f6b76afd56f83aa875725d132b/crates/committer/src/forest_errors.rs#L20)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why not `ClassesTrie`?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 61 at r7](https://reviewable.io/reviews/starkware-libs/committer/166#-O-_CJ0j36ryFjxczKh-:-O-a29r8-tYmSlR8lu2B:b-bq6rp4) ([raw file](https://github.com/starkware-libs/committer/blob/9683e7359862c9f6b76afd56f83aa875725d132b/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L61)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why does it need to be static?
</blockquote></details>

```
error[E0310]: the parameter type `L` may not live long enough
   --> crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs:148:21
    |
148 | /                     tokio::spawn(Self::compute_filled_tree_rec::<TH>(
149 | |                         Arc::clone(&updated_skeleton),
150 | |                         right_index,
151 | |                         Arc::clone(&leaf_modifications),
152 | |                         Arc::clone(&output_map),
153 | |                     )),
    | |                      ^
    | |                      |
    | |______________________the parameter type `L` must be valid for the static lifetime...
    |                        ...so that the type `L` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
61  | impl<L: LeafData + 'static> FilledTreeImpl<L> {
    |                  +++++++++
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs` line 3 at r7](https://reviewable.io/reviews/starkware-libs/committer/166#-O-_ETxo0uY6JZ3pw4HG:-O-a2GeN0fXtVCLOFUJW:b-4tqf6f) ([raw file](https://github.com/starkware-libs/committer/blob/9683e7359862c9f6b76afd56f83aa875725d132b/crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs#L3)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

we should test other leaf types too, no?
not for this PR, of course
</blockquote></details>

not exactly: when we split into crates (generic patricia / specific starknet commitment), the tests in the patricia crate should use some `DummyLeaf` as a concrete leaf type
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 24 at r7](https://reviewable.io/reviews/starkware-libs/committer/166#-O-_FPuB-9hbx6dit4sO:-O-a2Wpd1CQq2oI2Vv4O:bwybk8j) ([raw file](https://github.com/starkware-libs/committer/blob/9683e7359862c9f6b76afd56f83aa875725d132b/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L24)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why is it needed now?
</blockquote></details>

```
error: future cannot be sent between threads safely
   --> crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs:124:5
    |
124 |     #[async_recursion]
    |     ^^^^^^^^^^^^^^^^^^ future created by async block is not `Send`
    |
    = help: within `{async block@crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs:124:5: 124:23}`, the trait `Send` is not implemented for `impl Future<Output = Result<L, LeafError>>`, which is required by `{async block@crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs:124:5: 124:23}: Send`
note: future is not `Send` as it awaits another future which is not `Send`
   --> crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs:184:33
    |
184 |                 let leaf_data = L::create(&index, leaf_modifications).await?;
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ await occurs here on type `impl Future<Output = Result<L, LeafError>>`, which is not `Send`
    = note: required for the cast from `Pin<Box<{async block@crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs:124:5: 124:23}>>` to `Pin<Box<dyn Future<Output = Result<HashOutput, FilledTreeError<L>>> + Send>>`
    = note: this error originates in the attribute macro `async_recursion` (in Nightly builds, run with -Z macro-backtrace for more info)
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 35 at r7](https://reviewable.io/reviews/starkware-libs/committer/166#-O-_FnWnBXLIbOYbfFQZ:-O-a2c0wBBfZVlR4jiLg:bbwm7oo) ([raw file](https://github.com/starkware-libs/committer/blob/9683e7359862c9f6b76afd56f83aa875725d132b/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L35)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why are both `create` & `from_modifications` needed?
if they are both needed - please rename and add an explanation
</blockquote></details>

`create` is in prep for the case where "creating a leaf" can trigger another `FilledTree::create` call.
i.e, if the contract tree needs to compute the entire storage tree when reaching an updated leaf.
`from_modifications` is for the "simple case", where the entire "computation" of the leaf is just to read it from the modifications map.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1cuEdAdZdMoBPXACE:-O-a2wj33HCI1-nFJXmm:b-tprt5b) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs#L26)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

can you explain why it's relevant for non leaf nodes?
</blockquote></details>

it's not
it's irrelevant for inner nodes
the `NodeData` enum has a type parameter that is only relevant in the leaf variant


<!-- Sent from Reviewable.io -->

2024-06-17 12:36 UTC, amosStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/166)* status: 23 of 26 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 61 at r7](https://reviewable.io/reviews/starkware-libs/committer/166#-O-_CJ0j36ryFjxczKh-:-O-a7Jmq7zk_xejq_q7m:b-3pak9q) ([raw file](https://github.com/starkware-libs/committer/blob/9683e7359862c9f6b76afd56f83aa875725d132b/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L61)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

```
error[E0310]: the parameter type `L` may not live long enough
   --> crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs:148:21
    |
148 | /                     tokio::spawn(Self::compute_filled_tree_rec::<TH>(
149 | |                         Arc::clone(&updated_skeleton),
150 | |                         right_index,
151 | |                         Arc::clone(&leaf_modifications),
152 | |                         Arc::clone(&output_map),
153 | |                     )),
    | |                      ^
    | |                      |
    | |______________________the parameter type `L` must be valid for the static lifetime...
    |                        ...so that the type `L` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
61  | impl<L: LeafData + 'static> FilledTreeImpl<L> {
    |                  +++++++++
```
</blockquote></details>

why doesn't the tree own the leaves?
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs` line 3 at r7](https://reviewable.io/reviews/starkware-libs/committer/166#-O-_ETxo0uY6JZ3pw4HG:-O-a7esQE2-KpzNWByw_:bo6o2nr) ([raw file](https://github.com/starkware-libs/committer/blob/9683e7359862c9f6b76afd56f83aa875725d132b/crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not exactly: when we split into crates (generic patricia / specific starknet commitment), the tests in the patricia crate should use some `DummyLeaf` as a concrete leaf type
</blockquote></details>

ok, but the specific-starknet-commitment-repo should test all types of leaves
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 35 at r7](https://reviewable.io/reviews/starkware-libs/committer/166#-O-_FnWnBXLIbOYbfFQZ:-O-a8nHQ6XrkeERZZslC:b-6fabip) ([raw file](https://github.com/starkware-libs/committer/blob/9683e7359862c9f6b76afd56f83aa875725d132b/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`create` is in prep for the case where "creating a leaf" can trigger another `FilledTree::create` call.
i.e, if the contract tree needs to compute the entire storage tree when reaching an updated leaf.
`from_modifications` is for the "simple case", where the entire "computation" of the leaf is just to read it from the modifications map.
</blockquote></details>

please explain this in the code
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1cuEdAdZdMoBPXACE:-O-a9sZvBm33GKjEzNfK:b-o4cyfs) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs#L26)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it's not
it's irrelevant for inner nodes
the `NodeData` enum has a type parameter that is only relevant in the leaf variant
</blockquote></details>

after talking F2F: it is relevant, please remove the comments
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 301 at r8](https://reviewable.io/reviews/starkware-libs/committer/166#-O-aBHMP4bPGaphkTl4i:-O-aBHMP4bPGaphkTl4j:b-7joj38) ([raw file](https://github.com/starkware-libs/committer/blob/f5249d2c77ed2d04a130f1ef265e8f269eb024e7/crates/committer_cli/src/tests/python_tests.rs#L301)):*
> ```XML
>     };
> 
>     // Create a filled node (irrelevant leaf type) with binary data and zero hash.
> ```

is the leaf type in fact irrelevant?



_Code quote:_
```XML
// Create a filled node (irrelevant leaf type) with binary data and zero hash.
```


<!-- Sent from Reviewable.io -->

2024-06-17 13:10 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/166)* status: 23 of 26 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 61 at r7](https://reviewable.io/reviews/starkware-libs/committer/166#-O-_CJ0j36ryFjxczKh-:-O-aIOu1BuhTUahix6F7:b-9ppqc3) ([raw file](https://github.com/starkware-libs/committer/blob/9683e7359862c9f6b76afd56f83aa875725d132b/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L61)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why doesn't the tree own the leaves?
</blockquote></details>

The *type* `L` must be static, not the leaf instances (IIUC).
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 35 at r7](https://reviewable.io/reviews/starkware-libs/committer/166#-O-_FnWnBXLIbOYbfFQZ:-O-aJ2qz0vKZbGPtV7hy:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/9683e7359862c9f6b76afd56f83aa875725d132b/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L35)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please explain this in the code
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/committer/166#-O-1cuEdAdZdMoBPXACE:-O-aJ8lB9gDK53L8iT6y:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/b646b870f4655820a32b8f9617d89c7b8d5dd4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs#L26)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

after talking F2F: it is relevant, please remove the comments
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 301 at r8](https://reviewable.io/reviews/starkware-libs/committer/166#-O-aBHMP4bPGaphkTl4i:-O-aJDZbAqbJLGFuuuMN:byse8v4) ([raw file](https://github.com/starkware-libs/committer/blob/f5249d2c77ed2d04a130f1ef265e8f269eb024e7/crates/committer_cli/src/tests/python_tests.rs#L301)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

is the leaf type in fact irrelevant?
</blockquote></details>

here it is not relevant.
no actual hash is computed (`hash: HashOutput(Felt::ZERO)`)


<!-- Sent from Reviewable.io -->

2024-06-17 13:27 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/166)* status: 21 of 26 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 61 at r7](https://reviewable.io/reviews/starkware-libs/committer/166#-O-_CJ0j36ryFjxczKh-:-O-aNEFGBo77tbIJ9Ui-:b-mnexgn) ([raw file](https://github.com/starkware-libs/committer/blob/9683e7359862c9f6b76afd56f83aa875725d132b/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L61)):*
OK I'm wrong, but from the answer [here](https://stackoverflow.com/questions/32083758/parameter-type-may-not-live-long-enough-with-threads), it seems like this is a limitation of `tokio` anyway:

> The [`std::thread::spawn()`](http://doc.rust-lang.org/std/thread/fn.spawn.html) function is declared with a `Send + 'static` bound on its closure. Anything which this closure captures must satisfy the `Send + 'static` bound. There is _no_ way around this in safe Rust. If you want to pass data to other threads using this function, it must be `'static`, period.


<!-- Sent from Reviewable.io -->

2024-06-17 13:43 UTC, amosStarkware reviewed
> Reviewed 1 of 12 files at r5, 2 of 2 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/166)* status: 25 of 26 files reviewed, all discussions resolved (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-06-17 13:48 UTC, amosStarkware approved these changes
> Reviewed 3 of 24 files at r4, 2 of 8 files at r6, 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/166)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-06-17 13:51 UTC, merged