refactor: remove dependency on a given tree height of original skeletons
starkware-libs/committer pull request #179
Opened 2024-06-02 14:56 UTC by nimrod-starkware

First stage of the tree height refactor.
Small trees are now 'large' with an edge node to the root of the small tree.
Next stage is to remove the tree_height parameter inside original skeleton

2024-06-02 15:10 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/179)* status: all files reviewed, 8 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOTMEzCh64eGfv4UgK:-NzOTMF-6ydZpuM62vtv:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/types.rs#L165)):*
> ```XML
>     #[cfg(test)]
>     #[allow(dead_code)]
>     /// Assumes self represnts an index in a smaller tree height. Returns a node index represents the
> ```

typo



_Code quote:_
```XML
represnts
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOTP_G3xjZdR6kbcct:-NzOTP_H189mAfKngU6o:b-f1neu9) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/types.rs#L166)):*
> ```XML
>     #[allow(dead_code)]
>     /// Assumes self represnts an index in a smaller tree height. Returns a node index represents the
>     /// same index in tree of height 251 as if the smaller tree was 'planted' at the lowest leftmost
> ```

rephrase to refer to the starknet tree height, not to the number 251



_Code quote:_
```XML
of height 251
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOV5E71MPgiNyDUv4n:-NzOV5E71MPgiNyDUv4o:b-wy6iyo) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L220)):*
> ```XML
>     /// 'Plants' the given smaller tree at the lowest leftmost node in order to create a tree of
>     /// height TREE_HEIGHT::MAX.
>     pub(crate) fn create_actual_sized_tree_from_smaller_tree(smaller_tree: Self) -> Self {
> ```

this function isn't used in this PR, correct?
if so, then it doesn't belong in this PR; please remove it (open another PR with a usage later if it's useful)



_Code quote:_
```XML
create_actual_sized_tree_from_smaller_tree
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOTwQd5Io09fV38gsd:-NzOTwQd5Io09fV38gse:btxnkz1) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L185)):*
> ```XML
>     let mut sorted_leaf_indices: Vec<NodeIndex> = leaf_modifications
>         .keys()
>         .map(|idx| idx.to_actual_tree_index(tree_height))
> ```

"actual" is confusing, please rename



_Suggestion:_
```XML
from_subtree_index
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOUMfLE30JUGBcGtUX:-NzOUMfLE30JUGBcGtUY:b-470lr3) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L201)):*
> ```XML
>         .into_iter()
>         .map(|(node_idx, node)| (node_idx.to_actual_tree_index(tree_height), node))
>         .collect();
> ```

this mapping conversion is also done below; please make a test util out of it



_Code quote:_
```XML
    let mut expected_nodes: HashMap<NodeIndex, OriginalSkeletonNode> = expected_nodes
        .into_iter()
        .map(|(node_idx, node)| (node_idx.to_actual_tree_index(tree_height), node))
        .collect();
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOUSBg7dNgjRT-dWfa:-NzOUSBg7dNgjRT-dWfb:b-tbh6rx) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L209)):*
> ```XML
>             length: EdgePathLength(TreeHeight::MAX.0 - tree_height.0),
>         }),
>     );
> ```

duplicated logic; write a test util for it



_Suggestion:_
```XML
    add_containing_tree_root(&mut expected_nodes, tree_height);
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOUlDU4na4ObqgQf7R:-NzOUlDU4na4ObqgQf7S:bnbiosx) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L285)):*
> ```XML
>                     path: 0.into(),
>                     length: EdgePathLength(251 - height),
>                 }),
> ```

1. no hard coded 251
2. reuse the logc in `add_containing_tree_root` (see above)



_Code quote:_
```XML
                NodeIndex::ROOT,
                OriginalSkeletonNode::Edge(PathToBottom {
                    path: 0.into(),
                    length: EdgePathLength(251 - height),
                }),
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOUw_r5jtObqkcKZyP:-NzOUw_r5jtObqkcKZyQ:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L338)):*
> ```XML
> pub(crate) fn create_root_edge_entry(
>     old_root: u8,
>     small_tree_height: TreeHeight,
> ```





_Suggestion:_
```XML
subtree_height
```


<!-- Sent from Reviewable.io -->

2024-06-02 15:33 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/179)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOTMEzCh64eGfv4UgK:-NzOW5hU7M3wPCaHsCb-:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/types.rs#L165)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOTP_G3xjZdR6kbcct:-NzOWzBq7FEpqj5bIm3v:bpfi3mo) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/types.rs#L166)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rephrase to refer to the starknet tree height, not to the number 251
</blockquote></details>

Done, hope that's more obvious
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOV5E71MPgiNyDUv4n:-NzOVsu88tdhn06iJc_a:b-x5zf15) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L220)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this function isn't used in this PR, correct?
if so, then it doesn't belong in this PR; please remove it (open another PR with a usage later if it's useful)
</blockquote></details>

Done. removed
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOTwQd5Io09fV38gsd:-NzOXGN-AlCG7F3vUNJc:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L185)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

"actual" is confusing, please rename
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOUMfLE30JUGBcGtUX:-NzOZzQK0ooduLvYppw-:bb24uxk) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L201)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this mapping conversion is also done below; please make a test util out of it
</blockquote></details>

I used the function `create_expected_skeleton` which included the logic for the forest.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOUSBg7dNgjRT-dWfa:-NzO_7ir3eVnl558RqH5:bb24uxk) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L209)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

duplicated logic; write a test util for it
</blockquote></details>

I used the function `create_expected_skeleton` which included the logic for the forest.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOUlDU4na4ObqgQf7R:-NzO_Ayi31rKad4RppaN:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L285)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. no hard coded 251
2. reuse the logc in `add_containing_tree_root` (see above)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOUw_r5jtObqkcKZyP:-NzOYJbB2sjjsVbLe429:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d92462d4805752547ada8fcf050e82c901c17b30/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L338)):*
> ```XML
> pub(crate) fn create_root_edge_entry(
>     old_root: u8,
>     small_tree_height: TreeHeight,
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-06-02 16:16 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/179)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOiidv9F593_YyHCHd:-NzOiidv9F593_YyHCHe:bvfj3gv) ([raw file](https://github.com/starkware-libs/committer/blob/0e1bf97f95990180e9e028aa91c73ff90add5db7/crates/committer/src/patricia_merkle_tree/types.rs#L167)):*
> ```XML
>     /// the same index in the starknet state tree as if the smaller tree was 'planted' at the lowest
>     /// leftmost node from the root.
>     pub(crate) fn from_subtree_index(sub_tree_index: Self, subtree_height: TreeHeight) -> Self {
> ```

subtree is one word on our repo (not english but ok)



_Suggestion:_
```XML
subtree_index: Self, subtree_height: TreeHeight
```


<!-- Sent from Reviewable.io -->

2024-06-03 05:41 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/179)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/committer/179#-NzOiidv9F593_YyHCHd:-NzRbW07AeXRQocgqD40:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/0e1bf97f95990180e9e028aa91c73ff90add5db7/crates/committer/src/patricia_merkle_tree/types.rs#L167)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

subtree is one word on our repo (not english but ok)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-03 05:47 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/179#-:-NzRco6G5nQ4CMQQjT5z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-06-03 07:00 UTC, merged