Add serialization method for filled nodes
starkware-libs/committer pull request #18
Opened 2024-04-07 18:45 UTC by AvivYossef-starkware

This pull request introduces a serialization method for filled nodes in the Patricia Merkle tree implementation. The serialise method is implemented for the FilledNode type, allowing the conversion of filled nodes into byte vectors.

The method serializes the filled node into a byte vector according to the following rules:

For binary nodes: Concatenates the left and right hashes.
For edge nodes: Concatenates the bottom hash, path, and path length.
For leaf nodes: Concatenates the node's hash.
This functionality enhances the usability of the filled node struct by providing a convenient way to serialize its data for storage or transmission.

2024-04-08 09:37 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/storage.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-NuwvC4J6LmI0Nl9umfU:-NuwvC4J6LmI0Nl9umfV:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/storage.rs#L1)):*
> ```XML
> pub mod sorage_trait;
> ```

typo



_Suggestion:_
```XML
pub mod storage_trait;
```
___
*[`crates/committer/src/storage.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-NuwvFGk82gDgh24Vl-q:-NuwvFGk82gDgh24Vl-r:b-j9st85) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/storage.rs#L2)):*
> ```XML
> pub mod sorage_trait;
> pub mod committer_storage;
> ```

add a newline at the end of the file (your auto-formatter should be doing this for you...)



_Code quote:_
```XML
pub mod committer_storage;
```
___
*[`crates/committer/src/types.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nux1P8JEeTWIyvF5qdI:-Nux1P8JEeTWIyvF5qdJ:b-8ih667) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/types.rs#L15)):*
> ```XML
>     }
> 
> }
> ```

I don't think we really need a behavioral abstraction for our felt wrapper; `impl` is enough



_Suggestion:_
```XML
pub(crate) type Felt = StarknetTypesFelt;

impl Felt {
    pub fn to_bytes(&self) -> [u8; 32] {
        self.to_bytes_be()
    }
}
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nux22Oy-b8FN3JJBEYt:-Nux22Oy-b8FN3JJBEYu:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L67)):*
> ```XML
> 
>     #[allow(dead_code)]
>     pub(crate) fn serialise(&self,) -> Vec<u8> {
> ```





_Suggestion:_
```XML
(&self)
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nux1x3eEQEa0Cj_lIRQ:-Nux1x3eEQEa0Cj_lIRR:b-nedqfv) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L71)):*
> ```XML
>         // - For binary nodes: Concatenates left and right hashes.
>         // - For edge nodes: Concatenates bottom hash, path, and path length.
>         // - For leaf nodes: Concatenates the node's hash.
> ```

why the hash, and not the preimage?
seems other node types get their preimage returned as bytes, why is the leaf different?
maybe add a `serialized_data` method to `LeafDataTrait` if you need it



_Code quote:_
```XML
/ - For leaf nodes: Concatenates the node's hash.
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nux2jds-ErgnbOC4Jrk:-Nux2jds-ErgnbOC4Jrl:b-5g5q02) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L71)):*
> ```XML
>         // - For binary nodes: Concatenates left and right hashes.
>         // - For edge nodes: Concatenates bottom hash, path, and path length.
>         // - For leaf nodes: Concatenates the node's hash.
> ```

function docstring should be above the definition, and start with triple-slash



_Suggestion:_
```XML
    /// This method serialises the filled node into a byte vector, where:
    /// - For binary nodes: Concatenates left and right hashes.
    /// - For edge nodes: Concatenates bottom hash, path, and path length.
    /// - For leaf nodes: Concatenates the node's hash.
    #[allow(dead_code)]
    pub(crate) fn serialise(&self,) -> Vec<u8> {
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nux25WO-PlQgBNgGiNh:-Nux25WO-PlQgBNgGiNi:blbafse) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L84)):*
> ```XML
>                 serialised.extend_from_slice(&data.path_to_bottom.path.0.to_bytes());
>                 serialised.extend_from_slice(&data.path_to_bottom.length.0.to_be_bytes());
>             }
> ```

destructure in the match



_Suggestion:_
```XML
            NodeData::Binary(BinaryData {left_hash, right_hash}) => {
                serialised.extend_from_slice(&left_hash.0.to_bytes());
                serialised.extend_from_slice(&right_hash.0.to_bytes());
            }

            NodeData::Edge(EdgeData {bottom_hash, path_to_bottom}) => {
                serialised.extend_from_slice(&bottom_hash.0.to_bytes());
                serialised.extend_from_slice(&path_to_bottom.path.0.to_bytes());
                serialised.extend_from_slice(&path_to_bottom.length.0.to_be_bytes());
            }
```
___
*[`crates/committer/src/storage/committer_storage.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nux33YW1Vx5dja-mtRf:-Nux33YW1Vx5dja-mtRg:bqsxqmk) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/storage/committer_storage.rs#L0)):*
do not add empty files... add when needed / used
___
*[`crates/committer/src/storage/sorage_trait.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nux3D9B4UxHpyX-sq0Z:-Nux3D9B4UxHpyX-sq0_:b45h) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/storage/sorage_trait.rs#L4)):*
> ```XML
>     fn get(&self, key: &[u8]) -> Option<Vec<u8>>;
>     fn set(&mut self, key: Vec<u8>, value: Vec<u8>);
>     fn remove(&mut self, key: &[u8]);
> ```





_Suggestion:_
```XML
fn delete(&mut self, key: &[u8]);
```
___
*[`crates/committer/src/storage/sorage_trait.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nux3GzFC4ZPnYojvRTC:-Nux3GzFC4ZPnYojvRTD:bz91vau) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/storage/sorage_trait.rs#L5)):*
> ```XML
>     fn set(&mut self, key: Vec<u8>, value: Vec<u8>);
>     fn remove(&mut self, key: &[u8]);
>     fn new() -> Self;
> ```

not needed for general API; we don't know at this point how Storage implementors will be initialized.
remove


<!-- Sent from Reviewable.io -->

2024-04-09 09:18 UTC, amosStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 11 unresolved discussions (waiting on @AvivYossef-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nv171oN4Q7uCO0T99EB:-Nv171oN4Q7uCO0T99EC:b-32dmrn) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L67)):*
> ```XML
> 
>     #[allow(dead_code)]
>     pub(crate) fn serialise(&self,) -> Vec<u8> {
> ```

Maybe it's better to create an `Enum` `SerializedNode` with variants `Binary`, `Edge`, `Leaf`, which will contain the serialized data as a fixed size array?
fixed size arrays are probably a bit more effiecient than vectors. @dorimedini-starkware WYT? 



_Code quote:_
```XML
pub(crate) fn serialise(&self,) -> Vec<u8> {
```


<!-- Sent from Reviewable.io -->

2024-04-09 09:28 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 12 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nv171oN4Q7uCO0T99EB:-Nv19aqYCq58-TXenihe:b-rs31tg) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L67)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Maybe it's better to create an `Enum` `SerializedNode` with variants `Binary`, `Edge`, `Leaf`, which will contain the serialized data as a fixed size array?
fixed size arrays are probably a bit more effiecient than vectors. @dorimedini-starkware WYT?
</blockquote></details>

perhaps just make the return type `&[u8]`
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nv19w6s0t8XqdQwotF4:-Nv19w6s0t8XqdQwotF5:b-ge5or9) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L92)):*
> ```XML
>         serialised
>     }
> }
> ```

if this works, it may be better (see @amosStarkware 's comment above)



_Suggestion:_
```XML
    #[allow(dead_code)]
    pub(crate) fn serialise(&self) -> [u8] {
        // This method serialises the filled node into a byte vector, where:
        // - For binary nodes: Concatenates left and right hashes.
        // - For edge nodes: Concatenates bottom hash, path, and path length.
        // - For leaf nodes: Concatenates the node's hash.

        match &self.data {
            NodeData::Binary(data) => {
                [data.left_hash.0.to_bytes(), data.right_hash.0.to_bytes()].concat()
            }
            NodeData::Edge(data) => {
                [
                    data.bottom_hash.0.to_bytes(),
                    data.path_to_bottom.path.0.to_bytes(),
                    data.path_to_bottom.length.0.to_be_bytes()
                ].concat()
            }
            NodeData::Leaf(_data) => {
                self.hash.0.to_bytes()
            }
        }
    }
```


<!-- Sent from Reviewable.io -->

2024-04-09 11:40 UTC, amosStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 12 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nv171oN4Q7uCO0T99EB:-Nv1dtxdDXW3JOabnRJY:b9f74gq) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L67)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

perhaps just make the return type `&[u8]`
</blockquote></details>

Note it's not really what I suggested - I suggested using byte arrays of a length known at compile time, since IIUC for each node type the value is of a fixed size.


<!-- Sent from Reviewable.io -->

2024-04-09 12:05 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 12 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nv171oN4Q7uCO0T99EB:-Nv1jpG38YMyhXwLh5Au:bt06azl) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L67)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Note it's not really what I suggested - I suggested using byte arrays of a length known at compile time, since IIUC for each node type the value is of a fixed size.
</blockquote></details>

yes, but the general `serialize` function on a general node is not of fixed size, because you don't know the node type.
an implementation of this function will `match` on node type, right?


<!-- Sent from Reviewable.io -->

2024-04-10 08:22 UTC, AvivYossef-starkware commented
reopen

2024-04-10 10:46 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 6 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 12 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/types.rs` line 15 at r3](https://reviewable.io/reviews/starkware-libs/committer/18#-Nv6bIX48fY5xHdc4WI3:-Nv6bIX48fY5xHdc4WI4:bq3h32b) ([raw file](https://github.com/starkware-libs/committer/blob/d7d3d98d5fda2f190f25db3898d788a8941d4de2/crates/committer/src/types.rs#L15)):*
> ```XML
>     }
> 
> }
> ```

1. remove newline after function def
2. add newline at the end of the file



_Suggestion:_
```XML
        self.to_bytes_be()
    }
}
```


<!-- Sent from Reviewable.io -->

2024-04-11 10:54 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 5 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 20 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, and @nimrod-starkware)

___
*[`crates/committer/Cargo.toml` line 21 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBh7-T6_n1shFDyXPH:-NvBh7-T6_n1shFDyXPI:b-a0sgr6) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/Cargo.toml#L21)):*
> ```TOML
> starknet_api = "0.12.0-dev.0"
> serde_json = "1.0"
> serde = { version = "1.0", features = ["derive"] }
> ```

we only define these in the top level Cargo.toml; move them there, and use the `workspace = true` method here.



_Suggestion:_
```TOML
starknet_api.workspace = true
serde_json.workspace = true
serde.workspace = true
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 85 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBk-h19fCEA7rWSt_R:-NvBk-h19fCEA7rWSt_S:b5q657q) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L85)):*
> ```XML
>                 };
>                 serde_json::to_string(&temp_object_to_json)
>                 .expect("Failed to serialize class hash to JSON")
> ```

`serde_json::to_string` returns a `Result` object; instead of `unwrap`ing it and risking panic, we should propagate the error (with the `?` operator).
You will need to define an error type (for example, `TreeSerializationError`) that can be converted from `serde_json::error::Error`; usually done something like this (consult with Amos please first, maybe the error should be defined another way, perhaps as a variant of the `FilledTreeError` enum):
```
#[derive(thiserror::Error)]
enum TreeSerializationError {
    Serde(#[from] serde_json::error::Error),
}
```



_Suggestion:_
```XML
    pub(crate) fn to_pre_image_js(&self) -> Result<String, TreeSerializationError> {

        match &self {
            LeafData::StorageValue(_value) => {
                panic!("Storage leaf should not be serialised as JSON.")
            }
            LeafData::CompiledClassHash(class_hash) => {
                let temp_object_to_json = LeafCompiledClassToSerialise {
                    compiled_class_hash: class_hash.0,
                };
                serde_json::to_string(&temp_object_to_json)?
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 101 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBjCFE7IdSHyXb-n5r:-NvBjCFE7IdSHyXb-n5s:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L101)):*
> ```XML
>     /// - For storage values: Serialises the value into a 32-byte array.
>     /// - For compiled class hashes: cast the json describe the leaf into a byte vector.
>     /// - For state tree tuples: cast the json describe the leaf into a byte vector.
> ```





_Suggestion:_
```XML
    /// - For compiled class hashes or state tree tuples: casts the json string describing
    ///   the leaf into a byte vector.
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 114 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBisRT-yAzvqEMHL6J:-NvBisRT-yAzvqEMHL6K:b33g8st) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L114)):*
> ```XML
>             }
> 
>             LeafData::StateTreeTuple{ class_hash: _, contract_state_root_hash: _, nonce: _ } => {
> ```

shorthand for when you want to ignore parts of the struct.
you can also choose to ignore pars, for example
```
LeafData::StateTreeTuple{ nonce: leaf_nonce, .. }
```



_Suggestion:_
```XML
LeafData::StateTreeTuple{ .. }
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 121 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBiDfL-6tLL6cyxTJZ:-NvBiDfL-6tLL6cyxTJ_:bm51ich) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L121)):*
> ```XML
>         }
>     }
> }
> ```

`to_pre_image_js` introduces a redundant panic: move it's logic to where it's known to work



_Suggestion:_
```XML
impl LeafData{
    /// Serialises the leaf data into a byte array.
    /// The serialisation is done as follows:
    /// - For storage values: Serialises the value into a 32-byte array.
    /// - For compiled class hashes: cast the json describe the leaf into a byte vector.
    /// - For state tree tuples: cast the json describe the leaf into a byte vector.
    pub(crate) fn serialise(&self) -> SerialiseNode {
        match &self {
            LeafData::StorageValue(value) => {
                SerialiseNode::StorageLeaf(value.as_bytes())
            }

            LeafData::CompiledClassHash(class_hash) => {
                // Serialise the leaf into a JSON, and than to a byte Vector.
                let json_bytes = &serde_json::to_string(
                        LeafCompiledClassToSerialise {
                            compiled_class_hash: class_hash.0,
                        }
                    )
                    .expect("Failed to serialize class hash to JSON")
                    .into_bytes();
                SerialiseNode::CompiledClassLeaf(json_bytes.to_owned())
            }

            LeafData::StateTreeTuple{ class_hash: _, contract_state_root_hash: _, nonce: _ } => {
                // Serialise the leaf into a JSON, and than to a byte Vector.
                todo!("Aviv 11/04 Implement this method, I need referrence to tree struct");
                //let json_bytes = &self.to_pre_image_js().into_bytes();
                //SerialiseNode::StateTreeLeaf(json_bytes.to_owned())
            }
        }
    }
}
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 129 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBlIOh963I_VvWhjPP:-NvBlIOh963I_VvWhjPQ:b-75ywm7) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L129)):*
> ```XML
>     /// - For edge nodes: Concatenates bottom hash, path, and path length.
>     /// - For leaf nodes: use leaf.serialise() method.
>     #[allow(dead_code,non_snake_case)]
> ```

why is this needed?



_Code quote:_
```XML
non_snake_case
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 159 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBlibr6cJaIDyDr581:-NvBlibt35Ow2zoIK2XS:b-x6blgu) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L159)):*
> ```XML
>                 serialised[EDGE_SIZE-1] = length[0];
>                 SerialiseNode::Edge(serialised)
>             }
> ```

is it possible to make this shorter? not sure, maybe since the byte array lengths are fixed you can't do it without `clone()`ing things, but please try (non-blocking)



_Suggestion:_
```XML
            NodeData::Binary(BinaryData {left_hash, right_hash}) => {
                SerialiseNode::Binary([left_hash.0.as_bytes(), right_hash.0.as_bytes()].concat())
            }


            NodeData::Edge(EdgeData {bottom_hash, path_to_bottom}) => {
                // Serialise bottom hash, path, and path length to byte arrays.
                let mut serialised: [u8; EDGE_SIZE] = [0; EDGE_SIZE];
                let bottom: [u8; SERIALISE_HASH_SIZE] = bottom_hash.0.as_bytes();
                let path: [u8; SERIALISE_HASH_SIZE] = path_to_bottom.path.0.as_bytes();
       [...]

2024-04-14 08:46 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: 6 of 13 files reviewed, 20 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 85 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBk-h19fCEA7rWSt_R:-NvQ_6tk0dBOSBYLk829:b-1grujm) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L85)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`serde_json::to_string` returns a `Result` object; instead of `unwrap`ing it and risking panic, we should propagate the error (with the `?` operator).
You will need to define an error type (for example, `TreeSerializationError`) that can be converted from `serde_json::error::Error`; usually done something like this (consult with Amos please first, maybe the error should be defined another way, perhaps as a variant of the `FilledTreeError` enum):
```
#[derive(thiserror::Error)]
enum TreeSerializationError {
    Serde(#[from] serde_json::error::Error),
}
```
</blockquote></details>

First please add `pub(crate) type FilledTreeResult<T> = Result<T, FilledTreeError>;` to `filled_tree.rs` and use it as return type.
I'm reading about error handling with Serde and it's not as straightforward as I thought. so IMO it would be best to add
`FilledTreeError::SerializationError` and use it here for now, and add a TODO to properly propagate Serde errors and do it in another PR (I'll read about this and try to help).
and please sync with @nimrod-starkware about this - it's also relevant to him and he may have started something.


<!-- Sent from Reviewable.io -->

2024-04-14 10:04 UTC, dorimedini-starkware requested changes
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 20 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/types.rs` line 6 at r6](https://reviewable.io/reviews/starkware-libs/committer/18#-NvR2P8T12K8w7kCC42J:-NvR2P8U30R2v4NP_T8G:buhrma6) ([raw file](https://github.com/starkware-libs/committer/blob/bf97fefead6b97d344e43fc1f6d075a366d81fc3/crates/committer/src/types.rs#L6)):*
> ```XML
> #[derive(
>     Eq, PartialEq, Clone, Copy, Debug, Default, Hash, Serialize, Deserialize, derive_more::Add,
> )]
> ```

revert this change? why did it appear? is it longer than 100 chars?



_Suggestion:_
```XML
#[derive(Eq, PartialEq, Clone, Copy, Debug, Default, Hash, Serialize, Deserialize, derive_more::Add)]
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 85 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBk-h19fCEA7rWSt_R:-NvR2nmbDMGTzhIOGQej:bh0or6k) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L85)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

First please add `pub(crate) type FilledTreeResult<T> = Result<T, FilledTreeError>;` to `filled_tree.rs` and use it as return type.
I'm reading about error handling with Serde and it's not as straightforward as I thought. so IMO it would be best to add
`FilledTreeError::SerializationError` and use it here for now, and add a TODO to properly propagate Serde errors and do it in another PR (I'll read about this and try to help).
and please sync with @nimrod-starkware about this - it's also relevant to him and he may have started something.
</blockquote></details>

Error handling with serde involved more than doing this?
```
#[derive(thiserror::Error)]
enum TreeError {
    ...
    SerializationError(#[from] serde_json::Error),
}
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 165 at r6](https://reviewable.io/reviews/starkware-libs/committer/18#-NvR39sP-35tCgc9cmc7:-NvR39sP-35tCgc9cmc8:bvxypge) ([raw file](https://github.com/starkware-libs/committer/blob/bf97fefead6b97d344e43fc1f6d075a366d81fc3/crates/committer/src/patricia_merkle_tree/filled_node.rs#L165)):*
> ```XML
>         }
>     }
> }
> ```

missing newline at the end of the file



_Suggestion:_
```XML
}
```


<!-- Sent from Reviewable.io -->

2024-04-14 10:51 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 20 unresolved discussions (waiting on @AvivYossef-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 85 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBk-h19fCEA7rWSt_R:-NvRDaXU1-k4SJlI2r1z:bhyrxd1) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L85)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Error handling with serde involved more than doing this?
```
#[derive(thiserror::Error)]
enum TreeError {
    ...
    SerializationError(#[from] serde_json::Error),
}
```
</blockquote></details>

If `serde_json::Error` is the only `Serde` error that we expect here then that looks good.


<!-- Sent from Reviewable.io -->

2024-04-14 13:25 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 16 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/committer/Cargo.toml` line 21 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBh7-T6_n1shFDyXPH:-NvQMdPSCXjIPlABRZq2:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/Cargo.toml#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we only define these in the top level Cargo.toml; move them there, and use the `workspace = true` method here.
</blockquote></details>

Done.
___
*[`crates/committer/src/types.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nux1P8JEeTWIyvF5qdI:-Nv5t5L56xNJgU0woWau:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/types.rs#L15)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't think we really need a behavioral abstraction for our felt wrapper; `impl` is enough
</blockquote></details>

Done.
___
*[`crates/committer/src/types.rs` line 6 at r6](https://reviewable.io/reviews/starkware-libs/committer/18#-NvR2P8T12K8w7kCC42J:-NvRC5Oq1GfJvyys98MT:b-8tqydw) ([raw file](https://github.com/starkware-libs/committer/blob/bf97fefead6b97d344e43fc1f6d075a366d81fc3/crates/committer/src/types.rs#L6)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

revert this change? why did it appear? is it longer than 100 chars?
</blockquote></details>

Its the 
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nux22Oy-b8FN3JJBEYt:-NvQMqvg7uTjf7WjNFhE:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L67)):*
> ```XML
> 
>     #[allow(dead_code)]
>     pub(crate) fn serialise(&self,) -> Vec<u8> {
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nv171oN4Q7uCO0T99EB:-NvQMueN0S2xNyHMFBr3:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L67)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes, but the general `serialize` function on a general node is not of fixed size, because you don't know the node type.
an implementation of this function will `match` on node type, right?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nux1x3eEQEa0Cj_lIRQ:-NvQMqTX45L5V1SWzeJU:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L71)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why the hash, and not the preimage?
seems other node types get their preimage returned as bytes, why is the leaf different?
maybe add a `serialized_data` method to `LeafDataTrait` if you need it
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nux2jds-ErgnbOC4Jrk:-NvQMsv-1oYLX5SJwp02:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L71)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

function docstring should be above the definition, and start with triple-slash
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nux25WO-PlQgBNgGiNh:-NvQMrv01VJ4RnV5Whuc:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L84)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

destructure in the match
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/committer/18#-Nv19w6s0t8XqdQwotF4:-NvQMwM99mY85FsQqkow:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/08468176c54fb1c78496db0e8fed0c94c6c7d92d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L92)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if this works, it may be better (see @amosStarkware 's comment above)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 85 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBk-h19fCEA7rWSt_R:-NvRlknT-Rb-4CvVWsH-:bc1miy3) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L85)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

If `serde_json::Error` is the only `Serde` error that we expect here then that looks good.
</blockquote></details>

Great , I'm doing it with Dori's suggestion
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 101 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBjCFE7IdSHyXb-n5r:-NvQPf_MCslTvafyZMN3:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L101)):*
> ```XML
>     /// - For storage values: Serialises the value into a 32-byte array.
>     /// - For compiled class hashes: cast the json describe the leaf into a byte vector.
>     /// - For state tree tuples: cast the json describe the leaf into a byte vector.
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 114 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBisRT-yAzvqEMHL6J:-NvQRLq91CgF6wQy2QXz:b-ucfknh) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L114)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

shorthand for when you want to ignore parts of the struct.
you can also choose to ignore pars, for example
```
LeafData::StateTreeTuple{ nonce: leaf_nonce, .. }
```
</blockquote></details>

Thanks!
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 121 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBiDfL-6tLL6cyxTJZ:-NvRlv1k3VLEjyP-8eXo:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L121)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`to_pre_image_js` introduces a redundant panic: move it's logic to where it's known to work
</blockquote></details>

Done
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 129 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBlIOh963I_VvWhjPP:-NvQSQ3CCiBuqxgboDuH:bvx1kjn) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L129)):*
<details><summary><i>Previously, dorimedini-starkware wrote…< [...]

2024-04-14 14:04 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 6 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 12 unresolved discussions (waiting on @AvivYossef-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree.rs` line 6 at r8](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRuJr-AZcrTDAmx1FB:-NvRuJr-AZcrTDAmx1FC:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/286d4bc753a60e7e298459ffc9de85dee4df0eba/crates/committer/src/patricia_merkle_tree.rs#L6)):*
> ```XML
> pub mod original_skeleton_node;
> pub mod original_skeleton_tree;
> pub mod serialised_node;
> ```





_Suggestion:_
```XML
serialized_node
```
___
*[`crates/committer/src/types.rs` line 6 at r6](https://reviewable.io/reviews/starkware-libs/committer/18#-NvR2P8T12K8w7kCC42J:-NvRuXKw3IVeNwqyncrN:b3kre) ([raw file](https://github.com/starkware-libs/committer/blob/bf97fefead6b97d344e43fc1f6d075a366d81fc3/crates/committer/src/types.rs#L6)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Its the
</blockquote></details>

?
___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 2 at r7](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRoNzK2CWaYSWwGNYZ:-NvRoNzK2CWaYSWwGNY_:b-6u1ff5) ([raw file](https://github.com/starkware-libs/committer/blob/f17b37cb5aca097d521f71d39feb3dcd628033b7/crates/committer/src/patricia_merkle_tree/errors.rs#L2)):*
> ```XML
> // TODO(Amos, 01/04/2024): Add error types.
> use derive_more::Display;
> ```

I think the std version should be enough...? you sure you need the derive_more Display?



_Suggestion:_
```XML
use std::fmt::Display;
```
___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 15 at r7](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRoF4J9N6cMVp5m7DC:-NvRoF4J9N6cMVp5m7DD:b-d40zxa) ([raw file](https://github.com/starkware-libs/committer/blob/f17b37cb5aca097d521f71d39feb3dcd628033b7/crates/committer/src/patricia_merkle_tree/errors.rs#L15)):*
> ```XML
> pub(crate) enum FilledTreeError {
>     MissingRoot,
>     SerialiseError(#[from] serde_json::Error),
> ```

you are technically correct but apparently [with z is more popular](https://sapling.ai/usage/serialized-vs-serialised)



_Suggestion:_
```XML
Serialize
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 129 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBlIOh963I_VvWhjPP:-NvRtrEI5dHtAR37HMR8:b-n3uw8y) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L129)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

It doesn't compile without it because I don't split Leaf(LeafData) into cases
</blockquote></details>

I think the issue is this:
```
NodeData::Leaf(LeafData) => LeafData.serialise()
```
it should be:
```
NodeData::Leaf(leaf_data) => leaf_data.serialise()
```
try fixing this and removing the attribute
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 66 at r7](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRovJC3g7lLJ4ESiHK:-NvRovJC3g7lLJ4ESiHL:byr4ffv) ([raw file](https://github.com/starkware-libs/committer/blob/f17b37cb5aca097d521f71d39feb3dcd628033b7/crates/committer/src/patricia_merkle_tree/filled_node.rs#L66)):*
> ```XML
> 
> impl LeafData {
>     /// Serialises the leaf data into a JSON string.
> ```

see above



_Suggestion:_
```XML
Serializes
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 71 at r7](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRpSbpCbTTGxczspP2:-NvRpSbpCbTTGxczspP3:bggu8tr) ([raw file](https://github.com/starkware-libs/committer/blob/f17b37cb5aca097d521f71d39feb3dcd628033b7/crates/committer/src/patricia_merkle_tree/filled_node.rs#L71)):*
> ```XML
>     /// using temp structs which define in serialised_node.rs.
>     #[allow(dead_code)]
>     pub(crate) fn to_pre_image_js(&self) -> FilledTreeResult<String> {
> ```

why do you need this intermediate function?
ATM you have
```
serialize(self) {
    match &self {
        X => { ... X.to_pre_image_js }
        Y => { ... Y.to_pre_image_js }
        Z => { ... Z.to_pre_image_js }
   }
}
```
but `to_pre_image_js` also does `match &self`. No need for two matches... please combine the functions, and if you have common logic that doesn't depend on the enum variant you can extract the logic to a function



_Code quote:_
```XML
pub(crate) fn to_pre_image_js
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 75 at r7](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRodGo1jhR5KwMmwcA:-NvRodGo1jhR5KwMmwcB:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/f17b37cb5aca097d521f71d39feb3dcd628033b7/crates/committer/src/patricia_merkle_tree/filled_node.rs#L75)):*
> ```XML
>             LeafData::StorageValue(value) => {
>                 let json_string = serde_json::to_string(&value)?;
>                 Ok(json_string)
> ```





_Suggestion:_
```XML
                Ok(serde_json::to_string(&value)?)
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 83 at r7](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRojaO4EGSk33hiHSZ:-NvRojaO4EGSk33hiHS_:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/f17b37cb5aca097d521f71d39feb3dcd628033b7/crates/committer/src/patricia_merkle_tree/filled_node.rs#L83)):*
> ```XML
>                 };
>                 let json_string = serde_json::to_string(&temp_object_to_json)?;
>                 Ok(json_string)
> ```





_Suggestion:_
```XML
                Ok(serde_json::to_string(&temp_object_to_json)?)
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 89 at r7](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRozbf2QPm_S5LjyKa:-NvRozbf2QPm_S5LjyKb:b-1b18xo) ([raw file](https://github.com/starkware-libs/committer/blob/f17b37cb5aca097d521f71d39feb3dcd628033b7/crates/committer/src/patricia_merkle_tree/filled_node.rs#L89)):*
> ```XML
>                 class_hash: _,
>                 contract_state_root_hash: _,
>                 nonce: _,
> ```

shorter



_Suggestion:_
```XML
                ..
```
___
*[`crates/committer/src/patricia_merkle_tree/serialised_node.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBmQiR-tfyWbQh2rNt:-NvRubcIBmcBCHoODv4t:b-miq53d) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/serialised_node.rs#L8)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no, `EDGE_BYTES` is still explicitly 65 instead of with a formula
___
*[`crates/committer/src/patricia_merkle_tree/serialised_node.rs` line 20 at r8](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRup_ZAqM1u106uP3q:-NvRup_ZAqM1u106uP3r:b-p6g3es) ([raw file](https://github.com/starkware-libs/committer/blob/286d4bc753a60e7e298459ffc9de85dee4df0eba/crates/committer/src/patricia_merkle_tree/serialised_node.rs#L20)):*
> ```XML
> }
> 
> // Temporary struct to serialise the leaf CompiledClass.
> ```

some more words to explain that this can go away one day



_Suggestion:_
```XML
/// Temporary struct to serialize the leaf CompiledClass.
/// Required to comply to existing storage layout.
```


<!-- Sent from Reviewable.io -->

2024-04-14 20:17 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 12 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree.rs` line 6 at r8](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRuJr-AZcrTDAmx1FB:-NvS2KK_Be9I-oEgT8nj:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/286d4bc753a60e7e298459ffc9de85dee4df0eba/crates/committer/src/patricia_merkle_tree.rs#L6)):*
> ```XML
> pub mod original_skeleton_node;
> pub mod original_skeleton_tree;
> pub mod serialised_node;
> ```

Done.
___
*[`crates/committer/src/types.rs` line 6 at r6](https://reviewable.io/reviews/starkware-libs/committer/18#-NvR2P8T12K8w7kCC42J:-NvS1d6EEZ5-neRSQaTx:b-q53gi2) ([raw file](https://github.com/starkware-libs/committer/blob/bf97fefead6b97d344e43fc1f6d075a366d81fc3/crates/committer/src/types.rs#L6)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

The autoformat arranges it that way.
___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 2 at r7](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRoNzK2CWaYSWwGNYZ:-NvRySA_A002SrWLtVn2:b-8smjy1) ([raw file](https://github.com/starkware-libs/committer/blob/f17b37cb5aca097d521f71d39feb3dcd628033b7/crates/committer/src/patricia_merkle_tree/errors.rs#L2)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think the std version should be enough...? you sure you need the derive_more Display?
</blockquote></details>

Yes, it's not compiled like that since the std version is without a derive macro.
___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 15 at r7](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRoF4J9N6cMVp5m7DC:-NvRyGsU1rU0Q5Hlg1eJ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f17b37cb5aca097d521f71d39feb3dcd628033b7/crates/committer/src/patricia_merkle_tree/errors.rs#L15)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you are technically correct but apparently [with z is more popular](https://sapling.ai/usage/serialized-vs-serialised)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 129 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBlIOh963I_VvWhjPP:-NvS-dRD-bP6CNlY_aTe:bb76rw6) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L129)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think the issue is this:
```
NodeData::Leaf(LeafData) => LeafData.serialise()
```
it should be:
```
NodeData::Leaf(leaf_data) => leaf_data.serialise()
```
try fixing this and removing the attribute
</blockquote></details>

Work
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 66 at r7](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRovJC3g7lLJ4ESiHK:-NvRylMW0z6aPCCdJTIc:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f17b37cb5aca097d521f71d39feb3dcd628033b7/crates/committer/src/patricia_merkle_tree/filled_node.rs#L66)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 71 at r7](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRpSbpCbTTGxczspP2:-NvTDDqI-Os4WGXtWOzL:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/f17b37cb5aca097d521f71d39feb3dcd628033b7/crates/committer/src/patricia_merkle_tree/filled_node.rs#L71)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you need this intermediate function?
ATM you have
```
serialize(self) {
    match &self {
        X => { ... X.to_pre_image_js }
        Y => { ... Y.to_pre_image_js }
        Z => { ... Z.to_pre_image_js }
   }
}
```
but `to_pre_image_js` also does `match &self`. No need for two matches... please combine the functions, and if you have common logic that doesn't depend on the enum variant you can extract the logic to a function
</blockquote></details>

Done
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 75 at r7](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRodGo1jhR5KwMmwcA:-NvS0AuA0vEsXYjInHIx:bbmabee) ([raw file](https://github.com/starkware-libs/committer/blob/f17b37cb5aca097d521f71d39feb3dcd628033b7/crates/committer/src/patricia_merkle_tree/filled_node.rs#L75)):*
> ```XML
>             LeafData::StorageValue(value) => {
>                 let json_string = serde_json::to_string(&value)?;
>                 Ok(json_string)
> ```

Thats nice
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 83 at r7](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRojaO4EGSk33hiHSZ:-NvS0DhI4vHB1VNIrQlV:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f17b37cb5aca097d521f71d39feb3dcd628033b7/crates/committer/src/patricia_merkle_tree/filled_node.rs#L83)):*
> ```XML
>                 };
>                 let json_string = serde_json::to_string(&temp_object_to_json)?;
>                 Ok(json_string)
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 89 at r7](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRozbf2QPm_S5LjyKa:-NvTDYm61FhX8_vg9OO5:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f17b37cb5aca097d521f71d39feb3dcd628033b7/crates/committer/src/patricia_merkle_tree/filled_node.rs#L89)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

shorter
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/serialised_node.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/committer/18#-NvBmQiR-tfyWbQh2rNt:-NvS-D1v6EcaqvhdO8aN:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/33be17a0f7abc7516139b1366988462375f5ec4b/crates/committer/src/patricia_merkle_tree/serialised_node.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no, `EDGE_BYTES` is still explicitly 65 instead of with a formula
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/serialised_node.rs` line 20 at r8](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRup_ZAqM1u106uP3q:-NvRzb4a9-nO1OjbgWSu:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/286d4bc753a60e7e298459ffc9de85dee4df0eba/crates/committer/src/patricia_merkle_tree/serialised_node.rs#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

some more words to explain that this can go away one day
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-14 21:38 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 5 unresolved discussions (waiting on @AvivYossef-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 67 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvTWQjIBlxy0WSaPXjH:-NvTWQjJ8BfoMlMBnpmr:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/filled_node.rs#L67)):*
> ```XML
> impl LeafData {
>     /// This method serializes the leaf data into a byte array.
>     /// serializes the leaf data into a byte array.
> ```





_Suggestion:_
```XML
    /// Serializes the leaf data into a byte array.
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 88 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvTWi0_6r4Fhpxlk-Mr:-NvTWi0_6r4Fhpxlk-Ms:b-obuakb) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/filled_node.rs#L88)):*
> ```XML
>                 Ok(SerializeNode::CompiledClassLeaf(
>                     json?.into_bytes().to_owned(),
>                 ))
> ```

propagate the error as soon as possible



_Suggestion:_
```XML
                let json = serde_json::to_string(&temp_object_to_json)?;

                // Serialize the json into a byte vector.
                Ok(SerializeNode::CompiledClassLeaf(
                    json.into_bytes().to_owned(),
                ))
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 100 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvTX3AbE281qUB-pmeP:-NvTX3AbE281qUB-pmeQ:b6fom5d) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/filled_node.rs#L100)):*
> ```XML
>                 Ok(SerializeNode::CompiledClassLeaf(
>                     json?.into_bytes().to_owned(),
>                 ))
> ```

this is misleading (`SerializeNode::CompiledClassLeaf` is not the correct type for a `StateTreeTuple`, right?).
replace all the dummy logic here with a single todo



_Suggestion:_
```XML
                todo!("Implement.")
```
___
*[`crates/committer/src/patricia_merkle_tree/serialised_node.rs` line 20 at r8](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRup_ZAqM1u106uP3q:-NvTXXMsC0mwIQZnXH6r:b-ut7np8) ([raw file](https://github.com/starkware-libs/committer/blob/286d4bc753a60e7e298459ffc9de85dee4df0eba/crates/committer/src/patricia_merkle_tree/serialised_node.rs#L20)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it
___
*[`crates/committer/src/patricia_merkle_tree/serialized_node.rs` line 19 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvTXfUZ-Lq9q0FAxZwS:-NvTXfUZ-Lq9q0FAxZwT:b-zgxhhn) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/serialized_node.rs#L19)):*
> ```XML
>     CompiledClassLeaf(Vec<u8>),
>     StorageLeaf([u8; STORAGE_LEAF_SIZE]),
>     StateTreeLeaf(Vec<u8>),
> ```

`CompiledClassLeaf` and `StateTreeLeaf` will later have fixed sizes, right?
Can you add a TODO above each, to set their size?



_Code quote:_
```XML
    CompiledClassLeaf(Vec<u8>),
    StorageLeaf([u8; STORAGE_LEAF_SIZE]),
    StateTreeLeaf(Vec<u8>),
```


<!-- Sent from Reviewable.io -->

2024-04-16 18:30 UTC, amosStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 11 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`.gitignore` line 9 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvbLhAB7V1-FWEAqiaC:-NvbLhACB7Ni3k2m-Rey:bv2caw5) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/.gitignore#L9)):*
> ```ignore
> */.vscode/*
> *.DS_Store
> .vscode/settings.json
> ```

by mistake?



_Code quote:_
```ignore
.vscode/settings.json
```
___
*[`Cargo.toml` line 23 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvbM3jJ8Uml2Petfg3M:-NvbM3jJ8Uml2Petfg3N:b76hki7) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/Cargo.toml#L23)):*
> ```TOML
> starknet-types-core = { version = "0.0.11", features = ["hash"] }
> serde_json = "1.0"
> serde = { version = "1.0", features = ["derive"] }
> ```

why not the newest versions?
serde = "1.0.197"
serde_json = "1.0.116"



_Code quote:_
```TOML
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
```
___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 12 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvbMhrD8--B_2oReOf9:-NvbMhrE7i1lnVMVXj8S:bklkm4m) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/errors.rs#L12)):*
> ```XML
> }
> 
> #[derive(thiserror::Error, Debug, Display)]
> ```

IMO it's better to explicitly write `derive_more::Display`,
otherwise it will be confusing if we want to use std::fmt:Display.
non blocking



_Code quote:_
```XML
#[derive(thiserror::Error, Debug, Display)]
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 65 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvcA-lx7tVBDDCNMQPf:-NvcA-lx7tVBDDCNMQPg:b24rc7c) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/filled_node.rs#L65)):*
> ```XML
> }
> 
> impl LeafData {
> ```

this should move to `leaf/leaf_serde.rs`



_Code quote:_
```XML
impl LeafData {
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 112 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvbYZ79AHEj5HPvQ6wu:-NvbYZ79AHEj5HPvQ6wv:b-8m6ls4) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/filled_node.rs#L112)):*
> ```XML
>     /// - For leaf nodes: use leaf.serialize() method.
>     #[allow(dead_code)]
>     pub(crate) fn serialize(&self) -> FilledTreeResult<SerializeNode> {
> ```

better to make this an implementation of a separate serde_trait, and put it in `filled_node_serde.rs`



_Code quote:_
```XML
pub(crate) fn serialize(&self) -> FilledTreeResult<SerializeNode> {
```
___
*[`crates/committer/src/patricia_merkle_tree/serialised_node.rs` line 20 at r8](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRup_ZAqM1u106uP3q:-NvbQ-H0-vMengaMj0Th:bkp2abr) ([raw file](https://github.com/starkware-libs/committer/blob/286d4bc753a60e7e298459ffc9de85dee4df0eba/crates/committer/src/patricia_merkle_tree/serialised_node.rs#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't see it
</blockquote></details>

can you explain what this is for?
___
*[`crates/committer/src/patricia_merkle_tree/serialised_node.rs` line 2 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvbQA4wBWokLEcig9Et:-NvbQA4wBWokLEcig9Eu:b-4w0jlq) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/serialised_node.rs#L2)):*
> ```XML
> use crate::types::Felt;
> use serde::{Deserialize, Serialize};
> ```

looks like you have duplicate files by mistake - `serialised_node` & serialized_node`



_Code quote:_
```XML
use crate::types::Felt;
use serde::{Deserialize, Serialize};
```


<!-- Sent from Reviewable.io -->

2024-04-17 13:27 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: 5 of 16 files reviewed, 9 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`Cargo.toml` line 23 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvbM3jJ8Uml2Petfg3M:-NvfZ8oM5Cr9nZkaqPUn:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/Cargo.toml#L23)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why not the newest versions?
serde = "1.0.197"
serde_json = "1.0.116"
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 12 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvbMhrD8--B_2oReOf9:-NvfZUIz4DkqYfoWGpuo:b2nhktp) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/errors.rs#L12)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

IMO it's better to explicitly write `derive_more::Display`,
otherwise it will be confusing if we want to use std::fmt:Display.
non blocking
</blockquote></details>

OK.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 65 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvcA-lx7tVBDDCNMQPf:-Nvfc7C79XwVzL0HS-JR:bvgvv6y) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/filled_node.rs#L65)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

this should move to `leaf/leaf_serde.rs`
</blockquote></details>

We decide to move it in different PR.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 67 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvTWQjIBlxy0WSaPXjH:-NvfcCyn-705TkUeoa-L:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/filled_node.rs#L67)):*
> ```XML
> impl LeafData {
>     /// This method serializes the leaf data into a byte array.
>     /// serializes the leaf data into a byte array.
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 88 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvTWi0_6r4Fhpxlk-Mr:-NvgAwKw8NhsqGo_0mow:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/filled_node.rs#L88)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

propagate the error as soon as possible
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 100 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvTX3AbE281qUB-pmeP:-NvgB55X3SHgm4j7gHGD:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/filled_node.rs#L100)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is misleading (`SerializeNode::CompiledClassLeaf` is not the correct type for a `StateTreeTuple`, right?).
replace all the dummy logic here with a single todo
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 112 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvbYZ79AHEj5HPvQ6wu:-NvgBDfLDkvBB-vBuOi_:bwu2yn8) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/filled_node.rs#L112)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

better to make this an implementation of a separate serde_trait, and put it in `filled_node_serde.rs`
</blockquote></details>

We decide to do it in different PR.
___
*[`crates/committer/src/patricia_merkle_tree/serialized_node.rs` line 19 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvTXfUZ-Lq9q0FAxZwS:-NvgBhgX4DnxGdkfalwC:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/serialized_node.rs#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`CompiledClassLeaf` and `StateTreeLeaf` will later have fixed sizes, right?
Can you add a TODO above each, to set their size?
</blockquote></details>

Done.
___
*[`.gitignore` line 9 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvbLhAB7V1-FWEAqiaC:-NvfYXWqA84Viyu1RpeF:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/.gitignore#L9)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

by mistake?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/serialised_node.rs` line 20 at r8](https://reviewable.io/reviews/starkware-libs/committer/18#-NvRup_ZAqM1u106uP3q:-NvgBRC72kzqFTZHy4TA:b-h0vtk8) ([raw file](https://github.com/starkware-libs/committer/blob/286d4bc753a60e7e298459ffc9de85dee4df0eba/crates/committer/src/patricia_merkle_tree/serialised_node.rs#L20)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

can you explain what this is for?
</blockquote></details>

In serialized_node.rs
This is to be consist with marshmallow data class
___
*[`crates/committer/src/patricia_merkle_tree/serialised_node.rs` line 2 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvbQA4wBWokLEcig9Et:-NvgBISj9zQSCfKMBY-b:b-ucfkn4) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/serialised_node.rs#L2)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

looks like you have duplicate files by mistake - `serialised_node` & serialized_node`
</blockquote></details>

Thanks.


<!-- Sent from Reviewable.io -->

2024-04-17 13:44 UTC, dorimedini-starkware requested changes
> Reviewed 11 of 11 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, and @nimrod-starkware)

___
*[`crates/committer/Cargo.toml` line 22 at r10](https://reviewable.io/reviews/starkware-libs/committer/18#-NvgHe-C3U6AuU_3Abnp:-NvgHe-C3U6AuU_3Abnq:b-10o17o) ([raw file](https://github.com/starkware-libs/committer/blob/6a025b69aab3b4b078888fd76de847ee7942bb2d/crates/committer/Cargo.toml#L22)):*
> ```TOML
> thiserror.workspace = true
> serde.workspace = true
> serde_json.workspace = true
> ```

alphabetize



_Suggestion:_
```TOML
starknet-types-core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
```
___
*[`crates/committer/src/types.rs` line 55 at r10](https://reviewable.io/reviews/starkware-libs/committer/18#-NvgHief7AISLEaawegp:-NvgHief7AISLEaawegq:b-agr6lv) ([raw file](https://github.com/starkware-libs/committer/blob/6a025b69aab3b4b078888fd76de847ee7942bb2d/crates/committer/src/types.rs#L55)):*
> ```XML
>         Ok(StarknetTypesFelt::from_hex(hex_string)?.into())
>     }
>     pub(crate) fn as_bytes(&self) -> [u8; 32] {
> ```

newline between function defs



_Suggestion:_
```XML
    }
    
    pub(crate) fn as_bytes(&self) -> [u8; 32] {
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 9 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvgHpqn9PjaGioAMJKk:-NvgHpqn9PjaGioAMJKl:b-q4wq7g) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/filled_node.rs#L9)):*
> ```XML
> use crate::{hash::types::HashOutput, types::Felt};
> 
> // TODO(Nimrod, 1/6/2024): Swap to starknet-types-core types once implemented.
> ```

why was this deleted?



_Code quote:_
```XML
// TODO(Nimrod, 1/6/2024): Swap to starknet-types-core types once implemented.
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 134 at r10](https://reviewable.io/reviews/starkware-libs/committer/18#-NvgI9X3BYDNS27I58FQ:-NvgI9X3BYDNS27I58FR:bmh77m4) ([raw file](https://github.com/starkware-libs/committer/blob/6a025b69aab3b4b078888fd76de847ee7942bb2d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L134)):*
> ```XML
> 
>                 // Concatenate bottom hash, path, and path length.
>                 let serialized = [bottom.to_vec(), path.to_vec(), length.to_vec()].concat();
> ```

if this works, I would guess it's faster (and it's shorter anyway)



_Suggestion:_
```XML
[bottom, path, length].concat().to_vec();
```


<!-- Sent from Reviewable.io -->

2024-04-17 13:58 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18)* status: all files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/committer/Cargo.toml` line 22 at r10](https://reviewable.io/reviews/starkware-libs/committer/18#-NvgHe-C3U6AuU_3Abnp:-NvgK4L256syRca_aUq5:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/6a025b69aab3b4b078888fd76de847ee7942bb2d/crates/committer/Cargo.toml#L22)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

alphabetize
</blockquote></details>

Done.
___
*[`crates/committer/src/types.rs` line 55 at r10](https://reviewable.io/reviews/starkware-libs/committer/18#-NvgHief7AISLEaawegp:-NvgKHDi3-DFMLynm0h6:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/6a025b69aab3b4b078888fd76de847ee7942bb2d/crates/committer/src/types.rs#L55)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newline between function defs
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 9 at r9](https://reviewable.io/reviews/starkware-libs/committer/18#-NvgHpqn9PjaGioAMJKk:-NvgKTZc4B5aDfXHDeu_:bessqo8) ([raw file](https://github.com/starkware-libs/committer/blob/d8a4e47a5d2a0d605491aba8ceb7e1e121e415a3/crates/committer/src/patricia_merkle_tree/filled_node.rs#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why was this deleted?
</blockquote></details>

It is not deleted.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 134 at r10](https://reviewable.io/reviews/starkware-libs/committer/18#-NvgI9X3BYDNS27I58FQ:-NvgKu3p4MP0-85S8MAw:b-t3ak78) ([raw file](https://github.com/starkware-libs/committer/blob/6a025b69aab3b4b078888fd76de847ee7942bb2d/crates/committer/src/patricia_merkle_tree/filled_node.rs#L134)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if this works, I would guess it's faster (and it's shorter anyway)
</blockquote></details>

Rust doesn't like it since the length's size is different. 


<!-- Sent from Reviewable.io -->

2024-04-17 14:23 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18#-:-NvgR8n92RmijVbF8ST9:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-04-17 14:53 UTC, amosStarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/18#-:-NvgY80u6nfMnk_djakd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-04-17 14:58 UTC, merged