chore: add deserialization types and basic casting implementation
starkware-libs/committer pull request #27
Opened 2024-04-09 11:23 UTC by nimrod-starkware

Adding deserialized types that will be sent from python to the committer

2024-04-09 11:50 UTC, dorimedini-starkware requested changes
> Reviewed 8 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 20 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/Cargo.toml` line 17 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1b91C23Zn_yIGUI8J:-Nv1b91C23Zn_yIGUI8K:b-ojzh1n) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/Cargo.toml#L17)):*
> ```TOML
> [dependencies]
> starknet-types-core = "0.0.11"
> starknet_api = "0.12.0-dev.0"
> ```

it is a mistake that these are here... so while you're making changes:
1. starknet_api is not actually in use; please remove it (udeps should fail)
2. all dependencies should be declared in the root Cargo.toml; please move `starknet-types-core = "0.0.11"` there and use `workspace = true` here



_Suggestion:_
```TOML
starknet-types-core.workspace = true
```
___
*[`crates/committer/Cargo.toml` line 19 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1b5m62VkZpND0sO5P:-Nv1b5m62VkZpND0sO5Q:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/Cargo.toml#L19)):*
> ```TOML
> starknet_api = "0.12.0-dev.0"
> serde = { version = "1.0.197", features = ["derive"] }
> serde_json = "1.0"
> ```





_Suggestion:_
```TOML
serde.workspace = true
serde_json.workspace = true
```
___
*[`crates/committer/src/deserialization_impl.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1ewJg8ZuLJn2mQmg5:-Nv1ewJg8ZuLJn2mQmg6:b-86ojyn) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L0)):*
you are introducing possible panics to business logic; I would rather you use Result types.
1. instead of implementing `From`, implement `TryFrom`
2. define an error type for non-unique hashmap deserialization (that's what the `assert!`s are for, right?)
3. talk to Amos for how to do this; he already introduced errors types, he will have an opinion on where your new error type should be added
___
*[`crates/committer/src/deserialization_impl.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1bEdLCCMNCutYcAtg:-Nv1bEdM1uefsKMzwty5:b-gi0msf) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L7)):*
> ```XML
> };
> use crate::patricia_merkle_tree::filled_node::{ClassHash, Nonce};
> use starknet_types_core::felt::Felt;
> ```

use internal felt representation



_Suggestion:_
```XML
use crate::types::Felt;
```
___
*[`crates/committer/src/deserialization_impl.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1eNrx7MQoiQfbutIC:-Nv1eNrx7MQoiQfbutID:bu5oyob) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L11)):*
> ```XML
> #[allow(dead_code)]
> impl DeserializedInput {
>     pub fn actual_input(self) -> ActualInput {
> ```

when implementing type conversions, use the standard `From` trait when possible



_Suggestion:_
```XML
#[allow(dead_code)]
impl From<DeserializedInput> for ActualInput {
    pub fn from(deserialized_input: DeserializedInput) -> Self {
```
___
*[`crates/committer/src/deserialization_impl.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1fLbz1dwAnMlW2XkU:-Nv1fLc-EiWq50Y1E_o4:bkutiwa) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L14)):*
> ```XML
>         let mut storage = HashMap::new();
>         for entry in self.storage.into_iter() {
>             assert!(storage.insert(entry.key, entry.value).is_none())
> ```

remove (see above)



_Code quote:_
```XML
assert!
```
___
*[`crates/committer/src/deserialization_impl.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1fQVK3X8qVgcCVnoE:-Nv1fQVK3X8qVgcCVnoF:bkutiwa) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L19)):*
> ```XML
>         let mut address_to_class_hash = HashMap::new();
>         for entry in self.state_diff.address_to_class_hash {
>             assert!(address_to_class_hash
> ```

remove (see above)



_Code quote:_
```XML
assert!
```
___
*[`crates/committer/src/deserialization_impl.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1fTTt4DOYEYoukj2Z:-Nv1fTTt4DOYEYoukj2_:bkutiwa) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L29)):*
> ```XML
>         let mut address_to_nonce = HashMap::new();
>         for entry in self.state_diff.address_to_nonce {
>             assert!(address_to_nonce
> ```

remove (see above)



_Code quote:_
```XML
assert!
```
___
*[`crates/committer/src/deserialization_impl.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1fVG-EhLqs1jidfjl:-Nv1fVG-EhLqs1jidfjm:bkutiwa) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L39)):*
> ```XML
>         let mut class_hash_to_compiled_class_hash = HashMap::new();
>         for entry in self.state_diff.class_hash_to_compiled_class_hash {
>             assert!(class_hash_to_compiled_class_hash
> ```

remove (see above)



_Code quote:_
```XML
assert!
```
___
*[`crates/committer/src/deserialization_impl.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1fZWZ1THFMfBx6YPJ:-Nv1fZWZ1THFMfBx6YPK:bkutiwa) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L49)):*
> ```XML
>         let mut current_contract_state_leaves = HashMap::new();
>         for entry in self.state_diff.current_contract_state_leaves {
>             assert!(current_contract_state_leaves
> ```

remove (see above)



_Code quote:_
```XML
assert!
```
___
*[`crates/committer/src/deserialization_impl.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1gH1D0lm0TQkTaVCI:-Nv1gH1D0lm0TQkTaVCJ:b-qkzwtf) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L74)):*
> ```XML
>                 .collect();
>             storage_updates.insert(Felt::from_bytes_be_slice(&outer_entry.address), tmp_map);
>         }
> ```

you don't check for uniqueness here?
(not with assert, but you could return an `Err`)



_Code quote:_
```XML
        for outer_entry in self.state_diff.storage_updates {
            let tmp_map: HashMap<Felt, Felt> = outer_entry
                .storage_updates
                .iter()
                .map(|inner_entry| {
                    (
                        Felt::from_bytes_be_slice(&inner_entry.key),
                        Felt::from_bytes_be_slice(&inner_entry.value),
                    )
                })
                .collect();
            storage_updates.insert(Felt::from_bytes_be_slice(&outer_entry.address), tmp_map);
        }
```
___
*[`crates/committer/src/deserialization_types.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1dmSeEEvw3zqBIqGT:-Nv1buue4IN4AhXV2oMc:blez4wx) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_types.rs#L0)):*
WDYM by "deserialized" in this context?
It looks like the `ActualX` types are "deserialized";
what you call `DeserializedX` is actually the *serialized* version of X, right?
_ [...]

2024-04-09 12:55 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 20 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/Cargo.toml` line 17 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1b91C23Zn_yIGUI8J:-Nv1lSZ1BbaAalT2Yyp7:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/Cargo.toml#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it is a mistake that these are here... so while you're making changes:
1. starknet_api is not actually in use; please remove it (udeps should fail)
2. all dependencies should be declared in the root Cargo.toml; please move `starknet-types-core = "0.0.11"` there and use `workspace = true` here
</blockquote></details>

Done.
___
*[`crates/committer/Cargo.toml` line 19 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1b5m62VkZpND0sO5P:-Nv1lSpn0FJcs464ShX8:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/Cargo.toml#L19)):*
> ```TOML
> starknet_api = "0.12.0-dev.0"
> serde = { version = "1.0.197", features = ["derive"] }
> serde_json = "1.0"
> ```

Done.
___
*[`crates/committer/src/deserialization_impl.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1ewJg8ZuLJn2mQmg5:-Nv1vIFN3sfPfeUkBmRU:bgvs52y) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you are introducing possible panics to business logic; I would rather you use Result types.
1. instead of implementing `From`, implement `TryFrom`
2. define an error type for non-unique hashmap deserialization (that's what the `assert!`s are for, right?)
3. talk to Amos for how to do this; he already introduced errors types, he will have an opinion on where your new error type should be added
</blockquote></details>

will do.
___
*[`crates/committer/src/deserialization_types.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1bIzV51MqTgDLfcgl:-Nv1qv5uB15_4nKVBYQt:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_types.rs#L3)):*
> ```XML
> use crate::patricia_merkle_tree::filled_node::{ClassHash, Nonce};
> use serde::Deserialize;
> use starknet_types_core::felt::Felt;
> ```

Done.
___
*[`crates/committer/src/deserialization_types.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1c2-64LtY0SOt3H05:-Nv1qty73XBe090AHswF:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_types.rs#L6)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

field elements are fixed size
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization_types.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1dHWpC5v8NnKsyIjV:-Nv1pBLl0g-Yxy27H-yo:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_types.rs#L7)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. split key and value types
2. wrap, not type alias
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization_types.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1cDBfC2dYxOdjcF4P:-Nv1qtGcEb7FOS_dAuNz:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_types.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. you are overloading this type to mean two things; split the types
2. use wrapper types (`struct`) not type aliases (`type`) to make sure these types are *not* interchangeable
3. these "should" be defined in starknet-api but they use the "wrong" Felt type, so put TODOs
4. use the name `StarknetStorageKey` to differentiate between the storage key of a leaf in a starknet contract state tree, and a storage key in our storage abstraction
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization_types.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1fxOvCB8Bgc0aALWt:-Nv1qslPCJPF6D7Ysk8Y:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_types.rs#L22)):*
> ```XML
> #[allow(dead_code)]
> pub(crate) struct ActualInput {
>     pub storage: HashMap<Bytes, Bytes>,
> ```

Done.
___
*[`crates/committer/src/deserialization_types.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1d-Nx11XWBnKi0cs4:-Nv1rLeq-LEK8cpqaqaT:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_types.rs#L89)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this the correct type? WDYT?
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization_types.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1dmSeEEvw3zqBIqGT:-Nv1mYKj-QhhWQWqIT01:bvtiq3q) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_types.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM by "deserialized" in this context?
It looks like the `ActualX` types are "deserialized";
what you call `DeserializedX` is actually the *serialized* version of X, right?
</blockquote></details>

What i mean is:
DeserializedX is some way to represent X that can be easily deserialized with a json reader. 
ActualX is how we actually want to use those objects, with the correct types.
The casting is always DeserializedX => ActualX

I know the names are bad though...

Maybe i should change it?
changing DeserializedX => RawX, ActualX =>DeserializedX is better?


<!-- Sent from Reviewable.io -->

2024-04-09 13:48 UTC, dorimedini-starkware requested changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 12 unresolved discussions (waiting on @nimrod-starkware)

___
*[`Cargo.toml` line 22 at r3](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv25gv56hQoYPUZRvwN:-Nv25gv56hQoYPUZRvwO:b-2mmej8) ([raw file](https://github.com/starkware-libs/committer/blob/74a025cdddb5800800fe4db3ec3d227ee1ac1f9d/Cargo.toml#L22)):*
> ```TOML
> 
> 
> [workspace.lints.rust]
> ```

remove extra newline (non blocking)



_Suggestion:_
```TOML
starknet-types-core = "0.0.11"

[workspace.lints.rust]
```
___
*[`crates/committer/src/deserialization_impl.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv25znU5RrC8yqUU7EG:-Nv25znU5RrC8yqUU7EH:b-g2se1x) ([raw file](https://github.com/starkware-libs/committer/blob/74a025cdddb5800800fe4db3ec3d227ee1ac1f9d/crates/committer/src/deserialization_impl.rs#L75)):*
> ```XML
>                     (
>                         StarknetStorageKey(Felt::from_bytes_be_slice(&inner_entry.key)),
>                         Felt::from_bytes_be_slice(&inner_entry.value),
> ```

define a wrapper type for this please



_Suggestion:_
```XML
StarknetStorageValue(Felt::from_bytes_be_slice(&inner_entry.value))
```
___
*[`crates/committer/src/deserialization_types.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1dmSeEEvw3zqBIqGT:-Nv26AZN7Q8mVTE-W4lL:b-315cbs) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_types.rs#L)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

What i mean is:
DeserializedX is some way to represent X that can be easily deserialized with a json reader. 
ActualX is how we actually want to use those objects, with the correct types.
The casting is always DeserializedX => ActualX

I know the names are bad though...

Maybe i should change it?
changing DeserializedX => RawX, ActualX =>DeserializedX is better?
</blockquote></details>

yes, raw and deserialized is better.
although, instead of `DeserializedX` you could just go with `X`


<!-- Sent from Reviewable.io -->

2024-04-10 08:17 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: 2 of 11 files reviewed, 12 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/deserialization_impl.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1eNrx7MQoiQfbutIC:-Nv63dn6Bjby3Y9Zat2p:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

when implementing type conversions, use the standard `From` trait when possible
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization_impl.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1fLbz1dwAnMlW2XkU:-Nv63n4I-isxGgA3xxMv:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L14)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

remove (see above)
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization_impl.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1fQVK3X8qVgcCVnoE:-Nv63jy75gDRMU62eztg:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

remove (see above)
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization_impl.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1fTTt4DOYEYoukj2Z:-Nv63mXOByZUIK575fU-:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

remove (see above)
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization_impl.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1fVG-EhLqs1jidfjl:-Nv63knh6kVv1WLA11xs:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

remove (see above)
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization_impl.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1fZWZ1THFMfBx6YPJ:-Nv63kWx8ufl8TwclJMW:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

remove (see above)
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization_impl.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1ewJg8ZuLJn2mQmg5:-Nv63oHJBSkwKrYj6jcu:bs35qmi) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_impl.rs#L)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

will do.
</blockquote></details>

added a key duplicate error with this crate (it's used in the blockifier repository)
___
*[`crates/committer/src/deserialization_impl.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv25znU5RrC8yqUU7EG:-Nv63lh58Pxl6NdeCL56:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/74a025cdddb5800800fe4db3ec3d227ee1ac1f9d/crates/committer/src/deserialization_impl.rs#L75)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

define a wrapper type for this please
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization_types.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv1dmSeEEvw3zqBIqGT:-Nv5x6p62nhTFjbSzHdZ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ee11d2a10493cf1da49a5e97136120988298958/crates/committer/src/deserialization_types.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes, raw and deserialized is better.
although, instead of `DeserializedX` you could just go with `X`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-10 10:43 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 9 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 6 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/deserialization/cast.rs` line 1 at r5](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv6ZmVaD9FwTfL4pWtp:-Nv6ZmVaD9FwTfL4pWtq:bdhieua) ([raw file](https://github.com/starkware-libs/committer/blob/427ca5e047920cbc873faa16e1d2c8beb25b08d1/crates/committer/src/deserialization/cast.rs#L1)):*
> ```XML
> use super::errors::DeserializationError;
> ```

please implement and use this helper function for your hashmap constructions
```
fn<K, V> add_unique(map: &mut HashMap<K, V>, map_name: &str, key: &K, value: &V) -> Result<(), DeserializationError> {
    if map.insert(key, value).is_some() {
        return Err(DeserializationError::KeyDuplicate(format!("{map_name}: {key:?}"));
    }
    Ok(())
}
```
___
*[`crates/committer/src/deserialization/cast.rs` line 7 at r5](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv6aDwH-UN9fdcKPLtm:-Nv6aDwH-UN9fdcKPLtn:ba8ep0u) ([raw file](https://github.com/starkware-libs/committer/blob/427ca5e047920cbc873faa16e1d2c8beb25b08d1/crates/committer/src/deserialization/cast.rs#L7)):*
> ```XML
> use crate::patricia_merkle_tree::filled_node::{ClassHash, Nonce};
> use crate::types::Felt;
> use std::collections::HashMap;
> ```

please add a simple test for this: add a `cast_test.rs` module, create a dummy `RawInput` struct and assert the induced `Input` struct is as you expect



_Suggestion:_
```XML
use std::collections::HashMap;

#[cfg(test)]
#[path = "cast_test.rs"]
pub mod cast_test;
```
___
*[`crates/committer/src/deserialization/types.rs` line 33 at r7](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv6_pEx3VBu18x3jBfo:-Nv6_pEx3VBu18x3jBfp:bt3nicx) ([raw file](https://github.com/starkware-libs/committer/blob/163cbcf8e93477e11ebb009e86dbc28335824f7b/crates/committer/src/deserialization/types.rs#L33)):*
> ```XML
>     /// The height of the patricia tree.
>     // TODO(Nimrod,20/4/2024): Strong assumption - all trees have same height. How can I get
>     // rid of it?
> ```

(not in this PR) you can:
1. define a const in this repo
2. add a test in python that checks consistency between the height on the python side and the height here



_Code quote:_
```XML
    // TODO(Nimrod,20/4/2024): Strong assumption - all trees have same height. How can I get
    // rid of it?
```


<!-- Sent from Reviewable.io -->

2024-04-10 13:03 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 9 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/deserialization/cast.rs` line 1 at r8](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv75bIC9xeF5koLQKZI:-Nv75bIC9xeF5koLQKZJ:b-ibq8im) ([raw file](https://github.com/starkware-libs/committer/blob/4b68c78fb831764138ff308ee4ceadcd845a5857/crates/committer/src/deserialization/cast.rs#L1)):*
> ```XML
> use super::errors::DeserializationError;
> ```

Is it possible to do this entire deserialization using only serde attributes? without defining any intermediate `Raw` structs?
___
*[`crates/committer/src/deserialization/cast.rs` line 2 at r8](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv74lr59DZ97veKAVRV:-Nv74lr59DZ97veKAVRW:b-b3he2z) ([raw file](https://github.com/starkware-libs/committer/blob/4b68c78fb831764138ff308ee4ceadcd845a5857/crates/committer/src/deserialization/cast.rs#L2)):*
> ```XML
> use super::errors::DeserializationError;
> use super::types::{Input, RawInput, StarknetStorageKey, StarknetStorageValue, StateDiff};
> ```

didn't notice before: don't use `super` in non-test modules, import by `crate::` path explicitly



_Code quote:_
```XML
use super::errors::DeserializationError;
use super::types::{Input, RawInput, StarknetStorageKey, StarknetStorageValue, StateDiff};
```
___
*[`crates/committer/src/deserialization/cast.rs` line 50 at r8](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv753th-Z7Wk08p29hj:-Nv753th-Z7Wk08p29hk:b-2rb4zm) ([raw file](https://github.com/starkware-libs/committer/blob/4b68c78fb831764138ff308ee4ceadcd845a5857/crates/committer/src/deserialization/cast.rs#L50)):*
> ```XML
>                 "class hash to compiled class hash",
>                 ClassHash(Felt::from_bytes_be_slice(&entry.key)),
>                 ClassHash(Felt::from_bytes_be_slice(&entry.value)),
> ```

also didn't notice this before:
these two shouldn't be the same type.
the key is the hash of the sierra code, and the value is the hash of the CASM (compiled) code.
I think the terminology we use for the latter is `CompiledClassHash`



_Suggestion:_
```XML
                ClassHash(Felt::from_bytes_be_slice(&entry.key)),
                CompiledClassHash(Felt::from_bytes_be_slice(&entry.value)),
```
___
*[`crates/committer/src/deserialization/cast.rs` line 104 at r8](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv75X1N2xAeOHnZB-4Z:-Nv75X1N2xAeOHnZB-4_:b-q1ngl1) ([raw file](https://github.com/starkware-libs/committer/blob/4b68c78fb831764138ff308ee4ceadcd845a5857/crates/committer/src/deserialization/cast.rs#L104)):*
> ```XML
> }
> 
> pub(crate) fn add_unique<K, V>(
> ```

this util is only needed for this module



_Suggestion:_
```XML
fn add_unique<K, V>(
```


<!-- Sent from Reviewable.io -->

2024-04-10 13:13 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 10 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/deserialization/cast.rs` line 9 at r9](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv77uSQCopgdqfI29x7:-Nv77uSQCopgdqfI29x8:b-tfqtff) ([raw file](https://github.com/starkware-libs/committer/blob/0c6b37d8a72e49b372d4ef4e33d1dcecc7b49be5/crates/committer/src/deserialization/cast.rs#L9)):*
> ```XML
> use crate::storage::storage_trait::{StorageKey, StorageValue};
> use crate::types::Felt;
> use starknet_types_core::felt::Felt as StarknetTypesFelt;
> ```

do not use this type explicitly. only use our wrapper type.
implement a `from_bytes` method on our internal `Felt` instead



_Code quote:_
```XML
starknet_types_core::felt::Felt as StarknetTypesFelt;
```


<!-- Sent from Reviewable.io -->

2024-04-11 14:20 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: 12 of 13 files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/deserialization/cast.rs` line 1 at r5](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv6ZmVaD9FwTfL4pWtp:-NvCTs1H4_cqRg7OJ12k:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/427ca5e047920cbc873faa16e1d2c8beb25b08d1/crates/committer/src/deserialization/cast.rs#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please implement and use this helper function for your hashmap constructions
```
fn<K, V> add_unique(map: &mut HashMap<K, V>, map_name: &str, key: &K, value: &V) -> Result<(), DeserializationError> {
    if map.insert(key, value).is_some() {
        return Err(DeserializationError::KeyDuplicate(format!("{map_name}: {key:?}"));
    }
    Ok(())
}
```
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization/cast.rs` line 7 at r5](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv6aDwH-UN9fdcKPLtm:-NvCX2V79QSEv9-AodLG:b-d7bhn0) ([raw file](https://github.com/starkware-libs/committer/blob/427ca5e047920cbc873faa16e1d2c8beb25b08d1/crates/committer/src/deserialization/cast.rs#L7)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a simple test for this: add a `cast_test.rs` module, create a dummy `RawInput` struct and assert the induced `Input` struct is as you expect
</blockquote></details>

will do
___
*[`crates/committer/src/deserialization/cast.rs` line 1 at r8](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv75bIC9xeF5koLQKZI:-NvCTsCp4suuqpobBfr6:b53sanu) ([raw file](https://github.com/starkware-libs/committer/blob/4b68c78fb831764138ff308ee4ceadcd845a5857/crates/committer/src/deserialization/cast.rs#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Is it possible to do this entire deserialization using only serde attributes? without defining any intermediate `Raw` structs?
</blockquote></details>

we agreed to keep it that way
___
*[`crates/committer/src/deserialization/cast.rs` line 2 at r8](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv74lr59DZ97veKAVRV:-NvCU7GV2KviA3c5erho:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/4b68c78fb831764138ff308ee4ceadcd845a5857/crates/committer/src/deserialization/cast.rs#L2)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

didn't notice before: don't use `super` in non-test modules, import by `crate::` path explicitly
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization/cast.rs` line 50 at r8](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv753th-Z7Wk08p29hj:-NvCWzGm8Z1uZezMIwD_:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/4b68c78fb831764138ff308ee4ceadcd845a5857/crates/committer/src/deserialization/cast.rs#L50)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

also didn't notice this before:
these two shouldn't be the same type.
the key is the hash of the sierra code, and the value is the hash of the CASM (compiled) code.
I think the terminology we use for the latter is `CompiledClassHash`
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization/cast.rs` line 104 at r8](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv75X1N2xAeOHnZB-4Z:-NvCVNK70gnFLlo5aCiP:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/4b68c78fb831764138ff308ee4ceadcd845a5857/crates/committer/src/deserialization/cast.rs#L104)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this util is only needed for this module
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization/cast.rs` line 9 at r9](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv77uSQCopgdqfI29x7:-NvCVJxt00ofsO1oSsJi:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/0c6b37d8a72e49b372d4ef4e33d1dcecc7b49be5/crates/committer/src/deserialization/cast.rs#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do not use this type explicitly. only use our wrapper type.
implement a `from_bytes` method on our internal `Felt` instead
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-11 14:30 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 7 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/deserialization/cast.rs` line 2 at r8](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv74lr59DZ97veKAVRV:-NvCZAUS39adO3ssLyTC:b-r1owk) ([raw file](https://github.com/starkware-libs/committer/blob/4b68c78fb831764138ff308ee4ceadcd845a5857/crates/committer/src/deserialization/cast.rs#L2)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see `super::` here
___
*[`crates/committer/src/deserialization/cast.rs` line 50 at r8](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv753th-Z7Wk08p29hj:-NvCZGOiCC1XuRV4MvND:b-5rroz) ([raw file](https://github.com/starkware-libs/committer/blob/4b68c78fb831764138ff308ee4ceadcd845a5857/crates/committer/src/deserialization/cast.rs#L50)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

don't see it
___
*[`crates/committer/src/deserialization/cast.rs` line 9 at r9](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv77uSQCopgdqfI29x7:-NvCZDJ69s-BdfOk6Wnr:bh5xmp9) ([raw file](https://github.com/starkware-libs/committer/blob/0c6b37d8a72e49b372d4ef4e33d1dcecc7b49be5/crates/committer/src/deserialization/cast.rs#L9)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still here


<!-- Sent from Reviewable.io -->

2024-04-11 16:45 UTC, dorimedini-starkware requested changes
> Reviewed 11 of 11 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 8 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/types.rs` line 44 at r11](https://reviewable.io/reviews/starkware-libs/committer/27#-NvD-1wWAerS1FLQ8snw:-NvD-1wWAerS1FLQ8snx:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/f5e1bbe401248cb265a873e8085a5eaaed3d712e/crates/committer/src/types.rs#L44)):*
> ```XML
>     pub fn pow(&self, exponent: impl Into<u128>) -> Self {
>         Self(self.0.pow(exponent.into()))
>     }
> ```





_Suggestion:_
```XML
    pub(crate) const ZERO: Felt = Felt(StarknetTypesFelt::ZERO);
    pub(crate) const ONE: Felt = Felt(StarknetTypesFelt::ONE);
    pub(crate) const TWO: Felt = Felt(StarknetTypesFelt::TWO);
    
    pub(crate) fn from_bytes_be_slice(bytes: &[u8]) -> Self {
        Self(StarknetTypesFelt::from_bytes_be_slice(bytes))
    }
    
    /// Raises `self` to the power of `exponent`.
    pub(crate) fn pow(&self, exponent: impl Into<u128>) -> Self {
        Self(self.0.pow(exponent.into()))
    }
```
___
*[`crates/committer/src/deserialization/errors.rs` line 18 at r11](https://reviewable.io/reviews/starkware-libs/committer/27#-NvD1J828FqVzf0aE-DT:-NvD1J828FqVzf0aE-DU:b45h) ([raw file](https://github.com/starkware-libs/committer/blob/f5e1bbe401248cb265a873e8085a5eaaed3d712e/crates/committer/src/deserialization/errors.rs#L18)):*
> ```XML
>         DeserializationError::ParsingError
>     }
> }
> ```





_Suggestion:_
```XML
    #[error("Couldn't read and parse the given input JSON: {0}")]
    ParsingError(#[from] serde_json::Error),
}
```
___
*[`crates/committer/src/deserialization/read.rs` line 10 at r11](https://reviewable.io/reviews/starkware-libs/committer/27#-NvD1ZfY6xKwGH8Zt5hO:-NvD1ZfY6xKwGH8Zt5hP:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/f5e1bbe401248cb265a873e8085a5eaaed3d712e/crates/committer/src/deserialization/read.rs#L10)):*
> ```XML
> pub(crate) fn parse_input(input: String) -> DeserializationResult<Input> {
>     let raw_input: RawInput = serde_json::from_str(&input)?;
>     raw_input.try_into()
> ```





_Suggestion:_
```XML
    serde_json::from_str::<RawInput>(&input)?.try_into()
```
___
*[`crates/committer/src/deserialization/read.rs` line 17 at r11](https://reviewable.io/reviews/starkware-libs/committer/27#-NvD1j5f838Qd8u3G6VP:-NvD1j5f838Qd8u3G6VQ:bxg6gap) ([raw file](https://github.com/starkware-libs/committer/blob/f5e1bbe401248cb265a873e8085a5eaaed3d712e/crates/committer/src/deserialization/read.rs#L17)):*
> ```XML
> fn test_input_parsing() {
>     todo!()
> }
> ```

1. move this test to it's own module
2. move the `pub mod` instruction to the top, just under all the `use`s



_Suggestion:_
```XML
#[cfg(test)]
#[path = "read_test.rs"]
pub mod read_test;
```


<!-- Sent from Reviewable.io -->

2024-04-14 08:17 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: 11 of 14 files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/types.rs` line 44 at r11](https://reviewable.io/reviews/starkware-libs/committer/27#-NvD-1wWAerS1FLQ8snw:-NvQN7fuEQ85Pgo5wXZj:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f5e1bbe401248cb265a873e8085a5eaaed3d712e/crates/committer/src/types.rs#L44)):*
> ```XML
>     pub fn pow(&self, exponent: impl Into<u128>) -> Self {
>         Self(self.0.pow(exponent.into()))
>     }
> ```

Done.
___
*[`crates/committer/src/deserialization/errors.rs` line 18 at r11](https://reviewable.io/reviews/starkware-libs/committer/27#-NvD1J828FqVzf0aE-DT:-NvQOja2ERMbc107r-Ew:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f5e1bbe401248cb265a873e8085a5eaaed3d712e/crates/committer/src/deserialization/errors.rs#L18)):*
> ```XML
>         DeserializationError::ParsingError
>     }
> }
> ```

Done.
___
*[`crates/committer/src/deserialization/read.rs` line 10 at r11](https://reviewable.io/reviews/starkware-libs/committer/27#-NvD1ZfY6xKwGH8Zt5hO:-NvQfhdv-dMi1rcjG-Ul:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f5e1bbe401248cb265a873e8085a5eaaed3d712e/crates/committer/src/deserialization/read.rs#L10)):*
> ```XML
> pub(crate) fn parse_input(input: String) -> DeserializationResult<Input> {
>     let raw_input: RawInput = serde_json::from_str(&input)?;
>     raw_input.try_into()
> ```

Done.
___
*[`crates/committer/src/deserialization/read.rs` line 17 at r11](https://reviewable.io/reviews/starkware-libs/committer/27#-NvD1j5f838Qd8u3G6VP:-NvQfhDW8ofpIAaSr8zV:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f5e1bbe401248cb265a873e8085a5eaaed3d712e/crates/committer/src/deserialization/read.rs#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. move this test to it's own module
2. move the `pub mod` instruction to the top, just under all the `use`s
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-14 08:29 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 5 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/types.rs` line 44 at r11](https://reviewable.io/reviews/starkware-libs/committer/27#-NvD-1wWAerS1FLQ8snw:-NvQi7QT5wEhjJ3Ohj_P:b8azm5q) ([raw file](https://github.com/starkware-libs/committer/blob/f5e1bbe401248cb265a873e8085a5eaaed3d712e/crates/committer/src/types.rs#L44)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no, add `(crate)` to `pub`s
___
*[`crates/committer/src/deserialization/read.rs` line 22 at r12](https://reviewable.io/reviews/starkware-libs/committer/27#-NvQiHMr697xKf1bPtQ3:-NvQiHMr697xKf1bPtQ4:b-5jvx3u) ([raw file](https://github.com/starkware-libs/committer/blob/82776ff2061655a402afb316ae8316d115cb3648/crates/committer/src/deserialization/read.rs#L22)):*
> ```XML
>         assert!(parse_input(input.to_string()).is_ok());
>     }
> }
> ```

not quite :)
put the contents in a new file (`read_test.rs`)



_Suggestion:_
```XML
#[cfg(test)]
#[path = "read_test.rs"]
pub mod read_test;
```


<!-- Sent from Reviewable.io -->

2024-04-14 12:03 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/types.rs` line 44 at r11](https://reviewable.io/reviews/starkware-libs/committer/27#-NvD-1wWAerS1FLQ8snw:-NvQuh3V4tFvJjf7X_tB:b-7rl0jr) ([raw file](https://github.com/starkware-libs/committer/blob/f5e1bbe401248cb265a873e8085a5eaaed3d712e/crates/committer/src/types.rs#L44)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no, add `(crate)` to `pub`s
</blockquote></details>

done 
___
*[`crates/committer/src/deserialization/read.rs` line 22 at r12](https://reviewable.io/reviews/starkware-libs/committer/27#-NvQiHMr697xKf1bPtQ3:-NvQudRmA87A5snxc9C3:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/82776ff2061655a402afb316ae8316d115cb3648/crates/committer/src/deserialization/read.rs#L22)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not quite :)
put the contents in a new file (`read_test.rs`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-14 13:19 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 7 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/deserialization/read_test.rs` line 89 at r13](https://reviewable.io/reviews/starkware-libs/committer/27#-NvRjrNJ8-EUXXdsH8G8:-NvRjrNJ8-EUXXdsH8G9:b-39t7yt) ([raw file](https://github.com/starkware-libs/committer/blob/71f3f275dd5cbd0a7d39a108ea76a967c871eed6/crates/committer/src/deserialization/read_test.rs#L89)):*
> ```XML
> "#;
> 
>     assert!(parse_input(input.to_string()).is_ok());
> ```

for a basic test, I would prefer you compare explicitly to an expected deserialized object.
use `pretty_assertions::assert_eq` (may need to add the crate in cargo toml), construct the expected `Input` object explicitly and compare with `assert_eq` (may need to add `derive(Eq, PartialEq)` on `Input` for this to work)



_Code quote:_
```XML
assert!(parse_input(input.to_string()).is_ok());
```
___
*[`crates/committer/src/deserialization/read_test.rs` line 119 at r13](https://reviewable.io/reviews/starkware-libs/committer/27#-NvRhMPk9PyyixPhZv_t:-NvRhMPl5DoUj--mcLbL:b-3ijqn0) ([raw file](https://github.com/starkware-libs/committer/blob/71f3f275dd5cbd0a7d39a108ea76a967c871eed6/crates/committer/src/deserialization/read_test.rs#L119)):*
> ```XML
> 
>     assert!(parse_input(input.to_string())
>         .is_err_and(|err| { matches!(err, DeserializationError::KeyDuplicate(_)) }));
> ```

add `assert_matches` to our cargo toml and use it to check the expected error more explicitly



_Suggestion:_
```XML
    assert_matches!(
        parse_input(input.to_string()),
        Err(DeserializationError::KeyDuplicate(key))
        if key == "[14,6,78,90]"
    );
```
___
*[`crates/committer/src/deserialization/read_test.rs` line 158 at r13](https://reviewable.io/reviews/starkware-libs/committer/27#-NvRkR9L9jx714NvEyge:-NvRkR9L9jx714NvEygf:b67hodh) ([raw file](https://github.com/starkware-libs/committer/blob/71f3f275dd5cbd0a7d39a108ea76a967c871eed6/crates/committer/src/deserialization/read_test.rs#L158)):*
> ```XML
> 
>     assert!(parse_input(input.to_string())
>         .is_err_and(|err| { matches!(err, DeserializationError::KeyDuplicate(_)) }));
> ```

use `assert_matches` (see above)



_Code quote:_
```XML
    assert!(parse_input(input.to_string())
        .is_err_and(|err| { matches!(err, DeserializationError::KeyDuplicate(_)) }));
```
___
*[`crates/committer/src/deserialization/read_test.rs` line 188 at r13](https://reviewable.io/reviews/starkware-libs/committer/27#-NvRkiEj5YT2KcrbTIJt:-NvRkiEj5YT2KcrbTIJu:b67hodh) ([raw file](https://github.com/starkware-libs/committer/blob/71f3f275dd5cbd0a7d39a108ea76a967c871eed6/crates/committer/src/deserialization/read_test.rs#L188)):*
> ```XML
> 
>     assert!(parse_input(input.to_string())
>         .is_err_and(|err| { matches!(err, DeserializationError::ParsingError(_)) }));
> ```

use `assert_matches` (see above)



_Code quote:_
```XML
    assert!(parse_input(input.to_string())
        .is_err_and(|err| { matches!(err, DeserializationError::ParsingError(_)) }));
```


<!-- Sent from Reviewable.io -->

2024-04-17 13:52 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/deserialization/read_test.rs` line 89 at r13](https://reviewable.io/reviews/starkware-libs/committer/27#-NvRjrNJ8-EUXXdsH8G8:-NvgK4cG8p3jPxBJzSMn:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/71f3f275dd5cbd0a7d39a108ea76a967c871eed6/crates/committer/src/deserialization/read_test.rs#L89)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

for a basic test, I would prefer you compare explicitly to an expected deserialized object.
use `pretty_assertions::assert_eq` (may need to add the crate in cargo toml), construct the expected `Input` object explicitly and compare with `assert_eq` (may need to add `derive(Eq, PartialEq)` on `Input` for this to work)
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization/read_test.rs` line 119 at r13](https://reviewable.io/reviews/starkware-libs/committer/27#-NvRhMPk9PyyixPhZv_t:-NvgApxk4n3CaAYE4PD2:bsgmr3u) ([raw file](https://github.com/starkware-libs/committer/blob/71f3f275dd5cbd0a7d39a108ea76a967c871eed6/crates/committer/src/deserialization/read_test.rs#L119)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add `assert_matches` to our cargo toml and use it to check the expected error more explicitly
</blockquote></details>

vscode doesn't like `assert_matches!`
https://github.com/rust-lang/rust/issues/82775
___
*[`crates/committer/src/deserialization/read_test.rs` line 158 at r13](https://reviewable.io/reviews/starkware-libs/committer/27#-NvRkR9L9jx714NvEyge:-NvgBaxRB-SRMD5peXhQ:bsgmr3u) ([raw file](https://github.com/starkware-libs/committer/blob/71f3f275dd5cbd0a7d39a108ea76a967c871eed6/crates/committer/src/deserialization/read_test.rs#L158)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `assert_matches` (see above)
</blockquote></details>

vscode doesn't like `assert_matches!`
https://github.com/rust-lang/rust/issues/82775
___
*[`crates/committer/src/deserialization/read_test.rs` line 188 at r13](https://reviewable.io/reviews/starkware-libs/committer/27#-NvRkiEj5YT2KcrbTIJt:-NvgBbJbAbHi9qcp_7JW:bsgmr3u) ([raw file](https://github.com/starkware-libs/committer/blob/71f3f275dd5cbd0a7d39a108ea76a967c871eed6/crates/committer/src/deserialization/read_test.rs#L188)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `assert_matches` (see above)
</blockquote></details>

vscode doesn't like `assert_matches!`
https://github.com/rust-lang/rust/issues/82775


<!-- Sent from Reviewable.io -->

2024-04-17 15:05 UTC, dorimedini-starkware requested changes
> Reviewed 10 of 10 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 9 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/deserialization/read_test.rs` line 214 at r14](https://reviewable.io/reviews/starkware-libs/committer/27#-Nvg_fb11JriOZuJL93L:-Nvg_fb11JriOZuJL93M:bef1907) ([raw file](https://github.com/starkware-libs/committer/blob/027ba2c81760eb5c272526addd2b54cf4989fbd5/crates/committer/src/deserialization/read_test.rs#L214)):*
> ```XML
> "#;
>     let expected_error = "storage: StorageKey([14, 6, 78, 90])";
>     assert!(parse_input(input.to_string()).is_err_and(|err| {
> ```

use `unwrap_err` as mentioned below
___
*[`crates/committer/src/deserialization/read_test.rs` line 217 at r14](https://reviewable.io/reviews/starkware-libs/committer/27#-NvgS75FBQIxdATweNl9:-NvgS75FBQIxdATweNlA:b-f7gacr) ([raw file](https://github.com/starkware-libs/committer/blob/027ba2c81760eb5c272526addd2b54cf4989fbd5/crates/committer/src/deserialization/read_test.rs#L217)):*
> ```XML
>         matches!(err, DeserializationError::KeyDuplicate(key) if key == expected_error)
>     }));
> }
> ```

use `unwrap_err`



_Suggestion:_
```XML
    assert!(matches!(
        parse_input(input.to_string()).unwrap_err(),
        DeserializationError::KeyDuplicate(key) if key == expected_error
    ));
}
```
___
*[`crates/committer/src/deserialization/read_test.rs` line 255 at r14](https://reviewable.io/reviews/starkware-libs/committer/27#-NvgSje19uq-pzTRZQCM:-NvgSje19uq-pzTRZQCN:b-hedjmu) ([raw file](https://github.com/starkware-libs/committer/blob/027ba2c81760eb5c272526addd2b54cf4989fbd5/crates/committer/src/deserialization/read_test.rs#L255)):*
> ```XML
>     let expected_error = 
>     "address to class hash: ContractAddress(Felt(Felt(FieldElement { value: UnsignedInteger { limbs: [72718179, 18446744073709551615, 6917529027641073992, 16140901064500135204] } })))";
>     assert!(parse_input(input.to_string()).is_err_and(|err| {
> ```

use `unwrap_err` as above
___
*[`crates/committer/src/deserialization/read_test.rs` line 286 at r14](https://reviewable.io/reviews/starkware-libs/committer/27#-NvgSt_PDvyszHNG7MKV:-NvgSt_PDvyszHNG7MKW:b-hedjmu) ([raw file](https://github.com/starkware-libs/committer/blob/027ba2c81760eb5c272526addd2b54cf4989fbd5/crates/committer/src/deserialization/read_test.rs#L286)):*
> ```XML
> "#;
> 
>     assert!(parse_input(input.to_string())
> ```

use `unwrap_err` as above
___
*[`crates/committer/src/deserialization/types.rs` line 18 at r14](https://reviewable.io/reviews/starkware-libs/committer/27#-Nvg_OFB1bxPDDZV3Rym:-Nvg_OFB1bxPDDZV3Ryn:bs0iihz) ([raw file](https://github.com/starkware-libs/committer/blob/027ba2c81760eb5c272526addd2b54cf4989fbd5/crates/committer/src/deserialization/types.rs#L18)):*
> ```XML
> #[allow(dead_code)]
> #[derive(Debug, Eq, PartialEq)]
> pub(crate) struct StarknetStorageValue(pub Felt);
> ```

newlines around structs



_Suggestion:_
```XML
type RawFelt = [u8; 32];

#[derive(Debug, PartialEq, Eq, Hash)]
// TODO(Nimrod, 1/6/2024): Swap to starknet-types-core types once implemented.
pub(crate) struct ContractAddress(pub Felt);

#[derive(Debug, PartialEq, Eq, Hash)]
// TODO(Nimrod, 1/6/2024): Swap to starknet-types-core types once implemented.
pub(crate) struct StarknetStorageKey(pub Felt);

#[allow(dead_code)]
#[derive(Debug, Eq, PartialEq)]
pub(crate) struct StarknetStorageValue(pub Felt);
```
___
*[`crates/committer/src/deserialization/types.rs` line 92 at r14](https://reviewable.io/reviews/starkware-libs/committer/27#-Nvg_abdCkWFE4AFR7Dl:-Nvg_abeErQ_hcFP_b19:b-313957) ([raw file](https://github.com/starkware-libs/committer/blob/027ba2c81760eb5c272526addd2b54cf4989fbd5/crates/committer/src/deserialization/types.rs#L92)):*
> ```XML
> }
> #[allow(dead_code)]
> #[derive(Debug, Eq, PartialEq)]
> ```

newline between structs



_Code quote:_
```XML
}
#[allow(dead_code)]
#[derive(Debug, Eq, PartialEq)]
```


<!-- Sent from Reviewable.io -->

2024-04-18 06:53 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/deserialization/cast.rs` line 7 at r5](https://reviewable.io/reviews/starkware-libs/committer/27#-Nv6aDwH-UN9fdcKPLtm:-NvjvIuS7JEvd9UIbVC1:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/427ca5e047920cbc873faa16e1d2c8beb25b08d1/crates/committer/src/deserialization/cast.rs#L7)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

will do
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization/read_test.rs` line 214 at r14](https://reviewable.io/reviews/starkware-libs/committer/27#-Nvg_fb11JriOZuJL93L:-NvjxFij5w0Buf7QYlBU:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/027ba2c81760eb5c272526addd2b54cf4989fbd5/crates/committer/src/deserialization/read_test.rs#L214)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `unwrap_err` as mentioned below
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization/read_test.rs` line 217 at r14](https://reviewable.io/reviews/starkware-libs/committer/27#-NvgS75FBQIxdATweNl9:-NvjxFK-5AUE9BXXFtNk:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/027ba2c81760eb5c272526addd2b54cf4989fbd5/crates/committer/src/deserialization/read_test.rs#L217)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `unwrap_err`
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization/read_test.rs` line 255 at r14](https://reviewable.io/reviews/starkware-libs/committer/27#-NvgSje19uq-pzTRZQCM:-NvjxGN04wW8llpz6QX7:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/027ba2c81760eb5c272526addd2b54cf4989fbd5/crates/committer/src/deserialization/read_test.rs#L255)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `unwrap_err` as above
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization/read_test.rs` line 286 at r14](https://reviewable.io/reviews/starkware-libs/committer/27#-NvgSt_PDvyszHNG7MKV:-NvjxGccD5R-MTnuiP0R:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/027ba2c81760eb5c272526addd2b54cf4989fbd5/crates/committer/src/deserialization/read_test.rs#L286)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `unwrap_err` as above
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization/types.rs` line 18 at r14](https://reviewable.io/reviews/starkware-libs/committer/27#-Nvg_OFB1bxPDDZV3Rym:-NvjyNk74J1M83GvXhl8:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/027ba2c81760eb5c272526addd2b54cf4989fbd5/crates/committer/src/deserialization/types.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newlines around structs
</blockquote></details>

Done.
___
*[`crates/committer/src/deserialization/types.rs` line 92 at r14](https://reviewable.io/reviews/starkware-libs/committer/27#-Nvg_abdCkWFE4AFR7Dl:-NvjyZey4Z9xe1VNNP74:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/027ba2c81760eb5c272526addd2b54cf4989fbd5/crates/committer/src/deserialization/types.rs#L92)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newline between structs
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-18 07:10 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 6 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 6 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/deserialization/read.rs` line 14 at r15](https://reviewable.io/reviews/starkware-libs/committer/27#-Nvk1P5-3_Q40yd2OeE2:-Nvk1P5-3_Q40yd2OeE3:b-djpccp) ([raw file](https://github.com/starkware-libs/committer/blob/22e5c7df9e40c4f45cc558b6f22a71390826702b/crates/committer/src/deserialization/read.rs#L14)):*
> ```XML
> #[cfg(test)]
> #[path = "read_test.rs"]
> pub mod read_test;
> ```

sorry, missed this...
1. newlines
2. move the test declaration to under the `use`s



_Suggestion:_
```XML
use crate::deserialization::types::RawInput;

use crate::deserialization::errors::DeserializationError;

#[cfg(test)]
#[path = "read_test.rs"]
pub mod read_test;

#[allow(dead_code)]
type DeserializationResult<T> = Result<T, DeserializationError>;

#[allow(dead_code)]
pub(crate) fn parse_input(input: String) -> DeserializationResult<Input> {
    serde_json::from_str::<RawInput>(&input)?.try_into()
}
```
___
*[`crates/committer/src/deserialization/read_test.rs` line 216 at r15](https://reviewable.io/reviews/starkware-libs/committer/27#-Nvk0Gg_60ziVMEaOaDN:-Nvk0Gg_60ziVMEaOaDO:b-g6b8fg) ([raw file](https://github.com/starkware-libs/committer/blob/22e5c7df9e40c4f45cc558b6f22a71390826702b/crates/committer/src/deserialization/read_test.rs#L216)):*
> ```XML
>     assert!(matches!(parse_input(input.to_string()).unwrap_err(),
>     DeserializationError::KeyDuplicate(key) if key == expected_error
>     ));
> ```

no auto-formatting in macros... try like this (non blocking)



_Suggestion:_
```XML
    assert!(matches!(
        parse_input(input.to_string()).unwrap_err(),
        DeserializationError::KeyDuplicate(key) if key == expected_error
    ));
```
___
*[`crates/committer/src/deserialization/read_test.rs` line 255 at r15](https://reviewable.io/reviews/starkware-libs/committer/27#-Nvk0snL7sZTrRt-tFcR:-Nvk0snL7sZTrRt-tFcS:b-i6dwwm) ([raw file](https://github.com/starkware-libs/committer/blob/22e5c7df9e40c4f45cc558b6f22a71390826702b/crates/committer/src/deserialization/read_test.rs#L255)):*
> ```XML
>     let expected_error = 
>     "address to class hash: ContractAddress(Felt(Felt(FieldElement { value: UnsignedInteger { limbs: [72718179, 18446744073709551615, 6917529027641073992, 16140901064500135204] } })))";
>     assert!(matches!(parse_input(input.to_string()).unwrap_err(),
> ```

formatting
___
*[`crates/committer/src/deserialization/read_test.rs` line 286 at r15](https://reviewable.io/reviews/starkware-libs/committer/27#-Nvk0vWo4eXXreU9oP84:-Nvk0vWo4eXXreU9oP85:b-i6dwwm) ([raw file](https://github.com/starkware-libs/committer/blob/22e5c7df9e40c4f45cc558b6f22a71390826702b/crates/committer/src/deserialization/read_test.rs#L286)):*
> ```XML
> "#;
> 
>     assert!(matches!(parse_input(input.to_string()).unwrap_err(),
> ```

formatting


<!-- Sent from Reviewable.io -->

2024-04-18 07:12 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-04-18 07:15 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/deserialization/read.rs` line 14 at r15](https://reviewable.io/reviews/starkware-libs/committer/27#-Nvk1P5-3_Q40yd2OeE2:-Nvk2lStDypij_sZdHjf:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/22e5c7df9e40c4f45cc558b6f22a71390826702b/crates/committer/src/deserialization/read.rs#L14)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

sorry, missed this...
1. newlines
2. move the test declaration to under the `use`s
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-18 07:37 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/27#-:-Nvk8-6-Dd5_gIPt8jmC:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-04-18 09:17 UTC, merged