build: add main algorithm for computing tree hashes
starkware-libs/committer pull request #35
Opened 2024-04-11 08:17 UTC by aner-starkware

Sequential computation, no threading yet.

2024-04-15 07:18 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 10 files at r1, 7 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/35)* status: all files reviewed, 17 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer/src/types.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVYq6ZDMkC3GuV12X_:-NvVYq6ZDMkC3GuV12Xa:bo4skvt) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/types.rs#L41)):*
> ```XML
>     pub const ONE: Felt = Felt(StarknetTypesFelt::ONE);
>     pub const TWO: Felt = Felt(StarknetTypesFelt::TWO);
>     pub const THREE: Felt = Felt(StarknetTypesFelt::THREE);
> ```

rod is making all of these `pub(crate)`, please add the `(crate)` to you declaration



_Code quote:_
```XML
pub const
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVZ2SG4o7fKYr8vl_e:-NvVZ2SG4o7fKYr8vl_f:blvz4hd) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L9)):*
> ```XML
> #[allow(dead_code)]
> #[derive(Clone, Copy)]
> pub(crate) struct Nonce(pub Felt);
> ```

while you're here... add newlines



_Suggestion:_
```XML
use crate::patricia_merkle_tree::types::{EdgeData, LeafDataTrait};
use crate::{hash::types::HashOutput, types::Felt};

// TODO(Nimrod, 1/6/2024): Swap to starknet-types-core types once implemented.
#[allow(dead_code)]
#[derive(Clone, Copy)]
pub(crate) struct ClassHash(pub Felt);

#[allow(dead_code)]
#[derive(Clone, Copy)]
pub(crate) struct Nonce(pub Felt);
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVbZEx8LqvHVg6mxJN:-NvVbZEx8LqvHVg6mxJO:bbxypcz) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L36)):*
> ```XML
> 
> #[allow(dead_code)]
> #[derive(Clone)]
> ```

I think you should be able to remove these clones (see comment below)



_Code quote:_
```XML
#[derive(Clone)]
/// A node in a Patricia-Merkle tree which was modified during an update.
pub(crate) struct FilledNode<L: LeafDataTrait> {
    pub(crate) hash: HashOutput,
    pub(crate) data: NodeData<L>,
}

#[allow(dead_code)]
#[derive(Clone)]
// A Patricia-Merkle tree node's data, i.e., the pre-image of its hash.
pub(crate) enum NodeData<L: LeafDataTrait> {
    Binary(BinaryData),
    Edge(EdgeData),
    Leaf(L),
}

#[allow(dead_code)]
#[derive(Clone)]
pub(crate) struct BinaryData {
    pub(crate) left_hash: HashOutput,
    pub(crate) right_hash: HashOutput,
}

#[allow(dead_code)]
#[derive(Clone)]
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVbghf6eN4wiuoJdbj:-NvVbghf6eN4wiuoJdbk:bllmk4t) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/types.rs#L88)):*
> ```XML
>     pub(crate) bottom_hash: HashOutput,
>     pub(crate) path_to_bottom: PathToBottom,
> }
> ```

not sure about tree height, but you may be able to remove these clones (see comment below)



_Code quote:_
```XML
#[derive(Clone, Copy)]
pub(crate) struct EdgePath(pub Felt);

#[allow(dead_code)]
#[derive(Clone, Copy)]
pub(crate) struct EdgePathLength(pub u8);

#[allow(dead_code)]
pub(crate) struct TreeHeight(pub u8);

#[allow(dead_code)]
#[derive(Clone, Copy)]
pub(crate) struct PathToBottom {
    pub path: EdgePath,
    pub length: EdgePathLength,
}

#[allow(dead_code)]
#[derive(Clone, Copy)]
pub(crate) struct EdgeData {
    pub(crate) bottom_hash: HashOutput,
    pub(crate) path_to_bottom: PathToBottom,
}
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVZb7g2JUAJ7Rt4_Ax:-NvVZb7g2JUAJ7Rt4_Ay:b-4877qa) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L13)):*
> ```XML
> use super::filled_node::{BinaryData, FilledNode, NodeData};
> use super::filled_tree::FilledTreeImpl;
> use super::types::EdgeData;
> ```

don't use `super`, use `crate` (unless you are in a test module importing objects from the tested module)



_Code quote:_
```XML
use super::filled_node::{BinaryData, FilledNode, NodeData};
use super::filled_tree::FilledTreeImpl;
use super::types::EdgeData;
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVZj0d8gAvSkgnOb97:-NvVZj0d8gAvSkgnOb98:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L16)):*
> ```XML
> 
> #[cfg(test)]
> #[path = "./updated_skeleton_tree_test.rs"]
> ```





_Suggestion:_
```XML
#[path = "updated_skeleton_tree_test.rs"]
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVZkgb4kf6KIald_sz:-NvVZkgb4kf6KIald_t-:b-4yr6dt) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L18)):*
> ```XML
> #[path = "./updated_skeleton_tree_test.rs"]
> pub mod updated_skeleton_tree_test;
> /// Consider a Patricia-Merkle Tree which has been updated with new leaves.
> ```

newline



_Suggestion:_
```XML
pub mod updated_skeleton_tree_test;

/// Consider a Patricia-Merkle Tree which has been updated with new leaves.
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvV_A8iDTXK-tLSIrIZ:-NvV_A8iDTXK-tLSIrI_:bxvp5ff) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L74)):*
> ```XML
>                     right_hash,
>                 });
>                 let hash_value = TH::compute_node_hash(data.clone());
> ```

this is why you need to add `Clone`?
I think you should be able to borrow the data in `compute_node_hash`; can you try changing the signature of `compute_node_hash` to accept a reference to node data instead?
and then remove all the `Clone`s in the above `derive`s?



_Code quote:_
```XML
TH::compute_node_hash(data.clone());
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvV_Ya_BFeYmwFAdQg7:-NvV_Ya_BFeYmwFAdQg8:bhnat32) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L91)):*
> ```XML
>                     path_to_bottom: *path_to_bottom,
>                     bottom_hash: bottom_node_hash,
>                 });
> ```

a bit nicer



_Suggestion:_
```XML
                let bottom_hash =
                    self.compute_filled_tree_rec(bottom_node_index, output_map)?;
                let data = NodeData::Edge(EdgeData {
                    path_to_bottom: *path_to_bottom,
                    bottom_hash,
                });
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvV_dxpBu527deZYzRn:-NvV_dxpBu527deZYzRo:b-nfzmsc) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crate [...]

2024-04-15 11:19 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/35)* status: 6 of 12 files reviewed, 17 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/types.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVYq6ZDMkC3GuV12X_:-NvWQN4QB_yLOqimuppe:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/types.rs#L41)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rod is making all of these `pub(crate)`, please add the `(crate)` to you declaration
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVZ2SG4o7fKYr8vl_e:-NvWQeLnCTWaCsQWvbrj:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

while you're here... add newlines
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVbZEx8LqvHVg6mxJN:-NvWToQK0eVc00uVekIE:b-toeoyr) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think you should be able to remove these clones (see comment below)
</blockquote></details>

See my answer below.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVbghf6eN4wiuoJdbj:-NvWTLu6BeXq-WLK08U0:b-29fms3) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/types.rs#L88)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not sure about tree height, but you may be able to remove these clones (see comment below)
</blockquote></details>

It doesn't work smoothly - there are some implicit moves inside the code (the compiler started screaming after I removed all the copy&clones)
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVZb7g2JUAJ7Rt4_Ax:-NvWPoI-CFcuC45-2SD8:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't use `super`, use `crate` (unless you are in a test module importing objects from the tested module)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVZj0d8gAvSkgnOb97:-NvWPrhN14j0IaF5kyrb:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L16)):*
> ```XML
> 
> #[cfg(test)]
> #[path = "./updated_skeleton_tree_test.rs"]
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVZkgb4kf6KIald_sz:-NvWR9ghC7aU7KkHHmoi:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newline
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvV_A8iDTXK-tLSIrIZ:-NvWTbMx9kWO6-tkpAwz:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L74)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is why you need to add `Clone`?
I think you should be able to borrow the data in `compute_node_hash`; can you try changing the signature of `compute_node_hash` to accept a reference to node data instead?
and then remove all the `Clone`s in the above `derive`s?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvV_Ya_BFeYmwFAdQg7:-NvWQDq_CfwmKikLSblR:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L91)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

a bit nicer
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvV_dxpBu527deZYzRn:-NvWRwuSDDno5ayGOZnx:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L104)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

try borrowing (see above)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvV_lJp9YAEFwqbx6fS:-NvWTd9cEUweOIHZd8sO:bm2a9po) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L109)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you need to clone here?
is it because `get_node` borrows the node?
</blockquote></details>

I don't really know, I followed the compiler's suggestion. There might be a better way, but I'm a Rust noob...
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVaLUcCQ1g-xVgZqPO:-NvWNpFl1GPfayQLIO7t:bqn098a) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L16)):*
> ```XML
> 
> #[test]
> fn test_patricia_sanity() {
> ```

Done. But isn't it actually testing the updated_skeleton? (Well, I guess testing the updated_skeleton -> filled_tree transformation)
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVaOsqBmI46HOw97LY:-NvWP4f318eQ_64xis1A:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L37)):*
> ```XML
> 
> #[test]
> fn test_patricia_small() {
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVakLC5NL0MBroOZax:-NvWP5QA96cRhepR-EWQ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></sum [...]

2024-04-15 12:22 UTC, dorimedini-starkware requested changes
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/35)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/committer/35#-NvWgaGj6axk8t96T5_T:-NvWgaGj6axk8t96T5_U:b-snku69) ([raw file](https://github.com/starkware-libs/committer/blob/958ed14bf5201845eb60db9888ceb60ccd7e8a85/crates/committer/src/patricia_merkle_tree/types_test.rs#L63)):*
> ```XML
>     #[case] expected_hash: Felt,
> ) {
>     use crate::patricia_merkle_tree::types::EdgeData;
> ```

move to top of file



_Code quote:_
```XML
use crate::patricia_merkle_tree::types::EdgeData;
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVbOVb4xUWtqatMeEa:-NvWhAy18LRbDYKv54dT:b-e21ac5) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L80)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

newline above comment
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/committer/35#-NvWgvL26yHOo2yaxMzz:-NvWgvL26yHOo2yaxN--:b-vcz9sw) ([raw file](https://github.com/starkware-libs/committer/blob/958ed14bf5201845eb60db9888ceb60ccd7e8a85/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L30)):*
> ```XML
>             _hash_function: PhantomData,
>         },
>     };
> ```

I must have missed this: since when does `UpdatedSkeletonTreeImpl` need a tree hash function as *input*?
I would like it to be a generic type parameter



_Code quote:_
```XML
    let updated_skeleton_tree = UpdatedSkeletonTreeImpl {
        skeleton_tree,
        hash_function: PedersenHashFunction,
        tree_hash_function: TreeHashFunctionImpl {
            _hash_function: PhantomData,
        },
    };
```


<!-- Sent from Reviewable.io -->

2024-04-15 12:33 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/35)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/committer/35#-NvWjs-_ApbPCyzsG3Ql:-NvWjs-_ApbPCyzsG3Qm:b-rtagwg) ([raw file](https://github.com/starkware-libs/committer/blob/75474afd3039b15cc408f308e0e980b3e73b91f6/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L92)):*
> ```XML
>     // tree_hash_function: TreeHashFunctionImpl {
>     //     _hash_function: PhantomData,
>     // },
> ```

delete


<!-- Sent from Reviewable.io -->

2024-04-15 12:35 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/35)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-04-15 12:35 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/35)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/committer/35#-NvWgaGj6axk8t96T5_T:-NvWjTIH3lw6br9ccuk7:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/958ed14bf5201845eb60db9888ceb60ccd7e8a85/crates/committer/src/patricia_merkle_tree/types_test.rs#L63)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move to top of file
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVbOVb4xUWtqatMeEa:-NvWjPNNAxvWDL7ZLvCM:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L80)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newline above comment
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/committer/35#-NvWgvL26yHOo2yaxMzz:-NvWjm0w95BdHok2PEVr:bho4sxn) ([raw file](https://github.com/starkware-libs/committer/blob/958ed14bf5201845eb60db9888ceb60ccd7e8a85/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L30)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I must have missed this: since when does `UpdatedSkeletonTreeImpl` need a tree hash function as *input*?
I would like it to be a generic type parameter
</blockquote></details>

I think it was because of the generics of the trait, now that they're gone, it seems this has also disappeared.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/committer/35#-NvWjs-_ApbPCyzsG3Ql:-NvWkD2A6ufKHZYsr2Bd:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/75474afd3039b15cc408f308e0e980b3e73b91f6/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L92)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-16 10:59 UTC, aner-starkware commented
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVax6Y9erR8Y3dZ7J1:-NvaYqHAAjLWdBMOPMxa:b2v3jmq) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L40)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

OK. I drew it on the wall in the office, so hopefully I'll be in the office tomorrow and can copy it
</blockquote></details>

How is this drawing?


<!-- Sent from Reviewable.io -->

2024-04-16 11:16 UTC, dorimedini-starkware requested changes
> Reviewed 8 of 8 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/35)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree.rs` line 36 at r7](https://reviewable.io/reviews/starkware-libs/committer/35#-NvabHs55Kfa_K4po8U6:-NvabHs55Kfa_K4po8U7:b-heiepi) ([raw file](https://github.com/starkware-libs/committer/blob/1dc31179b692291c7825c68a312cb121501ea1be/crates/committer/src/patricia_merkle_tree/filled_tree.rs#L36)):*
> ```XML
> 
> impl<L: LeafDataTrait> FilledTree<L> for FilledTreeImpl<L> {
>     fn serialize(&self, _storage: impl Storage) -> Result<HashSet<&[u8]>, FilledTreeError> {
> ```

why do you need the storage as input?
or do you mean `write_to_storage` instead of serialize?
I don't see why you want both storage as input *and* return a hashset



_Code quote:_
```XML
fn serialize(&self, _storage: impl Storage)
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 17 at r7](https://reviewable.io/reviews/starkware-libs/committer/35#-NvabXMLBMT-x8uuZClQ:-NvabXMLBMT-x8uuZClR:b-2i29aa) ([raw file](https://github.com/starkware-libs/committer/blob/1dc31179b692291c7825c68a312cb121501ea1be/crates/committer/src/patricia_merkle_tree/types.rs#L17)):*
> ```XML
> 
> pub(crate) struct TreeHashFunctionImpl<H: HashFunction> {
>     pub(crate) _hash_function: PhantomData<H>,
> ```

why must this be public, actually...?



_Code quote:_
```XML
pub(crate)
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/committer/35#-NvVax6Y9erR8Y3dZ7J1:-NvabpFh9R2cZ-I0fAg5:b-7m74ox) ([raw file](https://github.com/starkware-libs/committer/blob/edcc9f67c10d46675cc5bd6c974319b192922c2b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L40)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

How is this drawing?
</blockquote></details>

nice!
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 97 at r7](https://reviewable.io/reviews/starkware-libs/committer/35#-NvaVhQu-hqba4cXvvbI:-NvaVhQu-hqba4cXvvbJ:b7ksg61) ([raw file](https://github.com/starkware-libs/committer/blob/1dc31179b692291c7825c68a312cb121501ea1be/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L97)):*
> ```XML
>         .unwrap()
>         .get_root_hash()
>         .unwrap();
> ```

good to test the expected structure, not just the root (sanity on correct node indices, types etc).
you may want to add a utility function that converts `HashMap<K, Mutex<V>>` to `HashMap<K, V>`.
sorry I missed this before...



_Suggestion:_
```XML
    let filled_tree = updated_skeleton_tree
        .compute_filled_tree::<PedersenHashFunction, TreeHashFunctionImpl<PedersenHashFunction>>()
        .unwrap();
    
    let expected_map = HashMap::from([
        // Write up explicit expecte node index -> value map
    ]);
    assert_eq!(filled_tree.tree_map, expected_map);
    
    let root_hash = filled_tree.get_root_hash().unwrap();
```


<!-- Sent from Reviewable.io -->

2024-04-16 11:29 UTC, aner-starkware commented
*[`crates/committer/src/patricia_merkle_tree/filled_tree.rs` line 36 at r7](https://reviewable.io/reviews/starkware-libs/committer/35#-NvabHs55Kfa_K4po8U6:-NvaejKG6UStd1Ex-gR2:b3l0h0i) ([raw file](https://github.com/starkware-libs/committer/blob/1dc31179b692291c7825c68a312cb121501ea1be/crates/committer/src/patricia_merkle_tree/filled_tree.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you need the storage as input?
or do you mean `write_to_storage` instead of serialize?
I don't see why you want both storage as input *and* return a hashset
</blockquote></details>

It's not part of my PR, I just added a dummy implementation to make it compile


<!-- Sent from Reviewable.io -->

2024-04-16 11:36 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/35)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 17 at r7](https://reviewable.io/reviews/starkware-libs/committer/35#-NvabXMLBMT-x8uuZClQ:-NvagJu70Fvg7FTadW9Z:b-ctdt6g) ([raw file](https://github.com/starkware-libs/committer/blob/1dc31179b692291c7825c68a312cb121501ea1be/crates/committer/src/patricia_merkle_tree/types.rs#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why must this be public, actually...?
</blockquote></details>

Seems like it doesn't have to be.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 97 at r7](https://reviewable.io/reviews/starkware-libs/committer/35#-NvaVhQu-hqba4cXvvbI:-NvafYRL682_zcFJzlbY:bur2dv4) ([raw file](https://github.com/starkware-libs/committer/blob/1dc31179b692291c7825c68a312cb121501ea1be/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L97)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

good to test the expected structure, not just the root (sanity on correct node indices, types etc).
you may want to add a utility function that converts `HashMap<K, Mutex<V>>` to `HashMap<K, V>`.
sorry I missed this before...
</blockquote></details>

The Python test doesn't publicly compute these values. Of course, I could compute them myself—is this what you mean? 


<!-- Sent from Reviewable.io -->

2024-04-16 11:46 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/35)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 97 at r7](https://reviewable.io/reviews/starkware-libs/committer/35#-NvaVhQu-hqba4cXvvbI:-NvaiUG9BHkeC4lVzzqy:bw3ipew) ([raw file](https://github.com/starkware-libs/committer/blob/1dc31179b692291c7825c68a312cb121501ea1be/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L97)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

The Python test doesn't publicly compute these values. Of course, I could compute them myself—is this what you mean?
</blockquote></details>

yes... it's not a huge tree, right?
important IMO to make sure the metadata you output is correct so we are covered as we develop the main algorithm


<!-- Sent from Reviewable.io -->

2024-04-16 14:21 UTC, aner-starkware commented
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 97 at r7](https://reviewable.io/reviews/starkware-libs/committer/35#-NvaVhQu-hqba4cXvvbI:-NvbGcyz1FmlT1vjBIlA:b-4zlxos) ([raw file](https://github.com/starkware-libs/committer/blob/1dc31179b692291c7825c68a312cb121501ea1be/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L97)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes... it's not a huge tree, right?
important IMO to make sure the metadata you output is correct so we are covered as we develop the main algorithm
</blockquote></details>

Yeah, quite small, only ~150 lines description for the hashmap :flushed: :face_with_spiral_eyes: 


<!-- Sent from Reviewable.io -->

2024-04-16 14:26 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/35)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 97 at r7](https://reviewable.io/reviews/starkware-libs/committer/35#-NvaVhQu-hqba4cXvvbI:-NvbIByC9wEBhYDxnlwU:bmj0btk) ([raw file](https://github.com/starkware-libs/committer/blob/1dc31179b692291c7825c68a312cb121501ea1be/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L97)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Yeah, quite small, only ~150 lines description for the hashmap :flushed: :face_with_spiral_eyes:
</blockquote></details>

nice!
(see below how to reduce the number of lines :) )
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 119 at r10](https://reviewable.io/reviews/starkware-libs/committer/35#-NvbHoz40DpHzUmUiFQP:-NvbHoz40DpHzUmUiFQQ:b-30vdg4) ([raw file](https://github.com/starkware-libs/committer/blob/24f8ca918ef9146b14f81b7cd9a90d0bce05b4dd/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L119)):*
> ```XML
>         Felt::from_hex("0xe8899e8c731a35f5e9ce4c4bc32aabadcc81c5cdcc1aeba74fa7509046c338").unwrap(),
>     );
>     let expected_filled_tree_map = HashMap::from([
> ```

it will help to read this if you write utility functions `create_X_entry(...) -> (NodeIndex, FilledNode)` for `X` in `[edge, binary, leaf]`... will reduce a lot of boilerplate. the inputs to these functions should be `uint` types for everything except hash outputs, which can be `&str`s
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 275 at r10](https://reviewable.io/reviews/starkware-libs/committer/35#-NvbH_LR08IrsfYn1a0-:-NvbH_LR08IrsfYn1a00:b-mxygc) ([raw file](https://github.com/starkware-libs/committer/blob/24f8ca918ef9146b14f81b7cd9a90d0bce05b4dd/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L275)):*
> ```XML
> fn remove_mutex(
>     hash_map_in: &HashMap<NodeIndex, Mutex<FilledNode<LeafData>>>,
> ) -> HashMap<NodeIndex, FilledNode<LeafData>> {
> ```

can you get this to work? non-blocking, just no need to be specific... will be easier to swap types later without breaking tests



_Suggestion:_
```XML
fn remove_mutex<K, V>(
    hash_map_in: &HashMap<K, Mutex<V>>,
) -> HashMap<K, V> {
```


<!-- Sent from Reviewable.io -->

2024-04-16 14:48 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/35)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree.rs` line 41 at r11](https://reviewable.io/reviews/starkware-libs/committer/35#-NvbNAm89YGhcuj_vpF7:-NvbNAm89YGhcuj_vpF8:b-f1nywd) ([raw file](https://github.com/starkware-libs/committer/blob/0192c506e6b0b2eecd0cb6b4530d2df910b171e8/crates/committer/src/patricia_merkle_tree/filled_tree.rs#L41)):*
> ```XML
>         _storage: &mut impl Storage,
>     ) -> std::result::Result<
>         std::collections::HashSet<storage::storage_trait::StorageKey>,
> ```

why full import paths...? 
add `use`s for HashSet and StorageKey, and I think `Result` doesn't need to be explicitly `use`d, does it? 



_Code quote:_
```XML
    ) -> std::result::Result<
        std::collections::HashSet<storage::storage_trait::StorageKey>,
```


<!-- Sent from Reviewable.io -->

2024-04-17 08:11 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/35)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree.rs` line 41 at r11](https://reviewable.io/reviews/starkware-libs/committer/35#-NvbNAm89YGhcuj_vpF7:-NvexSPx3UFRSg4UBvG3:b-687sdv) ([raw file](https://github.com/starkware-libs/committer/blob/0192c506e6b0b2eecd0cb6b4530d2df910b171e8/crates/committer/src/patricia_merkle_tree/filled_tree.rs#L41)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why full import paths...? 
add `use`s for HashSet and StorageKey, and I think `Result` doesn't need to be explicitly `use`d, does it?
</blockquote></details>

Done. Sorry, it isn't part of the PR, so I just let the compiler fix it and didn't check :grimacing: 
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 119 at r10](https://reviewable.io/reviews/starkware-libs/committer/35#-NvbHoz40DpHzUmUiFQP:-Nvf61utDEPpPZI7HG40:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/24f8ca918ef9146b14f81b7cd9a90d0bce05b4dd/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L119)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it will help to read this if you write utility functions `create_X_entry(...) -> (NodeIndex, FilledNode)` for `X` in `[edge, binary, leaf]`... will reduce a lot of boilerplate. the inputs to these functions should be `uint` types for everything except hash outputs, which can be `&str`s
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 275 at r10](https://reviewable.io/reviews/starkware-libs/committer/35#-NvbH_LR08IrsfYn1a0-:-NvbK4US8zD8oQtmLns_:b-bxdq99) ([raw file](https://github.com/starkware-libs/committer/blob/24f8ca918ef9146b14f81b7cd9a90d0bce05b4dd/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L275)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you get this to work? non-blocking, just no need to be specific... will be easier to swap types later without breaking tests
</blockquote></details>

Soft pass. I'll write it once we need it :)


<!-- Sent from Reviewable.io -->

2024-04-17 08:17 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/35#-:-Nvf7LGp6NOAHDzpVC5Q:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware, @AvivYossef-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-04-17 08:18 UTC, merged