chore: building original skeleton
starkware-libs/committer pull request #39
Opened 2024-04-15 13:40 UTC by nimrod-starkware

implementing rust equivalent to 'fetch_nodes` in the python repository.
wrote a few tests as well

2024-04-15 14:58 UTC, dorimedini-starkware requested changes
> Reviewed 12 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 12 of 14 files reviewed, 36 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX5GQ505tSQyKYvrbI:-NvX5GQ505tSQyKYvrbJ:bkh3sa5) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/Cargo.toml#L21)):*
> ```TOML
> rstest = "0.17.0"
> starknet-types-core = { version = "0.0.11", features = ["hash"] }
> bisection = "0.1.0"
> ```

alphabetize dependencies



_Suggestion:_
```TOML
[workspace.dependencies]
bisection = "0.1.0"
clap = { version = "4.5.4", features = ["cargo", "derive"] }
derive_more = "0.99.17"
pretty_assertions = "1.2.1"
rstest = "0.17.0"
starknet-types-core = { version = "0.0.11", features = ["hash"] }
```
___
*[`crates/committer/Cargo.toml` line 19 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX5J8hCBsD4jcX_frl:-NvX5J8hCBsD4jcX_frm:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/Cargo.toml#L19)):*
> ```TOML
> derive_more.workspace = true
> starknet-types-core.workspace = true
> bisection.workspace = true
> ```





_Suggestion:_
```TOML
[dependencies]
bisection.workspace = true
derive_more.workspace = true
starknet-types-core.workspace = true
```
___
*[`crates/committer/src/types.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX5Rmz3Qa1znNOmIZ7:-NvX5Rmz3Qa1znNOmIZ8:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L15)):*
> ```XML
>     Ord,
>     derive_more::Sub,
> )]
> ```





_Suggestion:_
```XML
#[derive(
    Eq,
    PartialEq,
    Clone,
    Copy,
    Debug,
    Default,
    Hash,
    derive_more::Add,
    derive_more::Sub,
    PartialOrd,
    Ord,
)]
```
___
*[`crates/committer/src/types.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX5nsS42q19CLiWO7C:-NvX5nsS42q19CLiWO7D:b5wdqxp) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L65)):*
> ```XML
>     }
> 
>     pub fn shift_left(&self, steps: u8) -> Self {
> ```

depending on use case, this can be misleading.
what should `(PRIME-1).shift_left(1)` return? i.e. what about overflow?



_Code quote:_
```XML
pub fn shift_left(&self, steps: u8) -> Self {
```
___
*[`crates/committer/src/types.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX5ebHDYq36JAFpkr9:-NvX5ebHDYq36JAFpkrA:b-hq2zjp) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L66)):*
> ```XML
> 
>     pub fn shift_left(&self, steps: u8) -> Self {
>         *self * Felt::TWO.pow(steps)
> ```

is there no built-in method of StarknetTypesFelt that does this?



_Code quote:_
```XML
*self * Felt::TWO.pow(steps)
```
___
*[`crates/committer/src/types.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX6Pp2-qx0NQsnBDxW:-NvX6Pp2-qx0NQsnBDxX:b-dzyz3a) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L70)):*
> ```XML
>     pub fn from_bytes_be_slice(bytes: &[u8]) -> Self {
>         Self(StarknetTypesFelt::from_bytes_be_slice(bytes))
>     }
> ```

while you're here, these should be `pub(crate)` unless we explicitly decide to include these functions as part of public API



_Suggestion:_
```XML
    pub(crate) const ZERO: Felt = Felt(StarknetTypesFelt::ZERO);
    pub(crate) const ONE: Felt = Felt(StarknetTypesFelt::ONE);
    pub(crate) const TWO: Felt = Felt(StarknetTypesFelt::TWO);

    /// Raises `self` to the power of `exponent`.
    pub(crate) fn pow(&self, exponent: impl Into<u128>) -> Self {
        Self(self.0.pow(exponent.into()))
    }
    pub(crate) fn bits(&self) -> u8 {
        self.0
            .bits()
            .try_into()
            .expect("Should not fail as it takes less than 252 bits to represent a felt.")
    }

    pub(crate) fn shift_left(&self, steps: u8) -> Self {
        *self * Felt::TWO.pow(steps)
    }
    pub(crate) fn from_bytes_be_slice(bytes: &[u8]) -> Self {
        Self(StarknetTypesFelt::from_bytes_be_slice(bytes))
    }
```
___
*[`crates/committer/src/types.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX5WVyEfq3rmrzhhuu:-NvX5WVyEfq3rmrzhhuv:bkv1djb) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L73)):*
> ```XML
>     pub(crate) fn to_bytes_be(self) -> [u8; 32] {
>         self.0.to_bytes_be()
>     }
> ```

newlines between functions



_Suggestion:_
```XML
    }

    pub fn bits(&self) -> u8 {
        self.0
            .bits()
            .try_into()
            .expect("Should not fail as it takes less than 252 bits to represent a felt.")
    }

    pub fn shift_left(&self, steps: u8) -> Self {
        *self * Felt::TWO.pow(steps)
    }

    pub fn from_bytes_be_slice(bytes: &[u8]) -> Self {
        Self(StarknetTypesFelt::from_bytes_be_slice(bytes))
    }

    pub(crate) fn to_bytes_be(self) -> [u8; 32] {
        self.0.to_bytes_be()
    }
```
___
*[`crates/committer/src/types.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX6_XP5JdjeSorapz8:-NvX6_XP5JdjeSorapz9:b-jg4wfn) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L78)):*
> ```XML
>     pub fn from_hex(hex_string: &str) -> Result<Self, FromStrError> {
>         Ok(StarknetTypesFelt::from_hex(hex_string)?.into())
>     }
> ```

while you're here...



_Suggestion:_
```XML
    pub(crate) fn from_hex(hex_string: &str) -> Result<Self, FromStrError> {
        Ok(StarknetTypesFelt::from_hex(hex_string)?.into())
    }
```
___
*[`crates/committer/src/hash/types.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX6feYAf0FtvoG2GQ3:-NvX6feYAf0FtvoG2GQ4:b-c8h50q) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/hash/types.rs#L9)):*
> ```XML
> 
> #[allow(dead_code)]
> #[derive(Debug, PartialEq, Eq, Clone, Copy, Hash)]
> ```

we will try to keep these ordered alphabetically, unless context requires otherwise (`Eq` next to `PartialEq`)



_Suggestion:_
```XML
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
```
___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX6p0g4Larqhhzhbb-:-NvX6p0g4Larqhhzhbb0:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/errors.rs#L5)):*
> ```XML
> #[allow(dead_code)]
> pub(crate) enum OriginalSkeletonTreeError {
>     Deserializtion(String),
> ```





_Suggestion:_
```XML
Deserialization
```
___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX8N8Y8SBQc1qtznqo:-NvX8N8Y8SBQc1qtznqp:b-2hxu0t) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/errors.rs#L6)):*
> ```XML
> pub(crate) enum OriginalSkeletonTreeError {
>     Deserializtion(String),
>     StorageRead,
> ```

we have a StorageError type, please use it



_Suggestion:_
```XML
StorageRead(#[from] StorageError)
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX6rXcDnnPV90rJ3bL:-NvX6rXcDnnPV90rJ3bM:b-w7i1le) ([raw file](https:// [...]

2024-04-15 15:15 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 13 of 14 files reviewed, 46 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXGiwk0CrKobfbx7NX:-NvXGiwk0CrKobfbx7NY:b-454c0m) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L39)):*
> ```XML
>                        17  13     \
>                        / \   \     \
>                           9  11    15
> ```

this is more precise, right?
1. Binary non-sibling nodes have no data
2. Edge nodes have data (path data) but it is described in the ASCII art
3. Leaves that don't change are siblings (have a "hash" value used to update the skeleton), `9` in this example
4. Updated leaves are either zero or nonzero



_Suggestion:_
```XML
                             B
                           /   \
                          B     E
                         / \     \
                        B   E     \
                       / \   \     \
                      NZ  9   NZ    NZ
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXGCTVD3iN26-_4loE:-NvXGCTVD3iN26-_4loF:b-fll98b) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L41)):*
> ```XML
>                           9  11    15
> 
> */
> ```

triple slash it (use alt+shift+mouse click in VSCode to edit multiple lines at once :) )



_Suggestion:_
```XML
/// This test assumes for simplicity that hash is addition (i.e hash(a,b) = a + b).
///
///                   Old tree structure:
///
///                             50
///                           /   \
///                         30     20
///                        /  \     \
///                       17  13     \
///                      /  \   \     \
///                     8    9  11     15
///
///                   Modified leaves indices: [8, 10, 13]
///
///                   Expected skeleton:
///
///                             50
///                           /   \
///                         30     20
///                        /  \     \
///                       17  13     \
///                       / \   \     \
///                          9  11    15
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXHuwH9t71-cE7zYU5:-NvXHuwH9t71-cE7zYU6:bsnxobo) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L55)):*
> ```XML
>     StorageValue((create_32_bytes_entry(8).into_iter().chain(create_32_bytes_entry(9).into_iter())).collect())),
>     (StorageKey(create_32_bytes_entry(11 + 1 + 1)).with_patricia_prefix(),
>     StorageValue(create_32_bytes_entry(11).into_iter().chain(create_32_bytes_entry(1).into_iter()).chain([1].into_iter()).collect())),
> ```

To reduce boilerplate and make this easier to read: in addition to `create_32_bytes_entry` define a
```
create_patricia_entry(key: u8, value: [u8]) -> (StorageKey, StorageValue)
```
... and use it everywhere



_Suggestion:_
```XML
    create_patricia_entry(11 + 1 + 1, [11, 1, 1]),
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXIf4L7t-oHRjw9Ige:-NvXIf4L7t-oHRjw9Igf:b-idntlv) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L68)):*
> ```XML
>         (NodeIndex::from(13), LeafData::StorageValue(Felt::from(2_u128))),
>     ]
>     ),
> ```

implement `node_data_map(data: [(u8, u8)]) -> HashMap<NodeIndex, LeafData>` and use it every case



_Suggestion:_
```XML
    node_data_map([(8, 4), (10, 3), (13, 2)]),
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXJ2U8D9gopt66uByl:-NvXJ2U8D9gopt66uBym:b-p119xk) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L83)):*
> ```XML
>         (NodeIndex::from(15), OriginalSkeletonNode::LeafOrBinarySibling(HashOutput(Felt::from(15_u128)))),
>         (NodeIndex::from(11), OriginalSkeletonNode::LeafOrBinarySibling(HashOutput(Felt::from(11_u128)))),
>     ]),
> ```

I can't think of a way to reduce this boilerplate :(
also, auto-formatters don't really work in macros - and `#[cases]` is a macro... here is a suggestion



_Suggestion:_
```XML
    HashMap::from([
        (NodeIndex::from(1), OriginalSkeletonNode::Binary),
        (NodeIndex::from(2), OriginalSkeletonNode::Binary),
        (NodeIndex::from(3), OriginalSkeletonNode::Edge {
            path_to_bottom: PathToBottom { path: EdgePath(Felt::from(3_u128)), length: EdgePathLength(2) }
        }),
        (NodeIndex::from(4), OriginalSkeletonNode::Binary),
        (NodeIndex::from(5), OriginalSkeletonNode::Edge {
            path_to_bottom: PathToBottom { path: EdgePath(Felt::from(1_u128)), length: EdgePathLength(1) }
        }),
        (NodeIndex::from(9), OriginalSkeletonNode::LeafOrBinarySibling(HashOutput(Felt::from(9_u128)))),
        (NodeIndex::from(15), OriginalSkeletonNode::LeafOrBinarySibling(HashOutput(Felt::from(15_u128)))),
        (NodeIndex::from(11), OriginalSkeletonNode::LeafOrBinarySibling(HashOutput(Felt::from(11_u128)))),
    ]),
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXJkUi7UG3G8dKQ4wR:-NvXJkUi7UG3G8dKQ4wS:b-g89u20) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L86)):*
> ```XML
>     TreeHeight(3)
> )]
> /*                 Old tree structure:
> ```

triple-slash it



_Code quote:_
```XML
/* 
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXJYTn0PJE2Rm-tr1B:-NvXJYTn0PJE2Rm-tr1C:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L106)):*
> ```XML
>                        12      5     11
>                       /  \      \
>                           2
> ```





_Suggestion:_
```XML
                             B
                           /    \
                         E       B
                        /      /    \
                       B       E     E
                      /  \      \     \
                     NZ   2      NZ    NZ
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXJoLRDpy3gpPcHF1n:-NvXJoLRDpy3gpPcHF1o:b-s3uj4b) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L175)):*
> ```XML
>                      24         \   6   59
>                                  \  /     \
>                                  20 5     40
> ```

fix to skeleton format



_Code quote:_
```XML
                             116 [...]

2024-04-16 12:04 UTC, TzahiTaub requested changes
> Reviewed 4 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 13 of 14 files reviewed, 48 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/types.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvalEmQAPQnxAz3jHHM:-NvalEmQAPQnxAz3jHHN:b5i97xg) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L62)):*
> ```XML
>             .bits()
>             .try_into()
>             .expect("Should not fail as it takes less than 252 bits to represent a felt.")
> ```

This looks like a comment msg. An error message should be clear without context - "Unexpected failure extracting bits from Felt" or something.



_Code quote:_
```XML
"Should not fail as it takes less than 252 bits to represent a felt.
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvamhsU10cvmSxK4-_Q:-NvamhsU10cvmSxK4-_R:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/filled_node.rs#L33)):*
> ```XML
> 
> #[allow(dead_code)]
> #[derive(Debug, PartialEq, Eq)]
> ```





_Suggestion:_
```XML
Debug, Eq, PartialEq
```


<!-- Sent from Reviewable.io -->

2024-04-16 13:14 UTC, amosStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 13 of 14 files reviewed, 51 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvarLf9DYqO_aNsbtCt:-NvarLfA4cockbBYf54n:blzcdtm) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree.rs#L4)):*
> ```XML
> pub mod filled_node;
> pub mod filled_tree;
> pub mod original_skeleton_calc;
> ```

why not do this in `original_skeleton_tree.rs`? @dorimedini-starkware WYT?



_Code quote:_
```XML
pub mod original_skeleton_calc;
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX79WD9aKRTmJRr45o:-NvasN8x3ECp_7aOzkdS:b-g7gly8) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

question (I don't know the answer): why should `SkeletonTree` not own the leaf modifications?
</blockquote></details>

IMO it shouldn't have this field - the modifications are passed as a param to `compute_updated_skeleton_tree()`
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvb13rp4agl5PG-ZzU2:-Nvb13rp4agl5PG-ZzU3:b-6o41q4) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L24)):*
> ```XML
> #[allow(dead_code)]
> impl SkeletonTree<'_> {
>     fn fetch_nodes(
> ```

this is the same as `fetch_nodes()` in Python, right?
did that implementation look good to you?
(maybe it's possible to come up with a better one)



_Code quote:_
```XML
fn fetch_nodes(
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX8p71DcTTwJufLiVJ:-Nvb0Z636ItMJSMRUmFI:bmobxke) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_tree.rs#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this needs to be renamed if it's no longer a collection of indices
</blockquote></details>

these aren't the modified leaves - these are the indices of the leaves in the original tree. @nimrod-starkware can you explain why this change is needed?
___
*[`crates/committer/src/storage/storage_trait.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvb-fnm876G3Fs8GiFR:-Nvb-fnm876G3Fs8GiFS:b-nbb7vm) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/storage/storage_trait.rs#L42)):*
> ```XML
>                 "Could not deserailize a binary node when building the original skeleton tree."
>                     .to_string(),
>             ));
> ```

This is probably not relevant anymore, but IMO it would be better to have two separate error variants, instead of one with a configurable error message.



_Code quote:_
```XML
            return Err(OriginalSkeletonTreeError::Deserializtion(
                "Could not deserailize a binary node when building the original skeleton tree."
                    .to_string(),
            ));
```


<!-- Sent from Reviewable.io -->

2024-04-16 13:27 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 3 of 14 files reviewed, 51 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX5GQ505tSQyKYvrbI:-Nv_aAISBmijXMU1Ztwg:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/Cargo.toml#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

alphabetize dependencies
</blockquote></details>

Done.
___
*[`crates/committer/Cargo.toml` line 19 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX5J8hCBsD4jcX_frl:-Nv_aFR-5orPIXkpADWA:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/Cargo.toml#L19)):*
> ```TOML
> derive_more.workspace = true
> starknet-types-core.workspace = true
> bisection.workspace = true
> ```

Done.
___
*[`crates/committer/src/types.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX5Rmz3Qa1znNOmIZ7:-Nv_aIHn978y3UUHp0-1:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L15)):*
> ```XML
>     Ord,
>     derive_more::Sub,
> )]
> ```

Done.
___
*[`crates/committer/src/types.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX5nsS42q19CLiWO7C:-Nv_dWQmE2XWv7Cm5418:bk4krcc) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L65)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

depending on use case, this can be misleading.
what should `(PRIME-1).shift_left(1)` return? i.e. what about overflow?
</blockquote></details>

I agree it may be misleading. maybe a better name is `times_two_to_the_power(&self, power: u8)`.
I am pretty sure that in case of overflow, it returns the result % PRIME (like we expect). However, I'm wondering how efficient it is.
___
*[`crates/committer/src/types.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX5ebHDYq36JAFpkr9:-Nv_fRqy9U8nXd-sNriq:b-9p3ds0) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L66)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is there no built-in method of StarknetTypesFelt that does this?
</blockquote></details>

couldn't find one..
___
*[`crates/committer/src/types.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX6Pp2-qx0NQsnBDxW:-Nv_artu-9Z79EN2WMij:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L70)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

while you're here, these should be `pub(crate)` unless we explicitly decide to include these functions as part of public API
</blockquote></details>

Done.
___
*[`crates/committer/src/types.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX5WVyEfq3rmrzhhuu:-Nv_fpA0--VCzOEK3MQO:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L73)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newlines between functions
</blockquote></details>

Done.
___
*[`crates/committer/src/types.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX6_XP5JdjeSorapz8:-Nv_fpNc8-9hSPFWAxon:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L78)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

while you're here...
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX6p0g4Larqhhzhbb-:-Nv_g28ZA7H7J7m0R9fz:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/errors.rs#L5)):*
> ```XML
> #[allow(dead_code)]
> pub(crate) enum OriginalSkeletonTreeError {
>     Deserializtion(String),
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX8N8Y8SBQc1qtznqo:-Nv_mfRWDHH8rk9nVCD8:b-d7bhn0) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/errors.rs#L6)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we have a StorageError type, please use it
</blockquote></details>

will do
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX6rXcDnnPV90rJ3bL:-Nv_ggC--MfP0q6a-HMw:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/filled_node.rs#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I wonder why rustfmt doesn't handle this...
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX70RU0_8b7e5GP3PE:-Nv_goAr2zTJdOO_QYSf:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L14)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do not use `super::`, use `crate::`, unless in a test module `X_test.rs` and you are importing from `X.rs`
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX7Q_d5F6EqdoVSW8L:-Nv_kC2I-8e853yYkt3r:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. consistency (we have other `Impl` structs IIRC)
2. Without the word "original", there is ambiguity (this struct represents the skeleton tree before or after update?)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX79WD9aKRTmJRr45o:-Nv_i-Xr4U0Zsl88E5er:bcmtmf3) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

question (I don't know the answer): why should `SkeletonTree` not own the leaf modifications?
</blockquote></details>

I think it actually can. changed it to have ownership of it.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX6y1rBJnUQEKT-f7h:-Nv_kBNV-wLBMwaA3wqT:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L22)):*
> ```XML
>     tree_height: TreeHeight,
> }
> #[allow(dead_code)]
> ```

Done.
___
*[`crates/committer/src/ [...]

2024-04-16 14:08 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 3 of 14 files reviewed, 50 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX79WD9aKRTmJRr45o:-NvbEELZE6wfguNID9ZQ:bhjqkge) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L21)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I think it actually can. changed it to have ownership of it.
</blockquote></details>

Why is it needed?


<!-- Sent from Reviewable.io -->

2024-04-16 14:10 UTC, TzahiTaub requested changes
> Reviewed 6 of 14 files at r1, 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 4 of 14 files reviewed, 53 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX6y1rBJnUQEKT-f7h:-Nvb8ABx4pMz6XcNKljc:bb710yj) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L22)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvb8VsG5UBXVgYE2iey:-Nvb8VsG5UBXVgYE2iez:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L33)):*
> ```XML
>     /// Function's purpose is to fetch from storage the patricia witnesses in order to build the
>     /// original skeleton tree. Given a list of subtrees, traverses towards their leaves and
>     /// fetches all non-empty and sibiling nodes. Assumes no subtrees of height 0 (leaves).
> ```





_Suggestion:_
```XML
    /// Fetches the Patricia witnesses, required to build the original skeleton tree from storage. 
    /// Given a list of subtrees, traverses towards their leaves and
    /// fetches all non-empty and sibling nodes. Assumes no subtrees of height 0 (leaves).
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXGCTVD3iN26-_4loE:-NvbCko96evQI6T8_sEc:b-duwv0m) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L41)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not sure I follow. Should this also follow the `H(node)=h(value, path) + length` for edge nodes? Shouldn't the 20 (right son of the root) here be `h(15, 0b111) + 3=15+7+3=25`? Be happy for the numbers calculation explanation as I don't think it's very straightforward (like the value of leaves is their index, for binary nodes h(left, right) is the sum of their descendants, and for edge nodes h(value, path) + length = value+path+length
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_node.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvan2mW-oJyqVWg-3CY:-Nvan2mW-oJyqVWg-3CZ:b-832zef) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_node.rs#L5)):*
> ```XML
> 
> #[allow(dead_code)]
> #[derive(PartialEq, Eq, Debug)]
> ```

Order
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvao7vGCpGxM6uNWBxY:-Nvao7vGCpGxM6uNWBxZ:bc4rxhm) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/types.rs#L89)):*
> ```XML
> }
> #[allow(dead_code)]
> #[derive(Debug, PartialEq, Eq)]
> ```

Order all



_Code quote:_
```XML
Debug, PartialEq, Eq
```


<!-- Sent from Reviewable.io -->

2024-04-16 14:13 UTC, amosStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 4 of 14 files reviewed, 54 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbFJEEEQwvk0GZ_59X:-NvbFJEEEQwvk0GZ_59Y:bs35dqi) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L24)):*
> ```XML
> #[allow(dead_code)]
> impl SkeletonTree<'_> {
>     fn fetch_nodes(
> ```

IMO this method should be divided into sub methods - it's hard to read



_Code quote:_
```XML
fn fetch_nodes(
```


<!-- Sent from Reviewable.io -->

2024-04-16 14:15 UTC, dorimedini-starkware requested changes
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 37 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvarLf9DYqO_aNsbtCt:-NvbFjwe7SmQME8V-VB6:b-fgzeir) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree.rs#L4)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why not do this in `original_skeleton_tree.rs`? @dorimedini-starkware WYT?
</blockquote></details>

let's think about it later; moving code in this PR will be painful
___
*[`crates/committer/src/types.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvalEmQAPQnxAz3jHHM:-NvbE46O8K56ESJjaSmQ:bb7r2f0) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L62)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

This looks like a comment msg. An error message should be clear without context - "Unexpected failure extracting bits from Felt" or something.
</blockquote></details>

why?
___
*[`crates/committer/src/types.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX5nsS42q19CLiWO7C:-NvbE91230CM_ygLnM7J:b-ma755h) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L65)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I agree it may be misleading. maybe a better name is `times_two_to_the_power(&self, power: u8)`.
I am pretty sure that in case of overflow, it returns the result % PRIME (like we expect). However, I'm wondering how efficient it is.
</blockquote></details>

ok, then please rename so it's clear what is done.
as for efficiency - I wouldn't worry about it, actual usage won't overflow
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvb819m2i8ouD1MVDaD:-Nvb819m2i8ouD1MVDaE:bvzt5rm) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/filled_node.rs#L75)):*
> ```XML
>         value: &StorageValue,
>     ) -> OriginalSkeletonTreeResult<Self> {
>         // TODO(Nimrod, 30/4/2024): Compare to constant values once Aviv's PR is merged.
> ```

even better, provide a link :)



_Suggestion:_
```XML
PR #18
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvb8A5r-OXaYoskCxbc:-Nvb8A5r-OXaYoskCxbd:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/filled_node.rs#L85)):*
> ```XML
>             })
>         }
>         // TODO(Nimrod, 30/4/2024): Compare to constant values once Aviv's PR is merged.
> ```





_Suggestion:_
```XML
PR #18
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvb8JvM0vMqmc-VoS5a:-Nvb8JvM0vMqmc-VoS5b:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/filled_node.rs#L101)):*
> ```XML
>             Err(OriginalSkeletonTreeError::Deserialization(
>                 "Could not deserialize given key and value.".to_string(),
>             ))
> ```





_Suggestion:_
```XML
            todo!("Deserialize leaves.")
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX79WD9aKRTmJRr45o:-NvbEUrtCdLmY4-5VvzV:b-3go6zb) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L21)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Why is it needed?
</blockquote></details>

ah, right... modifications aren't part of the "original skeleton".
@nimrod-starkware you should be able to remove it from the struct, you don't actually use this in `fetch_nodes` (right?), only @TzahiTaub will need it.
you only need a collection of leaf indices in the initial `SubTree`
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXD5OeDTvEt7Mf685p:-NvbA0OR7qRW8wFxXu3e:b-42frdk) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L89)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

not exactly, we don't want to call fetch nodes with a subtree representing a leaf (it requires extra context when reading from storage)..
</blockquote></details>

can you explain? it makes this code more difficult to follow
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX7iwvCkrM0pM4Byh-:-NvbAbWSCi0MKxKowZYe:b-m7s74o) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L149)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry... I meant, move this struct definition above the `impl OriginalSkeletonTreeImpl` block
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX7qg8D5pHBDL2dBu1:-NvbAlTU4rrbSm_8Tqzb:b-irwhab) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L173)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

where?
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvb8_be4wJJtP3K78sp:-Nvb8_be4wJJtP3K78sq:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L33)):*
> ```XML
>     /// Function's purpose is to fetch from storage the patricia witnesses in order to build the
>     /// original skeleton tree. Given a list of subtrees, traverses towards their leaves and
>     /// fetches all non-empty and sibiling nodes. Assumes no subtrees of height 0 (leaves).
> ```

typo



_Suggestion:_
```XML
sibling
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvb8pY80vRk45RgPoN3:-Nvb8pY80vRk45RgPoN4:b4gwmu4) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L39)):*
> ```XML
>         storage: HashMap<StorageKey, StorageValue>,
>         // TODO(Nimrod, 25/4/2024): Change input type to Storage once Amos has implemented the
>         // Storage trait for HashMap.
> ```

this is merged, no? PR #40



_Code quote:_
```XML
        // TODO(Nimrod, 25/4/2024): Change input type to Storage once Amos has implemented the
        // Storage trait for HashMap.
```
___
*[`crates/committe [...]

2024-04-16 14:40 UTC, amosStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 38 unresolved discussions (waiting on @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbLGNv7EEpwltRD5nB:-NvbLGNv7EEpwltRD5nC:bf9g8r4) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/filled_node.rs#L71)):*
> ```XML
> #[allow(dead_code)]
> impl FilledNode<LeafData> {
>     pub(crate) fn deserialize(
> ```

I liked @dorimedini-starkware 's suggestion of creating a trait for serialization (and deserialization) - @nimrod-starkware you don't like it?



_Code quote:_
```XML
pub(crate) fn deserialize(
```


<!-- Sent from Reviewable.io -->

2024-04-16 14:54 UTC, amosStarkware requested changes, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 39 unresolved discussions (waiting on @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbOj7_1xgkCCpnncf1:-NvbOj7aCEGMPdqZoSQ8:bc8pe1s) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/filled_node.rs#L74)):*
> ```XML
>         key: &StorageKey,
>         value: &StorageValue,
>     ) -> OriginalSkeletonTreeResult<Self> {
> ```

@AvivYossef-starkware created types for serializing nodes, please look here
https://reviewable.io/reviews/starkware-libs/committer/18



_Code quote:_
```XML
) -> OriginalSkeletonTreeResult<Self> {
```


<!-- Sent from Reviewable.io -->

2024-04-16 16:02 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 39 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbOj7_1xgkCCpnncf1:-Nvbd91m6e6iYKxPLChk:b-7zczeu) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/filled_node.rs#L74)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

@AvivYossef-starkware created types for serializing nodes, please look here
https://reviewable.io/reviews/starkware-libs/committer/18
</blockquote></details>

yes this is in reverse. we will combine to be an implementation of a single trait later, when both PRs are in, otherwise we will get annoying conflicts


<!-- Sent from Reviewable.io -->

2024-04-17 06:57 UTC, TzahiTaub reviewed
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 13 of 14 files reviewed, 37 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/hash/types.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX6feYAf0FtvoG2GQ3:-Nveq0JE1220EZPjrVYO:b-rz2ot4) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/hash/types.rs#L9)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why does Eq come after PartialEq?


<!-- Sent from Reviewable.io -->

2024-04-17 07:31 UTC, TzahiTaub reviewed
> Dismissed @nimrod-starkware from 9 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 13 of 14 files reviewed, 37 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, and @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-04-17 07:59 UTC, TzahiTaub requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 13 of 14 files reviewed, 39 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvf3DUdBKqZb7yDNbn-:-Nvf3DUeAgmaUpEPeOHm:b-q93bs6) ([raw file](https://github.com/starkware-libs/committer/blob/cccc0dc66b46fc7aeccffbd5d8fa900744418c39/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L75)):*
> ```XML
>         }
>         let mut next_subtrees = Vec::new();
>         let mut filled_nodes = Vec::new();
> ```

If this is right, I think it's clearer.



_Suggestion:_
```XML
  let mut subtrees_roots
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvf26zmEu96KVKjztsm:-Nvf26zmEu96KVKjztsn:b-gfjej0) ([raw file](https://github.com/starkware-libs/committer/blob/cccc0dc66b46fc7aeccffbd5d8fa900744418c39/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L80)):*
> ```XML
>                 .get(&subtree.root_hash.with_prefix(StoragePrefix::PatriciaNode))
>                 .ok_or(OriginalSkeletonTreeError::StorageRead)?;
>             filled_nodes.push(FilledNode::deserialize(&subtree.root_hash, val)?)
> ```

A FilledNode is the original node prior to the update?



_Code quote:_
```XML
 filled_nodes.push(FilledNode
```


<!-- Sent from Reviewable.io -->

2024-04-17 08:04 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 37 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvf37w67zUlfgpuOVaw:-Nvf37w67zUlfgpuOVax:b-bv6duk) ([raw file](https://github.com/starkware-libs/committer/blob/cccc0dc66b46fc7aeccffbd5d8fa900744418c39/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L34)):*
> ```XML
>     pub root_hash: StorageKey,
> }
> #[allow(dead_code)]
> ```

newlines



_Suggestion:_
```XML
}

#[allow(dead_code)]
struct SubTree<'a> {
    pub sorted_leaf_indices: &'a [NodeIndex],
    pub root_index: NodeIndex,
    pub root_hash: StorageKey,
}

#[allow(dead_code)]
```


<!-- Sent from Reviewable.io -->

2024-04-17 08:36 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 6 of 14 files reviewed, 36 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, @n, and @TzahiTaub)

___
*[`crates/committer/src/types.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX5nsS42q19CLiWO7C:-NveoVBSBzbowo-fWrJj:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L65)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok, then please rename so it's clear what is done.
as for efficiency - I wouldn't worry about it, actual usage won't overflow
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbLGNv7EEpwltRD5nB:-Nvepdnc6A6PIFVi9Da_:bjoer7q) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/filled_node.rs#L71)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I liked @dorimedini-starkware 's suggestion of creating a trait for serialization (and deserialization) - @nimrod-starkware you don't like it?
</blockquote></details>

[asf](https://github.com/starkware-libs/committer/pull/18)
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvb8JvM0vMqmc-VoS5a:-Nvercej2-O-80SC9P3W:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/filled_node.rs#L101)):*
> ```XML
>             Err(OriginalSkeletonTreeError::Deserialization(
>                 "Could not deserialize given key and value.".to_string(),
>             ))
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvb8VsG5UBXVgYE2iey:-Nves_RS380V1gYXUbUj:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L33)):*
> ```XML
>     /// Function's purpose is to fetch from storage the patricia witnesses in order to build the
>     /// original skeleton tree. Given a list of subtrees, traverses towards their leaves and
>     /// fetches all non-empty and sibiling nodes. Assumes no subtrees of height 0 (leaves).
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXGiwk0CrKobfbx7NX:-Nvf9QHxCBIt0kqeBVk4:b30tuj3) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah... maybe I'm misunderstanding how the original skeleton represents leaves.
the new leaves are not part of the skeleton?
that's why leaf number 13 does not appear in the example output?
so really no need to write `NZ`... sorry
</blockquote></details>

yes, new leaves are not part of the old skeleton.
I think it actually not a bad idea, when we want to indicate there was a NZ leaf, but it's actual value doesn't matter.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXGCTVD3iN26-_4loE:-Nvf1wso0ZQibytW8gTv:b-70c5x7) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L41)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I'm not sure I follow. Should this also follow the `H(node)=h(value, path) + length` for edge nodes? Shouldn't the 20 (right son of the root) here be `h(15, 0b111) + 3=15+7+3=25`? Be happy for the numbers calculation explanation as I don't think it's very straightforward (like the value of leaves is their index, for binary nodes h(left, right) is the sum of their descendants, and for edge nodes h(value, path) + length = value+path+length
</blockquote></details>

the length is 2 and the path is 3 (0b11) :)
I agree that the draw may be confusing
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbCLk2C9mudahv2wjn:-Nvf2Sx773yFmXj5dDbR:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

reduce boilerplate
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbC31C9W-MS3MBQi_X:-Nvf2U_YBr9oBljG5JVd:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L55)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

less duplication
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbCbRT2hZ5nE71qbJK:-NvfAs0aEATXC7B1hZfU:b-vvzud7) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L63)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is what I'm trying to avoid; also
```
X { y: Y {
   bla
}}
```
is not as good as
```
X {
    y: Y { bla }
}
```
</blockquote></details>

changed. not sure it's the format though.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbCsax3E5WmTGDRJqg:-Nvf2XzUDOhmWPDRo3ZB:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L103)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

fix boilerplate (see above)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 168 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbD2p1EarSxnR2GlRm:-Nvf7Nci2npkIUPWkwde:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L168)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

fix boilerplate (see above)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 211 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbD4hgB_X400nV1mkd:-NvfAzTYDLMYZwI8tR2H:b-w077bm) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L211)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

fix macro formatting (see above)
</blockquote></details>

Done. not sure it's the right format
___
*[`crates/committer/src/patricia_merkle_tre [...]

2024-04-17 08:43 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 6 of 14 files reviewed, 36 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, @n, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbLGNv7EEpwltRD5nB:-NvfC48jCdFqsV2oVx8Q:b-k70yoy) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/filled_node.rs#L71)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

[asf](https://github.com/starkware-libs/committer/pull/18)
</blockquote></details>

oops, it's a mistake above.

I like the idea as well. but I think it's best to do that in a future PR.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvb819m2i8ouD1MVDaD:-NvfCNwVCx9wVoOmsNFy:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/filled_node.rs#L75)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

even better, provide a link :)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvb8A5r-OXaYoskCxbc:-NvfCNlJ5LLkCcDaRXFr:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/filled_node.rs#L85)):*
> ```XML
>             })
>         }
>         // TODO(Nimrod, 30/4/2024): Compare to constant values once Aviv's PR is merged.
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvf3DUdBKqZb7yDNbn-:-NvfChO34I5rob87_Tmi:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/cccc0dc66b46fc7aeccffbd5d8fa900744418c39/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L75)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

If this is right, I think it's clearer.
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvf26zmEu96KVKjztsm:-NvfC_Sb-GwNPwSBcuLh:b-z0sr5s) ([raw file](https://github.com/starkware-libs/committer/blob/cccc0dc66b46fc7aeccffbd5d8fa900744418c39/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L80)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

A FilledNode is the original node prior to the update?
</blockquote></details>

yes exactly.


<!-- Sent from Reviewable.io -->

2024-04-17 09:09 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 1 of 15 files reviewed, 36 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, @n, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvb8pY80vRk45RgPoN3:-NvfJQ1Z7wFe2KxX5FtX:bb7f2mf) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is merged, no? PR #40
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-04-17 09:15 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 8 files at r4, 1 of 1 files at r5, 14 of 14 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 20 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @n, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/storage/storage_trait.rs` line 35 at r6](https://reviewable.io/reviews/starkware-libs/committer/39#-NvfK_r274QkX4Wk2NtU:-NvfK_r274QkX4Wk2NtV:b-4yr6dt) ([raw file](https://github.com/starkware-libs/committer/blob/3a036eb164da8cb432816884dc89d95700ae06a9/crates/committer/src/storage/storage_trait.rs#L35)):*
> ```XML
>     PatriciaNode,
> }
> #[allow(dead_code)]
> ```

newline



_Suggestion:_
```XML
}

#[allow(dead_code)]
```


<!-- Sent from Reviewable.io -->

2024-04-17 09:49 UTC, dorimedini-starkware reviewed
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 19 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @n, @nimrod-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-04-17 10:00 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 12 of 15 files reviewed, 19 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, @n, and @TzahiTaub)

___
*[`crates/committer/src/storage/storage_trait.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvb-fnm876G3Fs8GiFR:-NvfUsvAEraNmLVc_zEG:bk38rlw) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/storage/storage_trait.rs#L42)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I agree. I added a TODO 
`// TODO(Nimrod, 5/5/2024): If possible, divide Deserialization to more specific types of errors.`
I think it will be clearer in the future how to optimize it.
</blockquote></details>

I added some more specific error types @amosStarkware under `OriginalSkeletonTreeError`
___
*[`crates/committer/src/storage/storage_trait.rs` line 35 at r6](https://reviewable.io/reviews/starkware-libs/committer/39#-NvfK_r274QkX4Wk2NtU:-NvfNShwATPCTu-rAEfV:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3a036eb164da8cb432816884dc89d95700ae06a9/crates/committer/src/storage/storage_trait.rs#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newline
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-17 10:03 UTC, dorimedini-starkware reviewed
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 19 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @n, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 11 at r8](https://reviewable.io/reviews/starkware-libs/committer/39#-NvfVT76CkKigfaYQc_Z:-NvfVT76CkKigfaYQc__:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/ec0e9378b38fd5f86afb064d16667fd3c6dc74d7/crates/committer/src/patricia_merkle_tree/errors.rs#L11)):*
> ```XML
> pub(crate) enum OriginalSkeletonTreeError {
>     #[error(
>         "Falied to deserialize the storage value: {0:?} while building the original skeleton tree."
> ```

typo



_Code quote:_
```XML
Falied
```


<!-- Sent from Reviewable.io -->

2024-04-17 10:04 UTC, aner-starkware commented
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX9NQA8nzYweAIAkhj:-NvfVlLtDkvtiMd4pO_d:b-rwmzou) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/types.rs#L133)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

@aner-starkware did you write something similar?
</blockquote></details>

@nimrod-starkware There's [pub(crate) fn compute\_bottom\_index](https://github.com/starkware-libs/committer/blob/600f4b81e6e3028be773604c62a610a056ac6ce3/crates/committer/src/patricia_merkle_tree/types.rs#L59C1-L65C6) 


<!-- Sent from Reviewable.io -->

2024-04-17 11:03 UTC, TzahiTaub requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 11 of 17 files reviewed, 14 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, @n, and @nimrod-starkware)

___
*[`crates/committer/src/types.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvalEmQAPQnxAz3jHHM:-NvfhNsd5ubUN2BnB19k:bz18jm1) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L62)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why?
</blockquote></details>

Because this is what the end user will see in case the error is indeed raised for some reason.  Like getting an "Internal Error" instead of "this should always succeed so no need for a real error msg".
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXGCTVD3iN26-_4loE:-Nvfi9ag3lEydv7BsE6H:b-erh7pm) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L41)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

the length is 2 and the path is 3 (0b11) :)
I agree that the draw may be confusing
</blockquote></details>

Oh, I've counted every `\` as a level. Yes, pretty confusing. Maybe replace the middle `\` between `20/E` and `15` with `*`?


<!-- Sent from Reviewable.io -->

2024-04-17 11:17 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 11 of 17 files reviewed, 14 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, @n, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXGCTVD3iN26-_4loE:-Nvfketf8F8fSqslEaHc:bb7f2mf) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L41)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Oh, I've counted every `\` as a level. Yes, pretty confusing. Maybe replace the middle `\` between `20/E` and `15` with `*`?
</blockquote></details>

done
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 158 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbDAJg6Vt27xTg9Rky:-NvflDwKAFYN4SqT6eR9:bb7f2mf) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L158)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe remane so it's clear it's different than a regular edge?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-04-17 11:29 UTC, TzahiTaub requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 10 of 17 files reviewed, 15 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, @n, and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXGCTVD3iN26-_4loE:-NvfoIsoBdy1X4umwQe_:b-tukkio) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L41)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

done
</blockquote></details>

Great. Please do this change for all tree drawings in the file


<!-- Sent from Reviewable.io -->

2024-04-17 11:33 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 10 of 17 files reviewed, 15 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, @n, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXGCTVD3iN26-_4loE:-NvfpOlPDMYPAvuldKd5:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc_test.rs#L41)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Great. Please do this change for all tree drawings in the file
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-17 11:52 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 2 files at r9, 3 of 4 files at r10, 1 of 2 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 14 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @n, @nimrod-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-04-18 07:02 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 10 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 72 at r13](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvk-hvMEeRp5Sw-eAz5:-Nvk-hvMEeRp5Sw-eAz6:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/86aa8179113686a72cdbbc6c2096846839299e0b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L72)):*
> ```XML
> #[allow(dead_code)]
> impl FilledNode<LeafData> {
>     pub(crate) fn deserialize(
> ```





_Suggestion:_
```XML
impl FilledNode<LeafData> {
    /// Deserializes non-leaf nodes; if a serialized leaf node is given, the hash
    /// is used but the data is ignored.
    pub(crate) fn deserialize(
```


<!-- Sent from Reviewable.io -->

2024-04-18 10:07 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 7 of 17 files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX8N8Y8SBQc1qtznqo:-NvgMK9f4ghMIhNUpn0R:bb7f2mf) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/errors.rs#L6)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

will do
</blockquote></details>

done
___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 72 at r13](https://reviewable.io/reviews/starkware-libs/committer/39#-Nvk-hvMEeRp5Sw-eAz5:-NvkYwXuEByxJSg1jW8W:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/86aa8179113686a72cdbbc6c2096846839299e0b/crates/committer/src/patricia_merkle_tree/filled_node.rs#L72)):*
> ```XML
> #[allow(dead_code)]
> impl FilledNode<LeafData> {
>     pub(crate) fn deserialize(
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbADCNAGiG3prYEX45:-NvkfD0KBMZPDJMetrKq:b-d7bhn0) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L121)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this chunk of logic should be implemented on some `SkeletonNode` (see above);
can you open a separate PR for this, and rebase the current PR over it?
</blockquote></details>

will do
___
*[`crates/committer/src/storage/storage_trait.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvXAeQ_0aifewTM8hO2:-Nvkf6x6D79AynNkHRMJ:bb7f2mf) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/storage/storage_trait.rs#L35)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

will do. i'm waiting for his PR to merge
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-04-18 11:35 UTC, dorimedini-starkware reviewed
> Reviewed 10 of 10 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-04-18 12:40 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-04-18 12:54 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-04-18 12:57 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/types.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvalEmQAPQnxAz3jHHM:-NvlB67BCkKmmmuvjigg:b-24j4vq) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L62)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Because this is what the end user will see in case the error is indeed raised for some reason.  Like getting an "Internal Error" instead of "this should always succeed so no need for a real error msg".
</blockquote></details>

@dorimedini-starkware @TzahiTaub 
What do you think about that?
```
    pub(crate) fn bits(&self) -> u8 {
        self.0
            .bits()
            .try_into()
            // Should not fail as it takes less than 252 bits to represent a felt.
            .expect("Unexpected error occurred when extracting bits of a Felt.")
    }
```  
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX79WD9aKRTmJRr45o:-NvlGwIn5tRAxuMne1Go:b3kuitq) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah, right... modifications aren't part of the "original skeleton".
@nimrod-starkware you should be able to remove it from the struct, you don't actually use this in `fetch_nodes` (right?), only @TzahiTaub will need it.
you only need a collection of leaf indices in the initial `SubTree`
</blockquote></details>

will open another PR that solves that
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbFJEEEQwvk0GZ_59X:-NvlBrYP7hMpv5SqB1sg:ba4bvaw) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L24)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

IMO this method should be divided into sub methods - it's hard to read
</blockquote></details>

i have refactored it a little bit to be more readable, what do you think @amosStarkware ?
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX7iwvCkrM0pM4Byh-:-NvlAXgY1H-u6C8E8bxd:b-7s63fo) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L149)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

sorry... I meant, move this struct definition above the `impl OriginalSkeletonTreeImpl` block
</blockquote></details>

all the `SubTree` logic is above the `impl OriginalSkeletonTreeImpl` block
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX7xFj1SNboVrBP5i-:-NvlA4MCBswC_naHEsEG:bdkii3o) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L151)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

will this struct be useful for Tzahi as well? Please sync
</blockquote></details>

@TzahiTaub? 
At the Python repository, it seems like it's not used to build the updated skeleton.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbADCNAGiG3prYEX45:-Nvl9my71yboRBQtiTJI:bb7f2mf) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L121)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

will do
</blockquote></details>

done
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 152 at r2](https://reviewable.io/reviews/starkware-libs/committer/39#-NvbAR3IELXv8jh55_zB:-Nvl9pp450kPvCNDewHV:bm7ccii) ([raw file](https://github.com/starkware-libs/committer/blob/6a577af3d088030686990acd5bd77e1ab2dbd92e/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L152)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think it is worth adding extra context to storage (as you mention above) to avoid this scenario... would like to understand what the issue is
</blockquote></details>

no longer relevant..


<!-- Sent from Reviewable.io -->

2024-04-18 12:59 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/types.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvalEmQAPQnxAz3jHHM:-NvlHM6w81ih7x6GFYVg:bb7k0qh) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/types.rs#L62)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

@dorimedini-starkware @TzahiTaub 
What do you think about that?
```
    pub(crate) fn bits(&self) -> u8 {
        self.0
            .bits()
            .try_into()
            // Should not fail as it takes less than 252 bits to represent a felt.
            .expect("Unexpected error occurred when extracting bits of a Felt.")
    }
```
</blockquote></details>

lgtm
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX79WD9aKRTmJRr45o:-NvlHQMzAU_0093AtYRp:b-96hetl) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L21)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

will open another PR that solves that
</blockquote></details>

add a TODO here then, so we can merge this without worry


<!-- Sent from Reviewable.io -->

2024-04-18 13:08 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39#-:-NvlJbao0UMkDx18OI4i:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX79WD9aKRTmJRr45o:-NvlJVyfC4DLKy7VVxGe:bp9184i) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add a TODO here then, so we can merge this without worry
</blockquote></details>

nvm, [PR is open](https://reviewable.io/reviews/starkware-libs/committer/51)


<!-- Sent from Reviewable.io -->

2024-04-18 13:09 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX79WD9aKRTmJRr45o:-NvlJNu94QGe_WQHjg5i:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add a TODO here then, so we can merge this without worry
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-18 13:32 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/committer/39#-NvX7xFj1SNboVrBP5i-:-NvlP-qW52OzmF6JvvYw:b-hxy17n) ([raw file](https://github.com/starkware-libs/committer/blob/53fd168bc93f039697d96b9aca2faf42e9e390f0/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L151)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

@TzahiTaub? 
At the Python repository, it seems like it's not used to build the updated skeleton.
</blockquote></details>

I don't think I need it. I do need the split_leaves though, but I'll take if out after you merge.


<!-- Sent from Reviewable.io -->

2024-04-18 13:35 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-04-18 13:35 UTC, dorimedini-starkware approved these changes
> Dismissed @amosStarkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-04-18 13:35 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-04-18 13:37 UTC, dorimedini-starkware approved these changes
> Dismissed @amosStarkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/39)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-04-18 13:41 UTC, TzahiTaub approved these changes

2024-04-18 13:43 UTC, merged