WIP: interior mutability
starkware-libs/committer pull request #43
Opened 2024-04-16 10:37 UTC by aner-starkware

2024-04-16 11:22 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvac0yN5zf8yNpuNWvc:-Nvac0yOEKYQqMx7-CU4:bkdzobq) ([raw file](https://github.com/starkware-libs/committer/blob/da56e8f59ec9d65d1bf7066bb08ebaca65b23a17/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L99)):*
> ```XML
>                     }
>                     None => return Err(UpdatedSkeletonTreeError::MissingNode),
>                 }
> ```

nice!
now we can write in parallel, yes?
@Yoni-Starkware FYI



_Code quote:_
```XML
                let read_map = output_map.read().map_err(|_| {
                    UpdatedSkeletonTreeError::PoisonedLock(
                        "Cannot read from output map.".to_owned(),
                    )
                })?;

                match read_map.get(&index) {
                    Some(node) => {
                        node.lock()
                            .map_err(|_| {
                                UpdatedSkeletonTreeError::PoisonedLock(
                                    "Cannot lock node.".to_owned(),
                                )
                            })?
                            .data = data;
                    }
                    None => return Err(UpdatedSkeletonTreeError::MissingNode),
                }
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/committer/43#-NvacBvw1CPz6IfpedSO:-NvacBvw1CPz6IfpedSP:b77lrra) ([raw file](https://github.com/starkware-libs/committer/blob/da56e8f59ec9d65d1bf7066bb08ebaca65b23a17/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L129)):*
> ```XML
>                     }
>                     None => return Err(UpdatedSkeletonTreeError::MissingNode),
>                 }
> ```

can you implement a `write_to_map(output_map, index, data) -> UpdatedSkeletonTreeResult<()>` function and use it ~twice~ three times? 



_Suggestion:_
```XML
                Self::write_to_map(output_map, index, data)?;
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvad0ux-V4LC0ty7GMT:-Nvad0uy0YE1IBsSTL4i:b-l4jpqw) ([raw file](https://github.com/starkware-libs/committer/blob/da56e8f59ec9d65d1bf7066bb08ebaca65b23a17/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L135)):*
> ```XML
>             UpdatedSkeletonNode::Leaf(node_data) => {
>                 let hash_value = TH::compute_node_hash(&NodeData::Leaf(node_data.clone()));
>                 // TODO (Aner, 15/4/21): Change to use interior mutability.
> ```

right?



_Suggestion:_
```XML
// TODO (Aner, 15/4/21): Change to use interior mutability. Doing so will require
//   inserting all leaves as "unknown leaves" in advance, so they are only edited
//   here.
```


<!-- Sent from Reviewable.io -->

2024-04-16 12:02 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvac0yN5zf8yNpuNWvc:-NvaiWzf9JjKpOdHJreN:blf63w3) ([raw file](https://github.com/starkware-libs/committer/blob/da56e8f59ec9d65d1bf7066bb08ebaca65b23a17/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L99)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

nice!
now we can write in parallel, yes?
@Yoni-Starkware FYI
</blockquote></details>

I think so, once @TzahiTaub  and I  sort out where to write the hasmap with the empty nodes. Then we can check if this indeed works as expected.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/committer/43#-NvacBvw1CPz6IfpedSO:-Nvalrj3AFKTs7iHhjYh:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/da56e8f59ec9d65d1bf7066bb08ebaca65b23a17/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L129)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you implement a `write_to_map(output_map, index, data) -> UpdatedSkeletonTreeResult<()>` function and use it ~twice~ three times?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvad0ux-V4LC0ty7GMT:-NvalsFa0SAow8LEUtcJ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/da56e8f59ec9d65d1bf7066bb08ebaca65b23a17/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L135)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

right?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-16 12:07 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvampf3E8D0Us3NWWIf:-Nvampf3E8D0Us3NWWIg:b-6osmde) ([raw file](https://github.com/starkware-libs/committer/blob/e716e58462dfadc21d9c3da656581811c239ed39/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L104)):*
> ```XML
>                 // TODO (Aner, 15/4/21): Change to use interior mutability. Doing so will require
>                 // inserting all leaves as "unknown leaves" in advance, so they are only edited
>                 // here.
> ```

this comment edit is not relevant for binary nodes - only leaves



_Code quote:_
```XML
                // TODO (Aner, 15/4/21): Change to use interior mutability. Doing so will require
                // inserting all leaves as "unknown leaves" in advance, so they are only edited
                // here.
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/committer/43#-NvamuQU9mlyoxylp3eW:-NvamuQV7pzeEWcs_w7m:b-qudxmd) ([raw file](https://github.com/starkware-libs/committer/blob/e716e58462dfadc21d9c3da656581811c239ed39/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L119)):*
> ```XML
>                 // TODO (Aner, 15/4/21): Change to use interior mutability. Doing so will require
>                 // inserting all leaves as "unknown leaves" in advance, so they are only edited
>                 // here.
> ```

leaves only



_Code quote:_
```XML
                // TODO (Aner, 15/4/21): Change to use interior mutability. Doing so will require
                // inserting all leaves as "unknown leaves" in advance, so they are only edited
                // here.
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvan1Mq5xNJj4H9SGcM:-Nvan1Mr3shLByaFnkiu:b-gqf4px) ([raw file](https://github.com/starkware-libs/committer/blob/e716e58462dfadc21d9c3da656581811c239ed39/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L130)):*
> ```XML
>                 // inserting all leaves as "unknown leaves" in advance, so they are only edited
>                 // here.
>                 Self::write_to_output_map_with_interior_mutuability(output_map, index, data)?;
> ```

this will work? I thought leaves are *inserted* here, not mutated?



_Code quote:_
```XML
Self::write_to_output_map_with_interior_mutuability(output_map, index, data)?;
```


<!-- Sent from Reviewable.io -->

2024-04-16 12:24 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvampf3E8D0Us3NWWIf:-Nvar7dC-b7Y_zEImvro:b-a2lwmy) ([raw file](https://github.com/starkware-libs/committer/blob/e716e58462dfadc21d9c3da656581811c239ed39/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L104)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this comment edit is not relevant for binary nodes - only leaves
</blockquote></details>

I changed the comment to make it relevant for all nodes.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/committer/43#-NvamuQU9mlyoxylp3eW:-NvarLPx-prR92ucK6Z_:brdnsv) ([raw file](https://github.com/starkware-libs/committer/blob/e716e58462dfadc21d9c3da656581811c239ed39/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L119)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

leaves only
</blockquote></details>

OK, changed the comment.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvan1Mq5xNJj4H9SGcM:-Nvaqsa7-IbUYVfLoZkv:b-vgg10p) ([raw file](https://github.com/starkware-libs/committer/blob/e716e58462dfadc21d9c3da656581811c239ed39/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L130)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this will work? I thought leaves are *inserted* here, not mutated?
</blockquote></details>

If the leaves are inserted here, it will not work. This is not what's currently written though. Why should the leaves be inserted here?


<!-- Sent from Reviewable.io -->

2024-04-16 12:45 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvampf3E8D0Us3NWWIf:-NvavXoQCf2G8CObDZS6:bk06lzo) ([raw file](https://github.com/starkware-libs/committer/blob/e716e58462dfadc21d9c3da656581811c239ed39/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L104)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I changed the comment to make it relevant for all nodes.
</blockquote></details>

what?
you have already implemented interior mutability for binary and edge (and sibling) nodes; this TODO is only relevant for the leaves.
no?
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/committer/43#-NvamuQU9mlyoxylp3eW:-NvavxsJ1a0a1mmxSvo7:bhjj712) ([raw file](https://github.com/starkware-libs/committer/blob/e716e58462dfadc21d9c3da656581811c239ed39/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L119)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

OK, changed the comment.
</blockquote></details>

no, see above


<!-- Sent from Reviewable.io -->

2024-04-17 09:10 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/committer/43#-NvfJQ83EI6h2S0bnBvW:-NvfJQ843T4dPZNr9Cq1:b-bdjj9q) ([raw file](https://github.com/starkware-libs/committer/blob/83ab76bf915f853e6e9a81f4b1eb0167a9424249/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L48)):*
> ```XML
> 
>     fn write_to_output_map_with_interior_mutuability(
>         output_map: Arc<RwLock<HashMap<NodeIndex, Mutex<FilledNode<L>>>>>,
> ```

The point is to get rid of the `RwLock`, no?



_Code quote:_
```XML
output_map: Arc<RwLock<HashMap<NodeIndex, Mutex<FilledNode<L>>>>>,
```


<!-- Sent from Reviewable.io -->

2024-04-17 11:23 UTC, aner-starkware commented
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/committer/43#-NvfJQ83EI6h2S0bnBvW:-NvfmVIh0_MLwsllNBOy:b-ctqrsz) ([raw file](https://github.com/starkware-libs/committer/blob/e5d5c09e3670dce2fe5b9a0e69c92c5a1f15c434/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L48)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

The point is to get rid of the `RwLock`, no?
</blockquote></details>

Why? IIUC, RwLock allows several threads to read from the hashmap without locking it; locking is done only for writing to the hashmap (which is removed in this PR).


<!-- Sent from Reviewable.io -->

2024-04-17 12:34 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/committer/43#-NvamuQU9mlyoxylp3eW:-Nvg1OGHBi6QTqwRzo6X:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e716e58462dfadc21d9c3da656581811c239ed39/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L119)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no, see above
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/committer/43#-NvfJQ83EI6h2S0bnBvW:-Nvg1KCL4Ac_YSh1lnVH:b-uvcnel) ([raw file](https://github.com/starkware-libs/committer/blob/e5d5c09e3670dce2fe5b9a0e69c92c5a1f15c434/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L48)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Why? IIUC, RwLock allows several threads to read from the hashmap without locking it; locking is done only for writing to the hashmap (which is removed in this PR).
</blockquote></details>

OK, took your suggestion and removed the RwLock.


<!-- Sent from Reviewable.io -->

2024-04-17 13:10 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 2 files at r4, 5 of 6 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/committer/43#-NvfvhavAa97wqXRp5FF:-NvfvhavAa97wqXRp5FG:bvta32w) ([raw file](https://github.com/starkware-libs/committer/blob/a523b1ed8b6b8a7dccb99d148f87b635d649fc9e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L70)):*
> ```XML
>     }
> 
>     fn create_dummy_filled_tree_map(&self) -> HashMap<NodeIndex, Mutex<FilledNode<L>>> {
> ```

this is named like a test util - you need this so that all keys exist in advance?
1. please rename to `set_all_indices_to_empty_values` or something
2. why do you need to fill the correct node *types* when you initialize this? can't you just put empty binary nodes everywhere?



_Code quote:_
```XML
fn create_dummy_filled_tree_map
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 53 at r8](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgADAB4MXczBdKR3J_:-NvgADAB4MXczBdKR3Ja:b-358kq) ([raw file](https://github.com/starkware-libs/committer/blob/c70f694efcd25972b86c5cf86cc5970f27406918/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L53)):*
> ```XML
>         data: NodeData<L>,
>     ) -> Result<(), UpdatedSkeletonTreeError> {
>         let read_map = output_map;
> ```

redundant assignment, just use `output_map`



_Code quote:_
```XML
let read_map = output_map;
```


<!-- Sent from Reviewable.io -->

2024-04-17 13:33 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 9 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 85 at r5](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgDAIj8DEGk9nzaOyI:-NvgDAIj8DEGk9nzaOyJ:b-o34ybh) ([raw file](https://github.com/starkware-libs/committer/blob/875ca4122718c42c763dbd9e1abe2e89085b059e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L85)):*
> ```XML
>                         UpdatedSkeletonNode::Leaf(node_data) => NodeData::Leaf(node_data.clone()),
>                         UpdatedSkeletonNode::Sibling(_) => {
>                             unimplemented!("Sibling nodes should not be copied to the filled tree.")
> ```

Is this reachable?



_Code quote:_
```XML
unimplemented!("Sibling nodes should not be copied to the filled tree.")
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 177 at r5](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgC0hPAk-m5sBVJ6_B:-NvgC0hPAk-m5sBVJ6_C:by8nz7q) ([raw file](https://github.com/starkware-libs/committer/blob/875ca4122718c42c763dbd9e1abe2e89085b059e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L177)):*
> ```XML
>         )?;
>         // 3. Create and return a new FilledTreeImpl from the hashmap.
>         Ok(FilledTreeImpl::new(
> ```

Why is the return type `impl FilledTree<L>` if we always use a specific struct? `FilledTreeImpl` 



_Code quote:_
```XML
k(FilledTreeImpl::new(
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 177 at r5](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgDrLjBy7kgm92EA-K:-NvgDrLjBy7kgm92EA-L:b-9d27d6) ([raw file](https://github.com/starkware-libs/committer/blob/875ca4122718c42c763dbd9e1abe2e89085b059e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L177)):*
> ```XML
>         )?;
>         // 3. Create and return a new FilledTreeImpl from the hashmap.
>         Ok(FilledTreeImpl::new(
> ```

Let's avoid using `dummy` around here



_Suggestion:_
```XML
        // Compute the filled tree in two steps:
        //   1. Create a map containing the tree structure without hash values.
        //   2. Fill in the hash values.
        // Do so to enable non-blocking access to the shared map, using interior mutability. 
        let initial_filled_tree_map = Arc::new(self.create_dummy_filled_tree_map(););
        self.compute_filled_tree_rec::<H, TH>(
            NodeIndex::root_index(),
            Arc::clone(&initial_filled_tree_map),
        )?;
        // Create and return a new FilledTree from the hashmap.
        Ok(FilledTreeImpl::new(
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 177 at r5](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgFbuH9i1BI8oqJneb:-NvgFbuH9i1BI8oqJnec:b-l91108) ([raw file](https://github.com/starkware-libs/committer/blob/875ca4122718c42c763dbd9e1abe2e89085b059e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L177)):*
> ```XML
>         )?;
>         // 3. Create and return a new FilledTreeImpl from the hashmap.
>         Ok(FilledTreeImpl::new(
> ```

What's the difference?



_Code quote:_
```XML
FilledTreeImpl
```


<!-- Sent from Reviewable.io -->

2024-04-17 14:28 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/committer/43#-NvfvhavAa97wqXRp5FF:-NvgRALSB9yM1SQU2eJM:b-k7c7i4) ([raw file](https://github.com/starkware-libs/committer/blob/a523b1ed8b6b8a7dccb99d148f87b635d649fc9e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L70)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is named like a test util - you need this so that all keys exist in advance?
1. please rename to `set_all_indices_to_empty_values` or something
2. why do you need to fill the correct node *types* when you initialize this? can't you just put empty binary nodes everywhere?
</blockquote></details>

Renamed. Is this OK?
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 47 at r5](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvg8EaX4Q8x166AsIVP:-NvgRHXiAE0lSxEYOpuQ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/875ca4122718c42c763dbd9e1abe2e89085b059e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L47)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Also, consider defining a struct that wraps `Arc<HashMap<NodeIndex, Mutex<FilledNode<L>>>>` and implements `write`
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 68 at r5](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgA08UCoUa79cr3GPf:-NvgRETk9mqxMC7w-3Dq:b2soej2) ([raw file](https://github.com/starkware-libs/committer/blob/875ca4122718c42c763dbd9e1abe2e89085b059e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L68)):*
> ```XML
>     }
> 
>     fn create_dummy_filled_tree_map(&self) -> HashMap<NodeIndex, Mutex<FilledNode<L>>> {
> ```

Is the new name OK?
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 85 at r5](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgDAIj8DEGk9nzaOyI:-NvgQsdE1SYXyXcTC-km:bdeco5w) ([raw file](https://github.com/starkware-libs/committer/blob/875ca4122718c42c763dbd9e1abe2e89085b059e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L85)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is this reachable?
</blockquote></details>

It shouldn't be due to the `if` above, but it doesn't compile otherwise.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 121 at r5](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvg7mvj7mpLBDCL8g7W:-NvgOPi611-6euEPEYt1:b-o3hesg) ([raw file](https://github.com/starkware-libs/committer/blob/875ca4122718c42c763dbd9e1abe2e89085b059e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L121)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is this the standard way to retrieve values from threads?
</blockquote></details>

There are several different ways, depending on the library (Rayon vs. Tokio) and the way you use it (Scope&Spawn vs. join). I think for Rayon with join, this is a normal way (there might be a more standard way, I'm no expert, but some more "natural" ways don't compile here)
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 177 at r5](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgFbuH9i1BI8oqJneb:-NvgPQSVAZbJ2Xb98g5D:bv155v5) ([raw file](https://github.com/starkware-libs/committer/blob/875ca4122718c42c763dbd9e1abe2e89085b059e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L177)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

What's the difference?
</blockquote></details>

I changed it. Basically, one way matches the generic function declaration, the other matches the concrete return type implementation.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 177 at r5](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgDrLjBy7kgm92EA-K:-NvgPaJ99u_hxSziwvyX:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/875ca4122718c42c763dbd9e1abe2e89085b059e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L177)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Let's avoid using `dummy` around here
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 177 at r5](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgC0hPAk-m5sBVJ6_B:-NvgR5HR-00ankwXCdlY:b-toeoyr) ([raw file](https://github.com/starkware-libs/committer/blob/875ca4122718c42c763dbd9e1abe2e89085b059e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L177)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why is the return type `impl FilledTree<L>` if we always use a specific struct? `FilledTreeImpl`
</blockquote></details>

See my answer below.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 53 at r8](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgADAB4MXczBdKR3J_:-NvgQFdS2k6Cfa4syGLh:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/c70f694efcd25972b86c5cf86cc5970f27406918/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L53)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

redundant assignment, just use `output_map`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-17 14:44 UTC, aner-starkware commented
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/committer/43#-NvfvhavAa97wqXRp5FF:-NvgVtCA7V2Qzzj3nG3J:b-qnubtw) ([raw file](https://github.com/starkware-libs/committer/blob/a523b1ed8b6b8a7dccb99d148f87b635d649fc9e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L70)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Renamed. Is this OK?
</blockquote></details>

Done for point 2.


<!-- Sent from Reviewable.io -->

2024-04-17 15:02 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 147 at r9](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgYcOL4z2cN_UXMHas:-NvgYcOL4z2cN_UXMHat:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/96125fe7cce8f15f11ec57841e5259006a730efe/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L147)):*
> ```XML
>         //   2. Fill in the hash values.
>         let dummy_filled_tree_map = self.create_filled_tree_map_with_placeholders();
>         let filled_tree_map = Arc::new(dummy_filled_tree_map);
> ```





_Suggestion:_
```XML
        let filled_tree_map = Arc::new(self.create_filled_tree_map_with_placeholders());
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 72 at r10](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgZrJk76Ir1hAReB88:-NvgZrJk76Ir1hAReB89:b-b6gy2c) ([raw file](https://github.com/starkware-libs/committer/blob/63c34b49e1557e9c883d89c7bc6e887b7ec6d442/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L72)):*
> ```XML
>         for (index, node) in &self.skeleton_tree {
>             if !matches!(node, UpdatedSkeletonNode::Sibling(_)) {
>                 filled_tree_map.insert(*index, Mutex::new(FilledNode::default()));
> ```

Weird... maybe `None`, for sanity?



_Code quote:_
```XML
FilledNode::default()))
```


<!-- Sent from Reviewable.io -->

2024-04-17 15:09 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r10, 2 of 2 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 32 at r11](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvg_yEdA745JBG1e3zz:-Nvg_yEdA745JBG1e4--:b-51kbmt) ([raw file](https://github.com/starkware-libs/committer/blob/33ae06588fe5d570e554df39191b6db34392405c/crates/committer/src/patricia_merkle_tree/filled_node.rs#L32)):*
> ```XML
>         }
>     }
> }
> ```

this does not make sense to me; there is no such thing as a "default node".
"default binary node" - I get, ok.
is this used anywhere other than in tests?
if it's only in tests please move this `impl` block to a test module



_Code quote:_
```XML
impl<L: LeafDataTrait> default::Default for FilledNode<L> {
    fn default() -> Self {
        Self {
            hash: HashOutput::default(),
            data: NodeData::Binary(BinaryData::default()),
        }
    }
}
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 72 at r10](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgZrJk76Ir1hAReB88:-NvgaGOL7ZqwQqIeNWeI:b-jlakdj) ([raw file](https://github.com/starkware-libs/committer/blob/63c34b49e1557e9c883d89c7bc6e887b7ec6d442/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L72)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Weird... maybe `None`, for sanity?
</blockquote></details>

ok, yes I think it's worth change the type behind the Mutex from FilledNode to Option<FilledNode>; will remove the need for default, which is problematic on it's own (see above)


<!-- Sent from Reviewable.io -->

2024-04-17 15:13 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 32 at r11](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvg_yEdA745JBG1e3zz:-NvgbBmeATzapu_LB4t5:b8n5amf) ([raw file](https://github.com/starkware-libs/committer/blob/33ae06588fe5d570e554df39191b6db34392405c/crates/committer/src/patricia_merkle_tree/filled_node.rs#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this does not make sense to me; there is no such thing as a "default node".
"default binary node" - I get, ok.
is this used anywhere other than in tests?
if it's only in tests please move this `impl` block to a test module
</blockquote></details>

You wrote to put all the NodeData as default Binary, that's why I did this. I agree, it doesn't make much sense.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 147 at r9](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgYcOL4z2cN_UXMHas:-Nvga9vDE6SAN40i-rHp:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/96125fe7cce8f15f11ec57841e5259006a730efe/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L147)):*
> ```XML
>         //   2. Fill in the hash values.
>         let dummy_filled_tree_map = self.create_filled_tree_map_with_placeholders();
>         let filled_tree_map = Arc::new(dummy_filled_tree_map);
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 72 at r10](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgZrJk76Ir1hAReB88:-Nvg_TII7E5tjH369rbk:b-mrqz5u) ([raw file](https://github.com/starkware-libs/committer/blob/63c34b49e1557e9c883d89c7bc6e887b7ec6d442/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L72)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok, yes I think it's worth change the type behind the Mutex from FilledNode to Option<FilledNode>; will remove the need for default, which is problematic on it's own (see above)
</blockquote></details>

I can add a `None` or `Empty` type to the `NodeData` enum, that would be clearer in my opion. But I think it's better to just put the placeholder according to the type, as it was before.


<!-- Sent from Reviewable.io -->

2024-04-17 15:14 UTC, aner-starkware commented
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 72 at r10](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgZrJk76Ir1hAReB88:-NvgbpqjBkB1XILVqGN1:biee0il) ([raw file](https://github.com/starkware-libs/committer/blob/63c34b49e1557e9c883d89c7bc6e887b7ec6d442/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L72)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I can add a `None` or `Empty` type to the `NodeData` enum, that would be clearer in my opion. But I think it's better to just put the placeholder according to the type, as it was before.
</blockquote></details>

*opinion


<!-- Sent from Reviewable.io -->

2024-04-17 15:19 UTC, aner-starkware commented
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 72 at r10](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgZrJk76Ir1hAReB88:-NvgcdR8Ah8K3l-17ijT:bb1gvqe) ([raw file](https://github.com/starkware-libs/committer/blob/63c34b49e1557e9c883d89c7bc6e887b7ec6d442/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L72)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

*opinion
</blockquote></details>

@amosStarkware , @AvivYossef-starkware , this will also change the `FilledTreeImpl` struct.


<!-- Sent from Reviewable.io -->

2024-04-17 15:22 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 72 at r10](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgZrJk76Ir1hAReB88:-NvgcUlN-UzJEEq7uM1e:bt80l8p) ([raw file](https://github.com/starkware-libs/committer/blob/63c34b49e1557e9c883d89c7bc6e887b7ec6d442/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L72)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

@amosStarkware , @AvivYossef-starkware , this will also change the `FilledTreeImpl` struct.
</blockquote></details>

Either None or a special varaint for an enum is fine by me (None will be more elegant).
That way, you're getting two sanity checks for free:
1. Cannot override an already filled value
2. (next stage) can only read a filled value
I.e., enforce that you filled every value exactly once


<!-- Sent from Reviewable.io -->

2024-04-17 15:23 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 32 at r11](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvg_yEdA745JBG1e3zz:-NvgdlgTDNWLtpY36Cyr:b-2sa64m) ([raw file](https://github.com/starkware-libs/committer/blob/33ae06588fe5d570e554df39191b6db34392405c/crates/committer/src/patricia_merkle_tree/filled_node.rs#L32)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

You wrote to put all the NodeData as default Binary, that's why I did this. I agree, it doesn't make much sense.
</blockquote></details>

it doesn't make sense to implement `Default` on the node. if you want a dummy value currently, construct it explicitly.
implementing the trait indicates "there is a natural default for node", which is wrong
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 72 at r10](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgZrJk76Ir1hAReB88:-NvgdJh20f6z0-rcBqy7:buzd5ga) ([raw file](https://github.com/starkware-libs/committer/blob/63c34b49e1557e9c883d89c7bc6e887b7ec6d442/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L72)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

@amosStarkware , @AvivYossef-starkware , this will also change the `FilledTreeImpl` struct.
</blockquote></details>

I think it makes sense to use the built-in type for "maybe an X": Option<X>.
adding an "empty node" to the NodeData struct means every time we `match` on such an enum, we may panic due to getting an empty node when we don't expect one; this (the compute filled nodes logic) is the only place we could potentially panic (when converting the `Map<NodeIndex, Option<Node>>` to a `FilledTree`), which is OK


<!-- Sent from Reviewable.io -->

2024-04-17 15:37 UTC, aner-starkware commented
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 72 at r10](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgZrJk76Ir1hAReB88:-NvgghN93S9C5akM3ans:b-nto88m) ([raw file](https://github.com/starkware-libs/committer/blob/63c34b49e1557e9c883d89c7bc6e887b7ec6d442/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L72)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think it makes sense to use the built-in type for "maybe an X": Option<X>.
adding an "empty node" to the NodeData struct means every time we `match` on such an enum, we may panic due to getting an empty node when we don't expect one; this (the compute filled nodes logic) is the only place we could potentially panic (when converting the `Map<NodeIndex, Option<Node>>` to a `FilledTree`), which is OK
</blockquote></details>

I don't understand the difference. In both cases, we'll have to check everywhere for this (None \ Empty Node) and return an error in such case.


<!-- Sent from Reviewable.io -->

2024-04-17 15:41 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 104 at r12](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvghlrb-ghze1wP-Ms-:-Nvgi3w5D_tmmOru-D7H:b-xin7w1) ([raw file](https://github.com/starkware-libs/committer/blob/b07a56eaa6ccead4f580fdd6ef24d21a63e6dc77/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L104)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Hmmmm
</blockquote></details>

`let (left_hash, right_hash) = ...`


<!-- Sent from Reviewable.io -->

2024-04-17 15:43 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 104 at r12](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvghlrb-ghze1wP-Ms-:-NvgiQp08QVVG4m5JHDw:bgc5nol) ([raw file](https://github.com/starkware-libs/committer/blob/b07a56eaa6ccead4f580fdd6ef24d21a63e6dc77/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L104)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

`let (left_hash, right_hash) = ...`
</blockquote></details>

And remove this
```
                let mut left_hash = Ok(Default::default());
                let mut right_hash = Ok(Default::default());
```


<!-- Sent from Reviewable.io -->

2024-04-17 15:44 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 72 at r10](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgZrJk76Ir1hAReB88:-Nvgiach0x9bCVvAVAok:b-14xz80) ([raw file](https://github.com/starkware-libs/committer/blob/63c34b49e1557e9c883d89c7bc6e887b7ec6d442/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L72)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I don't understand the difference. In both cases, we'll have to check everywhere for this (None \ Empty Node) and return an error in such case.
</blockquote></details>

More elegant to code it with Option 


<!-- Sent from Reviewable.io -->

2024-04-17 15:54 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 72 at r10](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgZrJk76Ir1hAReB88:-Nvgkq9dERZFjZk5agH8:b4idi5n) ([raw file](https://github.com/starkware-libs/committer/blob/63c34b49e1557e9c883d89c7bc6e887b7ec6d442/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L72)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

More elegant to code it with Option
</blockquote></details>

you won't have to check it everywhere: once you have a FilledTree implementation with an internal `HashMap<NodeIndex, FilledNode>`, you will never need to unwrap or panic because `FilledNode` doesn't have a "None" variant


<!-- Sent from Reviewable.io -->

2024-04-18 07:30 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 32 at r11](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvg_yEdA745JBG1e3zz:-NviE0bN7SyA1lhzG9ag:b-hbzzja) ([raw file](https://github.com/starkware-libs/committer/blob/33ae06588fe5d570e554df39191b6db34392405c/crates/committer/src/patricia_merkle_tree/filled_node.rs#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it doesn't make sense to implement `Default` on the node. if you want a dummy value currently, construct it explicitly.
implementing the trait indicates "there is a natural default for node", which is wrong
</blockquote></details>

OK, got it.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 72 at r10](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgZrJk76Ir1hAReB88:-NviEBCL3UKxz4rG9oZu:bb06d8s) ([raw file](https://github.com/starkware-libs/committer/blob/63c34b49e1557e9c883d89c7bc6e887b7ec6d442/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L72)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you won't have to check it everywhere: once you have a FilledTree implementation with an internal `HashMap<NodeIndex, FilledNode>`, you will never need to unwrap or panic because `FilledNode` doesn't have a "None" variant
</blockquote></details>

Ahh, OK, now I understand. You want the Option to be only inside the function, and not part of the returned value.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 104 at r12](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvghlrb-ghze1wP-Ms-:-NvhHRwk0ku5TIkazIa1:b-rungwj) ([raw file](https://github.com/starkware-libs/committer/blob/b07a56eaa6ccead4f580fdd6ef24d21a63e6dc77/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L104)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

And remove this
```
                let mut left_hash = Ok(Default::default());
                let mut right_hash = Ok(Default::default());
```
</blockquote></details>

Did you check this? It doesn't compile for me, Rust doesn't see any real return value from the join. Maybe you're confusing it with Tokio?


<!-- Sent from Reviewable.io -->

2024-04-18 07:38 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 104 at r12](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvghlrb-ghze1wP-Ms-:-Nvk87E2Cbf0dZcP6ZXx:b-ndrm1c) ([raw file](https://github.com/starkware-libs/committer/blob/b07a56eaa6ccead4f580fdd6ef24d21a63e6dc77/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L104)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Did you check this? It doesn't compile for me, Rust doesn't see any real return value from the join. Maybe you're confusing it with Tokio?
</blockquote></details>

This works for me:
```rust
                let (left_hash, right_hash) = rayon::join(
                    || self.compute_filled_tree_rec::<H, TH>(left_index, Arc::clone(&output_map)),
                    || self.compute_filled_tree_rec::<H, TH>(right_index, Arc::clone(&output_map)),
                );

                let data = NodeData::Binary(BinaryData {
                    left_hash: left_hash?,
                    right_hash: right_hash?,
                });
```


<!-- Sent from Reviewable.io -->

2024-04-18 07:41 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 181 at r13](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvk8aVW5OXyXdgYJWvq:-Nvk8aVX-gSunifeBf9f:b-lmt9b6) ([raw file](https://github.com/starkware-libs/committer/blob/4d124965fb2d49c57ed065540978fa8d7041eec5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L181)):*
> ```XML
> 
>         // Create and return a new FilledTreeImpl from the hashmap.
>         Ok(FilledTreeImpl::new(Self::remove_arc_mutex_and_option(
> ```

I don't know rust but maybe `from` trait would be better here? @dorimedini-starkware 



_Code quote:_
```XML
Ok(FilledTreeImpl::new(Self::remove_arc_mutex_and_option(
```


<!-- Sent from Reviewable.io -->

2024-04-18 07:56 UTC, dorimedini-starkware requested changes
> Reviewed 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 10 at r13](https://reviewable.io/reviews/starkware-libs/committer/43#-NvkAOrQ52NK-jlmW8MN:-NvkAOrQ52NK-jlmW8MO:b-j4tmio) ([raw file](https://github.com/starkware-libs/committer/blob/4d124965fb2d49c57ed065540978fa8d7041eec5/crates/committer/src/patricia_merkle_tree/errors.rs#L10)):*
> ```XML
> pub(crate) enum UpdatedSkeletonTreeError {
>     MissingNode,
>     DoubleUpdate,
> ```

How about adding this data to the error?



_Suggestion:_
```XML
DoubleUpdate { index: NodeIndex, existing_value: FilledNode<Box<dyn LeafDataTrait>> },
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 104 at r12](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvghlrb-ghze1wP-Ms-:-NvkBa5VEKh03pQPsKYl:b-h747u1) ([raw file](https://github.com/starkware-libs/committer/blob/b07a56eaa6ccead4f580fdd6ef24d21a63e6dc77/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L104)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This works for me:
```rust
                let (left_hash, right_hash) = rayon::join(
                    || self.compute_filled_tree_rec::<H, TH>(left_index, Arc::clone(&output_map)),
                    || self.compute_filled_tree_rec::<H, TH>(right_index, Arc::clone(&output_map)),
                );

                let data = NodeData::Binary(BinaryData {
                    left_hash: left_hash?,
                    right_hash: right_hash?,
                });
```
</blockquote></details>

@aner-starkware note that if you have a semicolon at the end of the coroutine you will not see a "return value"
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 94 at r13](https://reviewable.io/reviews/starkware-libs/committer/43#-NvkB2x6DRjFsBQNIy7M:-NvkB2x6DRjFsBQNIy7N:b7tyje6) ([raw file](https://github.com/starkware-libs/committer/blob/4d124965fb2d49c57ed065540978fa8d7041eec5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L94)):*
> ```XML
>                     ))
>                 }
>             };
> ```

does this work?



_Suggestion:_
```XML
            let mut value = value.lock().unwrap_or(
                Err(UpdatedSkeletonTreeError::PoisonedLock("Cannot lock node.".to_owned()))
            )?;
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 99 at r13](https://reviewable.io/reviews/starkware-libs/committer/43#-NvkBKza1q7U13Ol2y9k:-NvkBKza1q7U13Ol2y9l:bkb2id2) ([raw file](https://github.com/starkware-libs/committer/blob/4d124965fb2d49c57ed065540978fa8d7041eec5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L99)):*
> ```XML
>                     hash_map_out.insert(*key, value);
>                 }
>                 None => return Err(UpdatedSkeletonTreeError::MissingNode),
> ```

add the node index as data in MissingNode error



_Suggestion:_
```XML
UpdatedSkeletonTreeError::MissingNode(key)
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 181 at r13](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvk8aVW5OXyXdgYJWvq:-NvkBmvF-a-MhSW0JZGH:b-we0b1m) ([raw file](https://github.com/starkware-libs/committer/blob/4d124965fb2d49c57ed065540978fa8d7041eec5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L181)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I don't know rust but maybe `from` trait would be better here? @dorimedini-starkware
</blockquote></details>

I disagree; I don't think a conversion of `Arc<HashMap<K, Mutex<Option<V>>>>` to a `HashMap<K, V>` is "natural". The knowledge of when and why to lock and unwrap values is coupled to the algorithm, not `FilledTreeImpl`


<!-- Sent from Reviewable.io -->

2024-04-18 08:39 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 181 at r13](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvk8aVW5OXyXdgYJWvq:-NvkM-arE4tsD7S7R6AU:bqqoem6) ([raw file](https://github.com/starkware-libs/committer/blob/4d124965fb2d49c57ed065540978fa8d7041eec5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L181)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I disagree; I don't think a conversion of `Arc<HashMap<K, Mutex<Option<V>>>>` to a `HashMap<K, V>` is "natural". The knowledge of when and why to lock and unwrap values is coupled to the algorithm, not `FilledTreeImpl`
</blockquote></details>

Ok, makes sense


<!-- Sent from Reviewable.io -->

2024-04-18 08:51 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 10 at r13](https://reviewable.io/reviews/starkware-libs/committer/43#-NvkAOrQ52NK-jlmW8MN:-NvkLWYgCOU5fPJMxfcT:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/4d124965fb2d49c57ed065540978fa8d7041eec5/crates/committer/src/patricia_merkle_tree/errors.rs#L10)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

How about adding this data to the error?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 104 at r12](https://reviewable.io/reviews/starkware-libs/committer/43#-Nvghlrb-ghze1wP-Ms-:-NvkGe-t7ej3tfolg8xI:bsi8v3l) ([raw file](https://github.com/starkware-libs/committer/blob/b07a56eaa6ccead4f580fdd6ef24d21a63e6dc77/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L104)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@aner-starkware note that if you have a semicolon at the end of the coroutine you will not see a "return value"
</blockquote></details>

Sorry, my bad.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 94 at r13](https://reviewable.io/reviews/starkware-libs/committer/43#-NvkB2x6DRjFsBQNIy7M:-NvkN_L472steB7NIVa3:b2nteyj) ([raw file](https://github.com/starkware-libs/committer/blob/4d124965fb2d49c57ed065540978fa8d7041eec5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L94)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work?
</blockquote></details>

It compiles, but fails the tests (panic), so... :shrug: 
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 99 at r13](https://reviewable.io/reviews/starkware-libs/committer/43#-NvkBKza1q7U13Ol2y9k:-NvkLnfx4o5jIXH4z7ME:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/4d124965fb2d49c57ed065540978fa8d7041eec5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L99)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add the node index as data in MissingNode error
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-18 09:24 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 18 at r14](https://reviewable.io/reviews/starkware-libs/committer/43#-NvkVawx-BHRdc_X4vu9:-NvkVawx-BHRdc_X4vuA:b5cst73) ([raw file](https://github.com/starkware-libs/committer/blob/950b64a040834e64a6b8e445ecf7cf51fd7a0ac2/crates/committer/src/patricia_merkle_tree/errors.rs#L18)):*
> ```XML
>     DoubleUpdate {
>         index: NodeIndex,
>         existing_value: Box<FilledNode<L>>,
> ```

do you need the box if you're not using `dyn LeafDataTrait`? size should be known at compile time if you're using a generic



_Code quote:_
```XML
Box<FilledNode<L>>
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 94 at r13](https://reviewable.io/reviews/starkware-libs/committer/43#-NvkB2x6DRjFsBQNIy7M:-NvkW2xoE-5r_1D5pRS1:bpawgu5) ([raw file](https://github.com/starkware-libs/committer/blob/4d124965fb2d49c57ed065540978fa8d7041eec5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L94)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

It compiles, but fails the tests (panic), so... :shrug:
</blockquote></details>

why does it panic...? maybe `unwrap_or_else`?


<!-- Sent from Reviewable.io -->

2024-04-18 10:48 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-04-18 12:07 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-04-18 12:09 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 18 at r14](https://reviewable.io/reviews/starkware-libs/committer/43#-NvkVawx-BHRdc_X4vu9:-NvkbynmDNNuLOBUiHVu:b-ypvo7p) ([raw file](https://github.com/starkware-libs/committer/blob/950b64a040834e64a6b8e445ecf7cf51fd7a0ac2/crates/committer/src/patricia_merkle_tree/errors.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do you need the box if you're not using `dyn LeafDataTrait`? size should be known at compile time if you're using a generic
</blockquote></details>

It didn't compile without it (something about error being too big):
`the  Err -variant returned from this function is very large  
try reducing the size of ..., for example by boxing large elements or replacing it with Box...`
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 94 at r13](https://reviewable.io/reviews/starkware-libs/committer/43#-NvkB2x6DRjFsBQNIy7M:-Nvkl_k8C0NEKeF6FbIC:b-rl6ds4) ([raw file](https://github.com/starkware-libs/committer/blob/4d124965fb2d49c57ed065540978fa8d7041eec5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L94)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why does it panic...? maybe `unwrap_or_else`?
</blockquote></details>

I couldn't make it compile :disappointed: I think maybe what you want is simply `?` and to implement the `from` for the error, but that would require someone with more understanding of Rust than me...


<!-- Sent from Reviewable.io -->

2024-04-18 12:21 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 94 at r13](https://reviewable.io/reviews/starkware-libs/committer/43#-NvkB2x6DRjFsBQNIy7M:-Nvl8sfv28bjTnXbGBKN:b-wbz2mf) ([raw file](https://github.com/starkware-libs/committer/blob/4d124965fb2d49c57ed065540978fa8d7041eec5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L94)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I couldn't make it compile :disappointed: I think maybe what you want is simply `?` and to implement the `from` for the error, but that would require someone with more understanding of Rust than me...
</blockquote></details>

ok, this compiles for me:
```
            let mut value = value.lock().map_err(|_| {
                UpdatedSkeletonTreeError::PoisonedLock("Cannot lock node.".to_owned())
            })?;
```


<!-- Sent from Reviewable.io -->

2024-04-18 12:24 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 94 at r13](https://reviewable.io/reviews/starkware-libs/committer/43#-NvkB2x6DRjFsBQNIy7M:-Nvl9TO481eqrbpdeMJy:b-87y4wx) ([raw file](https://github.com/starkware-libs/committer/blob/4d124965fb2d49c57ed065540978fa8d7041eec5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L94)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok, this compiles for me:
```
            let mut value = value.lock().map_err(|_| {
                UpdatedSkeletonTreeError::PoisonedLock("Cannot lock node.".to_owned())
            })?;
```
</blockquote></details>

Yep, you're right :sweat_smile: 


<!-- Sent from Reviewable.io -->

2024-04-18 12:41 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @AvivYossef-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-04-18 12:41 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43#-:-NvlDZ9-5SrEqZLg3ay1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @AvivYossef-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-04-18 13:57 UTC, aner-starkware commented
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 72 at r10](https://reviewable.io/reviews/starkware-libs/committer/43#-NvgZrJk76Ir1hAReB88:-NvlUnfe0vJcJYobbpJ8:b-5z85nw) ([raw file](https://github.com/starkware-libs/committer/blob/63c34b49e1557e9c883d89c7bc6e887b7ec6d442/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L72)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Ahh, OK, now I understand. You want the Option to be only inside the function, and not part of the returned value.
</blockquote></details>

@Yoni-Starkware ?


<!-- Sent from Reviewable.io -->

2024-04-18 14:00 UTC, dorimedini-starkware approved these changes
> Reviewed 4 of 4 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @AvivYossef-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-04-18 14:18 UTC, Yoni-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/43)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware, @AvivYossef-starkware, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-04-18 14:28 UTC, merged