Added tentative tree API.
starkware-libs/committer pull request #6
Opened 2024-03-24 17:16 UTC by amosStarkware

2024-03-24 17:56 UTC, amosStarkware reviewed
+reviewer:@dorimedini-starkware 
the commit linter test seems to be broken - I  changed the commit message multiple times but the commit linter test is failing on some past message:
actual message - "build: add tentative tree API"
message on which test is failing - "Added tentative tree API."

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6#-:-NtlYuXc-64cOeJ8ejKS:blv3d7)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-03-24 20:31 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/lib.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntm8w_X59lO5yz9VxSw:-Ntm8w_X59lO5yz9VxSx:bt6trpt) ([raw file](https://github.com/starkware-libs/committer/blob/217642448d0ae8a18200c7a08352bd74e023d1eb/crates/committer/src/lib.rs#L17)):*
> ```XML
>         assert_eq!(dummy(), 7);
>     }
> }
> ```

now that we have actual code: delete this :)
unless nothing is public yet, which will cause cargo to complain... in which case, keep it
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntm6za7Ex1Myop1bxOw:-Ntm6za7Ex1Myop1bxOx:b-9ibn1x) ([raw file](https://github.com/starkware-libs/committer/blob/217642448d0ae8a18200c7a08352bd74e023d1eb/crates/committer/src/patricia_merkle_tree/node.rs#L1)):*
> ```XML
> pub struct Node {}
> ```

let's use `pub(crate)` instead of `pub` by default; we can decide what to expose as public API later



_Suggestion:_
```XML
pub(crate) struct Node {}
```
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntm8_7EEYCjKjfvzjEK:-Ntm8_7EEYCjKjfvzjEL:bslcmzg) ([raw file](https://github.com/starkware-libs/committer/blob/217642448d0ae8a18200c7a08352bd74e023d1eb/crates/committer/src/patricia_merkle_tree/tree.rs#L5)):*
> ```XML
> trait Tree {
>     /// Returns the node with given full (Merkle) index, if it exists.
>     fn get_node(full_index: u128) -> Option<Node>;
> ```

1. I want to avoid using primitive types (like `u128`) directly; please use a wrapper type named `NodeIndex`.
2. 128 bits are not enough to encode an index in a state tree (of depth 251)



_Code quote:_
```XML
full_index: u128
```
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntm7RAg6ivKNqEI2lv8:-Ntm7RAg6ivKNqEI2lv9:b-dhmbk8) ([raw file](https://github.com/starkware-libs/committer/blob/217642448d0ae8a18200c7a08352bd74e023d1eb/crates/committer/src/patricia_merkle_tree/tree.rs#L11)):*
> ```XML
> 
>     /// Computes the hash of the given node.
>     fn compute_hash(node: Node) -> [u8; 32];
> ```

1. Define a `NodeValue` or `HashOutput` tuple struct for this, so we have our own wrapper type that can be changed later
2. Instead of `[u8; 32]`, use `pathfinder_crypto::Felt` instead (see [here](https://reviewable.io/reviews/starkware-libs/committer/4) for Aner's work using it). We may change it later but better to start with our best guess
```
struct NodeValue(pathfinder_crypto::Felt)
```



_Suggestion:_
```XML
NodeValue
```
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntm79WwBrM6I_ixstQ2:-Ntm79WwBrM6I_ixstQ3:b-zgq3vd) ([raw file](https://github.com/starkware-libs/committer/blob/217642448d0ae8a18200c7a08352bd74e023d1eb/crates/committer/src/patricia_merkle_tree/tree.rs#L12)):*
> ```XML
>     /// Computes the hash of the given node.
>     fn compute_hash(node: Node) -> [u8; 32];
> }
> ```

WDYT about making `Node` a trait as well? So we don't need to decide the data yet (we may decide to have a node aware of it's height, or maybe not, depending on implementation of things like `get_children()` on a node etc.)



_Suggestion:_
```XML
trait<N: Node> Tree {
    /// Returns the node with given full (Merkle) index, if it exists.
    fn get_node(full_index: u128) -> Option<N>;

    /// Returns the root if the tree is not empty.
    fn get_root() -> Option<N>;

    /// Computes the hash of the given node.
    fn compute_hash(node: N) -> [u8; 32];
}
```


<!-- Sent from Reviewable.io -->

2024-03-24 20:40 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/committer/6#-NtmB98nBuDrUcWlQG-C:-NtmB98nBuDrUcWlQG-D:b-6t6a1o) ([raw file](https://github.com/starkware-libs/committer/blob/217642448d0ae8a18200c7a08352bd74e023d1eb/crates/committer/src/patricia_merkle_tree/tree.rs#L11)):*
> ```XML
> 
>     /// Computes the hash of the given node.
>     fn compute_hash(node: Node) -> [u8; 32];
> ```

This should be a method of the `Node` trait (once you make it a trait), not an associated function of a tree.



_Code quote:_
```XML
    /// Computes the hash of the given node.
    fn compute_hash(node: Node) -> [u8; 32];
```
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntm79WwBrM6I_ixstQ2:-NtmBFZCAcOX75a7SrAD:b-6rzvm3) ([raw file](https://github.com/starkware-libs/committer/blob/217642448d0ae8a18200c7a08352bd74e023d1eb/crates/committer/src/patricia_merkle_tree/tree.rs#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYT about making `Node` a trait as well? So we don't need to decide the data yet (we may decide to have a node aware of it's height, or maybe not, depending on implementation of things like `get_children()` on a node etc.)
</blockquote></details>

More on this: how about
1. a `HashInput` type (three Felts) 
2. a `HashFunction` trait with a `hash(i: HashInput) -> HashOutput` associated function
3. Make the `Node` trait a templated trait: `trait<H: HashFunction> Node { ... }`
4. Make `Tree` double-templated: `trait<N: Node, H: HashFunction> Tree { ... }`, and whenever you want to use a `Node` type in the `Tree` trait use `N<H>`

WDYT?


<!-- Sent from Reviewable.io -->

2024-03-25 09:38 UTC, amosStarkware reviewed
Changed the title, as you suggested

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6#-:-Ntoxm3g0S8d5Qr9hYe0:b-j6wwio)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/lib.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntm8w_X59lO5yz9VxSw:-NtoVjZQ6VeL-qEEXJmt:b-fod36v) ([raw file](https://github.com/starkware-libs/committer/blob/217642448d0ae8a18200c7a08352bd74e023d1eb/crates/committer/src/lib.rs#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

now that we have actual code: delete this :)
unless nothing is public yet, which will cause cargo to complain... in which case, keep it
</blockquote></details>

I had to replace this with other dummy code, because Rust complained about unused fields
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntm6za7Ex1Myop1bxOw:-NtoYZR63Bp3pL3eqITd:b-yfv5lc) ([raw file](https://github.com/starkware-libs/committer/blob/217642448d0ae8a18200c7a08352bd74e023d1eb/crates/committer/src/patricia_merkle_tree/node.rs#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

let's use `pub(crate)` instead of `pub` by default; we can decide what to expose as public API later
</blockquote></details>

Changed to a trait and done
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntm8_7EEYCjKjfvzjEK:-Ntoboei8qMNSCcDMadG:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/217642448d0ae8a18200c7a08352bd74e023d1eb/crates/committer/src/patricia_merkle_tree/tree.rs#L5)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. I want to avoid using primitive types (like `u128`) directly; please use a wrapper type named `NodeIndex`.
2. 128 bits are not enough to encode an index in a state tree (of depth 251)
</blockquote></details>

Done
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntm7RAg6ivKNqEI2lv8:-NtoechnBFkkG2HLUHD0:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/217642448d0ae8a18200c7a08352bd74e023d1eb/crates/committer/src/patricia_merkle_tree/tree.rs#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. Define a `NodeValue` or `HashOutput` tuple struct for this, so we have our own wrapper type that can be changed later
2. Instead of `[u8; 32]`, use `pathfinder_crypto::Felt` instead (see [here](https://reviewable.io/reviews/starkware-libs/committer/4) for Aner's work using it). We may change it later but better to start with our best guess
```
struct NodeValue(pathfinder_crypto::Felt)
```
</blockquote></details>

Done
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/committer/6#-NtmB98nBuDrUcWlQG-C:-Ntog3hEBsfAhg-Nl0bP:b-mxp9f2) ([raw file](https://github.com/starkware-libs/committer/blob/217642448d0ae8a18200c7a08352bd74e023d1eb/crates/committer/src/patricia_merkle_tree/tree.rs#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

This should be a method of the `Node` trait (once you make it a trait), not an associated function of a tree.
</blockquote></details>

Done. (though IMO it makes sense for it to be a tree method, because the hash function can be seen as a tree attribute)
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntm79WwBrM6I_ixstQ2:-NtooODZEn_zqPCHgPEI:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/217642448d0ae8a18200c7a08352bd74e023d1eb/crates/committer/src/patricia_merkle_tree/tree.rs#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

More on this: how about
1. a `HashInput` type (three Felts) 
2. a `HashFunction` trait with a `hash(i: HashInput) -> HashOutput` associated function
3. Make the `Node` trait a templated trait: `trait<H: HashFunction> Node { ... }`
4. Make `Tree` double-templated: `trait<N: Node, H: HashFunction> Tree { ... }`, and whenever you want to use a `Node` type in the `Tree` trait use `N<H>`

WDYT?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-25 10:05 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/Cargo.toml` line 16 at r3](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntp3Q7d06hijVW0RSWc:-Ntp3Q7d06hijVW0RSWd:b-eluihw) ([raw file](https://github.com/starkware-libs/committer/blob/db632ea545432319f0eb4ee6ca76eda3d0c3a065/crates/committer/Cargo.toml#L16)):*
> ```TOML
> 
> [dependencies]
> pathfinder-crypto = { git = "https://github.com/eqlabs/pathfinder.git"}
> ```

1. @amosStarkware add a version explicitly
2. @ArielElp I can't find this crate on crates.io, is it published? if not, why not?



_Code quote:_
```TOML
pathfinder-crypto = { git = "https://github.com/eqlabs/pathfinder.git"}
```
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntp2OsJ7zAr3o_bLwRh:-Ntp2OsJ7zAr3o_bLwRi:b-56vcrl) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/node.rs#L3)):*
> ```XML
> use pathfinder_crypto::Felt;
> 
> use super::hash::HashFunction;
> ```

do not use `super::` in imports unless you have the following scenario:
```
// some_module.rs
#[cfg(test)]
pub mod some_test;

// some_test.rs
use super::*;
```
i.e., if you define a test *in* a module, you can `use super::*` in the test to get all the modules' objects.



_Suggestion:_
```XML
crate
```
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/committer/6#-NtmB98nBuDrUcWlQG-C:-Ntp306F4Np_RJUzjNW2:b-bcyy6l) ([raw file](https://github.com/starkware-libs/committer/blob/217642448d0ae8a18200c7a08352bd74e023d1eb/crates/committer/src/patricia_merkle_tree/tree.rs#L11)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Done. (though IMO it makes sense for it to be a tree method, because the hash function can be seen as a tree attribute)
</blockquote></details>

yes, but you propagate the hash function type via templating, so it's all good. since hashing doesn't need the entire tree context, and only a node (provided the hash function is set), it should be a node method


<!-- Sent from Reviewable.io -->

2024-03-25 14:18 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-NtpyJs07NzXKJNX8Q4W:-NtpyJs07NzXKJNX8Q4X:b-7ropln) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/tree.rs#L3)):*
> ```XML
> use crate::patricia_merkle_tree::node::Node;
> 
> use super::{hash::HashFunction, node::NodeIndex};
> ```

ditto



_Suggestion:_
```XML
crate
```


<!-- Sent from Reviewable.io -->

2024-03-25 14:21 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 8 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntpycey24Htki5hJiH5:-Ntpycey24Htki5hJiH6:bkj3rkx) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/node.rs#L8)):*
> ```XML
> 
> // TODO(Amos, 26/3/2024): Define trait's methods.
> pub(crate) trait Node<H: HashFunction> {}
> ```

1. Am I right in thinking these should be methods on a node? @amosStarkware @TzahiTaub 
2. Do we need to abstract the concept of `NodeValue`, since edge nodes have two felt values, and other nodes have one? @TzahiTaub 



_Suggestion:_
```XML
pub(crate) trait NodeValue {}

pub(crate) trait Node<H: HashFunction, V: NodeValue> {
    pub(crate) fn get_hash_function(&self) -> H;
    
    pub(crate) fn compute_node_value(&self) -> V;
}
```


<!-- Sent from Reviewable.io -->

2024-03-25 14:38 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/patricia_merkle_tree/hash.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntq1spJ9ktxd7A7xu68:-Ntq1spJ9ktxd7A7xu69:b-aaz0kg) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/hash.rs#L3)):*
> ```XML
> use pathfinder_crypto::Felt;
> 
> pub(crate) struct HashInput(pub Felt, pub Felt, pub Felt);
> ```

Since we want to be able to swap out the Felt type we use in the future, please wrap it in an internal type and use it everywhere



_Suggestion:_
```XML
use pathfinder_crypto::Felt;

pub(crate) type CommitterFelt = Felt;

pub(crate) struct HashInput(pub CommitterFelt, pub CommitterFelt, pub CommitterFelt);
```


<!-- Sent from Reviewable.io -->

2024-03-25 14:41 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/patricia_merkle_tree/hash.rs` line 0 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntq2VjS7F6vNwlKi1P7:-Ntq2VjS7F6vNwlKi1P8:b-p0fdrw) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/hash.rs#L0)):*
consider moving this module into `src/hash/types.rs`, I don't feel this belongs in `patricia_merkle_tree`. WDYT?


<!-- Sent from Reviewable.io -->

2024-03-25 15:12 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 8 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntpycey24Htki5hJiH5:-Ntq9QV65o_YQ-apSGFu:bkgnjy7) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/node.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. Am I right in thinking these should be methods on a node? @amosStarkware @TzahiTaub 
2. Do we need to abstract the concept of `NodeValue`, since edge nodes have two felt values, and other nodes have one? @TzahiTaub
</blockquote></details>

correction:
1. No need for `get_hash_function`; we can simply use `H::compute_hash` when needed
2. Better to make `compute_node_value` an `async fn`, not a `fn`
3. traits do not specify specific method scopes (replace `pub(crate) fn` with `fn`)
```
pub(crate) trait NodeValue {}

pub(crate) trait Node<H: HashFunction, V: NodeValue> {
    async fn compute_node_value(&self) -> V;
}
```


<!-- Sent from Reviewable.io -->

2024-03-25 21:03 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 8 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntpycey24Htki5hJiH5:-NtrP0tM8qecQoXEzvGZ:bgvxcdo) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/node.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

correction:
1. No need for `get_hash_function`; we can simply use `H::compute_hash` when needed
2. Better to make `compute_node_value` an `async fn`, not a `fn`
3. traits do not specify specific method scopes (replace `pub(crate) fn` with `fn`)
```
pub(crate) trait NodeValue {}

pub(crate) trait Node<H: HashFunction, V: NodeValue> {
    async fn compute_node_value(&self) -> V;
}
```
</blockquote></details>

I'm not sure I follow, but edge and binary nodes have two felt values (edge also has the length byte), a leaf has 1, and empty has none, I guess. How do we plan to use the NodeValue abstraction without specifying the concrete type?


<!-- Sent from Reviewable.io -->

2024-03-26 08:02 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 8 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntpycey24Htki5hJiH5:-NttlBuR8apS_LcnfXDu:b-lfwc9h) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/node.rs#L8)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I'm not sure I follow, but edge and binary nodes have two felt values (edge also has the length byte), a leaf has 1, and empty has none, I guess. How do we plan to use the NodeValue abstraction without specifying the concrete type?
</blockquote></details>

Like this maybe?
```
// Trait
trait NodeValueTrait {
    fn some_fn(...) -> ...;
}

// Concrete type
enum NodeValue {
    Binary { left: CommitterFelt, right: CommitterFelt },
    Edge { path: CommitterFelt, bottom: CommitterFelt, length: CommitterFelt },
    Leaf(CommitterFelt),
}

impl NodeValueTrait for NodeValue {
    fn some_fn(...) {
        // Specific logic per variant
        match self {
            Binary(left, right) => ...
            ...
        }
    }
}
```


<!-- Sent from Reviewable.io -->

2024-03-26 08:26 UTC, aner-starkware commented
*[`crates/committer/src/patricia_merkle_tree/hash.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntq1spJ9ktxd7A7xu68:-NttrG3nCSFhoE9Mx5CS:b-ui1yls) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/hash.rs#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Since we want to be able to swap out the Felt type we use in the future, please wrap it in an internal type and use it everywhere
</blockquote></details>

Don't the three hash inputs represent different types?


<!-- Sent from Reviewable.io -->

2024-03-26 08:32 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/hash.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntq1spJ9ktxd7A7xu68:-Nttsi6cDouSzfnAz0oM:bciod6b) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/hash.rs#L3)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Don't the three hash inputs represent different types?
</blockquote></details>

Any input to Pathfinder's pedersen hash is a `pathfinder_crypto::Felt`, not sure what you mean?


<!-- Sent from Reviewable.io -->

2024-03-26 09:04 UTC, aner-starkware commented
*[`crates/committer/src/patricia_merkle_tree/hash.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntq1spJ9ktxd7A7xu68:-NttxPJA1A09xBnzWz5U:b-we80vf) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/hash.rs#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Any input to Pathfinder's pedersen hash is a `pathfinder_crypto::Felt`, not sure what you mean?
</blockquote></details>

Now I'm a bit confused - is `Hash` = `pedersen_hash`? Because Pedersen hash has 2 Felts as input, why is the input determined to be 3? If it's a wrapper, then maybe it makes more sense for the types to indicate where they come from and not how they are used?


<!-- Sent from Reviewable.io -->

2024-03-26 09:24 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/hash.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntq1spJ9ktxd7A7xu68:-Ntu3Y-K83KPqYWAyT5j:b9wsvos) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/hash.rs#L3)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Now I'm a bit confused - is `Hash` = `pedersen_hash`? Because Pedersen hash has 2 Felts as input, why is the input determined to be 3? If it's a wrapper, then maybe it makes more sense for the types to indicate where they come from and not how they are used?
</blockquote></details>

1. It's a wrapper that defines how hash inputs *must* look like. If you implement an edge node, you will need to define explicit conversion from the edge node to a hash input - this is fine.
2. Our hash function may be `hash(x,y,z)=pedersen(pedersen(x,y),z)`, need to read the spec and the existing code


<!-- Sent from Reviewable.io -->

2024-03-26 10:55 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/hash.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntq1spJ9ktxd7A7xu68:-NtuO_fy8U8utPDYc41O:bhwfngd) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/hash.rs#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. It's a wrapper that defines how hash inputs *must* look like. If you implement an edge node, you will need to define explicit conversion from the edge node to a hash input - this is fine.
2. Our hash function may be `hash(x,y,z)=pedersen(pedersen(x,y),z)`, need to read the spec and the existing code
</blockquote></details>

After discussion with Aner - we need to investigate this. Discussion in slack


<!-- Sent from Reviewable.io -->

2024-03-26 11:50 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/hash.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntq1spJ9ktxd7A7xu68:-Ntu_vMZ52JVAon4QgBX:bz4k4uk) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/hash.rs#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

After discussion with Aner - we need to investigate this. Discussion in slack
</blockquote></details>

I think maybe `HashInput` should be a `trait`, because it is indeed different depending on the type of node we're computing... something like:
```
pub(crate) trait HashInput {};

pub(crate) trait<I: HashInput> HashFunction {
    fn compute_hash(i: I) -> HashOutput;
}
```
WDYT @aner-starkware ?


<!-- Sent from Reviewable.io -->

2024-03-26 11:57 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/hash.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntq1spJ9ktxd7A7xu68:-NtubdnJ-2xZI_pIX4FC:bv802vz) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/hash.rs#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think maybe `HashInput` should be a `trait`, because it is indeed different depending on the type of node we're computing... something like:
```
pub(crate) trait HashInput {};

pub(crate) trait<I: HashInput> HashFunction {
    fn compute_hash(i: I) -> HashOutput;
}
```
WDYT @aner-starkware ?
</blockquote></details>

mmm... also not so great... because then the `Tree` will need several `HashFunction` type parameters, one for each hash input type...
perhaps better to define
```
pub(crate) trait HashFunction {
    fn<N: Node> compute_hash(node: N) -> HashOutput;
}
```


<!-- Sent from Reviewable.io -->

2024-03-26 12:23 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/hash.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntq1spJ9ktxd7A7xu68:-Ntuefr01-GOwgwsPeWt:b-lm2lq8) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/hash.rs#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

mmm... also not so great... because then the `Tree` will need several `HashFunction` type parameters, one for each hash input type...
perhaps better to define
```
pub(crate) trait HashFunction {
    fn<N: Node> compute_hash(node: N) -> HashOutput;
}
```
</blockquote></details>

e.g. the `Node` trait can require a `fn hash_input_chain(&self) -> Iterator<CommitterFelt>` which outputs the hash inputs one by one


<!-- Sent from Reviewable.io -->

2024-03-26 16:45 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: 2 of 9 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/hash.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntq1spJ9ktxd7A7xu68:-NtvdblVDxkOqiGFHKwp:biluyy7) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/hash.rs#L3)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

isn't it better for the node to use the hash function itself?
i.e., for a node Node<H: hash>, there will be a method `compute_hash` that uses `H` to compute its own hash.
regarding the `CommiterFelt` type - done, added a types module in the src directory.
should `HashOutput` also be an alias to `Felt` instead of a struct?
</blockquote></details>

instead of `compute_hash` I called it `get_value`.


<!-- Sent from Reviewable.io -->

2024-03-26 17:34 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: 2 of 9 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/hash.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntq1spJ9ktxd7A7xu68:-NtvogUj8T16RFyeEHK4:b-29ng57) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/hash.rs#L3)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

instead of `compute_hash` I called it `get_value`.
</blockquote></details>

scratch that.
called it `compute_and_set_hash`


<!-- Sent from Reviewable.io -->

2024-03-27 08:51 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: 2 of 9 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/hash.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/committer/6#-Ntq1spJ9ktxd7A7xu68:-Ntz5ggh2KsKZVazZgrh:b-8c3i30) ([raw file](https://github.com/starkware-libs/committer/blob/641c39945dfaf1718051215eb789b5886005e1f3/crates/committer/src/patricia_merkle_tree/hash.rs#L3)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

scratch that.
called it `compute_and_set_hash`
</blockquote></details>

scratch that, called it `set_value`


<!-- Sent from Reviewable.io -->

2024-03-27 10:05 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 12 at r6](https://reviewable.io/reviews/starkware-libs/committer/6#-NtzMRfG1am_XIrJ_8cY:-NtzMRfH2dA8te0VpZm-:bldti1j) ([raw file](https://github.com/starkware-libs/committer/blob/291602a4c7dd8de8bea4e2a8028a64a2384abcef/crates/committer/src/patricia_merkle_tree/tree.rs#L12)):*
> ```XML
> 
>     /// Returns the root if the tree is not empty.
>     fn get_root(&mut self) -> Option<&mut N>;
> ```

1. you can default-impl this, right?
2. why `mut`?



_Suggestion:_
```XML
    /// Returns the node with given full (Merkle) index, if it exists.
    fn get_node(&self, full_index: NodeIndex) -> Option<&N>;

    /// Returns the root if the tree is not empty.
    fn get_root(&self) -> Option<&N> {
        self.get_node(NodeIndex(CommitterFelt::ONE))
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 18 at r6](https://reviewable.io/reviews/starkware-libs/committer/6#-NtzMADmB86Ie_O1HHyd:-NtzMADmB86Ie_O1HHye:b-4pkrws) ([raw file](https://github.com/starkware-libs/committer/blob/291602a4c7dd8de8bea4e2a8028a64a2384abcef/crates/committer/src/patricia_merkle_tree/tree.rs#L18)):*
> ```XML
> 
>     /// Returns all nodes added or modified in the last update.
>     fn get_all_new_or_modified_nodes(&self) -> Map<NodeIndex, &N>;
> ```

I think it would be more efficient to combine these functions; maybe we can save a tree traversal



_Suggestion:_
```XML
    /// Updates tree in place with given leaves. Returns all nodes added or modified in the last update.
    fn update_and_get_modified(&mut self, index_to_updated_leaf: Map<NodeIndex, &N>) -> Map<NodeIndex, &N>;
```


<!-- Sent from Reviewable.io -->

2024-03-27 10:06 UTC, dorimedini-starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-03-28 08:40 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 12 at r6](https://reviewable.io/reviews/starkware-libs/committer/6#-NtzMRfG1am_XIrJ_8cY:-NtzzFw01kN4gdiulmpi:b-e9h7k0) ([raw file](https://github.com/starkware-libs/committer/blob/291602a4c7dd8de8bea4e2a8028a64a2384abcef/crates/committer/src/patricia_merkle_tree/tree.rs#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. you can default-impl this, right?
2. why `mut`?
</blockquote></details>

Root needs to be `mut` because it's now used in the method which computes and sets that hashes.
I deleted `get_node`
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 18 at r6](https://reviewable.io/reviews/starkware-libs/committer/6#-NtzMADmB86Ie_O1HHyd:-NtzzHvt7jaOa0UZrl5C:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/291602a4c7dd8de8bea4e2a8028a64a2384abcef/crates/committer/src/patricia_merkle_tree/tree.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think it would be more efficient to combine these functions; maybe we can save a tree traversal
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-28 09:23 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 8 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 5 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3L7cZ-iFnLihOlvSB:-Nu3L7cZ-iFnLihOlvSC:buvfzo5) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/errors.rs#L5)):*
> ```XML
> pub enum HashComputationError {
>     EmptyTree,
> }
> ```

We should be able to commit to an empty tree; why is hashing an empty tree an error?



_Code quote:_
```XML
// TODO(Amos, 01/04/2024): Add HashComputationError types.
#[derive(Debug)]
pub enum HashComputationError {
    EmptyTree,
}
```
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 29 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3LOsq3UWUiT3NU6z_:-Nu3LOsq3UWUiT3NU6za:batb8dw) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/node.rs#L29)):*
> ```XML
>     Hash(HashOutput),
>     LeafValue(LeafValue),
> }
> ```

the bottom of an edge is always either a binary node or a leaf



_Suggestion:_
```XML
#[allow(dead_code)]
pub(crate) enum BottomValue {
    BinaryValue(HashOutput),
    LeafValue(LeafValue),
}
```
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 35 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3LcKg7Ac-YGhfIFIL:-Nu3LcKg7Ac-YGhfIFIM:bmu840j) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/node.rs#L35)):*
> ```XML
>     pub path: CommitterFelt,
>     pub length: CommitterFelt,
> }
> ```

wrap path and length in their own types; way may need to perform arithmetic/bitwise manipulations on these, I would like it abstracted



_Suggestion:_
```XML
#[allow(dead_code)]
pub(crate) struct PathToBottom {
    pub path: EdgePath,
    pub length: EdgeLength,
}
```
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 42 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3LtKiBU-QUQu0Oc2X:-Nu3LtKiBU-QUQu0Oc2Y:bygecel) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/node.rs#L42)):*
> ```XML
>     CompiledClassHash(CommitterFelt),
>     StateTreeValue {
>         class_hash: CommitterFelt,
> ```

import this type from starknet-api



_Suggestion:_
```XML
ClassHash
```
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 44 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3Ly4A0A7Pw6-xlnVr:-Nu3Ly4A0A7Pw6-xlnVs:bygecel) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/node.rs#L44)):*
> ```XML
>         class_hash: CommitterFelt,
>         contract_state_root_hash: CommitterFelt,
>         nonce: CommitterFelt,
> ```

import this type from starknet-api



_Suggestion:_
```XML
Nonce
```
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 50 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3M38k8RImegq_aipV:-Nu3M38k8RImegq_aipW:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/node.rs#L50)):*
> ```XML
> pub(crate) trait Node<H: HashFunction> {
>     /// Traverses sub-tree and computes & sets all nodes' hashes and values, if possible.
>     /// If successful of if hash and value of node are already set - returns hash.
> ```

typo



_Suggestion:_
```XML
If successful or if hash and value of node are already set - returns hash.
```
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 15 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3MHmT9VZuesgmtLdD:-Nu3MHmT9VZuesgmtLdE:bksufrx) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/tree.rs#L15)):*
> ```XML
>             return root.compute_and_set_hash_and_value_recursively();
>         }
>         Err(HashComputationError::EmptyTree)
> ```

We should be able to commit to an empty tree.
Check the main repo's code to find the value of an empty tree, define it in this repo and return it here



_Code quote:_
```XML
Err(HashComputationError::EmptyTree)
```
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 25 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3MkS1EcOTkTaCHDo9:-Nu3MkS1EcOTkTaCHDoA:b-eg8fhk) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/tree.rs#L25)):*
> ```XML
>         &mut self,
>         index_to_updated_leaf: Map<NodeIndex, &N>,
>     ) -> Map<NodeIndex, &N>;
> ```

this mapping needs to include the node type; we store nodes in fact storage using the type to determine the key prefix.
Does the `Node` trait include a `type()` method?
Is there a way to discern the type of the node without this method?



_Code quote:_
```XML
) -> Map<NodeIndex, &N>;
```


<!-- Sent from Reviewable.io -->

2024-03-28 10:57 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 5 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3L7cZ-iFnLihOlvSB:-Nu3Ng4SD_gaA-n3yF_u:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/errors.rs#L5)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

We should be able to commit to an empty tree; why is hashing an empty tree an error?
</blockquote></details>

Done
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 29 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3LOsq3UWUiT3NU6z_:-Nu3OcdG5KBUS1KtSBCT:b-7ql1td) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/node.rs#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the bottom of an edge is always either a binary node or a leaf
</blockquote></details>

fixed
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 35 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3LcKg7Ac-YGhfIFIL:-Nu3Qg276oHNbUkKnYyz:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/node.rs#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

wrap path and length in their own types; way may need to perform arithmetic/bitwise manipulations on these, I would like it abstracted
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 42 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3LtKiBU-QUQu0Oc2X:-Nu3UehS41KjT0bXG60K:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/node.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

import this type from starknet-api
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 44 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3Ly4A0A7Pw6-xlnVr:-Nu3Uf8JA4FqvQG8j8iJ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/node.rs#L44)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

import this type from starknet-api
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 15 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3MHmT9VZuesgmtLdD:-Nu3gqHR6wSSFIULF6G-:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/tree.rs#L15)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

We should be able to commit to an empty tree.
Check the main repo's code to find the value of an empty tree, define it in this repo and return it here
</blockquote></details>

Done
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 25 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3MkS1EcOTkTaCHDo9:-Nu3NPcU72344KzCz2Ma:byi6o7b) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/tree.rs#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this mapping needs to include the node type; we store nodes in fact storage using the type to determine the key prefix.
Does the `Node` trait include a `type()` method?
Is there a way to discern the type of the node without this method?
</blockquote></details>

the type can be discerned with the `get_value` method, because the value type depends on the type 


<!-- Sent from Reviewable.io -->

2024-03-28 11:30 UTC, dorimedini-starkware requested changes
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 5 at r8](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3L7cZ-iFnLihOlvSB:-Nu3oswN2COWPpAqm3rO:bj7i4gs) ([raw file](https://github.com/starkware-libs/committer/blob/d2a2bd627a86fa36e546c988aafe2da7e3602b32/crates/committer/src/patricia_merkle_tree/errors.rs#L5)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Done
</blockquote></details>

remove this `EmptyTree` enum variant
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 51 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3nLyF7vFGei4C2SlG:-Nu3nLyF7vFGei4C2SlH:btybrdm) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L51)):*
> ```XML
>     StateTreeValue {
>         class_hash: ClassHash,
>         contract_state_root_hash: CommitterFelt,
> ```

now that I think of it: a `StateRoot(CommitterFelt)` type would be handy, so we don't mix general node hashes with tree roots



_Code quote:_
```XML
contract_state_root_hash: CommitterFelt
```
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 61 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3nkivEC6999LprZLp:-Nu3nkivEC6999LprZLq:bsyvda8) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L61)):*
> ```XML
>     fn compute_and_set_hash_and_value_recursively(
>         &mut self,
>     ) -> Result<HashOutput, HashComputationError>;
> ```

rename to the specific reason *this* method should fail - a `HashComputationError` sounds like an error coming from the `HashFunction` implementation, not the `Node`.



_Code quote:_
```XML
HashComputationError
```


<!-- Sent from Reviewable.io -->

2024-03-28 11:52 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 7 files at r5, 2 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/types.rs` line 3 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3sIaT0MTZ5v4YopOo:-Nu3sIaT0MTZ5v4YopOp:bt87j6x) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/types.rs#L3)):*
> ```XML
> use pathfinder_crypto::Felt;
> 
> pub(crate) type CommitterFelt = Felt;
> ```

Suggestion



_Suggestion:_
```XML
use pathfinder_crypto::Felt as PathfinderFelt;

pub(crate) type Felt = PathfinderFelt;
```
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 15 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3t5q4BiQSo9NyTkyv:-Nu3t5q4BiQSo9NyTkyw:b-8i2nvb) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L15)):*
> ```XML
> 
> #[allow(dead_code)]
> pub(crate) struct EdgePathLength(pub CommitterFelt);
> ```

Not accurate. The tree has 2**251 leaves, and these indices are unrelated to felts (other than upper bound). See how papyrus defined them



_Code quote:_
```XML
pub(crate) struct NodeIndex(pub CommitterFelt);

#[allow(dead_code)]
pub(crate) struct EdgePath(pub CommitterFelt);

#[allow(dead_code)]
pub(crate) struct EdgePathLength(pub CommitterFelt);
```


<!-- Sent from Reviewable.io -->

2024-03-28 11:57 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 25 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3ukvb6crJ99_oTrvj:-Nu3ukvb6crJ99_oTrvk:b8we5xk) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L25)):*
> ```XML
>     },
>     Leaf(LeafValue),
> }
> ```

You may need another type, for brother nodes that you have their hash but not their structure.
They act like leaves



_Code quote:_
```XML
pub(crate) enum NodeValue {
    Binary(Option<BinaryValue>),
    Edge {
        bottom_value: Option<BottomValue>,
        path_to_bottom: PathToBottom,
    },
    Leaf(LeafValue),
}
```
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3uL6qDakNMqxI3RMo:-Nu3uL6qDakNMqxI3RMp:b-k5dnwz) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L54)):*
> ```XML
>         nonce: Nonce,
>     },
> }
> ```

Make sure the inner patricia update logic does not know these specific values.
IMO it should only know that a leaf value is felt. (or alias to felt)



_Code quote:_
```XML
pub(crate) enum LeafValue {
    StorageKey(CommitterFelt),
    CompiledClassHash(CommitterFelt),
    StateTreeValue {
        class_hash: ClassHash,
        contract_state_root_hash: CommitterFelt,
        nonce: Nonce,
    },
}
```


<!-- Sent from Reviewable.io -->

2024-03-28 12:10 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3uL6qDakNMqxI3RMo:-Nu3xoU76xpK-jmfDOPZ:b-i5eaw6) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L54)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Make sure the inner patricia update logic does not know these specific values.
IMO it should only know that a leaf value is felt. (or alias to felt)
</blockquote></details>

We need to be able to compute the hash of a state tree leaf in this repo; knowing the internal data is a must. What do you have in mind?


<!-- Sent from Reviewable.io -->

2024-03-28 15:22 UTC, dorimedini-starkware approved these changes
> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 51 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3nLyF7vFGei4C2SlG:-Nu4dGvqB1EWIIF9TwwT:bcax2ja) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L51)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

~no; I mean a wrapper type for the Felt representing the root of the tree. Wrap the `Felt` here in `StateRoot(Felt)` or something~
nevermind, see below
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 25 at r10](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu4d1U4-llJtbcaf8Eg:-Nu4d1U4-llJtbcaf8Eh:b-ysak7t) ([raw file](https://github.com/starkware-libs/committer/blob/e5f08dbd6b61da131227ee970103e9f2be646294/crates/committer/src/patricia_merkle_tree/node.rs#L25)):*
> ```XML
>     },
>     Leaf(LeafValue),
>     Sibling,
> ```

should sibling contain a `NodeHash` (a non-optional felt value)? siblings should always be known when constructing a tree, the fact that it's a sibling means no changes were made in the subtree so the value is known at construction time



_Code quote:_
```XML
Sibling,
```
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 10 at r10](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu4dVSl9VHJmWQ4Bif0:-Nu4dVSl9VHJmWQ4Bif1:b7rkgi5) ([raw file](https://github.com/starkware-libs/committer/blob/e5f08dbd6b61da131227ee970103e9f2be646294/crates/committer/src/patricia_merkle_tree/tree.rs#L10)):*
> ```XML
> 
> #[allow(dead_code)]
> pub(crate) struct RootHash(HashOutput);
> ```

you call this a `RootHash` but you use it to represent roots of subtrees.
I am fine with this... unblocking above



_Code quote:_
```XML
pub(crate) struct RootHash(HashOutput);
```


<!-- Sent from Reviewable.io -->

2024-03-28 15:38 UTC, Yoni-Starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3uL6qDakNMqxI3RMo:-Nu4ff9O4f-VPt5ApWyl:b6p6g5y) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L54)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

We need to be able to compute the hash of a state tree leaf in this repo; knowing the internal data is a must. What do you have in mind?
</blockquote></details>

Separate the patricia update logic from the leaf hash calc - for the update logic, it is enough to get the leaves as flat felts.. I want to separate the patricia logic from SN specific trees so it could be reused easily.

Alternatively, you can (?) work with leaf trait 
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 25 at r10](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu4d1U4-llJtbcaf8Eg:-Nu4fXlo1VkLx3OC83n1:bh95ke4) ([raw file](https://github.com/starkware-libs/committer/blob/e5f08dbd6b61da131227ee970103e9f2be646294/crates/committer/src/patricia_merkle_tree/node.rs#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

should sibling contain a `NodeHash` (a non-optional felt value)? siblings should always be known when constructing a tree, the fact that it's a sibling means no changes were made in the subtree so the value is known at construction time
</blockquote></details>

You're right
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 48 at r10](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu4hPTO-r2BxSlON5nS:-Nu4hPTO-r2BxSlON5nT:b-kd8gle) ([raw file](https://github.com/starkware-libs/committer/blob/e5f08dbd6b61da131227ee970103e9f2be646294/crates/committer/src/patricia_merkle_tree/node.rs#L48)):*
> ```XML
> #[allow(dead_code)]
> pub(crate) enum LeafValue {
>     StorageKey(Felt),
> ```

StorageKey usually refers to the index of a leaf.
Rename to storageValue


<!-- Sent from Reviewable.io -->

2024-03-28 15:45 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-03-28 16:19 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3uL6qDakNMqxI3RMo:-Nu4qFln938Ik5Bdpt4a:b-wstqtk) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L54)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Separate the patricia update logic from the leaf hash calc - for the update logic, it is enough to get the leaves as flat felts.. I want to separate the patricia logic from SN specific trees so it could be reused easily.

Alternatively, you can (?) work with leaf trait
</blockquote></details>

by 'flat felts' you mean that `LeafValue` will have two variants - `OneFelt` & `ThreeFelt`, with values as the names suggest?
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 25 at r10](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu4d1U4-llJtbcaf8Eg:-Nu4lMBk6AQz_0_vJCaJ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e5f08dbd6b61da131227ee970103e9f2be646294/crates/committer/src/patricia_merkle_tree/node.rs#L25)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You're right
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 48 at r10](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu4hPTO-r2BxSlON5nS:-Nu4lcct7-cxUaTpc7pp:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e5f08dbd6b61da131227ee970103e9f2be646294/crates/committer/src/patricia_merkle_tree/node.rs#L48)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

StorageKey usually refers to the index of a leaf.
Rename to storageValue
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 10 at r10](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu4dVSl9VHJmWQ4Bif0:-Nu4lmjv8ivEQvaaiVLT:bhofej8) ([raw file](https://github.com/starkware-libs/committer/blob/e5f08dbd6b61da131227ee970103e9f2be646294/crates/committer/src/patricia_merkle_tree/tree.rs#L10)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you call this a `RootHash` but you use it to represent roots of subtrees.
I am fine with this... unblocking above
</blockquote></details>

Deleted


<!-- Sent from Reviewable.io -->

2024-03-28 19:23 UTC, TzahiTaub requested changes
> Reviewed 1 of 8 files at r5, 2 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: 8 of 10 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/committer/Cargo.toml` line 16 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu4OFBLAj1EoFlRiDSc:-Nu4OFBLAj1EoFlRiDSd:br0ao8l) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/Cargo.toml#L16)):*
> ```TOML
> 
> [dependencies]
> pathfinder-crypto = { git = "https://github.com/eqlabs/pathfinder.git"}
> ```

Probably want to set this to some tag. I also think the current is not supported with bazel build (as it searches for a "master" branch and it's called "main" on pathfinder).


<!-- Sent from Reviewable.io -->

2024-03-28 19:37 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3uL6qDakNMqxI3RMo:-Nu5Z-fE5SHFi0vL7o9-:bodsl4z) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L54)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

by 'flat felts' you mean that `LeafValue` will have two variants - `OneFelt` & `ThreeFelt`, with values as the names suggest?
</blockquote></details>

No, just felt. (either a regular value or a hash of some struct)


<!-- Sent from Reviewable.io -->

2024-03-28 19:50 UTC, dorimedini-starkware approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-03-28 21:58 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3uL6qDakNMqxI3RMo:-Nu63MN00-65dPT-89Mt:bkxe3y) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L54)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

No, just felt. (either a regular value or a hash of some struct)
</blockquote></details>

How will the values class_hash, contract_state_root_hash and nonce be stored in one Felt?


<!-- Sent from Reviewable.io -->

2024-03-29 09:03 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3uL6qDakNMqxI3RMo:-Nu8RpK8AsIayFEUFr-L:b-x6hoq0) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L54)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

How will the values class_hash, contract_state_root_hash and nonce be stored in one Felt?
</blockquote></details>

by their hash


<!-- Sent from Reviewable.io -->

2024-03-29 09:10 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @Yoni-Starkware)

___
*[`crates/committer/Cargo.toml` line 16 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu4OFBLAj1EoFlRiDSc:-Nu8SBRO0W3_7psUdYd2:b-mxn7gn) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/Cargo.toml#L16)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Probably want to set this to some tag. I also think the current is not supported with bazel build (as it searches for a "master" branch and it's called "main" on pathfinder).
</blockquote></details>

actually we will be moving to starknet-types-core library...
@amosStarkware in a separate PR
```
starknet-types-core = { version = "0.0.11", features = ["num-traits"] }
```
(maybe `starknet-types-core = "0.0.11"` is enough at this point)
___
*[`crates/committer/Cargo.toml` line 17 at r11](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu8TK2D-K1w80Jm_gjs:-Nu8TK2D-K1w80Jm_gjt:b-zanf7e) ([raw file](https://github.com/starkware-libs/committer/blob/96c5ad1611f29e24b12a814e6108c6c63dabd863/crates/committer/Cargo.toml#L17)):*
> ```TOML
> [dependencies]
> pathfinder-crypto = { git = "https://github.com/eqlabs/pathfinder.git"}
> starknet_api = "0.11.0"
> ```

published yesterday; we should work with it starting now (includes new pedersen/poseidon implementations)



_Suggestion:_
```TOML
starknet_api = "0.12.0-dev.0"
```
___
*[`crates/committer/src/types.rs` line 3 at r11](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu8SZlI-KBUpWA9LUgq:-Nu8SZlI-KBUpWA9LUgr:b-aht6dw) ([raw file](https://github.com/starkware-libs/committer/blob/96c5ad1611f29e24b12a814e6108c6c63dabd863/crates/committer/src/types.rs#L3)):*
> ```XML
> use pathfinder_crypto::Felt as PathFinderFelt;
> 
> pub(crate) type Felt = PathFinderFelt;
> ```

consider changing this in the current PR (non-blocking, see above)



_Suggestion:_
```XML
use starknet_types_core::felt::Felt as StarknetTypesFelt;

pub(crate) type Felt = StarknetTypesFelt;
```


<!-- Sent from Reviewable.io -->

2024-03-29 13:48 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3uL6qDakNMqxI3RMo:-Nu9Swx_7vKdBX8nDvBZ:b-ruh5rn) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L54)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

by their hash
</blockquote></details>

Yes, and you don't need the `update` logic to do that for you. You can do it before since the hash is known


<!-- Sent from Reviewable.io -->

2024-03-30 09:11 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/Cargo.toml` line 16 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu4OFBLAj1EoFlRiDSc:-NuDZ7J40-97ntkSJxiJ:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/Cargo.toml#L16)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

actually we will be moving to starknet-types-core library...
@amosStarkware in a separate PR
```
starknet-types-core = { version = "0.0.11", features = ["num-traits"] }
```
(maybe `starknet-types-core = "0.0.11"` is enough at this point)
</blockquote></details>

Done
___
*[`crates/committer/Cargo.toml` line 17 at r11](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu8TK2D-K1w80Jm_gjs:-NuD_8mkAV68IS-Ak92o:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/96c5ad1611f29e24b12a814e6108c6c63dabd863/crates/committer/Cargo.toml#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

published yesterday; we should work with it starting now (includes new pedersen/poseidon implementations)
</blockquote></details>

Done.
___
*[`crates/committer/src/types.rs` line 3 at r11](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu8SZlI-KBUpWA9LUgq:-NuD_GHi5iu6kjJazwlu:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/96c5ad1611f29e24b12a814e6108c6c63dabd863/crates/committer/src/types.rs#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider changing this in the current PR (non-blocking, see above)
</blockquote></details>

Done
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3uL6qDakNMqxI3RMo:-NuD_LSx441IfUqoZCPx:b-9fq6u4) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L54)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Yes, and you don't need the `update` logic to do that for you. You can do it before since the hash is known
</blockquote></details>

(I still don't understand - what about the facts of new leaves? the facts hold the actual values of the new leaves. or did you mean that Rust will return their hashes, and Python will add their values when storing them?)

anyway, I used a Leaf generic type
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 27 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuDbhk3BMDBQXJWehv9:-NuDbhk3BMDBQXJWehvA:bdakmgw) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/node.rs#L27)):*
> ```XML
>     },
>     Leaf(LeafVal),
>     Sibling,
> ```

Siblings have no value: their hash is set when they are created, not their value.



_Code quote:_
```XML
    Sibling,
```


<!-- Sent from Reviewable.io -->

2024-03-31 05:13 UTC, Yoni-Starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3uL6qDakNMqxI3RMo:-NuHssD0AfQkyT5lXa6s:bpy85tl) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L54)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

(I still don't understand - what about the facts of new leaves? the facts hold the actual values of the new leaves. or did you mean that Rust will return their hashes, and Python will add their values when storing them?)

anyway, I used a Leaf generic type
</blockquote></details>

You can write these facts (in rust) before/after the `update` function since it does not depend on the tree structure
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 27 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuDbhk3BMDBQXJWehv9:-NuHuPxSBSqsLwI1u44J:bkje5pf) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/node.rs#L27)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Siblings have no value: their hash is set when they are created, not their value.
</blockquote></details>

(It may be simpler to put the hash inside it - otherwise, you would have to go back to its parent)
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 57 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuHtReS6k0nnFHET2mV:-NuHtReS6k0nnFHET2mW:bdy78v8) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/node.rs#L57)):*
> ```XML
>         nonce: Nonce,
>     },
> }
> ```

I don't think we need this enum (technically, when would you enumerate over it?)
and then you could rename `LeafVal` -> `LeafValue`
Non-blocking



_Code quote:_
```XML
pub(crate) enum LeafValue {
    StorageValue(Felt),
    CompiledClassHash(Felt),
    StateTreeValue {
        class_hash: ClassHash,
        contract_state_root_hash: Felt,
        nonce: Nonce,
    },
}
```


<!-- Sent from Reviewable.io -->

2024-03-31 05:24 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: 2 of 10 files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 27 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuDbhk3BMDBQXJWehv9:-NuHxlFn2x1twtFXxhQC:bwux6du) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/node.rs#L27)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

(It may be simpler to put the hash inside it - otherwise, you would have to go back to its parent)
</blockquote></details>

Same re leaves (that was my intention - keep just the hash as the value)
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 64 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuHx2Io59ROvOm5ci9R:-NuHx2Ip3gF7S_yZCoub:b1h30bn) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/node.rs#L64)):*
> ```XML
>     fn compute_and_set_subtree_hashes_and_values(
>         &mut self,
>     ) -> Result<HashOutput, NodeHashComputationError>;
> ```

How would it work? don't you need the tree to do that?
Who is going to implement this trait?
Maybe the trait `Tree` is the right resolution for this



_Code quote:_
```XML
pub(crate) trait Node<H: HashFunction, LeafVal> {
    /// Computes and sets sub-tree's hashes and values, if possible.
    /// If successful or if hash and value of node are already set - returns hash of node.
    fn compute_and_set_subtree_hashes_and_values(
        &mut self,
    ) -> Result<HashOutput, NodeHashComputationError>;
```
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 11 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuHxKrN1_wp_7fKpvZo:-NuHxKrN1_wp_7fKpvZp:b-ufmfgx) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/tree.rs#L11)):*
> ```XML
>     fn get_root(&self) -> Option<&mut N>;
> 
>     /// Updates tree in place with given leaves, and returns all modified (and new) nodes.
> ```

Was this decided? is it easier than creating a new tree?



_Code quote:_
```XML
in place
```


<!-- Sent from Reviewable.io -->

2024-03-31 07:19 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: 2 of 10 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 27 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuDbhk3BMDBQXJWehv9:-NuILjC82vJVrZLmD_zI:bwntai8) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/node.rs#L27)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Same re leaves (that was my intention - keep just the hash as the value)
</blockquote></details>

the hash should be set when the node is created (it just makes less sense to do it in the node's value, IMO).
maybe the `get_hash` method should return a `NodeHash` enum, with optional hash values for all node types except sibling nodes (which will be non-optional).
WYT?
FYI @dorimedini-starkware 
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 57 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuHtReS6k0nnFHET2mV:-NuIJKZp8l8ZkQGenzI1:bcdrwl4) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/node.rs#L57)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I don't think we need this enum (technically, when would you enumerate over it?)
and then you could rename `LeafVal` -> `LeafValue`
Non-blocking
</blockquote></details>

it's not needed for the API, it's part of the implementation
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 64 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuHx2Io59ROvOm5ci9R:-NuIJddY5KPIOiESIBTo:b16okz8) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/node.rs#L64)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

How would it work? don't you need the tree to do that?
Who is going to implement this trait?
Maybe the trait `Tree` is the right resolution for this
</blockquote></details>

The node can recursively go down to leaves and then go back up while computing and setting the values and hashes.
If the nodes have pointers to their children / bottoms this is easy (doesn't have to be implemented this way though, of course).
I removed the method `Tree::compute_and_set_all_hashes()` because it duplicates what this method does, IMO
@dorimedini-starkware WYT?
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 11 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuHxKrN1_wp_7fKpvZo:-NuIL8EY4IzVftIPY2XH:b8ornx8) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/tree.rs#L11)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Was this decided? is it easier than creating a new tree?
</blockquote></details>

I don't think it's easier, it's just our use case.
you think it makes more sense to create a new updated tree?


<!-- Sent from Reviewable.io -->

2024-03-31 07:39 UTC, dorimedini-starkware requested changes
> Reviewed 8 of 8 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3uL6qDakNMqxI3RMo:-NuIPgXfAyHKBSfMVBvc:b-dquo8x) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L54)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You can write these facts (in rust) before/after the `update` function since it does not depend on the tree structure
</blockquote></details>

@Yoni-Starkware your suggestion means we separate hashing into (1) leaves and (2) internal nodes; this may be a perf hit.
since the input to the hashing phase is the new skeleton + new leaf *values* it would be nice if the hashes remained unknown until we start the `update`
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 20 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuIRJJIA0cvWZf3ZWHx:-NuIRJJIA0cvWZf3ZWHy:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/node.rs#L20)):*
> ```XML
> 
> #[allow(dead_code)]
> pub(crate) enum NodeValue<LeafVal> {
> ```





_Suggestion:_
```XML
LeafVal: LeafValTrait
```
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 27 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuDbhk3BMDBQXJWehv9:-NuIR8NxCmhgbTcAhLGL:b-xmv5x4) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/node.rs#L27)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

the hash should be set when the node is created (it just makes less sense to do it in the node's value, IMO).
maybe the `get_hash` method should return a `NodeHash` enum, with optional hash values for all node types except sibling nodes (which will be non-optional).
WYT?
FYI @dorimedini-starkware
</blockquote></details>

Each node has a value (preimage of its hash) and a hash.
`NodeValue` contains the *values* and not the hashes?
Maybe it should contain both? I.e. each variant has an optional hash and optional value, and siblings have non-optional hashes and no values?
@aner-starkware inputs here?
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 59 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuIQmCEDsEctmA4x-xC:-NuIQmCEDsEctmA4x-xD:b5b19q9) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/node.rs#L59)):*
> ```XML
> }
> 
> pub(crate) trait Node<H: HashFunction, LeafVal> {
> ```

this type param should be bound to some trait (can be empty for now) to prevent sending just anything as a type



_Suggestion:_
```XML
, LeafVal: LeafValTrait
```
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 64 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuHx2Io59ROvOm5ci9R:-NuIQKh4DBzC4QiNmtkr:bphxskw) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/node.rs#L64)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

The node can recursively go down to leaves and then go back up while computing and setting the values and hashes.
If the nodes have pointers to their children / bottoms this is easy (doesn't have to be implemented this way though, of course).
I removed the method `Tree::compute_and_set_all_hashes()` because it duplicates what this method does, IMO
@dorimedini-starkware WYT?
</blockquote></details>

Without starting to implement the update algorithm it is hard to tell whether or not nodes should be aware of their subtree.
this may be hard to do - does each node *own* the subtree data? how do we parallelize access to left and right subtrees in this case?
@aner-starkware 
___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 7 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuIQvQ20kLaAtUb1Rje:-NuIQvQ20kLaAtUb1Rjf:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/tree.rs#L7)):*
> ```XML
> use crate::hash::types::HashFunction;
> 
> pub(crate) trait Tree<H: HashFunction, LeafVal, N: Node<H, LeafVal>> {
> ```





_Suggestion:_
```XML
LeafVal: LeafValTrait
```


<!-- Sent from Reviewable.io -->

2024-03-31 10:28 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/committer/6#-Nu3uL6qDakNMqxI3RMo:-NuJ1BTn5TvrXcCo3Zrl:b-nso6mi) ([raw file](https://github.com/starkware-libs/committer/blob/64ccea6f8d94d35a9d25854393fbd21b704928db/crates/committer/src/patricia_merkle_tree/node.rs#L54)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@Yoni-Starkware your suggestion means we separate hashing into (1) leaves and (2) internal nodes; this may be a perf hit.
since the input to the hashing phase is the new skeleton + new leaf *values* it would be nice if the hashes remained unknown until we start the `update`
</blockquote></details>

Okay, I'm fine with this as long as it's generic
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 57 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuHtReS6k0nnFHET2mV:-NuJ1NwAEl3LbuubC78Z:b-u9bzt1) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/node.rs#L57)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

it's not needed for the API, it's part of the implementation
</blockquote></details>

Yeah, I mean in the implementation. When would you need to enumerate over it?
___
*[`crates/committer/src/patricia_merkle_tree/node.rs` line 64 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuHx2Io59ROvOm5ci9R:-NuJ1lm96HGsIdS19R9J:b-oewr00) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/node.rs#L64)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Without starting to implement the update algorithm it is hard to tell whether or not nodes should be aware of their subtree.
this may be hard to do - does each node *own* the subtree data? how do we parallelize access to left and right subtrees in this case?
@aner-starkware
</blockquote></details>

Yeah, it's not clear.
I though, according to this PR, that the tree is going to be represented by the following map:
```rust
Map<NodeIndex, NodeValue>
```

Anyway, if you have representation X that the node is enough and representation Y that the whole tree is needed, it's best to go for a trait just for the tree, to be able to implement both X and Y behind it


<!-- Sent from Reviewable.io -->

2024-03-31 10:29 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/6)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/tree.rs` line 11 at r12](https://reviewable.io/reviews/starkware-libs/committer/6#-NuHxKrN1_wp_7fKpvZo:-NuJ2Y5V6sxyzZHOW5c3:b-9swofi) ([raw file](https://github.com/starkware-libs/committer/blob/94edaba251c18bad9ee8a0109958b19d9863260f/crates/committer/src/patricia_merkle_tree/tree.rs#L11)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I don't think it's easier, it's just our use case.
you think it makes more sense to create a new updated tree?
</blockquote></details>

I know that creating a new tree is trivial. I didn't think about modifying in-place, maybe it's more complicated since you need to prune things - but maybe not. Someone needs to think and decide


<!-- Sent from Reviewable.io -->

2024-04-03 13:41 UTC, closed without merging