build: add python test command
starkware-libs/committer pull request #68
Opened 2024-04-24 13:11 UTC by AvivYossef-starkware

This PR adds a new module for Patricia Merkle Tree functionality and enables running Python tests within the Committer CLI. It introduces a PythonTest command to specify test names and inputs as JSON, executing tests and printing output to the console.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/68)

2024-04-24 13:49 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/68)* status: all files reviewed, 9 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer/src/lib.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFMQVHD-nl1y5oULc6:-NwFMQVHD-nl1y5oULc7:b-rtagwg) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer/src/lib.rs#L5)):*
> ```XML
> pub mod patricia_merkle_tree;
> pub mod storage;
> pub mod tests;
> ```

delete



_Code quote:_
```XML
pub mod tests;
```
___
*[`crates/committer/src/tests.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFMSGLDQv6JrJJt2VH:-NwFMSGLDQv6JrJJt2VI:bxbutuc) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer/src/tests.rs#L1)):*
> ```XML
> pub mod python_tests;
> ```

delete (move to CLI crate)



_Code quote:_
```XML
pub mod python_tests;
```
___
*[`crates/committer/src/tests/python_tests.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFLKn221VtUQmnvDD4:-NwFLKn221VtUQmnvDD5:b-z1y6e2) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer/src/tests/python_tests.rs#L0)):*
move this to the committer_cli crate (no python-related logic in the main crate)
___
*[`crates/committer/src/tests/python_tests.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFMKd_4RcR6YqF1O2Z:-NwFMKd_4RcR6YqF1O2_:bef99at) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer/src/tests/python_tests.rs#L8)):*
> ```XML
>         _ => panic!("Unknown test name: {}", test_name),
>     }
> }
> ```

replace with the enum method (see below)



_Code quote:_
```XML
pub fn run_test(test_name: String, test_args: HashMap<String, String>) -> String {
    match test_name.as_str() {
        "example_test" => example_test(test_args),
        _ => panic!("Unknown test name: {}", test_name),
    }
}
```
___
*[`crates/committer/src/tests/python_tests.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFMHF2600t4-WACq_4:-NwFMHF2600t4-WACq_5:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer/src/tests/python_tests.rs#L15)):*
> ```XML
> 
>     let output = format!("Calling example test with args: x: {}, y: {}", x, y);
>     output
> ```





_Suggestion:_
```XML
    format!("Calling example test with args: x: {}, y: {}", x, y)
```
___
*[`crates/committer_cli/Cargo.toml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFIV0M5iWmUNuwwxN8:-NwFIV0M5iWmUNuwwxN9:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer_cli/Cargo.toml#L18)):*
> ```TOML
> clap.workspace = true
> serde_json.workspace = true
> committer = { path = "../committer" }
> ```





_Suggestion:_
```TOML
committer = { path = "../committer" }
serde_json.workspace = true
```
___
*[`crates/committer_cli/src/main.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFIf-M3z38GmqKd4I5:-NwFIf-M3z38GmqKd4I6:bhwt9rj) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer_cli/src/main.rs#L82)):*
> ```XML
> 
>             // Run relevant test.
>             let output = committer::tests::python_tests::run_test(test_name, test_args);
> ```

"python tests" should be in the committer_cli crate, not the committer crate.
Python-related stuff should not be in the published crate



_Code quote:_
```XML
committer::tests::python_tests
```
___
*[`crates/committer_cli/src/main.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFInNI9AkQzEd8FgZb:-NwFInNI9AkQzEd8FgZc:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer_cli/src/main.rs#L84)):*
> ```XML
>             let output = committer::tests::python_tests::run_test(test_name, test_args);
> 
>             // Output test result to a file.
> ```





_Suggestion:_
```XML
// Output test result.
```
___
*[`crates/committer_cli/src/main.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFL1HS-g4CY089IK4y:-NwFL1HS-g4CY089IK4z:b-dkb851) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer_cli/src/main.rs#L85)):*
> ```XML
> 
>             // Output test result to a file.
>             print!("{}", output);
> ```

1. Not all tests may need a str->str mapping as input; better to deserialize input by test name.
2. I would suggest using an enum:
```
enum PythonTest {
    Example,
    ...
}

impl TryFrom<String> for PythonTest {
    type error = PythonTestNameError;
    fn try_from(value: String) -> Self {
        match value.as_str() {
            "example_test" => Ok(Self::Exampled),
            ...
            _ => Err(PythonTestNameError(value))
        }
    }
}

impl PythonTest {
    fn run(&self, input: &String) -> String {
        match self {
            Self::Example => {
                let example_input: HashMap<String, String> = serde_json::from_str(&input)
                    .unwrap_or_else(|_| panic!("Failed to parse input json"));
                example_test(example_input)
            }
            ...
        }
    }
}
```



_Suggestion:_
```XML
            let test = PythonTest::try_from(test_name).unwrap_or(|_| ...);
            print!("{}", test.run(&input));
```


<!-- Sent from Reviewable.io -->

2024-04-24 15:30 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/68)* status: 0 of 7 files reviewed, 9 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer_cli/Cargo.toml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFIV0M5iWmUNuwwxN8:-NwFSKXhAYdPKCgc5RIU:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer_cli/Cargo.toml#L18)):*
> ```TOML
> clap.workspace = true
> serde_json.workspace = true
> committer = { path = "../committer" }
> ```

Done.
___
*[`crates/committer_cli/src/main.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFIf-M3z38GmqKd4I5:-NwFSMdLAcnQXjFXserR:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer_cli/src/main.rs#L82)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

"python tests" should be in the committer_cli crate, not the committer crate.
Python-related stuff should not be in the published crate
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/main.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFInNI9AkQzEd8FgZb:-NwFSYDE9wccffYgB-Tt:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer_cli/src/main.rs#L84)):*
> ```XML
>             let output = committer::tests::python_tests::run_test(test_name, test_args);
> 
>             // Output test result to a file.
> ```

Done.
___
*[`crates/committer_cli/src/main.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFL1HS-g4CY089IK4y:-NwFijgJAsfGE0cwqzAE:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer_cli/src/main.rs#L85)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. Not all tests may need a str->str mapping as input; better to deserialize input by test name.
2. I would suggest using an enum:
```
enum PythonTest {
    Example,
    ...
}

impl TryFrom<String> for PythonTest {
    type error = PythonTestNameError;
    fn try_from(value: String) -> Self {
        match value.as_str() {
            "example_test" => Ok(Self::Exampled),
            ...
            _ => Err(PythonTestNameError(value))
        }
    }
}

impl PythonTest {
    fn run(&self, input: &String) -> String {
        match self {
            Self::Example => {
                let example_input: HashMap<String, String> = serde_json::from_str(&input)
                    .unwrap_or_else(|_| panic!("Failed to parse input json"));
                example_test(example_input)
            }
            ...
        }
    }
}
```
</blockquote></details>

Done.
___
*[`crates/committer/src/lib.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFMQVHD-nl1y5oULc6:-NwFRu978PYPYXRIScML:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer/src/lib.rs#L5)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/committer/src/tests/python_tests.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFMKd_4RcR6YqF1O2Z:-NwFihEk7DhNE6UDYvd5:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer/src/tests/python_tests.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

replace with the enum method (see below)
</blockquote></details>

Done.
___
*[`crates/committer/src/tests/python_tests.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFMHF2600t4-WACq_4:-NwFSAkG8ER4kdEcYtSe:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer/src/tests/python_tests.rs#L15)):*
> ```XML
> 
>     let output = format!("Calling example test with args: x: {}, y: {}", x, y);
>     output
> ```

Done.
___
*[`crates/committer/src/tests/python_tests.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFLKn221VtUQmnvDD4:-NwFRvnpDu6TG31KnCga:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer/src/tests/python_tests.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move this to the committer_cli crate (no python-related logic in the main crate)
</blockquote></details>

Done.
___
*[`crates/committer/src/tests.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/committer/68#-NwFMSGLDQv6JrJJt2VH:-NwFRujJ347Wpe-l2Kct:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3487a7270bd80cd7cc4052dd059337a7222d0265/crates/committer/src/tests.rs#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete (move to CLI crate)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-24 19:59 UTC, dorimedini-starkware requested changes
> Reviewed 5 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/68)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer_cli/src/main.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/committer/68#-NwGc5g21_tWHvixVCxs:-NwGc5g21_tWHvixVCxt:b-k0ceay) ([raw file](https://github.com/starkware-libs/committer/blob/197864ce814165416a12430ea1dbcc78117a4bd5/crates/committer_cli/src/main.rs#L82)):*
> ```XML
>             let test = match PythonTest::try_from(test_name) {
>                 Ok(test) => test,
>                 Err(e) => {
> ```

`x.expect("oops")` is basically shorthand for `match x { Ok(x) => x, Err(_) => panic!("oops"); }`, please use `expect`



_Code quote:_
```XML
            let test = match PythonTest::try_from(test_name) {
                Ok(test) => test,
                Err(e) => {
```
___
*[`crates/committer_cli/src/main.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/committer/68#-NwGg3G74cKNdyOoWaOI:-NwGg3G74cKNdyOoWaOJ:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/197864ce814165416a12430ea1dbcc78117a4bd5/crates/committer_cli/src/main.rs#L94)):*
> ```XML
>                     panic!("Failed to run test: {}", e)
>                 }
>             };
> ```





_Suggestion:_
```XML
            let output = test.run(&inputs).unwrap_or_else(
                |error| panic!("Failed to run test: {}", error)
            );
            print!("{}", output);
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/committer/68#-NwGfUlr3KetOLy7SlSL:-NwGfUlr3KetOLy7SlSM:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/197864ce814165416a12430ea1dbcc78117a4bd5/crates/committer_cli/src/tests/python_tests.rs#L4)):*
> ```XML
> use thiserror;
> 
> // Define an enum representing different Python tests. with their respective arguments.
> ```





_Suggestion:_
```XML
// Enum representing different Python tests.
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/committer/68#-NwGfZ8B1ER-W4T0Y2xW:-NwGfZ8B1ER-W4T0Y2xX:b-9w1z4g) ([raw file](https://github.com/starkware-libs/committer/blob/197864ce814165416a12430ea1dbcc78117a4bd5/crates/committer_cli/src/tests/python_tests.rs#L7)):*
> ```XML
> pub(crate) enum PythonTest {
>     ExampleTest,
>     // Add additional test variants as needed
> ```

unnecessary comment
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/committer/68#-NwGfgle9CfnnnM7TmAY:-NwGfgle9CfnnnM7TmAZ:b-au1nft) ([raw file](https://github.com/starkware-libs/committer/blob/197864ce814165416a12430ea1dbcc78117a4bd5/crates/committer_cli/src/tests/python_tests.rs#L26)):*
> ```XML
>         match value.as_str() {
>             "example_test" => Ok(Self::ExampleTest),
>             _ => Err(PythonTestError::UnknownTestName((value).to_string())),
> ```

`value` is already a string, no?
actually, why doesn't clippy fail here?



_Suggestion:_
```XML
(value))
```


<!-- Sent from Reviewable.io -->

2024-04-24 22:19 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/68)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/committer/68#-NwHBAjA6-i34pndfqhM:-NwHBAjA6-i34pndfqhN:bp73f45) ([raw file](https://github.com/starkware-libs/committer/blob/197864ce814165416a12430ea1dbcc78117a4bd5/crates/committer_cli/src/tests/python_tests.rs#L23)):*
> ```XML
>     type Error = PythonTestError;
> 
>     fn try_from(value: String) -> Result<PythonTest, PythonTestError> {
> ```

Single point of truth



_Suggestion:_
```XML
Result<Self, Self::Error>
```


<!-- Sent from Reviewable.io -->

2024-04-25 06:20 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/68)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer_cli/src/main.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/committer/68#-NwGc5g21_tWHvixVCxs:-NwIrrs8EQJn89s4gPAA:bmim3el) ([raw file](https://github.com/starkware-libs/committer/blob/197864ce814165416a12430ea1dbcc78117a4bd5/crates/committer_cli/src/main.rs#L82)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`x.expect("oops")` is basically shorthand for `match x { Ok(x) => x, Err(_) => panic!("oops"); }`, please use `expect`
</blockquote></details>

Ok, changed to unwrap_or_else
___
*[`crates/committer_cli/src/main.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/committer/68#-NwGg3G74cKNdyOoWaOI:-NwIr9hM2lS3D7mEiH5f:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/197864ce814165416a12430ea1dbcc78117a4bd5/crates/committer_cli/src/main.rs#L94)):*
> ```XML
>                     panic!("Failed to run test: {}", e)
>                 }
>             };
> ```

Done.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/committer/68#-NwGfUlr3KetOLy7SlSL:-NwIs2Pi0jB09FugBwep:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/197864ce814165416a12430ea1dbcc78117a4bd5/crates/committer_cli/src/tests/python_tests.rs#L4)):*
> ```XML
> use thiserror;
> 
> // Define an enum representing different Python tests. with their respective arguments.
> ```

Done.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/committer/68#-NwGfZ8B1ER-W4T0Y2xW:-NwIs4rT7OAl5WZVzOKi:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/197864ce814165416a12430ea1dbcc78117a4bd5/crates/committer_cli/src/tests/python_tests.rs#L7)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

unnecessary comment
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/committer/68#-NwHBAjA6-i34pndfqhM:-NwIsvVD1_sy9yvzXrnr:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/197864ce814165416a12430ea1dbcc78117a4bd5/crates/committer_cli/src/tests/python_tests.rs#L23)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Single point of truth
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/committer/68#-NwGfgle9CfnnnM7TmAY:-NwItudC9ey1kZ-b-2Co:b-3gmy72) ([raw file](https://github.com/starkware-libs/committer/blob/197864ce814165416a12430ea1dbcc78117a4bd5/crates/committer_cli/src/tests/python_tests.rs#L26)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`value` is already a string, no?
actually, why doesn't clippy fail here?
</blockquote></details>

I don't know, but it works without it.


<!-- Sent from Reviewable.io -->

2024-04-25 07:28 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/68#-:-NwJ93GMADbYg5aap-2B:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2024-04-25 07:49 UTC, merged