Nimrod/commit lower trees
starkware-libs/committer pull request #83
Opened 2024-05-02 06:57 UTC by nimrod-starkware

2024-05-02 10:14 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/83)* status: all files reviewed, 9 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/block_committer/commit.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-NwsibwCC5uJdeYFMwZK:-NwsibwCC5uJdeYFMwZL:bniw5ow) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/commit.rs#L13)):*
> ```XML
> 
> #[allow(dead_code)]
> pub(crate) fn commit_block(input: Input) -> BlockCommitmentResult<Vec<OriginalSkeletonTreeImpl>> {
> ```

let's prepare for when we use this function to compute the entire first part of the algorithm.
1. Define a struct return type, which we will use to represent all original skeletons in a block
2. make it generic by skeleton trait (we may need 3 different skeleton trait implementors in the struct later, but for now one is enough)
3. don't use `OriginalSkeletonTreeImpl` in the function body



_Suggestion:_
```XML
type BlockCommitmentResult<T> = Result<T, BlockCommitmentError>;

pub(crate) struct OriginalSkeletonForest<S: OriginalSkeletonTree> {
    // TODO(Nimrod): Add compiled class tree.
    // TODO(Nimrod): Add global state tree.
    contract_states: HashMap<ContractAddress, S>
}

#[allow(dead_code)]
pub(crate) fn commit_block<S: OriginalSkeletonTree>(input: Input) -> BlockCommitmentResult<OriginalSkeletonForest<S>> {
```
___
*[`crates/committer/src/block_committer/commit.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-Nwsj8Cs57xdI84wnaad:-Nwsj8Cs57xdI84wnaae:bvc0u78) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/commit.rs#L13)):*
> ```XML
> 
> #[allow(dead_code)]
> pub(crate) fn commit_block(input: Input) -> BlockCommitmentResult<Vec<OriginalSkeletonTreeImpl>> {
> ```

this is not the entire commitment logic.
1. move this function to the skeleton area (I think original skeleton area is the correct place).
2. rename



_Suggestion:_
```XML
deserialize_original_skeleton_forest
```
___
*[`crates/committer/src/block_committer/commit.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-NwslGcI6GKd3LyHm2vV:-NwslGcI6GKd3LyHm2vW:boibair) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/commit.rs#L14)):*
> ```XML
> #[allow(dead_code)]
> pub(crate) fn commit_block(input: Input) -> BlockCommitmentResult<Vec<OriginalSkeletonTreeImpl>> {
>     let actual_storage = MapStorage::from(input.storage);
> ```

is it possible to add a `from(HashMap<StorageKey, StorageValue>)` on the generic `Storage` trait?
I prefer this function be agnostic to the storage implementation, i.e. make a generic `S: Storage` type parameter and use `S::from(input.storage)`.
the `create_tree` method of the skeleton tree trait accepts any implementor of the Storage trait



_Code quote:_
```XML
let actual_storage = MapStorage::from(input.storage);
```
___
*[`crates/committer/src/block_committer/commit.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-NwskYV_3XrV62we-S5U:-NwskYV_3XrV62we-S5V:b-2dlg3m) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/commit.rs#L31)):*
> ```XML
>             .current_contract_state_leaves
>             .get(address)
>             .ok_or_else(|| BlockCommitmentError::LowerTreeCommitmentError(*address))?;
> ```

errors indicating bad input should have their own enum. it shouldn't be a direct variant in BlockCommitmentError, please create an intermediate enum



_Code quote:_
```XML
 BlockCommitmentError::LowerTreeCommitmentError
```
___
*[`crates/committer/src/block_committer/errors.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-NwslzwY7d53iOCd2dDh:-NwslzwY7d53iOCd2dDi:ba4zlfq) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/errors.rs#L9)):*
> ```XML
> #[derive(Debug, Error)]
> pub(crate) enum BlockCommitmentError {
>     #[error("Failed to build the original skeleton tree while committing the block.\n {0:?}")]
> ```

prefer using `transparent` when the error variant is of the form `X(#[from] Y)`



_Suggestion:_
```XML
#[error(transparent)]
```
___
*[`crates/committer/src/block_committer/errors.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-Nwslokb8g7UXAb58xSS:-Nwslokb8g7UXAb58xST:b4gmcgn) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/errors.rs#L12)):*
> ```XML
>     BuildingOriginalSkeletonTree(#[from] OriginalSkeletonTreeError),
>     #[error("Failed to commit lower tree at address: {0:?}")]
>     LowerTreeCommitmentError(ContractAddress),
> ```

this is a specific error you encounter when the input data does not contain the required information to compute an original skeleton.
this belongs as a variant in the `OriginalSkeletonTreeError` enum



_Code quote:_
```XML
    #[error("Failed to commit lower tree at address: {0:?}")]
    LowerTreeCommitmentError(ContractAddress),
```
___
*[`crates/committer/src/block_committer/types.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-NwsmCcu80W_DfnQt-AF:-NwsmCcu80W_DfnQt-AG:bt3beyn) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/types.rs#L65)):*
> ```XML
>             ]
>             .concat(),
>         )
> ```

does this work? I see no reason to `collect` anything before passing it to `HashMap::from_iter`



_Suggestion:_
```XML
        HashSet::from_iter(
            self.address_to_class_hash
                .keys()
                .chain(self.address_to_nonce.keys())
                .chain(self.storage_updates.keys())
        )
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-NwsmVf6BvecW6Rdfhei:-NwsmVf6BvecW6Rdfhej:b59noxc) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/patricia_merkle_tree/types.rs#L51)):*
> ```XML
>     pub(crate) fn as_full_index(&self, tree_height: &TreeHeight) -> Self {
>         Self(U256::from(2_u8) << tree_height.0) + *self
>     }
> ```

@TzahiTaub PTAL as well



_Code quote:_
```XML
    pub(crate) fn as_full_index(&self, tree_height: &TreeHeight) -> Self {
        Self(U256::from(2_u8) << tree_height.0) + *self
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-Nwsm_neD2ywzRPvgRyj:-Nwsm_neD2ywzRPvgRyk:bxzww72) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/patricia_merkle_tree/types.rs#L86)):*
> ```XML
>         NodeIndex::from(value.0)
>     }
> }
> ```

why do you need this conversion?
this is dangerous
for a state tree of depth 251, node index 2^251 is leaf number 0, so starknet storage key should be zero.
please delete this and use explicit conversions if and when you need to



_Code quote:_
```XML
impl From<StarknetStorageKey> for NodeIndex {
    fn from(value: StarknetStorageKey) -> Self {
        NodeIndex::from(value.0)
    }
}
```


<!-- Sent from Reviewable.io -->

2024-05-05 07:54 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/83)* status: all files reviewed, 9 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/block_committer/commit.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-NwsibwCC5uJdeYFMwZK:-NwtPE2G2C7xNiINy4F7:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/commit.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

let's prepare for when we use this function to compute the entire first part of the algorithm.
1. Define a struct return type, which we will use to represent all original skeletons in a block
2. make it generic by skeleton trait (we may need 3 different skeleton trait implementors in the struct later, but for now one is enough)
3. don't use `OriginalSkeletonTreeImpl` in the function body
</blockquote></details>

Done.
___
*[`crates/committer/src/block_committer/commit.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-Nwsj8Cs57xdI84wnaad:-Nx6OhXoERadHLZ6aRao:b-nh12au) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/commit.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is not the entire commitment logic.
1. move this function to the skeleton area (I think original skeleton area is the correct place).
2. rename
</blockquote></details>

1. IMO it's better to separate between a single tree logic and the entire block commitment logic. I can create a file `block_committer\create_original_skeleton_forest` and move the logic there..
2. renamed to `create_original_skeleton_forest`
___
*[`crates/committer/src/block_committer/commit.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-NwslGcI6GKd3LyHm2vV:-Nx6Na6-0TdmcOTjbe-S:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/commit.rs#L14)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is it possible to add a `from(HashMap<StorageKey, StorageValue>)` on the generic `Storage` trait?
I prefer this function be agnostic to the storage implementation, i.e. make a generic `S: Storage` type parameter and use `S::from(input.storage)`.
the `create_tree` method of the skeleton tree trait accepts any implementor of the Storage trait
</blockquote></details>

Done.
___
*[`crates/committer/src/block_committer/commit.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-NwskYV_3XrV62we-S5U:-Nx6TO9k7hxUuorPpdB3:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/commit.rs#L31)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

errors indicating bad input should have their own enum. it shouldn't be a direct variant in BlockCommitmentError, please create an intermediate enum
</blockquote></details>

Done.
___
*[`crates/committer/src/block_committer/errors.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-NwslzwY7d53iOCd2dDh:-NwtOcdp1HL6c_rfT9Bj:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/errors.rs#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

prefer using `transparent` when the error variant is of the form `X(#[from] Y)`
</blockquote></details>

Done.
___
*[`crates/committer/src/block_committer/errors.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-Nwslokb8g7UXAb58xSS:-Nx6ZNxI2ugdsVTzqUpi:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/errors.rs#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is a specific error you encounter when the input data does not contain the required information to compute an original skeleton.
this belongs as a variant in the `OriginalSkeletonTreeError` enum
</blockquote></details>

Done.
___
*[`crates/committer/src/block_committer/types.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-NwsmCcu80W_DfnQt-AF:-Nwt3C9l5d9FkhTnW4ih:b-7m74ox) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/types.rs#L65)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work? I see no reason to `collect` anything before passing it to `HashMap::from_iter`
</blockquote></details>

nice!
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-Nwsm_neD2ywzRPvgRyj:-NwtO14_AegtwAzIarzw:bpemebq) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/patricia_merkle_tree/types.rs#L86)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you need this conversion?
this is dangerous
for a state tree of depth 251, node index 2^251 is leaf number 0, so starknet storage key should be zero.
please delete this and use explicit conversions if and when you need to
</blockquote></details>

I don't understand why it's dangerous... `StarknetStorageKey` wraps a `Felt`.
It's similar to a cast `Felt` => `U256` (which should be fine IMO)


<!-- Sent from Reviewable.io -->

2024-05-05 08:13 UTC, dorimedini-starkware requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/83)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/block_committer/commit.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-NwsibwCC5uJdeYFMwZK:-Nx6kjqc0DymA8YhqiYu:b-g99vft) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/commit.rs#L13)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

use a generic `L` for leaf data type
___
*[`crates/committer/src/block_committer/commit.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-Nwsj8Cs57xdI84wnaad:-Nx6ktvZAvU2ukuUynYj:b-agauc7) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/commit.rs#L13)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

1. IMO it's better to separate between a single tree logic and the entire block commitment logic. I can create a file `block_committer\create_original_skeleton_forest` and move the logic there..
2. renamed to `create_original_skeleton_forest`
</blockquote></details>

1. separate between single tree and multi tree logic - yes, that's good. however, creating many skeleton trees *is not commitment logic*, it's still only skeleton logic and shouldn't be under `block_committer` folder. this code should be moved to skeleton area (you can create a new file for skeleton-forest)
___
*[`crates/committer/src/block_committer/commit.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx6lH931-jG_2lTe1tl:-Nx6lH931-jG_2lTe1tm:br0qrut) ([raw file](https://github.com/starkware-libs/committer/blob/ac9673bc970b9b78d2c4e2dfc523a5366d905939/crates/committer/src/block_committer/commit.rs#L22)):*
> ```XML
> 
> #[allow(dead_code)]
> pub(crate) fn create_original_skeleton_forest<O: OriginalSkeletonTree<LeafDataImpl>, S: Storage>(
> ```

we use `T` for tree type at the moment, let's stay consistent



_Suggestion:_
```XML
L: LeafData, T: OriginalSkeletonTree<L>
```
___
*[`crates/committer/src/block_committer/errors.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-Nwslokb8g7UXAb58xSS:-Nx6mxpJ-ZhSUpSKb3SV:bp8ni8t) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/errors.rs#L12)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no, you created a new enum.
why not make this a variant of `OriginalSkeletonTreeError`?
the final error would be
```
BlockCommitmentError::BuildingOriginalSkeletonTree(
    OriginalSkeletonTreeError::LowerTreeCommitmentError(ContractAddress)
)
```
___
*[`crates/committer/src/block_committer/types.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx6nKoI7MMhpg10J5nw:-Nx6nKoI7MMhpg10J5nx:bmby0qi) ([raw file](https://github.com/starkware-libs/committer/blob/ac9673bc970b9b78d2c4e2dfc523a5366d905939/crates/committer/src/block_committer/types.rs#L59)):*
> ```XML
>                 .cloned()
>                 .chain(self.address_to_nonce.keys().cloned())
>                 .chain(self.storage_updates.keys().cloned()),
> ```

sure these `cloned()`s are needed? iterating over borrowed objects isn't good enough?



_Code quote:_
```XML
                .cloned()
                .chain(self.address_to_nonce.keys().cloned())
                .chain(self.storage_updates.keys().cloned()),
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-Nwsm_neD2ywzRPvgRyj:-Nx6n_WJ2Gd6zT-4hJNQ:b-el7z1o) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/patricia_merkle_tree/types.rs#L86)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I don't understand why it's dangerous... `StarknetStorageKey` wraps a `Felt`.
It's similar to a cast `Felt` => `U256` (which should be fine IMO)
</blockquote></details>

not dangerous w.r.t. overflow: I mean, a storage key should never be used as a node index.
just for type-safety.
why do you need it?


<!-- Sent from Reviewable.io -->

2024-05-05 09:19 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/83)* status: 6 of 11 files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/block_committer/commit.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-NwsibwCC5uJdeYFMwZK:-Nx6ukfuBsQ3P9PE-Y39:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/commit.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use a generic `L` for leaf data type
</blockquote></details>

Done.
___
*[`crates/committer/src/block_committer/commit.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-Nwsj8Cs57xdI84wnaad:-Nx6x3pV9WK2FrJIsr0q:b-d5z8ue) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/commit.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. separate between single tree and multi tree logic - yes, that's good. however, creating many skeleton trees *is not commitment logic*, it's still only skeleton logic and shouldn't be under `block_committer` folder. this code should be moved to skeleton area (you can create a new file for skeleton-forest)
</blockquote></details>

moved logic to a new file at `original_skeleton_tree/skeleton_forest.rs`
___
*[`crates/committer/src/block_committer/commit.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx6lH931-jG_2lTe1tl:-Nx6upUlB-YuWp4D6Y0Q:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/ac9673bc970b9b78d2c4e2dfc523a5366d905939/crates/committer/src/block_committer/commit.rs#L22)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we use `T` for tree type at the moment, let's stay consistent
</blockquote></details>

Done.
___
*[`crates/committer/src/block_committer/errors.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-Nwslokb8g7UXAb58xSS:-Nx71qjqEXgBQgtqzTWc:bluyhnb) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/errors.rs#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no, you created a new enum.
why not make this a variant of `OriginalSkeletonTreeError`?
the final error would be
```
BlockCommitmentError::BuildingOriginalSkeletonTree(
    OriginalSkeletonTreeError::LowerTreeCommitmentError(ContractAddress)
)
```
</blockquote></details>

I'm not sure i understand; removed the new enum and added this entry 
```
#[error("Missing input: Couldn't build the skeleton at address {0:?}")]
    LowerTreeCommitmentError(ContractAddress),
``` 
to ` OriginalSkeletonTreeError`
___
*[`crates/committer/src/block_committer/types.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx6nKoI7MMhpg10J5nw:-Nx70c3N-s5g4GfjZEiq:b-ugorzy) ([raw file](https://github.com/starkware-libs/committer/blob/ac9673bc970b9b78d2c4e2dfc523a5366d905939/crates/committer/src/block_committer/types.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

sure these `cloned()`s are needed? iterating over borrowed objects isn't good enough?
</blockquote></details>

it's enough for the iteration, but it's returned from the function (inside `OriginalSkeletonForest`), which makes it more complicated
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-Nwsm_neD2ywzRPvgRyj:-Nx6xaeH9gtS6dsC-eWz:b-gqgby1) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/patricia_merkle_tree/types.rs#L86)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not dangerous w.r.t. overflow: I mean, a storage key should never be used as a node index.
just for type-safety.
why do you need it?
</blockquote></details>

it is actually. 
storage updates have the type `Hashmap<ContractAddress, Hashmap<StarknetStorageKey, StarknetStorageValue>>` (mapping each contract to its modified storage values) each storage value is a leaf at the lower trees (and the leaf index is represented by `StarknetStorageKey`)

I think `StarknetStorageKey` and `ContractAddress` should wrap `U256` instead. will do that in a separate PR


<!-- Sent from Reviewable.io -->

2024-05-05 09:31 UTC, dorimedini-starkware requested changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/83)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/block_committer/errors.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-Nwslokb8g7UXAb58xSS:-Nx73svkBBzZxw5A9vmv:b52izmv) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/block_committer/errors.rs#L12)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I'm not sure i understand; removed the new enum and added this entry 
```
#[error("Missing input: Couldn't build the skeleton at address {0:?}")]
    LowerTreeCommitmentError(ContractAddress),
``` 
to ` OriginalSkeletonTreeError`
</blockquote></details>

perfect :)
___
*[`crates/committer/src/block_committer/types.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx6nKoI7MMhpg10J5nw:-Nx74uwF5CRidaICbQAY:bn0mywv) ([raw file](https://github.com/starkware-libs/committer/blob/ac9673bc970b9b78d2c4e2dfc523a5366d905939/crates/committer/src/block_committer/types.rs#L59)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

it's enough for the iteration, but it's returned from the function (inside `OriginalSkeletonForest`), which makes it more complicated
</blockquote></details>

can you explain?
from the code it looks like the function can make do with only references to contract addresses, why is the copy / clone needed?
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-Nwsm_neD2ywzRPvgRyj:-Nx74C0A7KtVuUBqPfuF:b-1xehlb) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/patricia_merkle_tree/types.rs#L86)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

it is actually. 
storage updates have the type `Hashmap<ContractAddress, Hashmap<StarknetStorageKey, StarknetStorageValue>>` (mapping each contract to its modified storage values) each storage value is a leaf at the lower trees (and the leaf index is represented by `StarknetStorageKey`)

I think `StarknetStorageKey` and `ContractAddress` should wrap `U256` instead. will do that in a separate PR
</blockquote></details>

Neither should be 256 bits, both are field elements.
And note that if `StarknetStorageKey` is `0`, then the node index is `2^251`! this is not a trivial conversion, so you should not implement `From` IMO.
It depends on the tree height.
Please implement specific and explicit `from_contract_address` and `from_storage_key` methods if you need them


<!-- Sent from Reviewable.io -->

2024-05-05 09:37 UTC, amosStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/83)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 20 at r3](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx73mF-1GCyn9v2_0xw:-Nx73mF01ZA61fLI3FQg:bmwjon7) ([raw file](https://github.com/starkware-libs/committer/blob/ce3c442a333b638e1c71f84c2f33b53c091c6a1f/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L20)):*
> ```XML
>     #[allow(dead_code)]
>     contract_states: HashMap<ContractAddress, T>,
>     leaf_data: PhantomData<L>,
> ```

I don't think this is needed



_Code quote:_
```XML
 leaf_data: PhantomData<L>,
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx76DZc-tITCsZcN9_R:-Nx76DZc-tITCsZcN9_S:b-r7ed4u) ([raw file](https://github.com/starkware-libs/committer/blob/ce3c442a333b638e1c71f84c2f33b53c091c6a1f/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L44)):*
> ```XML
>             .collect();
>         sorted_leaf_indices.sort();
>         let cur_contract_state = input
> ```

I would remove the `cur` from these variables. non blocking



_Code quote:_
```XML
let cur_contract_state = input
```


<!-- Sent from Reviewable.io -->

2024-05-05 10:09 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/83)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/block_committer/types.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx6nKoI7MMhpg10J5nw:-Nx75eaC-_WHfFOKDAAr:ba99m1u) ([raw file](https://github.com/starkware-libs/committer/blob/ac9673bc970b9b78d2c4e2dfc523a5366d905939/crates/committer/src/block_committer/types.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you explain?
from the code it looks like the function can make do with only references to contract addresses, why is the copy / clone needed?
</blockquote></details>

Changed it (as we agreed on huddle)
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-NwsmVf6BvecW6Rdfhei:-Nx7CgdU-jrwanr3gCAK:brotlw7) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/patricia_merkle_tree/types.rs#L51)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@TzahiTaub PTAL as well
</blockquote></details>

I deleted this function
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/committer/83#-Nwsm_neD2ywzRPvgRyj:-Nx7CjrpCrY7UJOkR-mp:b-lu3rjk) ([raw file](https://github.com/starkware-libs/committer/blob/fec16661d90ed9b833761e19b3c827a9dc0db17e/crates/committer/src/patricia_merkle_tree/types.rs#L86)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Neither should be 256 bits, both are field elements.
And note that if `StarknetStorageKey` is `0`, then the node index is `2^251`! this is not a trivial conversion, so you should not implement `From` IMO.
It depends on the tree height.
Please implement specific and explicit `from_contract_address` and `from_storage_key` methods if you need them
</blockquote></details>

added a method `NodeIndex::from_starknet_storage_key(key: &StarknetStorageKey, tree_height: &TreeHeight,) -> Self`
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 20 at r3](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx73mF-1GCyn9v2_0xw:-Nx7DDAw1N16NxFE1D8r:b-izen1t) ([raw file](https://github.com/starkware-libs/committer/blob/ce3c442a333b638e1c71f84c2f33b53c091c6a1f/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L20)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I don't think this is needed
</blockquote></details>

it is needed, without it i get the following error:
error[E0392]: type parameter `L` is never used
 = help: consider removing `L`, referring to it in a field, or using a marker such as `std::marker::PhantomData`
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx76DZc-tITCsZcN9_R:-Nx7D8HCBviLy48cpwio:b-5dft58) ([raw file](https://github.com/starkware-libs/committer/blob/ce3c442a333b638e1c71f84c2f33b53c091c6a1f/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L44)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I would remove the `cur` from these variables. non blocking
</blockquote></details>

removed :)


<!-- Sent from Reviewable.io -->

2024-05-05 12:44 UTC, dorimedini-starkware requested changes
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/83)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 54 at r4](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx7layaC2OoX_AL4J86:-Nx7layaC2OoX_AL4J87:bxn9ueu) ([raw file](https://github.com/starkware-libs/committer/blob/a5818a1dcfbc1ebe4b58cc65def2ce26d334ca27/crates/committer/src/patricia_merkle_tree/types.rs#L54)):*
> ```XML
>     ) -> Self {
>         Self(U256::from(2_u8) << tree_height.0) + Self::from(key.0)
>     }
> ```

1. write a small unit test for this
2. make sure it fails (because `2_u8` should be `1_u8`, right?)



_Code quote:_
```XML
    pub(crate) fn from_starknet_storage_key(
        key: &StarknetStorageKey,
        tree_height: &TreeHeight,
    ) -> Self {
        Self(U256::from(2_u8) << tree_height.0) + Self::from(key.0)
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx7lvLJEo6MCc7kFfHy:-Nx7lvLJEo6MCc7kFfHz:b-rtagwg) ([raw file](https://github.com/starkware-libs/committer/blob/a5818a1dcfbc1ebe4b58cc65def2ce26d334ca27/crates/committer/src/patricia_merkle_tree/types.rs#L89)):*
> ```XML
>         NodeIndex::from(value.0)
>     }
> }
> ```

delete


<!-- Sent from Reviewable.io -->

2024-05-05 13:26 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/83)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 54 at r4](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx7layaC2OoX_AL4J86:-Nx7nkf84G9E6wTkQnAd:blz4wa1) ([raw file](https://github.com/starkware-libs/committer/blob/a5818a1dcfbc1ebe4b58cc65def2ce26d334ca27/crates/committer/src/patricia_merkle_tree/types.rs#L54)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. write a small unit test for this
2. make sure it fails (because `2_u8` should be `1_u8`, right?)
</blockquote></details>

oops, wrote tests and changed to `1_u8`
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx7lvLJEo6MCc7kFfHy:-Nx7ngc-E-UhfZwjGoAM:brn0f32) ([raw file](https://github.com/starkware-libs/committer/blob/a5818a1dcfbc1ebe4b58cc65def2ce26d334ca27/crates/committer/src/patricia_merkle_tree/types.rs#L89)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

oops, done


<!-- Sent from Reviewable.io -->

2024-05-05 13:36 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/83)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 46 at r5](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx7xcgvExWcxo4x49VG:-Nx7xcgvExWcxo4x49VH:b5oeogy) ([raw file](https://github.com/starkware-libs/committer/blob/994371c76cc1070f25bdc325be7858b01d2ba3e1/crates/committer/src/patricia_merkle_tree/types_test.rs#L46)):*
> ```XML
> 
>     assert_eq!(actual, expected);
> }
> ```

put the expected result in the test case parametrization



_Suggestion:_
```XML
#[rstest]
#[case(0, 127, 2_u128.pow(127))]
#[case(15, 118, 2_u128.pow(118) + 15)]
#[case(0xDEADBEEF, 60, 2_u128.pow(60) + 0xDEADBEEF)]
fn test_starknet_storage_key_to_node_index(
    #[case] leaf_index: u128,
    #[case] tree_height: u8
    #[case] expected_node_index: u128
) {
    assert!(
        node_index < 2_u128.pow(tree_height.into()),
        "Invalid test arguments. The node index must be smaller than the number of nodes."
    );
    let actual = NodeIndex::from_starknet_storage_key(
        &StarknetStorageKey(Felt::from(node_index)),
        &TreeHeight(tree_height),
    );

    assert_eq!(actual, expected_node_index.into());
}
```


<!-- Sent from Reviewable.io -->

2024-05-05 14:01 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/83)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 46 at r5](https://reviewable.io/reviews/starkware-libs/committer/83#-Nx7xcgvExWcxo4x49VG:-Nx82jqc8y0XM-s_JVTa:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/994371c76cc1070f25bdc325be7858b01d2ba3e1/crates/committer/src/patricia_merkle_tree/types_test.rs#L46)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

put the expected result in the test case parametrization
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-05 14:02 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/83#-:-Nx83185CZlGbbr1nKQ5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-05-06 09:48 UTC, amosStarkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/83)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-05-06 11:17 UTC, merged