test: serialize storage with filled nodes
starkware-libs/committer pull request #89
Opened 2024-05-05 09:11 UTC by AvivYossef-starkware

2024-05-05 09:13 UTC, AvivYossef-starkware commented on crates/committer_cli/src/tests/python_tests.rs
> +    todo!("implement.")
It will remain blocked until it is implemented.

2024-05-05 09:25 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/89)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 407 at r1](https://reviewable.io/reviews/starkware-libs/committer/89#-Nx73fOz4koKPBIkb8LX:-Nx73fOz4koKPBIkb8LY:b-uhfx9i) ([raw file](https://github.com/starkware-libs/committer/blob/7f634658568505f8c1cc410391de18aff833d2be/crates/committer_cli/src/tests/python_tests.rs#L407)):*
> ```XML
> fn test_storage_node() -> String {
>     todo!("implement.")
> }
> ```

blocking until implemented



_Code quote:_
```XML
fn test_storage_node() -> String {
    todo!("implement.")
}
```


<!-- Sent from Reviewable.io -->

2024-05-08 16:00 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/89)* status: all files reviewed, 12 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/committer/src/felt.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNqXyCDuRapnUG9Z7o:-NxNqXyCDuRapnUG9Z7p:bpb0hlv) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer/src/felt.rs#L96)):*
> ```XML
>         // Zero-pad the remaining string to 64 characters
>         format!("{:0>64}", self.to_hex().strip_prefix("0x").unwrap_or("0"))
>     }
> ```

TAL at `StarknetTypesFelt::to_fixed_hex_string`, it should do what you want



_Code quote:_
```XML
    pub fn to_padded_64_hex(&self) -> String {
        // Zero-pad the remaining string to 64 characters
        format!("{:0>64}", self.to_hex().strip_prefix("0x").unwrap_or("0"))
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNr6kz51pafRvSHqBB:-NxNr6kz51pafRvSHqBC:bh7coe) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs#L21)):*
> ```XML
> 
>             LeafDataImpl::ContractState(contract_state) => {
>                 //todo: Aviv(8/5/2024): Use height from the input.
> ```

this is the format we use technically.
Also, WDYM by "use height from the input"? why do you need a tree height here?



_Suggestion:_
```XML
// TODO(Aviv, 8/5/2024): Use height from the input.
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNqsl3DWU5Jlj8JNYP:-NxNqsl3DWU5Jlj8JNYQ:b4tagza) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs#L27)):*
> ```XML
>                     contract_state.storage_root_hash.0.to_padded_64_hex(),
>                     contract_state.nonce.0.to_hex(),
>                 );
> ```

prefer destructuring to exactly what you need



_Suggestion:_
```XML
            LeafDataImpl::ContractState(ContractState { class_hash, storage_root, nonce }) => {
                //todo: Aviv(8/5/2024): Use height from the input.
                let json_string = format!(
                    r#"{{"contract_hash": "{}", "storage_commitment_tree": {{"root": "{}", "height": 252}}, "nonce": "{}"}}"#,
                    class_hash.0.to_padded_64_hex(),
                    storage_root_hash.0.to_padded_64_hex(),
                    nonce.0.to_hex(),
                );
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNrpYW-qNFPCdKZkri:-NxNrpYW-qNFPCdKZkrj:b4yepba) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer_cli/src/tests/python_tests.rs#L55)):*
> ```XML
>     StdinReadError(#[from] io::Error),
>     #[error("Failed to serialize {0}")]
>     SerializationError(#[from] SerializationError),
> ```

when using `#[from]` error variants I think it's best to use the `transparent` option. The extra text adds no new information: we already know where the error came from because we will see the `PythonTestError` enum in the trace.
(while you're here, please change the other variants to use `transparent`, hopefully it breaks nothing)



_Suggestion:_
```XML
    #[error("Unknown test name: {0}")]
    UnknownTestName(String),
    #[error(transparent)]
    ParseInputError(#[from] serde_json::Error),
    #[error(transparent)]
    ParseIntError(#[from] std::num::ParseIntError),
    #[error("{0}")]
    KeyNotFound(String),
    #[error(transparent)]
    InvalidCastError(#[from] std::num::TryFromIntError),
    #[error(transparent)]
    DeserializationTestFailure(#[from] DeserializationError),
    #[error(transparent)]
    StdinReadError(#[from] io::Error),
    #[error(transparent)]
    SerializationError(#[from] SerializationError),
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 441 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNsTqGAW6ZonbdxvzA:-NxNsTqGAW6ZonbdxvzB:b-x08xla) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer_cli/src/tests/python_tests.rs#L441)):*
> ```XML
>     }
> 
>     serde_json::to_string(&storage).map_err(PythonTestError::from)
> ```

this notation should work: there is a `#[from]` variant of PythonTestError coming from the error type returned in `serde_json::to_string`, right? the compiler should do the conversion itself...
please check if it compiles? (non-blocking)



_Suggestion:_
```XML
serde_json::to_string(&storage)?
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 444 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNsjWuEbzdMVKcaWmj:-NxNsjWuEbzdMVKcaWmk:bcr8ude) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer_cli/src/tests/python_tests.rs#L444)):*
> ```XML
> }
> 
> fn python_hash_constants_compare() -> String {
> ```

don't understand the reason for the the function name, it just encodes the version to string, right?



_Suggestion:_
```XML
contract_state_hash_version_string
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 453 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNt-TzC7A2KRhim4gr:-NxNt-TzC7A2KRhim4gs:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer_cli/src/tests/python_tests.rs#L453)):*
> ```XML
> ///
> /// # Arguments
> /// * `date` - A map containing JSON strings for different node data:
> ```

typo



_Suggestion:_
```XML
data
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 462 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNt1J774eC-MDG9UA5:-NxNt1J774eC-MDG9UA6:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer_cli/src/tests/python_tests.rs#L462)):*
> ```XML
> /// # Returns
> /// A `Result<String, PythonTestError>` containing a serialized map of all nodes on success, or an error if keys are missing or parsing fails.
> fn test_storage_node(date: HashMap<String, String>) -> Result<String, PythonTestError> {
> ```

typo



_Suggestion:_
```XML
data
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 467 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNu5a_4QquQEYf6Q3p:-NxNu5a_4QquQEYf6Q3q:b63jcat) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer_cli/src/tests/python_tests.rs#L467)):*
> ```XML
>         storage: HashMap::new(),
>     };
> ```

to reduce boilerplate in this test please define and use this utility:
```
fn get_or_key_not_found(map: &HashMap<String, u128>, key: &str) -> Result<u128, PythonTestError> {
    Ok(map.get(key).ok_or_else(|| {
        PythonTestError::KeyNotFound("Failed to get value for key '{key}' from {map:?}.".to_string())
    })?)
}
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 507 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNtji81Gsc567xm-mP:-NxNtji81Gsc567xm-mQ:b-qxk1ry) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer_cli/src/tests/python_tests.rs#L507)):*
> ```XML
>         PythonTestError::KeyNotFound("Failed to get value for key 'length'".to_string())
>     })?)
>     .try_into()?;
> ```

why is `length` special? computed outside the construction of the FilledNode?



_Code quote:_
```XML
    // Parse  [...]

2024-05-09 09:10 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/89)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/felt.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNqXyCDuRapnUG9Z7o:-NxR5weWCl9cFOpDtorA:b-ucfkn4) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer/src/felt.rs#L96)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

TAL at `StarknetTypesFelt::to_fixed_hex_string`, it should do what you want
</blockquote></details>

Thanks.
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNr6kz51pafRvSHqBB:-NxR6Si5Ejcy3PfynVsf:b9u1ypb) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is the format we use technically.
Also, WDYM by "use height from the input"? why do you need a tree height here?
</blockquote></details>

Contract_State serializes with height, as you can see in the JSON string.
We should get it as input from Python to enforce consistency.
https://github.com/starkware-libs/committer/blob/aab1f12aed375062b65bf10370db1f22ca515cf2/crates/committer/src/block_committer/input.rs#L39
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNqsl3DWU5Jlj8JNYP:-NxRAEpV4Xm8yQDWeNob:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs#L27)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

prefer destructuring to exactly what you need
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNrpYW-qNFPCdKZkri:-NxRARcLCXjTtX_xU8t_:b-896fiz) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer_cli/src/tests/python_tests.rs#L55)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

when using `#[from]` error variants I think it's best to use the `transparent` option. The extra text adds no new information: we already know where the error came from because we will see the `PythonTestError` enum in the trace.
(while you're here, please change the other variants to use `transparent`, hopefully it breaks nothing)
</blockquote></details>

Done,
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 441 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNsTqGAW6ZonbdxvzA:-NxRBCAb-Vvb4XYy9pyw:b-e50z0g) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer_cli/src/tests/python_tests.rs#L441)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this notation should work: there is a `#[from]` variant of PythonTestError coming from the error type returned in `serde_json::to_string`, right? the compiler should do the conversion itself...
please check if it compiles? (non-blocking)
</blockquote></details>

It works like in the code snippet. 
I'm Change it but it's from an older PR



_Code snippet:_
```XML
Ok(serde_json::to_string(&storage)?)
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 444 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNsjWuEbzdMVKcaWmj:-NxRDCjx48tdSzrlqVv7:btf248a) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer_cli/src/tests/python_tests.rs#L444)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't understand the reason for the the function name, it just encodes the version to string, right?
</blockquote></details>

It's not part of the PR.
It's from Nimrod's older PR. 
Should I change it? 
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 467 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNu5a_4QquQEYf6Q3p:-NxRFoidD7zBVWNZVqvr:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer_cli/src/tests/python_tests.rs#L467)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

to reduce boilerplate in this test please define and use this utility:
```
fn get_or_key_not_found(map: &HashMap<String, u128>, key: &str) -> Result<u128, PythonTestError> {
    Ok(map.get(key).ok_or_else(|| {
        PythonTestError::KeyNotFound("Failed to get value for key '{key}' from {map:?}.".to_string())
    })?)
}
```
</blockquote></details>

Done.



_Code snippet:_
```XML
    /// Returns value from storage or an error if it does not exist.
    fn get_or_key_not_found(&self, key: StorageKey) -> Result<&StorageValue, StorageError> {
        self.get(&key).ok_or( StorageError::MissingKey(key))
    }
    
    #[error(transparent)]
    KeyNotFound(#[from] StorageError::MissingKey),
    
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 507 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNtji81Gsc567xm-mP:-NxRSpNB4g3B0rvoGRZB:b-807s54) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer_cli/src/tests/python_tests.rs#L507)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is `length` special? computed outside the construction of the FilledNode?
</blockquote></details>

It was special since I needed to cast it to u8. But now with
get_or_key_not_found func It's ok.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 560 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNvQTP9TOXdOqhsK0B:-NxRTcTo0tUFP9gFVZsE:b-2o2glk) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer_cli/src/tests/python_tests.rs#L560)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the code location is enough to completely identify the error; no need for extra text.
(this is a test file, it's fine to unwrap)
</blockquote></details>

It's not compile.
I change it to be the same as the rest



_Code snippet:_
```XML
error: used `unwrap()` on an `Option` value
   --> crates/committer_cli/src/tests/python_tests.rs:552:31
    |
552 |       let contract_state_leaf = data
    |  _______________________________^
553 | |         .get("contract_state_leaf")
554 | |         .unwrap();
    | |_________________^
    |
    = note: if this value is `None`, it will panic
    = help: consider using `expect()` to provide a better panic message
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_used
    = note: requested on the command line with `-D clippy::unwrap-used`
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 640 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNvekNBpslJB4ovW54:-NxRaVXpAUkZu9H-g61s:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer_cli/src/tests/python_tests.rs#L640)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same as above: conversion should be automatic
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-09 10:36 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/89)* status: all files reviewed, 6 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/committer/src/felt.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/committer/89#-NxRu8pG2hn5IUf809EY:-NxRu8pG2hn5IUf809EZ:b903z4h) ([raw file](https://github.com/starkware-libs/committer/blob/d0cc4cd5eb63291204ee84a8cd7c5068ee742841/crates/committer/src/felt.rs#L100)):*
> ```XML
>             .unwrap_or("0")
>             .to_string()
>     }
> ```

if you string the `0x` prefix you will get a 6-character string; not a 66-character.



_Suggestion:_
```XML
    // Convert to a 64-character hexadecimal string without the "0x" prefix.
    pub fn to_fixed_hex_string(&self) -> String {
        // Zero-pad the remaining string
        self.0
            .to_fixed_hex_string()
            .strip_prefix("0x")
            .unwrap_or("0")
            .to_string()
    }
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 444 at r2](https://reviewable.io/reviews/starkware-libs/committer/89#-NxNsjWuEbzdMVKcaWmj:-NxRugcF99yCjkEKYJBn:b-tnnuag) ([raw file](https://github.com/starkware-libs/committer/blob/e36e02ceffeb70a1329232aeede79e936e0c540b/crates/committer_cli/src/tests/python_tests.rs#L444)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

It's not part of the PR.
It's from Nimrod's older PR. 
Should I change it?
</blockquote></details>

ah no... probably from rebase... nevermind
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/committer/89#-NxRut4G9wHrCPTKOOTf:-NxRut4G9wHrCPTKOOTg:byrq2m7) ([raw file](https://github.com/starkware-libs/committer/blob/d0cc4cd5eb63291204ee84a8cd7c5068ee742841/crates/committer_cli/src/tests/python_tests.rs#L127)):*
> ```XML
>         )
>     })?)
> }
> ```

see below



_Suggestion:_
```XML
fn get_or_key_not_found<T>(map: &HashMap<String, T>, key: &str) -> Result<T, PythonTestError> {
    Ok(*map.get(key).ok_or_else(|| {
        PythonTestError::KeyNotFound(
            "Failed to get value for key '{key}' from {map:?}.".to_string(),
        )
    })?)
}
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 512 at r3](https://reviewable.io/reviews/starkware-libs/committer/89#-NxRuyMl8CvcMiKZyfuB:-NxRuyMl8CvcMiKZyfuC:bxytyg1) ([raw file](https://github.com/starkware-libs/committer/blob/d0cc4cd5eb63291204ee84a8cd7c5068ee742841/crates/committer_cli/src/tests/python_tests.rs#L512)):*
> ```XML
>     let edge_json = data.get("edge").ok_or_else(|| {
>         PythonTestError::KeyNotFound("Failed to get value for key 'edge'".to_string())
>     })?;
> ```

use util (see above)



_Code quote:_
```XML
    let edge_json = data.get("edge").ok_or_else(|| {
        PythonTestError::KeyNotFound("Failed to get value for key 'edge'".to_string())
    })?;
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 533 at r3](https://reviewable.io/reviews/starkware-libs/committer/89#-NxRv4nNB3J_8Ix_gS4E:-NxRv4nNB3J_8Ix_gS4F:bxytyg1) ([raw file](https://github.com/starkware-libs/committer/blob/d0cc4cd5eb63291204ee84a8cd7c5068ee742841/crates/committer_cli/src/tests/python_tests.rs#L533)):*
> ```XML
>     let storage_leaf_json = data.get("storage").ok_or_else(|| {
>         PythonTestError::KeyNotFound("Failed to get value for key 'storage'".to_string())
>     })?;
> ```

use util (see above)



_Code quote:_
```XML
    let storage_leaf_json = data.get("storage").ok_or_else(|| {
        PythonTestError::KeyNotFound("Failed to get value for key 'storage'".to_string())
    })?;
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 555 at r3](https://reviewable.io/reviews/starkware-libs/committer/89#-NxRv9pz9vOhQKeVKaJW:-NxRv9pz9vOhQKeVKaJX:bxytyg1) ([raw file](https://github.com/starkware-libs/committer/blob/d0cc4cd5eb63291204ee84a8cd7c5068ee742841/crates/committer_cli/src/tests/python_tests.rs#L555)):*
> ```XML
>             "Failed to get value for key 'contract state_leaf'".to_string(),
>         )
>     })?;
> ```

use util (see above)



_Code quote:_
```XML
    let contract_state_leaf = data.get("contract_state_leaf").ok_or_else(|| {
        PythonTestError::KeyNotFound(
            "Failed to get value for key 'contract state_leaf'".to_string(),
        )
    })?;
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 594 at r3](https://reviewable.io/reviews/starkware-libs/committer/89#-NxRvDqQ5OHDqbinhEtW:-NxRvDqQ5OHDqbinhEtX:bxytyg1) ([raw file](https://github.com/starkware-libs/committer/blob/d0cc4cd5eb63291204ee84a8cd7c5068ee742841/crates/committer_cli/src/tests/python_tests.rs#L594)):*
> ```XML
>             "Failed to get value for key 'contract class_leaf'".to_string(),
>         )
>     })?;
> ```

use util (see above)



_Code quote:_
```XML
    let compiled_class_leaf = data.get("contract_class_leaf").ok_or_else(|| {
        PythonTestError::KeyNotFound(
            "Failed to get value for key 'contract class_leaf'".to_string(),
        )
    })?;
```


<!-- Sent from Reviewable.io -->

2024-05-09 11:45 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/89)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/felt.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/committer/89#-NxRu8pG2hn5IUf809EY:-NxSA0lg5G-O82eN62CX:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d0cc4cd5eb63291204ee84a8cd7c5068ee742841/crates/committer/src/felt.rs#L100)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you string the `0x` prefix you will get a 6-character string; not a 66-character.
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/committer/89#-NxRut4G9wHrCPTKOOTf:-NxS6OKz4K_95B6r_ZZ7:b-xpa1m9) ([raw file](https://github.com/starkware-libs/committer/blob/d0cc4cd5eb63291204ee84a8cd7c5068ee742841/crates/committer_cli/src/tests/python_tests.rs#L127)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see below
</blockquote></details>

After the first review, I tried to do it but couldn't succeed.
I got it now ( first time using live time parameters : )  )  
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 512 at r3](https://reviewable.io/reviews/starkware-libs/committer/89#-NxRuyMl8CvcMiKZyfuB:-NxS6L5Y18krX77GCc3W:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d0cc4cd5eb63291204ee84a8cd7c5068ee742841/crates/committer_cli/src/tests/python_tests.rs#L512)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use util (see above)
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 533 at r3](https://reviewable.io/reviews/starkware-libs/committer/89#-NxRv4nNB3J_8Ix_gS4E:-NxS6LMO7Kr1inqB3L2i:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d0cc4cd5eb63291204ee84a8cd7c5068ee742841/crates/committer_cli/src/tests/python_tests.rs#L533)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use util (see above)
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 555 at r3](https://reviewable.io/reviews/starkware-libs/committer/89#-NxRv9pz9vOhQKeVKaJW:-NxS6LnR7BV6WJc3Qdz9:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d0cc4cd5eb63291204ee84a8cd7c5068ee742841/crates/committer_cli/src/tests/python_tests.rs#L555)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use util (see above)
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 594 at r3](https://reviewable.io/reviews/starkware-libs/committer/89#-NxRvDqQ5OHDqbinhEtW:-NxS6MCL6IMKUx8lUFm7:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d0cc4cd5eb63291204ee84a8cd7c5068ee742841/crates/committer_cli/src/tests/python_tests.rs#L594)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use util (see above)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-09 11:54 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/89)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/committer/89#-NxRut4G9wHrCPTKOOTf:-NxSBQxsB0MX-MXM91Xm:b-yfcl2x) ([raw file](https://github.com/starkware-libs/committer/blob/d0cc4cd5eb63291204ee84a8cd7c5068ee742841/crates/committer_cli/src/tests/python_tests.rs#L127)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

After the first review, I tried to do it but couldn't succeed.
I got it now ( first time using live time parameters : )  )
</blockquote></details>

WHOOP!
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 125 at r4](https://reviewable.io/reviews/starkware-libs/committer/89#-NxSBei0BMANE53LbRwx:-NxSBei0BMANE53LbRwy:b-7x7tcf) ([raw file](https://github.com/starkware-libs/committer/blob/129257614de88c9cdff99d6bbf9aa5f1deb3b717/crates/committer_cli/src/tests/python_tests.rs#L125)):*
> ```XML
>     map: &'a HashMap<String, T>,
>     key: &'a str,
> ) -> Result<&'a T, PythonTestError>
> ```

you need the lifetime parameter `'a` because you are returning `&T` instead of `T`.
I think you should be able to return `T`: maybe you also need `Copy` and/or `Clone` on `T` (in addition to `Debug`).
Can you try?



_Suggestion:_
```XML
fn get_or_key_not_found<T: Clone + Copy + Debug>(
    map: &HashMap<String, T>,
    key: &str,
) -> Result<T, PythonTestError>
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 128 at r4](https://reviewable.io/reviews/starkware-libs/committer/89#-NxSBT1eELR3ECHXQWVX:-NxSBT1eELR3ECHXQWVY:bweady6) ([raw file](https://github.com/starkware-libs/committer/blob/129257614de88c9cdff99d6bbf9aa5f1deb3b717/crates/committer_cli/src/tests/python_tests.rs#L128)):*
> ```XML
> where
>     T: Debug,
> {
> ```

does this work? (non-blocking)



_Suggestion:_
```XML
fn get_or_key_not_found<'a, T: Debug>(
    map: &'a HashMap<String, T>,
    key: &'a str,
) -> Result<&'a T, PythonTestError>
{
```


<!-- Sent from Reviewable.io -->

2024-05-09 11:58 UTC, AvivYossef-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/89)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 125 at r4](https://reviewable.io/reviews/starkware-libs/committer/89#-NxSBei0BMANE53LbRwx:-NxSC5Rs1v7fcWD9lfki:b1zlrxy) ([raw file](https://github.com/starkware-libs/committer/blob/129257614de88c9cdff99d6bbf9aa5f1deb3b717/crates/committer_cli/src/tests/python_tests.rs#L125)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you need the lifetime parameter `'a` because you are returning `&T` instead of `T`.
I think you should be able to return `T`: maybe you also need `Copy` and/or `Clone` on `T` (in addition to `Debug`).
Can you try?
</blockquote></details>

I tried it. I need <T: Copy>, and its a problem since String doesn't impl Copy 
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 128 at r4](https://reviewable.io/reviews/starkware-libs/committer/89#-NxSBT1eELR3ECHXQWVX:-NxSCet62yjZGT5MjTOJ:b8596yh) ([raw file](https://github.com/starkware-libs/committer/blob/129257614de88c9cdff99d6bbf9aa5f1deb3b717/crates/committer_cli/src/tests/python_tests.rs#L128)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work? (non-blocking)
</blockquote></details>

Yes, I think that it's equivalent.


<!-- Sent from Reviewable.io -->

2024-05-09 12:12 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/89)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 131 at r5](https://reviewable.io/reviews/starkware-libs/committer/89#-NxSFFS3B8jmwAbPlGAj:-NxSFFS3B8jmwAbPlGAk:bzg1vfv) ([raw file](https://github.com/starkware-libs/committer/blob/47dd697d272f5f3a8bac2ec5bd0eaedad243500e/crates/committer_cli/src/tests/python_tests.rs#L131)):*
> ```XML
>             key, map
>         ))
>     })
> ```

String implements Clone though.
This works (I checked now)



_Suggestion:_
```XML
fn get_or_key_not_found<T: Clone + Debug>(
    map: &HashMap<String, T>,
    key: &str,
) -> Result<T, PythonTestError> {
    match map.get(key) {
        Some(value) => Ok(value.clone()),
        None => Err(PythonTestError::KeyNotFound(format!(
            "Failed to get value for key '{}' from {:?}.",
            key, map
        ))),
    }
```


<!-- Sent from Reviewable.io -->

2024-05-09 12:14 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/89)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 131 at r5](https://reviewable.io/reviews/starkware-libs/committer/89#-NxSFFS3B8jmwAbPlGAj:-NxSGX4fDk00nUKwN5l7:b35vj6) ([raw file](https://github.com/starkware-libs/committer/blob/47dd697d272f5f3a8bac2ec5bd0eaedad243500e/crates/committer_cli/src/tests/python_tests.rs#L131)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

String implements Clone though.
This works (I checked now)
</blockquote></details>

the point is, you return `value.clone()` instead of `value` (the latter requires the `Copy` trait, IIUC)


<!-- Sent from Reviewable.io -->

2024-05-09 12:17 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/89)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 131 at r5](https://reviewable.io/reviews/starkware-libs/committer/89#-NxSFFS3B8jmwAbPlGAj:-NxSHJEx2c4U2g-I0Ji-:bpbc5vh) ([raw file](https://github.com/starkware-libs/committer/blob/47dd697d272f5f3a8bac2ec5bd0eaedad243500e/crates/committer_cli/src/tests/python_tests.rs#L131)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the point is, you return `value.clone()` instead of `value` (the latter requires the `Copy` trait, IIUC)
</blockquote></details>

ah wait no
your way is simply more efficient (no clones needed)
unblocking


<!-- Sent from Reviewable.io -->

2024-05-09 12:17 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/89#-:-NxSHP8z1GLNrd64S-2v:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)



<!-- Sent from Reviewable.io -->

2024-05-09 13:02 UTC, AvivYossef-starkware reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/89#-:-NxSRar01N2TlgKMkevu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)



<!-- Sent from Reviewable.io -->

2024-05-09 13:03 UTC, AvivYossef-starkware reviewed
ok

2024-05-09 13:05 UTC, merged